{
  "hash": "f82b62e6c9c51bac82fb62100b8e6c82",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"122_wk13_labActivity2\"\nauthor: \"Margriet Groen\"\ndate: \"2024-01-24\"\noutput: html_document\n---\n\n\n\n\n\n\n## Lab activity 2 - Statistics anxiety and engagement in module activities\n\n>*Question 1a* If our hypothesis is correct, what type of correlation (if any) should we observe between students' mean anxiety levels and the variable `n_weeks`? **A negative correlation**\n\n# Step 1. Loading the relevant libraries\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(broom)\nlibrary(car)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: carData\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.0     ✔ readr     2.1.6\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.2     ✔ tibble    3.3.1\n✔ lubridate 1.9.4     ✔ tidyr     1.3.2\n✔ purrr     1.2.1     \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n✖ dplyr::recode() masks car::recode()\n✖ purrr::some()   masks car::some()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n:::\n\n\n\n# Step 2. Read in the data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstars <- read_csv(\"stars2.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 1887 Columns: 3\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (1): Question\ndbl (2): ID, Score\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nengage <- read_csv(\"psess.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 100 Columns: 2\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\ndbl (2): ID, n_weeks\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(stars) # Look at the data frames\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n     ID Question Score\n  <dbl> <chr>    <dbl>\n1     3 Q01          1\n2     3 Q02          1\n3     3 Q03          1\n4     3 Q04          1\n5     3 Q05          1\n6     3 Q06          1\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(engage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n     ID n_weeks\n  <dbl>   <dbl>\n1     1       7\n2     2       8\n3     3       5\n4     4       2\n5     7       2\n6     8       5\n```\n\n\n:::\n:::\n\n\n\n>*Question 2a* In the `stars` data frame, what do the numbers in the first row across the three columns refer to? **ID = 3, Question = Q01 and Score = 1 shows us that participant 3 reported a score of 1 on question 1.**\n\n# Step 3. Getting the data ready.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstars_means <- stars %>%\n  group_by(ID) %>%\n  summarise(mean_anxiety = mean(Score, na.rm = TRUE))\nstars_means\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 37 × 2\n      ID mean_anxiety\n   <dbl>        <dbl>\n 1     3         1.06\n 2     7         2.71\n 3    12         2.24\n 4    16         2.86\n 5    23         1.71\n 6    29         1.80\n 7    39         1.96\n 8    42         2.24\n 9    43         2.69\n10    44         1.92\n# ℹ 27 more rows\n```\n\n\n:::\n:::\n\n\n\n\n>*Question 3a* What is the mean anxiety score for participant 3? **1.058824**\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\njoined <- inner_join(stars_means, engage, \"ID\")\n```\n:::\n\n\n\n\n# Step 4: Calculating descriptive statistics\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndescriptives <- joined %>%\n  summarise(mean_anx = mean(mean_anxiety, na.rm = TRUE),\n            sd_anx = sd(mean_anxiety, na.rm = TRUE),\n            mean_weeks = mean(n_weeks, na.rm = TRUE),\n            sd_weeks = sd(n_weeks, na.rm = TRUE))\ndescriptives\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  mean_anx sd_anx mean_weeks sd_weeks\n     <dbl>  <dbl>      <dbl>    <dbl>\n1     2.08  0.563       4.54     2.42\n```\n\n\n:::\n:::\n\n\n\n\n>*Question 4a* What are the means and standard deviation for anxiety and engagement with the statistics module? **Anxiety *M* = 2.08, *SD* = 0.56; Engagement *M* = 4.54, *SD* = 2.42.**\n\n# Step 5: Visualise the data\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(joined, aes(x = mean_anxiety, y = n_weeks)) +\n  geom_point() +\n  geom_smooth(method = \"lm\") +\n  labs(x = \"Anxiety\", y = \"Engagement\") +\n  theme_bw()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](122_wk13_labAct2_files/figure-html/scatterplot-1.png){width=672}\n:::\n:::\n\n\n\n\n>*Question 5a* What does the scatterplot suggest about the relationship between anxiety and engagement? **That there might indeed be a relatively strong negative correlation between the two; students with more anxiety, engage less.**\n\n# Step 6: Build the regression model ----------------------------------\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod <- lm(n_weeks ~ mean_anxiety, data = joined)\nmod_summary <- summary(mod)\nmod_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = n_weeks ~ mean_anxiety, data = joined)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-3.990 -1.734 -0.093  1.907  2.929 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    9.0572     1.3500   6.709  9.1e-08 ***\nmean_anxiety  -2.1727     0.6274  -3.463  0.00143 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.12 on 35 degrees of freedom\nMultiple R-squared:  0.2552,\tAdjusted R-squared:  0.2339 \nF-statistic: 11.99 on 1 and 35 DF,  p-value: 0.001428\n```\n\n\n:::\n:::\n\n\n\n\n>*Question 6a* What is the estimate of the y-intercept for the model, rounded to three decimal places? **9.057. Explanation: In the summary table, this is the estimate of the intercept.**\n\n>*Question 6b* To three decimal places, if the General Linear Model for this model is `Y=beta0 + beta1X + e`, then the value of `beta1` is ... **-2.173. Explanation: In the summary table, this is the estimate of mean_anxiety, i.e., the slope.**\n\n>*Question 6c* To three decimal places, for each unit increase in anxiety, engagement decreases by ... **2.173. Explanation: In the summary table, this is also the estimate of mean_anxiety, the slope is how much it decreases so you just remove the - sign.**\n\n>*Question 6d* To two decimal places, what is the overall F-value of the model? **11.99. Explanation: In the summary table, the F-ratio is noted as the F-statistic.**\n\n>*Question 6e* Is the overall model significant? **Yes. Explanation: The overall model p-value is .001428 which is less than .05, therefore significant.**\n\n>*Question 6f* What proportion of the variance does the model explain? **25.52%. Explanation: The variance explained is determined by R-squared, you simply multiple it by 100 to get the percent.**\n\n# Step 7: Checking assumptions\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrPlots(mod)                  # Plot linear line and line that best fits the data to check the relationship between outcome and predictor is linear\n```\n\n::: {.cell-output-display}\n![](122_wk13_labAct2_files/figure-html/assumptions-1.png){width=672}\n:::\n\n```{.r .cell-code}\nqqPlot(mod$residuals)         # Create qq-plot to check residuals are normally distributed\n```\n\n::: {.cell-output-display}\n![](122_wk13_labAct2_files/figure-html/assumptions-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13 11\n```\n\n\n:::\n\n```{.r .cell-code}\nresidualPlot(mod)             # Create residual plot to check residual show homoscedasticity\n```\n\n::: {.cell-output-display}\n![](122_wk13_labAct2_files/figure-html/assumptions-3.png){width=672}\n:::\n:::\n\n\n\n\n>*Question 7a* Does the relationship appear to be linear? **Yes, the pink line roughly falls across the dashed blue line and looks mostly linear.**\n\n>*Question 7b* Do the residuals show normality? **Yes, in the qq-plot the open circles mostly assemble around the solid blue line, and fall mostly within the range of the dashed blue lines.**\n\n>*Question 7c* Do the residuals show homoscedasticity? **Yes, the residual plot shows that the spread of the residuals is roughly similar for different fitted values.**\n\n# Step 8: Write up\n\n**A simple linear regression was performed with engagement (*M* = 4.54, *SD* = 0.56) as the outcome variable and statistics anxiety (*M* = 2.08, *SD* = 0.56) as the predictor variable. The results of the regression indicated that the model significantly predicted course engagement (*F*(1, 35) = 11.99, *p* \\< .001, *R\\^2* = 0.25), accounting for 25% of the variance. Anxiety was a significant negative predictor (*beta* = -2.17, *p* \\< 0.001): as anxiety increased, course engagement decreased.**",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}