{
  "hash": "a7585da15bd322b71fee480678eda708",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Week 10. Developing the linear model\nsubtitle: Written by Rob Davies\norder: 13\nbibliography: references.bib\ncsl: psychological-bulletin.csl\n---\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n\n## 10.1 Overview {#sec-lm-dev-overview}\n\nWelcome to your overview of the work we will do together in **Week 10**.\n\nThis week, we focus on strengthening your ability to apply the linear model approach to a wider range of research questions.\n\nIn the context of the *Clearly understood* project, we frame our analysis concerns and methods in relation to example research questions, including the question:\n\n1.  What person attributes predict success in understanding?\n\nThis is to help you to learn to think critically about what it is you want to do with linear models when you use them, or when you read about their results in research reports.\n\nIt will be seen that, to answer research questions like this example question, we will need to think about how we analyze data when *multiple* different predictor variables could be included in our model.\n\nMost of the time, in your future professional work, when you use linear models you will be trying to predict outcomes (behaviours, person attributes) given information from multiple different predictor variables at once.\n\nYou will be able to do this work using what you learn this week.\n\nAs students, now, learning how to move from analyses involving one outcome and one predictor variable, to analyses involving one outcome and *multiple* outcome variables **unlocks a much wider range of contexts** in which you can apply the skills and understanding you develop here to address research problems and questions of your own.\n\n::: callout-tip\nWe encounter linear models with multiple predictors, often, as *multiple regression* or *regression* analyses. The difference in names in different fields disguises the fact that we are working with the same technique: multiple regressions **are** linear models.\n:::\n\n## 10.2 Our learning goals {#sec-lm-dev-goals}\n\nWe will learn how to:\n\n-   *Skills* -- extend our capacity to code models so that we can incorporate **multiple predictors**;\n-   *Concepts* -- develop the critical thinking processes required to make **decisions about what predictors to include** in your model;\n-   *Concepts and skills* -- learn how to **critically evaluate results**, given variation between samples.\n\nWe will revise how to:\n\n-   *Skills* -- identify and interpret model statistics;\n-   *Concepts and skills* -- critically evaluate the results;\n-   *Concepts and skills* -- communicate the results.\n\nAs we progress, we will continue to strengthen your skills in building *professional visualizations*.\nThis week, we will learn how to exploit professional tools to *automatically* generate and plot model predictions, when previously we produced model predictions by hand.\n\n## 10.3 Learning resources {#sec-lm-dev-resources}\n\nYou will see, next, the lectures we share to explain the concepts you will learn about, and the practical data analysis skills you will develop. Then you will see information about the practical materials you can use to build and practise your skills.\n\nEvery week, you will learn best if you *first* watch the lectures *then* do the practical exercises.\n\n::: callout-tip\n## Linked resources\n1. In [the chapter for week 7](../part2/hypotheses-associations.qmd#sec-associations-overview), we share materials to support your development of critical thinking about associations, and your development of practical skills in working with correlation-based analyses.\n2. In [the chapter for week 8](../part2/lm-intro.qmd#sec-lm-intro-overview), we introduce you to the main ideas and practical steps involved in conducting linear model analyses.\n:::\n\n### 10.3.1 Lectures {#sec-lm-dev-lectures}\n\nThe lecture materials for this week are presented in four short parts. \n\nClick on a link and your browser should open a tab showing the *Panopto* video for the lecture part.\n\n1. Part 1 (20 minutes) **Developing the linear model**: The concepts and skills we will learn about in week 10: our aims, the research questions we can answer with linear models, making the move to working with linear models with multiple predictors, why the main challenge is not the coding but the *choices* over which predictors to include in a model.\n\n\n\n```{=html}\n<iframe src=\"https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=14284d6d-f17d-4c0a-a827-b23d00bda67f&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all\" height=\"405\" width=\"720\" style=\"border: 1px solid #464646;\" allowfullscreen allow=\"autoplay\" aria-label=\"Panopto Embedded Video Player\" aria-description=\"PSYC411-lm-dev-1\" ></iframe>\n```\n\n\n\n2. Part 2 (13 minutes): Coding, thinking about, and reporting linear models with multiple predictors.\n\n\n\n```{=html}\n<iframe src=\"https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=cce303a1-392c-4607-aecd-af63010c4070&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all\" height=\"405\" width=\"720\" style=\"border: 1px solid #464646;\" allowfullscreen allow=\"autoplay\" aria-label=\"Panopto Embedded Video Player\" aria-description=\"PSYC411-lm-dev-2\" ></iframe>\n```\n\n\n\n3. Part 3 (21 minutes): Critically evaluating the results of analyses involving linear models.\n\n\n\n```{=html}\n<iframe src=\"https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=5f02f90d-5a7f-4742-9638-af63011046b8&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all\" height=\"405\" width=\"720\" style=\"border: 1px solid #464646;\" allowfullscreen allow=\"autoplay\" aria-label=\"Panopto Embedded Video Player\" aria-description=\"PSYC411-lm-dev-3\" ></iframe>\n```\n\n\n\n4. Part 4 (19 minutes): The linear model is very flexible, powerful and general.\n\n\n\n```{=html}\n<iframe src=\"https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=b559ac42-6752-4eaa-b3a9-af630116c7e8&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all\" height=\"405\" width=\"720\" style=\"border: 1px solid #464646;\" allowfullscreen allow=\"autoplay\" aria-label=\"Panopto Embedded Video Player\" aria-description=\"PSYC411-lm-dev-4\" ></iframe>\n```\n\n\n\n### 10.3.2 Lecture slides {#sec-lm-dev-lectures-slides}\n\n::: callout-tip\n## Download the lecture slides\nThe slides presented in the videos can be downloaded here:\n\n- [The slides](files/411-linear-model-develop.html) exactly as presented (11 MB). \n\nYou can download the web page `.html` file and click on it to open it in any browser (e.g., Chrome, Edge or Safari). The slide images are high quality so the file is quite big and may take a few seconds to download.\n:::\n\nWe are going to work through some practical exercises, next, to develop your critical thinking and practical skills for working with linear models.\n\n### 10.4 Practical materials: data and R-Studio {#sec-lm-dev-practical}\n\nWe will work with one data file which you can download by clicking on its name (below):\n\n-   [`2022-12-08_all-studies-subject-scores.csv`](files/2022-12-08_all-studies-subject-scores.csv).\n\nOnce you have downloaded the file, you will need to upload it to the R-Studio server to access it so that you can do the practical exercises.\n\n::: callout-important\nHere is a link to the sign-in page for [R-Studio Server](https://psy-rstudio.lancaster.ac.uk/auth-sign-in?appUri=%2F)\n:::\n\n### 10.4.1 Practical materials guide {#sec-lm-dev-practical-guide}\n\nAs usual, you will find that the practical exercises are simpler to do if you follow these steps in order.\n\n1. **The data** --- We will take a quick look at what is inside the data files so you know what everything means.\n2. **The `how-to` guide** --- We will go through the practical analysis and visualization coding steps, showing all the code required for each step.\n3. **The `practical` exercises** --- We will set out the tasks, questions and challenges that you should complete to learn the practical skills we target this week.\n\nThis week --- **Week 10** --- we aim to *further* develop skills in working with the linear model, and in visualizing and testing the associations between variables in psychological data.\n\n- While we build on everything you have learned so far, the skills you learn in this class unlock your capacity to analyse most kinds of data you will encounter in most situations: **a big expansion in the scope** of your capacities.\n\n::: callout-tip\n## Week 10 parts\n\n1. Set-up\n2. Load the data\n3. **Revision**: using a linear model to answer research questions -- one predictor.\n4. **New**: using a linear model to answer research questions -- multiple predictors.\n5. **New**: plot predictions from linear models with multiple predictors.\n6. **New**: estimate the effects of factors as well as numeric variables.\n7. **New**: examine associations comparing data from different samples.\n:::\n\nWe learn these skills so that we can answer research questions like:\n\n1. What person attributes predict success in understanding?\n\nQuestions like this are often answered by analyzing psychological data using some form of linear model.\n\nAs usual, when we do these analyses, we need to think about how we report the results, so part of the learning you will complete will enable you to:  \n\n- report information about the kind of model you specify;\n- report the nature of the associations (or effects) estimated in your model;\n- evaluate the results, making decisions about (i.) the significance of effects (ii.) whether estimates of effects suggest a positive or negative relationship between outcome and predictor (iii.) whether estimates of effects suggest a strong or a weak relationship.\n\nWe will really strengthen your ability to produce professional visualizations by learning how to translate model results into plots that help you and your audience to translate what your model tells you into accurate understanding and plain language.\n\n#### 10.4.1.1 The data files {#sec-lm-dev-practical-data}\n\nEach of the data files we have worked with has had a similar structure. This week, that continuity remains. But, this week, we move on to working with a *big* data-set similar to the data you may encounter in real-world situations.\n\n- **What is new** about this data-set is that it holds data from multiple studies in which the same methods were used -- these are *replication* studies -- enabling us to look the questions about *results reproducibility* across studies that you have been hearing about.\n\nHere are what the first few rows in the data file `all.studies.subjects` looks like:\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|ResponseId        | mean.acc| mean.self| AGE|GENDER |EDUCATION |ETHNICITY | SHIPLEY| HLVA| FACTOR3|NATIVE.LANGUAGE |study   |\n|:-----------------|--------:|---------:|---:|:------|:---------|:---------|-------:|----:|-------:|:---------------|:-------|\n|R_1lcaBAGJNNI2kju |     1.00|       7.6|  18|Female |Further   |White     |      31|   10|      48|English         |PSYC122 |\n|R_AG4jiTm8oxmuOOZ |     0.90|       7.6|  18|Female |Further   |White     |      35|   10|      40|English         |PSYC122 |\n|R_2Ckb6YXLPGwYSvg |     0.95|       7.2|  18|Male   |Further   |Asian     |      35|    9|      47|Other           |PSYC122 |\n|R_27JY5xHHcMs7jGi |     0.90|       6.8|  18|Female |Further   |White     |      35|    8|      52|English         |PSYC122 |\n|R_1DtJ4mrOXmxre01 |     0.85|       6.4|  19|Female |Further   |White     |      33|    9|      41|English         |PSYC122 |\n|R_PRFQFInzSS6T8e5 |     0.90|       6.2|  19|Female |Further   |Mixed     |      36|    5|      52|English         |PSYC122 |\n\n\n:::\n:::\n\n\n\n::: callout-tip\nThe webpage has a slider under the data table window, so you can scroll across the columns: move your cursor over the window to show the slider.\n:::\n\nWhen you look at the data table, you can see the columns:\n\n-   `ResponseId` participant code\n-   `mean.acc` average accuracy of response to questions testing understanding of health guidance\n-   `mean.self` average self-rated accuracy of understanding of health guidance\n-   `study` variable coding for what study the data were collected in\n-   `AGE` age in years\n-   `HLVA` health literacy test score\n-   `SHIPLEY` vocabulary knowledge test score\n-   `FACTOR3` reading strategy survey score\n-   `GENDER` gender code\n-   `EDUCATION` education level code\n-   `ETHNICITY` ethnicity (Office National Statistics categories) code\n\nYou can now see a new column:\n\n- `NATIVE.LANGUAGE` which codes for what language study participants grew up speaking (`English, Other`)\n\n#### 10.4.2 The how-to guide {#sec-lm-dev-practical-how-to}\n\nWe will take things *step-by-step*.\n\nMake sure you complete each part, task and question, in order, before you move on to the next one.\n\n#### 10.4.2.1 How-to Part 1: Set-up\n\nTo begin, we set up our environment in R.\n\n##### How-to Task 1 -- Run code to empty the R environment\n\n:::{.callout-tip collapse=\"true\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list=ls())                            \n```\n:::\n\n\n:::\n\n##### How-to Task 2 -- Run code to load libraries\n\nLoad libraries using `library()`.\n\n- Notice that we are working with libraries that may be new to you here.\n\n:::{.callout-tip collapse=\"true\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"ggeffects\")\nlibrary(\"patchwork\")\nlibrary(\"psych\")\nlibrary(\"tidyverse\")\n```\n:::\n\n\n:::\n\n#### 10.4.2.2 How-to Part 2: Load the data\n\n##### How-to Task 3 -- Read in the data file we will be using\n\nWe will be working with the data file:\n\n- `2022-12-08_all-studies-subject-scores.csv`.\n\nRead in the file -- using `read_csv()`.\n\n:::{.callout-tip collapse=\"true\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall.studies.subjects <- read_csv(\"2022-12-08_all-studies-subject-scores.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 615 Columns: 12\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (6): ResponseId, GENDER, EDUCATION, ETHNICITY, NATIVE.LANGUAGE, study\ndbl (6): mean.acc, mean.self, AGE, SHIPLEY, HLVA, FACTOR3\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n:::\n\n##### How-to Task 4 -- Inspect the data file\n\nIn previous classes, we have used the `summary()` function to inspect the data.\n\nNow, let's do something new.\n\nWe use the `describe()` function from the `{psych}` library to produce descriptive statistics for the variables in the data-set.\n\n:::{.callout-tip collapse=\"true\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndescribe(all.studies.subjects)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 vars   n   mean     sd median trimmed    mad   min max  range\nResponseId*         1 615 308.00 177.68  308.0  308.00 228.32  1.00 615 614.00\nmean.acc            2 561   0.73   0.21    0.8    0.76   0.22  0.15   1   0.85\nmean.self           3 561   6.53   1.72    6.8    6.69   1.78  1.00   9   8.00\nAGE                 4 615  28.34  13.56   23.0   25.59   5.93 18.00 100  82.00\nGENDER*             5 615   1.32   0.54    1.0    1.25   0.00  1.00   5   4.00\nEDUCATION*          6 615   1.73   0.64    2.0    1.67   0.00  1.00   3   2.00\nETHNICITY*          7 615   2.75   1.95    1.0    2.69   0.00  1.00   5   4.00\nSHIPLEY             8 615  28.98   9.52   32.0   30.48   7.41  0.00  40  40.00\nHLVA                9 615   7.22   3.09    8.0    7.49   2.97  0.00  13  13.00\nFACTOR3            10 615  44.03  14.67   48.0   46.69   8.90  0.00  63  63.00\nNATIVE.LANGUAGE*   11 615   1.54   0.50    2.0    1.55   0.00  1.00   2   1.00\nstudy*             12 615   4.04   2.69    4.0    3.92   2.97  1.00   8   7.00\n                  skew kurtosis   se\nResponseId*       0.00    -1.21 7.16\nmean.acc         -0.83    -0.31 0.01\nmean.self        -0.86     0.49 0.07\nAGE               2.05     4.70 0.55\nGENDER*           2.15     8.21 0.02\nEDUCATION*        0.30    -0.70 0.03\nETHNICITY*        0.25    -1.90 0.08\nSHIPLEY          -1.47     1.96 0.38\nHLVA             -0.69     0.00 0.12\nFACTOR3          -1.85     3.25 0.59\nNATIVE.LANGUAGE* -0.15    -1.98 0.02\nstudy*            0.29    -1.46 0.11\n```\n\n\n:::\n:::\n\n\n:::\n\nIn the reports you write -- whether as a student or, later, in your professional work -- you may often be required to present table summaries of the variables in your data, incorporating descriptive statistics.\n\n- You can use the `describe()` function to get R to do the work for you.\n\nWe want to get just the descriptive statistics we want. \n\nWe are going to do this in two steps: \n\n1. we select the variables we care about;\n2. we get just the descriptive statistics we want for those variables\n\nWe will do this using *two different* but equivalent methods.\n\nFirst, we are going to do this using the `%>%` pipes that you saw previously (in week 5):\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall.studies.subjects %>%\n  select(mean.acc, mean.self, AGE, SHIPLEY, HLVA, FACTOR3) %>%\n  describe(skew = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          vars   n  mean    sd median   min max range   se\nmean.acc     1 561  0.73  0.21    0.8  0.15   1  0.85 0.01\nmean.self    2 561  6.53  1.72    6.8  1.00   9  8.00 0.07\nAGE          3 615 28.34 13.56   23.0 18.00 100 82.00 0.55\nSHIPLEY      4 615 28.98  9.52   32.0  0.00  40 40.00 0.38\nHLVA         5 615  7.22  3.09    8.0  0.00  13 13.00 0.12\nFACTOR3      6 615 44.03 14.67   48.0  0.00  63 63.00 0.59\n```\n\n\n:::\n:::\n\n\n\nThese are the code elements and what they do:\n\n1. `all.studies.subjects %>%` -- you tell R to use the `all.studies.subjects` dataset, then use `%>%` to ask R to take those data to the next step.\n2. `select(mean.acc, mean.self, AGE, SHIPLEY, HLVA, FACTOR3) %>%` -- you tell R to select just those variables in `all.studies.subjects` that you name and `%>%` pipe them to the next step.\n3. `describe(...)` -- you tell R to give you descriptive statistics for the variables you have selected.\n4. `describe(skew = FALSE)` -- critically, you add the argument `skew = FALSE` to *turn off* the option in `describe()` to report skew, kurtosis: because we do not typically see these statistics reported in psychology.\n\n::: callout-tip\nModern R coding often uses the pipe. When you see it, you see it used in a process involving a series of steps.\n\n- Do this thing, then send the results `%>` to the next step, do the next thing then send the results `%>%` to the next step...\n- When you look at `ggplot()` code, the `+` at the end of each line of plotting code is doing a similar job to the pipe.\n:::\n\nNot everyone is comfortable coding this way so next we will do the same thing in an *old style*.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall.studies.subjects.select <- select(all.studies.subjects, \n                           mean.acc, mean.self, AGE, SHIPLEY, HLVA, FACTOR3)\ndescribe(all.studies.subjects.select, skew = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          vars   n  mean    sd median   min max range   se\nmean.acc     1 561  0.73  0.21    0.8  0.15   1  0.85 0.01\nmean.self    2 561  6.53  1.72    6.8  1.00   9  8.00 0.07\nAGE          3 615 28.34 13.56   23.0 18.00 100 82.00 0.55\nSHIPLEY      4 615 28.98  9.52   32.0  0.00  40 40.00 0.38\nHLVA         5 615  7.22  3.09    8.0  0.00  13 13.00 0.12\nFACTOR3      6 615 44.03 14.67   48.0  0.00  63 63.00 0.59\n```\n\n\n:::\n:::\n\n\n\nThese are the code elements and what they do:\n\n1. `all.studies.subjects.select <- ...(all.studies.subjects, ...)` -- you tell R to create a new dataset `all.studies.subjects.select` from the original `all.studies.subjects` -- the new dataset will include just the variables we select from the original.\n2. `select(all.studies.subjects, ...)` -- you tell R to select the variables you want using the `select(...)` function: telling R to select variables from `all.studies.subjects`.\n3. `... select(..., mean.acc, mean.self, AGE, SHIPLEY, HLVA, FACTOR3)` -- you tell R to select the variables you want by entering the variable names, separated by commas, after you have named the dataset.\n4. `describe(...)` -- you tell R to give you descriptive statistics.\n5. `describe(all.studies.subjects.select, ...)` -- you name the dataset with the selection of variables you have created, telling the `describe()` function what data to work with.\n5. `describe(skew = FALSE)` -- critically, you add the argument `skew = FALSE` to turn off the option to report skew, kurtosis to keep the descriptive statistics short.\n\n**What are we learning here?**\n\nFirst, we can do exactly the same thing in two different but related ways:\n\n- Use the way that (1.) works and (2.) you prefer.\n- Which should you prefer? You may reflect on how easy the code is to write, read, understand and use\n\nSecond, we modify how the function `describe()` works by adding an argument: `describe(skew = FALSE)`.\n\n- We have been doing this kind of move, already, by adding arguments to, e.g., specify point colour in `ggplot()` code.\n\nAs your skills advance, so your preferences on how you want R to work for you will become more specific.\n\n- You can modify the outputs from functions so that you get exactly what you want *in the way that you want it*.\n\nThe information on the options available to you for any argument can be found in different kinds of places, see the further information box, below.\n\n::: callout-tip\n## Further information you can explore\n\n1. Here is an explanation for how to use pipes `%>%` when you code and why it may be helpful to do so:\n\n<https://r4ds.had.co.nz/pipes.html>\n\nNote that we do not *require* the use of pipes in PSYC411: we are showing you this to expand your knowledge.\n\n2. You can get a guide to the `{psych}` library here:\n\n<http://personality-project.org/r/psych/vignettes/intro.pdf>\n\nEvery \"official\" R library has a technical manual on the central R resource CRAN, and the manual for 'psych' can be found here:\n\n<https://cran.r-project.org/web/packages/psych/psych.pdf>\n\n- where you can see information on the functions the library provides, and how you can use each function.\n\nThis is how you ask for help in R for a function, e.g., just type: `?describe` or\n`help(describe)`.\n\nThe `{psych}` library is written by William Revelle who provides a lot of useful resources here:\n\n<http://personality-project.org/r/psych/>\n:::\n\n#### 10.4.2.3 How-to Part 3: Using a linear model to answer research questions -- one predictor\n\n##### How-to Task 5 -- Examine the relation between outcome mean accuracy (`mean.acc`) and health literacy (`HLVA`)\n\nOne of our research questions is:\n\n1. What person attributes predict success in understanding?\n\nHere, we can address the question directly because we have information on an outcome, mean accuracy (`mean.acc`), and information on a predictor, health literacy (`HLVA`).\n\n- Given the theoretical account outlined in [the chapter for week 7](../part2/hypotheses-associations.qmd#sec-associations-overview), our hypothesis is that people who possess a higher level of background knowledge, measured here using the health literacy (`HLVA`) test, will be more likely to accurately understand health information when they read it, with understanding tested to calculate the mean accuracy (`mean.acc`).\n- This hypothesis translates into a statistical prediction: if people in our sample have higher `HLVA` scores, we predict that, on average, they will also have higher `mean.acc` scores.\n\nTo address the research question, we test the statistical prediction using the linear model:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.acc ~ HLVA, data = all.studies.subjects)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ HLVA, data = all.studies.subjects)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.59375 -0.11731  0.02981  0.13269  0.37100 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.414250   0.025912   15.99   <2e-16 ***\nHLVA        0.041188   0.003182   12.94   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1853 on 559 degrees of freedom\n  (54 observations deleted due to missingness)\nMultiple R-squared:  0.2306,\tAdjusted R-squared:  0.2292 \nF-statistic: 167.5 on 1 and 559 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n  \nIf you look at the model summary you can answer the following questions  \n\n> Q.1. What is the estimate for the coefficient of the effect of the predictor, HLVA?\n\n:::{.callout-tip collapse=\"true\"}\n> A.1. 0.041188 \n:::\n\n> Q.2. Is the effect significant?\n\n:::{.callout-tip collapse=\"true\"}\n> A.2. It is significant because p < .05\n:::\n\n> Q.3. What are the values for t and p for the significance test for the coefficient?\n\n:::{.callout-tip collapse=\"true\"}\n> A.3. t = 12.94, p <2e-16\n:::\n\n> Q.4. What do you conclude is the answer to the research question, given the linear model results?\n\n:::{.callout-tip collapse=\"true\"}\n> A.4. The model slope estimate suggests that as `HLVA` scores increase so also do `mean.acc` scores.\n:::\n\n> Q.5. What is the F-statistic for the regression? Report F, DF and the p-value.\n\n:::{.callout-tip collapse=\"true\"}\n> A.5. F-statistic: 167.5 on 1 and 559 DF,  p-value: < 2.2e-16\n:::\n\n> Q.6. Is the regression significant?\n\n:::{.callout-tip collapse=\"true\"}\n> A.6. Yes: the regression is significant.\n:::\n\n> Q.7. What is the Adjusted R-squared?\n\n:::{.callout-tip collapse=\"true\"}\n> A.7. Adjusted R-squared:  0.2292\n:::\n\n> Q.8. Explain in words what this R-squared value indicates?\n\n:::{.callout-tip collapse=\"true\"}\n> A.8. The R-squared suggests that 23% of outcome variance can be explained \n# by the model\n:::\n\n**What are we learning here?**\n\nIt is worth your time reflecting, here, on how statistical analyses are incorporated in research work.\n\n1. We have ideas about a psychological process: e.g., reading comprehension.\n2. We have assumptions of a theoretical account of that process: e.g., we use background knowledge to understand what we read.\n3. Given those assumptions, we derive hypotheses that we translate into statistical predictions: e.g., higher health literacy predicts higher accuracy of understanding.\n4. We test a statistical prediction using a method like `lm()`, specifying a model that aligns with the prediction terms: the outcome, the predictor(s).\n\n::: callout-tip\nThinking ahead to your dissertation project, can you reflect on the research question you will hope to answer, how you will address that question through measurement, then data analysis to test a statistical prediction?\n:::\n\n#### 10.4.2.4 How-to Part 4: Using a linear model to answer research questions -- multiple predictors\n\n##### How-to Task 6 --Examine the relation between outcome mean accuracy (`mean.acc`) and multiple predictors including: health literacy (`HLVA`); vocabulary (`SHIPLEY`); `AGE`; reading strategy (`FACTOR3`)\n\nWe saw that our research question is:\n\n1. What person attributes predict success in understanding?\n\nIn the previous task, we tried to model success in understanding using just one predictor variable but it is unrealistic that a person's capacity to understand health information will be predicted by just one thing, their background knowledge.\nIt is more likely that variation on multiple dimensions will predict understanding.\n\nWhat could those variables be?\n\nWe can examine the relation between outcome mean accuracy (`mean.acc`) and multiple predictors simultaneously.\nHere, the candidate predictor variables include: health literacy (`HLVA`); vocabulary (`SHIPLEY`); `AGE`; reading strategy (`FACTOR3`).\n\nWe can incorporate all predictors together in a linear model: we use `lm()`, as before, but now specify each variable listed here by variable name.\n\n:::{.callout-tip collapse=\"true\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.acc ~ HLVA + SHIPLEY + FACTOR3 + AGE, data = all.studies.subjects)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ HLVA + SHIPLEY + FACTOR3 + AGE, data = all.studies.subjects)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.57543 -0.08115  0.02303  0.11169  0.38810 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.0996243  0.0468313   2.127   0.0338 *  \nHLVA         0.0274954  0.0032461   8.470  < 2e-16 ***\nSHIPLEY      0.0083457  0.0011430   7.302 9.88e-13 ***\nFACTOR3      0.0050332  0.0009246   5.444 7.84e-08 ***\nAGE         -0.0025503  0.0005074  -5.026 6.75e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1668 on 556 degrees of freedom\n  (54 observations deleted due to missingness)\nMultiple R-squared:  0.3799,\tAdjusted R-squared:  0.3755 \nF-statistic: 85.17 on 4 and 556 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n:::\n\nIf we look closely at this code example, we can first identify the working elements in the linear model code, but then we can identify some general properties that it will be useful to you to learn about.\n\nFirst, let's work through the elements of the linear model code so we can see what everything does:\n\n1. `model <- lm(...)` -- tell R you want to fit the model using `lm(...)`, and give the model a name: here, we call it \"model\".\n2. `...lm(mean.acc ~ HLVA...)` -- tell R you want a model of the outcome `mean.acc` predicted `~` by the predictors: `HLVA`, `SHIPLEY`, `FACTOR3`, `AGE`.\n\n- Note that we use the variable names as they appear in the dataset, and that each predictor variable is separated from the next by a plus sign.\n\n3. `...data = all.studies.subjects)` -- tell R that the variables you name in the formula are in the `all.studies.subjects` data-set.\n4. `summary(model)` -- ask R for a summary of the model you called \"model\": **this is how you get the results**.\n\n::: callout-tip\nNotice that R has a general formula syntax: `outcome ~ predictor` *or* `y ~ x`\n\n- and uses the same format across a number of different functions;\n- each time, on the left of the tilde symbol `~` you identify the output or outcome variable;\n- here, **what is new** is that you see on the right of the tilde `~` multiple predictor variables: `y ~ x1 + x2 + ...`\n:::\n\nIf you look at the model summary you can answer the following questions.\n\n(We have hidden the answers -- so that you can test yourself -- but you can reveal each answer by clicking on the box.)\n\n> Q.7. What is the estimate for the coefficient of the effect of the predictor `HLVA` in *this* model?\n\n:::{.callout-tip collapse=\"true\"}\n## Answer\n> A.7. 0.0274954 \n:::\n\n> Q.8. Is the effect significant?\n\n:::{.callout-tip collapse=\"true\"}\n## Answer\n> A.8. It is significant because p < .05.\n:::\n\n> Q.9. What are the values for t and p for the significance test for the coefficient?\n\n:::{.callout-tip collapse=\"true\"}\n## Answer\n> A.9. t = 8.470, p < 2e-16\n:::\n\n> Q.10. What do you conclude is the answer to the research question, given the linear model results?\n\n:::{.callout-tip collapse=\"true\"}\n## Answer\n> A.10. The model slope estimate 0.0274954 suggests that as HLVA scores \n# increase so also do mean.acc scores\n:::\n\n> Q.11. How is the coefficient estimate for the HLVA slope similar or different, comparing this model with multiple predictors to the previous model with one predictor?\n\n:::{.callout-tip collapse=\"true\"}\n## Answer\n> A.11. It can be seen that the HLVA estimate in the two models is different in that it is a bit smaller in the model with multiple predictors compared to the model with one predictor. The HLVA estimate is similar in that it remains positive, and it is about the same size.\n:::\n\n**What are we learning here?**\n\nThe estimate of the coefficient of any one predictor can be expected to vary depending on the presence of other predictors.\n\n- This is one reason why we need to be transparent about why we choose to use the predictors we include in our model.\n- The lecture for this week discusses this concern in relation to the motivation for good open science practices.\n\n> Q.12. Can you report the estimated effect of `SHIPLEY` (the measure of vocabulary)?\n\n:::{.callout-tip collapse=\"true\"}\n## Answer\n> A.12. The effect of vocabulary knowledge (`SHIPLEY`) on mean accuracy of understanding is significant (estimate = 0.01, t = 7.30, p < .001), indicating that increasing skill is associated with increasing accuracy.\n:::\n\n> Q.13. Can you report the model and the model fit statistics?\n\n:::{.callout-tip collapse=\"true\"}\n## Answer\n> A.13. We fitted a linear model with mean comprehension accuracy as the outcome and health literacy (`HLVA`),  reading strategy (`FACTOR3`), vocabulary (`SHIPLEY`) and `AGE` (in years) as predictors. The model is significant overall, with F(4, 556) = 85.17, p < .001, and explains 38% of variance (adjusted R2 = 0.38).\n:::\n\n#### 10.4.2.5 How-to Part 5: Plot predictions from linear models with multiple predictors\n\n##### How-to Task 7 -- Produce and plot model results using R functions that make the process easier\n\nWe can begin by plotting linear model predictions for one of the predictors in the multiple predictors model we have been working with.\n\n- Previously, we used `geom_abline()`, specifying intercept and slope estimates, to produce and plot model predictions.\n- Here, we use functions that are very helpful when we need to plot model predictions for a predictor, for models where we have multiple predictors.\n\nWe do this in three steps:\n\n1. We first fit a linear model of the outcome, given our predictors, and we save information about the model.\n2. We use the `ggpredict()` function from the `{ggeffects}` library to take the information about the model and create a set of predictions we can use for plotting.\n3. We plot the model predictions, producing what are also called *marginal effects* plots.\n\nWe write the code to do the work as follows.\n\n1. We first fit a linear model of the outcome, given our predictors:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.acc ~ HLVA + SHIPLEY + FACTOR3 + AGE, \n                         data = all.studies.subjects)\n```\n:::\n\n\n\n- `model <- lm(...)` -- we fit the model using `lm(...)`, giving the model a name: \"model\".\n- `...lm(mean.acc ~ HLVA + ... + ...)` -- this model estimates how the outcome `mean.acc` changes, is predicted `~` given information about the predictors `HLVA`, `SHIPLEY`, `FACTOR3`, and `AGE`.\n- Notice: when we use `lm()` to fit the model, R creates a set of information about the model, including estimates.\n- We give that set of information a name (\"model\"), and we use that name, next, to call on and use the model information to make the plot.\n\n2. We use the `ggpredict()` function from the `{ggeffects}` library to take the information about the model and create a set of predictions we can use for plotting:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- ggpredict(model, \"HLVA\")\n```\n:::\n\n\n\n- `dat <- ggpredict(...)` -- we ask R to create a set of predictions, and we give that set of predictions a name `dat`.\n- `... ggpredict(model, \"HLVA\")` -- we tell R what model information it should use (from \"model\"), and which predictor variable we need predictions for: `HLVA`.\n\n3. We plot the model predictions (marginal effects plots):\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(dat)\n```\n\n::: {.cell-output-display}\n![](lm-dev_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\n::: callout-tip\n## Further information you can explore\nIn producing prediction plots, we are using functions from the `{ggeffects}` library. Can you locate online information about working with the library functions?\n\n- Try doing a search with the key words: `in r ggeffects`.\n\nIf you do that, you will see links to the website:\n\n<https://strengejacke.github.io/ggeffects/>\n\nIn the `{ggeffects}` online information, you can see links to practical examples. Can you use the information under `Practical examples` to adjust the appearance of the prediction plots?\n:::\n\n##### How-to Task 8 -- *Optional* -- Edit the appearance of the marginal effect (prediction) plot as you can with any `ggplot` object\n\nOnce we have created the model predictions plot, we can edit it like we would edit any other `ggplot` object.\n\n- This is clearly advanced but it helps you to see just how powerful your capabilities can be if you aim to develop skills in this kind of work.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np.model <- plot(dat)\np.model +\n  geom_point(data = all.studies.subjects, \n             aes(x = HLVA, y = mean.acc), size = 1.5, alpha = .75, colour = \"lightgreen\") +\n  geom_line(linewidth = 1.5) +\n  ylim(0, 1.1) + xlim(0, 16) +\n  theme_bw() +\n  theme(\n    axis.text = element_text(size = rel(1.15)),\n    axis.title = element_text(size = rel(1.25)),\n    plot.title = element_text(size = rel(1.4))\n  ) +\n  xlab(\"Health literacy (HLVA)\") + ylab(\"Mean accuracy\") +\n  ggtitle(\"Effect of health literacy on mean comprehension accuracy\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nScale for y is already present.\nAdding another scale for y, which will replace the existing scale.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 54 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](lm-dev_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n\nWe do this in stages, as we have done for other kinds of plots:\n\n1. `p.model <- plot(dat)` -- we create a plot object, which we call 'p.model'.\n2. `p.model +` -- we then set up the first line of a series of code lines, starting with the name of the plot, `p.model` and a `+` to show we are going to add some edits.\n3. `geom_point(data = all.studies.subjects, aes(x = HLVA, y = mean.acc) ...)` -- we first add the raw data points showing the observed `HLVA` and `mean.acc` for each person in our sample.\n4. `geom_point(... size = 1.5, alpha = .75, colour = \"lightgreen\") +` -- we modify the appearance of the points, then\n5. `geom_line(size = 1.5) +` -- we add the prediction line, using the predictions created earlier, then\n6. `ylim(0, 1.1) + xlim(0, 16) +` -- we set axis limits to show the full potential range of variation in each variable, then\n7. `theme_bw()` -- we set the theme to black and white, then\n8. `theme(axis.text = element_text(size = rel(1.15)), ...)` -- we modify the relative size of x-axis, y-axis and plot title label font, then\n9. `xlab(\"Health literacy (HLVA)\") + ylab(\"Mean accuracy\") +` -- we edit labels to make them easier to understand, then\n10. `ggtitle(\"Effect of health literacy on mean comprehension accuracy\")` -- we give the plot a title\n\nNotice that we are constructing a complex plot from two datasets:\n\n- We use `plot(dat)` to construct a plot from (1.) the set of predictions, showing the prediction line using `geom_line(size = 1.5) + ` \n- We then add a layer to the plot to show (2.) the raw sample data, using\n`geom_point(data = all.studies.subjects, ...)` -- to tell R to work with the sample data-set `all.studies.subjects`, and to show points representing the (aesthetic mappings) values, given that sample data, for (`x = HLVA, y = mean.acc`).\n\n**What are we learning here?**\n\nThis complex plot is a good example of:\n\n1. How we can plot summary of prediction data plus observed outcomes, and this connects to the classes on visualization.\n2. How we can add layers of edits, or geometric objects, together to create complex plots that can show our audience messages like, here, that there is an average trend (shown by the line) but that individual outcomes vary quite a bit from the average.\n\n::: callout-tip\nNo model will be perfect.\n\n- It is often useful to compare model estimates -- here, the slopes -- with the raw data observations.\n- Visualizing the difference between what we observe and what we predict helps to make sense of how our prediction model could be improved.\n:::\n\n##### How-to Task 9 -- *Optional* -- Now produce plots that show the predictions for all the predictor variables in the model\n\nThis is optional but we offer the task as an opportunity for practice with these notes.\n\n1. The code may get pretty lengthy.\n2. You will need to adjust axis labels so for each plot we see the correct predictor as the x-axis label\n3. You will give the plot titles as letters a-e so that, if you put this plot in a report, you can refer to each plot by letter in comments in a report.\n\n:::{.callout-tip collapse=\"true\"}\n## Code\nWe will use the `{Patchwork}` library:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(patchwork)\n```\n:::\n\n\n\nFirst, fit the model and get the model information:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.acc ~ HLVA + SHIPLEY + FACTOR3 + AGE, \n                         data = all.studies.subjects)\n```\n:::\n\n\n\nSecond, get the predictions, given the model information, for two different predictor variables.\n\n- Notice that I use different names for different sets of predictors.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.HLVA <- ggpredict(model, \"HLVA\")\ndat.SHIPLEY <- ggpredict(model, \"SHIPLEY\")\n```\n:::\n\n\n  \nThird, produce plots of the predictions, giving each *plot object* a different plot name.\n\n- Notice that I use different names for different sets of predictors.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot.HLVA <- plot(dat.HLVA)\nplot.SHIPLEY <- plot(dat.SHIPLEY)\n```\n:::\n\n\n  \nLast, put the two plots together by calling their names.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot.HLVA + plot.SHIPLEY\n```\n\n::: {.cell-output-display}\n![](lm-dev_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\nThe `{Patchwork}` library functions are *really* powerful and the documentation information is *really* helpful:\n\n<https://patchwork.data-imaginist.com/articles/patchwork.html>\n:::\n\n**What are we learning here?**\n\nIf you follow the code example, and learn how to:\n\n1. complete a linear model analysis with multiple predictors and \n2. present the model results, for all effects (estimates of the impact of all predictors) simultaneously\n\n- then *this* is a big deal, as a skill development learning achievement\n- because knowing about this process, and knowing how to do it, *unlocks* an important advanced analysis and visualization skill.\n\n::: callout-tip\nKnowing how to follow this model $\\rightarrow$ visualization workflow gives you a competitive advantage in future professional settings (job applications, interviews, workplace) because not many Psychology graduates can do it, yet.\n:::\n\n#### 10.4.2.6 How-to Part 6: **New**: estimate the effects of factors as well as numeric variables\n\nAs we have seen, one of our research questions is:\n\n1. What person attributes predict success in understanding?\n\nWe have not yet included any categorical or nominal variables as predictors but we can, and should: `lm()` can cope with any kind of variable as a predictor.\n\n::: callout-tip\nIn Part 4 of the Week 10 lectures, I explain that fundamentally every kind of analysis you have learnt before (t-test, ANOVA, etc.) can be understood as a kind of linear model. This part shows how that works.\n\n- In a (two groups) t-test, you are comparing the average outcome between two different groups.\n- To do that analysis, you need an outcome variable (like `mean.acc`) and a categorical variable or factor (like, say, experimental condition: condition 1 versus condition 2). \n- Here, we see how you can do the same kind of group comparison using a linear model.\n:::\n\nThere are different ways to do this, here we look at one. Extra information about the second can be found in the drop-down box, following.\n\n##### How-to Task 10 -- Fit a linear model including both numeric variables and categorical variables as predictors model including both numeric variables and categorical variables as predictors\n\nWe begin by inspecting the data to check what variables are categorical or nominal variables -- factors -- using `summary()`.\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(all.studies.subjects)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  ResponseId           mean.acc       mean.self          AGE        \n Length:615         Min.   :0.150   Min.   :1.000   Min.   : 18.00  \n Class :character   1st Qu.:0.600   1st Qu.:5.600   1st Qu.: 20.00  \n Mode  :character   Median :0.800   Median :6.800   Median : 23.00  \n                    Mean   :0.734   Mean   :6.529   Mean   : 28.34  \n                    3rd Qu.:0.900   3rd Qu.:7.800   3rd Qu.: 30.50  \n                    Max.   :1.000   Max.   :9.000   Max.   :100.00  \n                    NA's   :54      NA's   :54                      \n    GENDER           EDUCATION          ETHNICITY            SHIPLEY     \n Length:615         Length:615         Length:615         Min.   : 0.00  \n Class :character   Class :character   Class :character   1st Qu.:25.00  \n Mode  :character   Mode  :character   Mode  :character   Median :32.00  \n                                                          Mean   :28.98  \n                                                          3rd Qu.:36.00  \n                                                          Max.   :40.00  \n                                                                         \n      HLVA           FACTOR3      NATIVE.LANGUAGE       study          \n Min.   : 0.000   Min.   : 0.00   Length:615         Length:615        \n 1st Qu.: 5.000   1st Qu.:41.00   Class :character   Class :character  \n Median : 8.000   Median :48.00   Mode  :character   Mode  :character  \n Mean   : 7.224   Mean   :44.03                                        \n 3rd Qu.: 9.500   3rd Qu.:53.00                                        \n Max.   :13.000   Max.   :63.00                                        \n                                                                       \n```\n\n\n:::\n:::\n\n\n:::\n\n`summary()` gives you the information you need because R shows factors with a count of the number of observations for each level.\n\nWe can build on our previous work by including the factor `NATIVE.LANGUAGE` as a predictor:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.acc ~ HLVA + SHIPLEY + FACTOR3 + AGE + NATIVE.LANGUAGE, \n            data = all.studies.subjects)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ HLVA + SHIPLEY + FACTOR3 + AGE + NATIVE.LANGUAGE, \n    data = all.studies.subjects)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.55939 -0.08115  0.02056  0.10633  0.41598 \n\nCoefficients:\n                       Estimate Std. Error t value Pr(>|t|)    \n(Intercept)           0.1873086  0.0472991   3.960 8.47e-05 ***\nHLVA                  0.0242787  0.0031769   7.642 9.44e-14 ***\nSHIPLEY               0.0073947  0.0011144   6.635 7.70e-11 ***\nFACTOR3               0.0053455  0.0008947   5.975 4.12e-09 ***\nAGE                  -0.0026434  0.0004905  -5.390 1.05e-07 ***\nNATIVE.LANGUAGEOther -0.0900035  0.0141356  -6.367 4.04e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1612 on 555 degrees of freedom\n  (54 observations deleted due to missingness)\nMultiple R-squared:  0.4221,\tAdjusted R-squared:  0.4169 \nF-statistic: 81.09 on 5 and 555 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nNow, take a look at the results to answer the following questions.\n\n> Q.14. Can you report the estimated effect of `NATIVE.LANGUAGE` (the coding of participant language status: `English` versus `Other`)?\n\n:::{.callout-tip collapse=\"true\"}\n> A.14. The effect of language status (`NATIVE.LANGUAGE`) on mean accuracy of \n understanding is significant (estimate = -0.09, t = -6.37, p < .001) indicating that not being a native speaker of English ('Other') is associated with lower accuracy.\n:::\n\n> Q.15. Can you report the model and the model fit statistics?\n\n:::{.callout-tip collapse=\"true\"}\n> A.15. We fitted a linear model with mean comprehension accuracy as the outcome and health literacy (`HLVA`), reading strategy (`FACTOR3`), vocabulary (`SHIPLEY`) and `AGE` (years), as well as language status as predictors. The model is significant overall, with F(5, 555) = 81.09, p < .001, and explains 42% of variance (adjusted R2 = 0.42).\n:::\n\n> Q.16. What changes, when you compare the models with versus without `NATIVE.LANGUAGE`?\n\n:::{.callout-tip collapse=\"true\"}\n> A.16. If you compare the summaries, for the last two models, you can see that the proportion of variance explained, `R-sq`, increases to 42% (0.4221), suggesting that knowing about participant language background helps to account for their response accuracy in tests of comprehension of health advice.\n:::\n\n**What are we learning here?**\n\nWhat are factors?\n\n- A *factor* is a categorical variable.\n- Categorical variables have a \"fixed and known set of possible values\", for example, maybe you are working with the factor `EDUCATION`: in the data collection process, answers to the question \"What is your education level?\" can have only one of three possible values (`further, higher, secondary`).\n- For any factor, different values of the variable are called `levels` so, for `EDUCATION` the different levels are: `further, higher, secondary`\n\nR treats factors differently from other kinds of variables:\n\n1. R *will not* give you summary statistics (e.g., a mean) for values of a factor. It can't because: what is the mean of education?\n2. R *will* count the number of times each `level` in a `factor` appears in a sample.\n3. If you are plotting a bar chart or a boxplot to show outcomes for different groups or conditions then the group or condition coding variable (e.g., `aes(x = group)`) has to be a factor.\n\nR handles factors, by default, by picking one level (e.g., `English`) as the reference level (or baseline) and comparing outcomes to that baseline, for each other factor level (here, `Other`).\n\n- This is why, in the summary of estimates for this model, the effect of `NATIVE.LANGUAGE` is estimated as the average difference in `mean.acc` outcome for `English` compared to `Other` participants.\n- This is why the effect is listed as: `NATIVE.LANGUAGEOther` in the summary table for the model\n\n::: callout-tip\n## Further information you can explore\nNote that I quote, here, from the powerful `{forcats}` library of tools for working with factors:\n\n<https://forcats.tidyverse.org/>\n\nYou can read more about factor coding schemes here:\n\n<https://talklab.psy.gla.ac.uk/tvw/catpred/>\n\nand here:\n\n<https://phillipalday.com/stats/coding.html>\n:::\n\n:::{.callout-tip collapse=\"true\"}\n## Extra information for students interested in ANOVAs\n\nThere are different ways to code factors for analysis:\n\n- If you are doing an analysis where your data come from, say, a factorial design (e.g. a 2 x 2 study design) then you will want to use a different coding scheme: *sum* or *effect* coding.\n\nIt is easy to do this, in two steps, proceeding as follows.\n  \n1. We first change the coding scheme.\n\n- Get the `{memisc}` library:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(memisc)\n```\n:::\n\n\n\n- Make sure that the variable is being treated as a factor:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall.studies.subjects$NATIVE.LANGUAGE <- as.factor(all.studies.subjects$NATIVE.LANGUAGE)\n```\n:::\n\n\n\n- Check the coding:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrasts(all.studies.subjects$NATIVE.LANGUAGE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        Other\nEnglish     0\nOther       1\n```\n\n\n:::\n:::\n\n\n\n- Change the coding\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrasts(all.studies.subjects$NATIVE.LANGUAGE) <- contr.sum(2, base = 1)\n```\n:::\n\n\n\nThe arguments in `contr.sum(2, base = 1)` tell R which level we want to be the reference level.\n\n- Check the coding to show you got what you want:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrasts(all.studies.subjects$NATIVE.LANGUAGE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         2\nEnglish -1\nOther    1\n```\n\n\n:::\n:::\n\n\n\n2. We then fit a linear model of the outcome, given our predictors:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.acc ~ HLVA + SHIPLEY + FACTOR3 + AGE + NATIVE.LANGUAGE, \n            data = all.studies.subjects)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ HLVA + SHIPLEY + FACTOR3 + AGE + NATIVE.LANGUAGE, \n    data = all.studies.subjects)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.55939 -0.08115  0.02056  0.10633  0.41598 \n\nCoefficients:\n                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       0.1423068  0.0457437   3.111  0.00196 ** \nHLVA              0.0242787  0.0031769   7.642 9.44e-14 ***\nSHIPLEY           0.0073947  0.0011144   6.635 7.70e-11 ***\nFACTOR3           0.0053455  0.0008947   5.975 4.12e-09 ***\nAGE              -0.0026434  0.0004905  -5.390 1.05e-07 ***\nNATIVE.LANGUAGE2 -0.0450018  0.0070678  -6.367 4.04e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1612 on 555 degrees of freedom\n  (54 observations deleted due to missingness)\nMultiple R-squared:  0.4221,\tAdjusted R-squared:  0.4169 \nF-statistic: 81.09 on 5 and 555 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n:::\n\n> Optional.Q.1. What changes, when you compare the models with versus without sum coding of `NATIVE.LANGUAGE`?\n\n:::{.callout-tip collapse=\"true\"}\n> Optional.A.1. If you compare the summaries, for the last two models, you can see that the estimate for the coefficient of `NATIVE.LANGUAGE` changes in two ways: \n\n> 1. the name changes, from `NATIVE.LANGUAGEOther` to `NATIVE.LANGUAGE2`, reflecting the change in coding;\n\n> 2. the slope estimate changes, from `-0.0900035` to `-0.0450018`.\n\n> Note: the change in the estimate happens because we go from estimating the average difference in level between 0 (`English`) versus 1 (`Other`), a change of one unit to estimating the average difference in level between -1 (`English`) versus 1 (`Other`), a change of 2 units.\n\nBeing able to change the coding of nominal or categorical variables is very useful.\nAnd enables you to do ANOVA style analyses given factorial study designs e.g.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- aov(lm(mean.acc ~ HLVA + SHIPLEY + FACTOR3 + AGE + NATIVE.LANGUAGE, \n       data = all.studies.subjects))\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 Df Sum Sq Mean Sq F value   Pr(>F)    \nHLVA              1  5.753   5.753  221.47  < 2e-16 ***\nSHIPLEY           1  2.272   2.272   87.44  < 2e-16 ***\nFACTOR3           1  0.751   0.751   28.92 1.11e-07 ***\nAGE               1  0.703   0.703   27.06 2.78e-07 ***\nNATIVE.LANGUAGE   1  1.053   1.053   40.54 4.04e-10 ***\nResiduals       555 14.418   0.026                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n54 observations deleted due to missingness\n```\n\n\n:::\n:::\n\n\n\nNotice: we use `aov()` to get an ANOVA summary for the model.\n\nAs before, you can fit a linear model including both numeric variables and categorical variables as predictors: and then plot the predicted effect of the factor.\n\n- We first fit the model, including `NATIVE.LANGUAGE` then use the ggpredict() function to get the predictions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- ggpredict(model, \"NATIVE.LANGUAGE\")\nplot(dat)\n```\n\n::: {.cell-output-display}\n![](lm-dev_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n:::\n\n#### 10.4.2.7 How-to Part 7: **New**: examine associations comparing data from different samples\n\nThe lecture for developing the linear model includes a discussion of the ways in which the observed associations between variables or the estimated effects of predictor variables on some outcome may differ between different studies, different samples of data.\n\nTo draw the plots, I used the `{ggplot2}` library function `facet_wrap()`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall.studies.subjects %>%\n  ggplot(aes(x = SHIPLEY, y = mean.acc)) +\n  geom_point(size = 2, alpha = .5, colour = \"darkgrey\") +\n  geom_smooth(size = 1.5, colour = \"red\", method = \"lm\", se = FALSE) +\n  xlim(0, 40) +\n  ylim(0, 1.1)+\n  theme_bw() +\n  theme(\n    axis.text = element_text(size = rel(1.15)),\n    axis.title = element_text(size = rel(1.5))\n  ) +\n  xlab(\"Vocabulary (Shipley)\") + ylab(\"Mean accuracy\") +\n  facet_wrap(~ study)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 54 rows containing non-finite outside the scale range\n(`stat_smooth()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 54 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](lm-dev_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n\nWhat is new here is this bit: `facet_wrap(~ study)`\n\nThis is how it works:\n\n1. `facet_wrap()` -- the function asks R to take the data-set and split it into subsets.\n2. `facet_wrap(~ study)` -- tells the function to split the data-set according to the different levels of a named factor: `study`.\n\nSo: you need to identify a factor to do this work.\n\n##### How-to Task 11 -- *Optional* -- Fit a linear model and plot the model predictions, for different study samples, all together, to enable comparisons of effects between studies\n\nChange the factor in `facet_wrap()` to show how the vocabulary effect may vary between English monolinguals versus non-native speakers of English.\n\n:::{.callout-tip collapse=\"true\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall.studies.subjects %>%\n  ggplot(aes(x = SHIPLEY, y = mean.acc)) +\n  geom_point(size = 2, alpha = .5, colour = \"darkgrey\") +\n  geom_smooth(size = 1.5, colour = \"red\", method = \"lm\", se = FALSE) +\n  xlim(0, 40) +\n  ylim(0, 1.1)+\n  theme_bw() +\n  theme(\n    axis.text = element_text(size = rel(1.15)),\n    axis.title = element_text(size = rel(1.5))\n  ) +\n  xlab(\"Vocabulary (Shipley)\") + ylab(\"Mean accuracy\") +\n  facet_wrap(~ NATIVE.LANGUAGE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 54 rows containing non-finite outside the scale range\n(`stat_smooth()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 54 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](lm-dev_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n:::\n\n**What are we learning here?**\n\nWe can work with factors to split data-sets up by group or condition, or combinations of groups or conditions. We can then compare patterns, like outcomes, or the ways that outcomes are affected by predictors, in different groups or in different combinations.\n\n::: callout-important\nBut the *critical lesson* is that, when we visualize trends or differences between groups or, as here, between different studies, then we often see that the effects of variables *varies* between samples.\n\n- This variation between samples in the effects we observe is a key insight into what working with people involves: variation.\n:::\n\n::: callout-tip\n## Further information you can explore\nYou can read more about faceting here:\n\n<https://ggplot2.tidyverse.org/reference/facet_wrap.html>\n:::\n\n#### 10.4.3 The practical exercises {#sec-lm-dev-practical-workbook}\n\nNow you will progress through a series of tasks, and challenges, to test what you have learnt.\n\n::: callout-warning\nWe will continue to work with the data file\n\n-   `2022-12-08_all-studies-subject-scores.csv`\n:::\n\nWe again split the steps into into parts, tasks and questions.\n\nWe are going to work through the following workflow steps: **each step is labelled as a practical part**.\n\n1. Set-up\n2. Load the data\n3. **Revision**: using a linear model to answer research questions -- one predictor.\n4. **New**: using a linear model to answer research questions -- multiple predictors.\n5. **New**: plot predictions from linear models.\n6. **New**: estimate the effects of factors as well as numeric variables.\n7. **New**: examine associations comparing data from different samples.\n\n::: callout-tip\n- The `how-to` guide showed you what functions you needed and how you should write the function code.\n- Use the code structure you have seen and *change* it to use the data required for these `practical exercises`: you will need to change the data-set name, the variable names, to get the code to work for the following exercises.\n- Identify what code elements must change, and what code elements have to stay the same.\n:::\n\nNote that, for Part 5, we focus on using the `ggpredict()` tools you saw in the `how-to` guide but, for the practical exercises, use these tools to better understand what linear models (generally) do when we use them.\n\nIn the following, we will guide you through the tasks and questions step by step.\n\n::: callout-important\nAn answers version of the workbook will be provided after the practical class.\n:::\n\n#### 10.4.3.1 Practical Part 1: Set-up\n\nTo begin, we set up our environment in R.\n\n##### Practical Task 1 -- Run code to empty the R environment\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list=ls())\n```\n:::\n\n\n:::\n\n##### Practical Task 2 -- Run code to load relevant libraries\n\nNotice that in Week 10 we need to work with the libraries `ggeffects`, `patchwork` and `tidyverse`.\nUse the `library()` function to make these libraries available to you.\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"ggeffects\")\nlibrary(\"patchwork\")\nlibrary(\"psych\")\nlibrary(\"tidyverse\")\n```\n:::\n\n\n:::\n\n#### 10.4.3.2 Practical Part 2: Load the data\n\n##### Practical Task 3 -- Read in the data file we will be using\n\nThe data file is called:\n\n- `2022-12-08_all-studies-subject-scores.csv`\n\nUse the `read_csv()` function to read the data files into R:\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall.studies.subjects <- read_csv(\"2022-12-08_all-studies-subject-scores.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 615 Columns: 12\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (6): ResponseId, GENDER, EDUCATION, ETHNICITY, NATIVE.LANGUAGE, study\ndbl (6): mean.acc, mean.self, AGE, SHIPLEY, HLVA, FACTOR3\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n:::\n\n##### Practical Task 4 -- Get summary statistics for *only* the numeric variables: `AGE` and `HLVA`\n\nUse the `{psych}` library `describe()` function to get a table summary of descriptive statistics for these variables.\n\n:::{.callout-tip collapse=\"true\"}\n## Code\nHere, we can do this in two steps:\n\n1. we select the variables we care about\n2. we get just the descriptive statistics we want for those variables\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall.studies.subjects %>%\n  dplyr::select(AGE, HLVA) %>%\n  describe(skew = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     vars   n  mean    sd median min max range   se\nAGE     1 615 28.34 13.56     23  18 100    82 0.55\nHLVA    2 615  7.22  3.09      8   0  13    13 0.12\n```\n\n\n:::\n:::\n\n\n:::\n\n>**Pract.Q.1.** What is the mean health literacy (HLVA) score in this sample?\n\n> Pract.A.1. 7.22\n\n>**Pract.Q.2.** What are the minimum and maximum ages in this sample?\n\n> Pract.A.2. 18-100\n\n>**Pract.Q.3.** Do you see any reason to be concerned about the data in this sample?\n\n> Hint: It is always a good idea to use your visualization skills to examine the distribution of variable values in a dataset:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall.studies.subjects %>%\n  ggplot(aes(x = AGE)) +\n  geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](lm-dev_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\n\n> Pract.A.3. It looks like the `AGE` of 100 is maybe an error, or an extreme outlier.\n\n#### 10.4.3.3 Practical Part 3: Revision -- using a linear model to answer research questions -- one predictor.\n\nOne of our research questions is:\n\n2. Can people accurately evaluate whether they correctly understand written health information?\n\nWe can address this question by examining whether someone's rated evaluation of their own understanding matches their performance on a test of that understanding, and by investigating what variables predict variation in mean self-rated accuracy.\n\n::: callout-tip\nNote that ratings of accuracy are ordinal (categorical ordered) data but that, here, we may choose to examine the average of participants' ratings of their own understanding of health information for the purposes of this example.\n\n- We learn about ordinal models for ordinal data in PSYC412.\n:::\n\nFor these data, participants were asked to respond to questions about health information to get `mean.acc` scores and were asked to rate their own understanding of the same information.\n\n- If you *can* evaluate your own understanding then ratings of understanding *should* be associated with performance on tests of understanding.\n\n##### Practical Task 5 -- Estimate the relation between outcome mean self-rated accuracy (`mean.self`) and tested accuracy of understanding (`mean.acc`)\n\nWe can use `lm()` to estimate whether the ratings of accuracy actually predict the outcome tested accuracy levels.\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.acc ~ mean.self, data = all.studies.subjects)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ mean.self, data = all.studies.subjects)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.58815 -0.09437  0.03841  0.13530  0.34080 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.351300   0.030683   11.45   <2e-16 ***\nmean.self   0.058613   0.004544   12.90   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1855 on 559 degrees of freedom\n  (54 observations deleted due to missingness)\nMultiple R-squared:  0.2294,\tAdjusted R-squared:  0.228 \nF-statistic: 166.4 on 1 and 559 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n:::\n\nIf you first fit the appropriate model, then read the model summary, you can answer the following questions.\n\n>**Pract.Q.4.** What is the estimate for the coefficient of the effect of the predictor `mean.self` on the outcome `mean.acc` in this model?\n\n> Pract.A.4. 0.058613\n\n>**Pract.Q.5.** Is the effect significant?\n\n> Pract.A.5. It is significant, p < .05\n\n>**Pract.Q.6.** What are the values for t and p for the significance test for the coefficient?\n\n> Pract.A.6. t = 12.90, p <2e-16\n\n>**Pract.Q.7.** What do you conclude is the answer to the research question, given the linear model results?\n\n> Pract.A.7. The model slope estimate suggests that higher levels of rated understanding can predict higher levels of tested understanding so, yes: it does appear that people can evaluate their own understanding.\n\n>**Pract.Q.8.** What is the F-statistic for the regression? Report F, DF and the p-value.\n\n> Pract.A.8. F-statistic: 166.4 on 1 and 559 DF,  p-value: < 2.2e-16\n\n>**Pract.Q.9.** Is the regression significant?\n\n> Pract.A.9. Yes: the regression is significant.\n\n>**Pract.Q.10.** What is the Adjusted R-squared?\n\n> Pract.A.10. Adjusted R-squared:  0.228\n\n>**Pract.Q.11.** Explain in words what this R-squared value indicates?\n\n> Pract.A.11. The R-squared suggests that 23% of outcome variance can be explained by the model\n\n#### 10.4.3.4 Practical Part 4: New -- using a linear model to answer research questions -- multiple predictors\n\nOne of our research questions is:\n\n2. Can people accurately evaluate whether they correctly understand written health information?\n\nWe have already looked at this question by asking whether ratings of understanding predict performance on tests of understanding. But there is a problem with that analysis -- it leaves open the question: \n\n- What actually predicts ratings of understanding?\n\nWe can look at that follow-up question through the analysis we do next.\n\n##### Practical Task 6 -- Examine the relation between outcome mean self-rated accuracy (`mean.self`) and  multiple predictors including: health literacy (`HLVA`); vocabulary (`SHIPLEY`); `AGE`; reading strategy (`FACTOR3`); as well as `mean.acc`\n\nWe use `lm()`, as before, but now specify each variable listed here by variable name\n\n- outcome: mean self-rated accuracy (`mean.self`)\n- predictors: health literacy (`HLVA`); vocabulary (`SHIPLEY`); `AGE`; reading strategy (`FACTOR3`); as well as `mean.acc`.\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.self ~ HLVA + SHIPLEY + FACTOR3 + AGE + mean.acc,\n            data = all.studies.subjects)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.self ~ HLVA + SHIPLEY + FACTOR3 + AGE + mean.acc, \n    data = all.studies.subjects)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-5.4479 -0.8585  0.1459  0.9327  4.6791 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.756121   0.400363   1.889   0.0595 .  \nHLVA        0.066543   0.029368   2.266   0.0238 *  \nSHIPLEY     0.012512   0.010188   1.228   0.2199    \nFACTOR3     0.062333   0.008079   7.715 5.64e-14 ***\nAGE         0.002707   0.004417   0.613   0.5403    \nmean.acc    2.502024   0.361094   6.929 1.18e-11 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.42 on 555 degrees of freedom\n  (54 observations deleted due to missingness)\nMultiple R-squared:  0.3279,\tAdjusted R-squared:  0.3219 \nF-statistic: 54.17 on 5 and 555 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n:::\n\nIf you look at the model summary you can answer the following questions  \n\n>**Pract.Q.12.** What predictors are significant in this model?\n\n> Pract.A.12. Health literacy ('HLVA'), reading strategy ('FACTOR3') and performance on tests of accuracy of understanding ('mean.acc') all appear to significantly predict variation in mean ratings of understanding ('mean.self').\n\n>**Pract.Q.13.** What is the estimate for the coefficient of the effect of the predictor, `mean.acc`, in this model?\n\n> Pract.A.13. 2.502024\n\n>**Pract.Q.14.** Is the effect significant?\n\n> Pract.A.14. It is significant because p < .05\n\n>**Pract.Q.15.** What are the values for t and p for the significance test for the coefficient?\n\n> Pract.A.15. t = 6.929, p = 1.18e-11\n\n>**Pract.Q.16.** What do you conclude is the answer to the follow-up question, what actually predicts ratings of understanding?\n\n> Pract.A.16. Ratings of understanding appear to be predicted by performance on tests of accuracy of understanding, together with variation in health literacy and reading strategy.\n\n#### 10.4.3.5 Practical Part 5: New -- plot predictions from linear models\n\nIn this part, the practical work involves plotting the predictions from two linear models but the benefit from this practical work is to better your understanding of what linear models are doing.\n\nSo, our research questions is:\n\n2. Can people accurately evaluate whether they correctly understand written health information?\n\nWe can look at this question in two ways:\n\n- we can focus on whether `mean.self` predicts `mean.acc`?\n- or, in reverse, whether `mean.acc` predicts `mean.self`?\n\nPeople could (1.) be good at understanding accurately what they read (measured as `mean.acc`), so that that accurate understanding results in accurate evaluation of their own understanding (measured as `mean.self`). Or people could (2.) be good at judging their own understanding (`mean.self`) so that they can then be accurate in their understanding of what they read. This is not just a tricksy way of talking: it could be that people who are good at evaluating if they understand what they read are able to work more effectively at that understanding, or the opposite could be the case. \n\nThe *direction of cause-and-effect* is just unclear, here. \n\n##### Practical Task 7 -- We cannot actually resolve the question of causality but we can learn a lot if we look at two models incorporating the same variables\n\n1. If we focus on whether (predictor) `mean.self` predicts (outcome) `mean.acc` then the model should be: `mean.acc ~ mean.self`\n2. If we focus on whether (predictor) `mean.acc` predicts (outcome) `mean.self` then the model should be: `mean.self ~ mean.acc`\n\nThe two models involve the same variables but arrange the variables differently, in the code, depending on which variable is specified as the outcome versus which variable is specified as the predictor.\n\n::: callout-tip\nNote that the comparison between these models teaches us something about *what* it is that linear models predict.\n\n- You want to focus on the estimate of the coefficient of the predictor variable, for each model, presented in the model summary results.\n:::\n  \n>**Pract.Q.17.** Can you write the code for the two models? Can you give each model a distinctive name?\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel.1 <- lm(mean.acc ~ mean.self, data = all.studies.subjects)\nsummary(model.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ mean.self, data = all.studies.subjects)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.58815 -0.09437  0.03841  0.13530  0.34080 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.351300   0.030683   11.45   <2e-16 ***\nmean.self   0.058613   0.004544   12.90   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1855 on 559 degrees of freedom\n  (54 observations deleted due to missingness)\nMultiple R-squared:  0.2294,\tAdjusted R-squared:  0.228 \nF-statistic: 166.4 on 1 and 559 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nmodel.2 <- lm(mean.self ~ mean.acc,\n              data = all.studies.subjects)\nsummary(model.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.self ~ mean.acc, data = all.studies.subjects)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-5.2003 -0.7917  0.2040  0.9781  3.9737 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   3.6565     0.2317   15.78   <2e-16 ***\nmean.acc      3.9135     0.3034   12.90   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.515 on 559 degrees of freedom\n  (54 observations deleted due to missingness)\nMultiple R-squared:  0.2294,\tAdjusted R-squared:  0.228 \nF-statistic: 166.4 on 1 and 559 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n:::\n  \nTake a look at the summary for each model.  \n\n>**Pract.Q.18.** Why do you think it appears that the slope coefficient estimate is different if you compare:\n\n> (1.) the model, mean.acc ~ mean.self\n\n> versus\n\n> (2.) the model, mean.self ~ mean.acc?\n\n> Hint: You may benefit by reflecting on the lectures and practical materials in [the chapter for week 8](../part2/lm-intro.qmd#sec-lm-intro-overview), especially where they concern predictions.\n\n> Pract.A.18. Linear models are prediction models. We use them to predict variation in *outcomes* given some set of predictor variables. Because of this, predictions *must* be scaled in the same way as the *outcome variable*.\n\n> So:\n\n> (1.) the model `mean.acc ~ mean.self` identifies `mean.acc` as the outcome so if we are predicting change in `mean.acc` (scaled 0-1) then we are looking at coefficients that will lie somewhere on the same scale (also 0-1).\n\n> Here: the model suggests that unit change in `mean.self` predicts increase of 0.058613 in `mean.acc`.\n\n> Versus:\n\n> (2.) the model, `mean.self ~ mean.acc` identifies `mean.self` as the outcome so if we are predicting change in `mean.self` (scaled 1-9) then we are looking at coefficients that will lie somewhere on the same scale (also 1-9).\n\n> Here: the model suggests that unit change in `mean.acc` predicts increase of 3.9135 in `mean.self`.\n\n>**Pract.Q.19.** Can you plot the predictions from each model?\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n> Pract.A.19. Here is the code to plot the predictions from both models:\n\nFirst fit the models -- give the model objects distinct names:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel.1 <- lm(mean.acc ~ mean.self, data = all.studies.subjects)\nsummary(model.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ mean.self, data = all.studies.subjects)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.58815 -0.09437  0.03841  0.13530  0.34080 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.351300   0.030683   11.45   <2e-16 ***\nmean.self   0.058613   0.004544   12.90   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1855 on 559 degrees of freedom\n  (54 observations deleted due to missingness)\nMultiple R-squared:  0.2294,\tAdjusted R-squared:  0.228 \nF-statistic: 166.4 on 1 and 559 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nmodel.2 <- lm(mean.self ~ mean.acc,\n            data = all.studies.subjects)\nsummary(model.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.self ~ mean.acc, data = all.studies.subjects)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-5.2003 -0.7917  0.2040  0.9781  3.9737 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   3.6565     0.2317   15.78   <2e-16 ***\nmean.acc      3.9135     0.3034   12.90   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.515 on 559 degrees of freedom\n  (54 observations deleted due to missingness)\nMultiple R-squared:  0.2294,\tAdjusted R-squared:  0.228 \nF-statistic: 166.4 on 1 and 559 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nThen get the predictions:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.1 <- ggpredict(model.1, \"mean.self\")\ndat.2 <- ggpredict(model.2, \"mean.acc\")\n```\n:::\n\n\n\nThen make the plots, and arrange them for easy comparison, side-by-side:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot.1 <- plot(dat.1)\nplot.2 <- plot(dat.2)\n\nplot.1 + plot.2\n```\n\n::: {.cell-output-display}\n![](lm-dev_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\n:::\n\n>**Pract.Q.20.** Look at the two plots side-by-side: what do you see?\n\nHint: Look at changes in height of the prediction line, given changes in x-axis position of the line.\n\n> Pract.A.20. A side-by-side comparison shows that for (1.) `mean.acc ~ mean.self,` increases in `mean.self` from about 2-8 are associated with a change in `mean.acc` from about .4 to about .85, while for (2.) `mean.self ~ mean.acc`, increases in `mean.self` from about .2-1.0 are associated with a change in `mean.acc` from about 4 to about 8.\n\n**What are we learning here?**\n\nLinear models are prediction models. We use them to predict variation in outcomes given some set of predictor variables. \n\n::: callout-important\nPredictions *must* be scaled in the same way as the outcome variable.\n:::\n\n#### 10.4.3.6 Practical Part 6: New -- estimate the effects of factors as well as numeric variables\n\n##### Practical Task 8 -- Fit a linear model to examine what variables predict outcome mean self-rated accuracy of `mean.self`\n\nInclude in the model both numeric variables and categorical variables as predictors:\n\n- health literacy (`HLVA`); vocabulary (`SHIPLEY`); `AGE`; reading strategy (`FACTOR3`); as well as `mean.acc` and `NATIVE.LANGUAGE`.\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.self ~ HLVA + SHIPLEY + FACTOR3 + AGE + mean.acc +\n                        NATIVE.LANGUAGE,\n            data = all.studies.subjects)\n```\n:::\n\n\n:::\n\n>**Pract.Q.21.** Can you report the estimated effect of `NATIVE.LANGUAGE` (the coding of participant language status: `English` versus `other`)?\n\nHint: you will need to get a summary of the model you have coded.\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.self ~ HLVA + SHIPLEY + FACTOR3 + AGE + mean.acc + \n    NATIVE.LANGUAGE, data = all.studies.subjects)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-5.3580 -0.8804  0.1250  0.9093  4.7323 \n\nCoefficients:\n                      Estimate Std. Error t value Pr(>|t|)    \n(Intercept)           0.992731   0.421865   2.353   0.0190 *  \nHLVA                  0.063174   0.029377   2.150   0.0319 *  \nSHIPLEY               0.011553   0.010184   1.134   0.2571    \nFACTOR3               0.063973   0.008119   7.880 1.75e-14 ***\nAGE                   0.002039   0.004425   0.461   0.6452    \nmean.acc              2.331519   0.373357   6.245 8.46e-10 ***\nNATIVE.LANGUAGEOther -0.225432   0.128793  -1.750   0.0806 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.418 on 554 degrees of freedom\n  (54 observations deleted due to missingness)\nMultiple R-squared:  0.3316,\tAdjusted R-squared:  0.3244 \nF-statistic: 45.82 on 6 and 554 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n:::\n\n> Pract.A.21. The effect of language status (`NATIVE.LANGUAGE`) on mean accuracy of understanding is not significant (estimate = -0.225432, t = -1.750, p = .081) indicating that not being a native speaker of English (`Other`) is not associated with lower self-rated accuracy.\n\n>**Pract.Q.22.** Can you report the overall model and model fit statistics?\n\n> Pract.A.22. We fitted a linear model with mean self-rated accuracy as the outcome and with the predictors: health literacy (HLVA),  reading strategy (FACTOR3), vocabulary (SHIPLEY) and AGE (years), as well as mean accuracy (mean.acc) and language status. The model is significant overall, with F(6, 554) = 45.82, p < .001, and explains 32% of variance (adjusted R2 = 0.32).\n\n>**Pract.Q.23.** Can you plot the predicted effect of `NATIVE.LANGUAGE` given your model?\n\n:::{.callout-tip collapse=\"true\"}\n## Code\nWe first fit the model, including `NATIVE.LANGUAGE`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.self ~ HLVA + SHIPLEY + FACTOR3 + AGE + mean.acc +\n              NATIVE.LANGUAGE,\n            data = all.studies.subjects)\n```\n:::\n\n\n\nThen use the `ggpredict()` function to get the predictions\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- ggpredict(model, \"NATIVE.LANGUAGE\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSome of the focal terms are of type `character`. This may lead to\n  unexpected results. It is recommended to convert these variables to\n  factors before fitting the model.\n  The following variables are of type character: `NATIVE.LANGUAGE`\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(dat)\n```\n\n::: {.cell-output-display}\n![](lm-dev_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n\n:::\n\n>**Pract.Q.24.** The plot should give you dot-and-whisker representations of the estimated `mean.self` for `English` versus `Other` participants in the dataset. What is the difference in the estimated `mean.self` between these groups?\n\nHint: The effect or prediction plot will show you dot-and-whisker representations of predicted outcome `mean.self`. In these plots, the dots represent the estimated `mean.self` while the lines (whiskers) represent confidence intervals.\n\n> Pract.A.24. The difference in the estimated 'mean.self' between these groups is about .2.\n\n>**Pract.Q.25.** Compare the difference in the estimated `mean.self` between these groups, given the plot, with the coefficient estimate from the model summary: what do you see?\n\n> Pract.A.25. The coefficient estimate = -0.225432. This matches the difference shown in the plot.\n\n#### 10.4.3.7 Practical Part 7: New -- examine associations comparing data from different samples\n\n##### Practical Task 8 -- Use `facet_wrap()` to show how the association between `mean.self` and `mean.acc` can vary between the different studies in the data-set\n\nChange the factor in `facet_wrap()` to show how the association between `mean.self` and `mean.acc` can vary between the different studies\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall.studies.subjects %>%\n  ggplot(aes(x = mean.self, y = mean.acc)) +\n  geom_point(size = 2, alpha = .5, colour = \"darkgrey\") +\n  geom_smooth(size = 1.5, colour = \"red\", method = \"lm\", se = FALSE) +\n  xlim(0, 10) +\n  ylim(0, 1.1)+\n  theme_bw() +\n  theme(\n    axis.text = element_text(size = rel(1.15)),\n    axis.title = element_text(size = rel(1.5))\n  ) +\n  xlab(\"Mean self-rated accuracy\") + ylab(\"Mean accuracy\") +\n  facet_wrap(~ study)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 54 rows containing non-finite outside the scale range\n(`stat_smooth()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 54 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](lm-dev_files/figure-html/unnamed-chunk-45-1.png){width=672}\n:::\n:::\n\n\n:::\n\nYou may need to edit the x-axis labeling to make it readable\n\n- Can you work out how to do that, given `ggplot()` help information?\n\nHint: check out the continuous scale information in:\n\n<https://ggplot2.tidyverse.org/reference/scale_continuous.html>\n\n#### 10.4.3.8 Practical Part Optional: New -- save or export plots so that you can insert them in reports\n\nLearning how to export plots from R will help you later with reports.\n\nThe task is to save or export a plot that you produce, so that you can insert it in a report or presentation.\n\nThere are different ways to do this, we can look at one simple example.\n\n- We can save the last plot we produce using the `{tidyverse}` function `ggsave()`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggsave(\"facet-plots.png\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nSaving 7 x 5 in image\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 54 rows containing non-finite outside the scale range\n(`stat_smooth()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 54 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n:::\n\n\n\nNotice, here, that:\n\n- `ggsave(\"facet-plots...\")` -- we need to give the plot a name;\n- `ggsave(\"...png\")` -- and we need to tell R what format we require.\n\nThe plot is saved as a file with the name you specify, in the working directory (folder) you are using.\n\nR will save the plot in the format you specify: here, I choose .png because .png image files can be imported into Microsoft Word documents easily.\n\n- Notice that `ggsave()` will use pretty good defaults but that you can over-ride the defaults, by adding arguments to specify the plot width, height and resolution (in dpi).\n\n::: callout-tip\n## Further information you can explore\nCheck out reference information here:\n\n<https://ggplot2.tidyverse.org/reference/ggsave.html>\n\nand\n\n<http://www.cookbook-r.com/Graphs/Output_to_a_file/>\n:::\n\n#### Practical Task Optional: Now try it for yourself: make a plot, and save it, using what you have learnt so far\n\nYou will need to:\n\n1. Fit a model\n2. Create a set of predictions we can use for plotting\n3. Make a plot\n4. Save it\n\nThen, you can import the saved plot into Word.\n\n:::{.callout-tip collapse=\"true\"}\n## Code\nFit a model:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.acc ~ HLVA + SHIPLEY + FACTOR3 + AGE,\n            data = all.studies.subjects)\n```\n:::\n\n\n\nCreate a set of predictions we can use for plotting\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- ggpredict(model, \"FACTOR3\")\n```\n:::\n\n\n\nMake a plot\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np.model <- plot(dat)\np.model +\n  geom_point(data = all.studies.subjects,\n             aes(x = FACTOR3, y = mean.acc), size = 1.5, alpha = .75, colour = \"darkgrey\") +\n  geom_line(size = 1.5) +\n  theme_bw() +\n  theme(\n    axis.text = element_text(size = rel(1.15)),\n    axis.title = element_text(size = rel(1.25)),\n    plot.title = element_text(size = rel(1.4))\n  ) +\n  xlab(\"Reading strategy (FACTOR3)\") + ylab(\"Mean accuracy\") +\n  ggtitle(\"Effect of reading strategy on \\n mean comprehension accuracy\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 54 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](lm-dev_files/figure-html/unnamed-chunk-49-1.png){width=672}\n:::\n:::\n\n\n\nSave it\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggsave(\"reading-strategy-prediction.png\", width = 10, height = 10, units = \"cm\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 54 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n:::\n\n\n:::\n\nSome advice:\n\n- It is often helpful to present plots that are almost square i.e. height about = width.\n- This helps to present the best fit line in scatterplots in a way that is easier to perceive.\n- We may experiment with width-height (aspect ratio) until we get something that \"looks\" right. \n- Notice also that different presentation venues will require different levels if image resolution e.g. journals may require .tiff file plots at dpi = 180 or greater.\n\n### The answers\n\nAfter the practical class, we will reveal the answers that are currently hidden.\n\nThe answers version of the webpage will present my answers for questions, and some extra information where that is helpful.\n\n### Look ahead: growing in independence\n\n#### General advice\n\nAn old saying goes:\n\n> All models are wrong but some are useful\n\n(attributed to George Box).\n\n::: callout-tip\n-   Sometimes, it can be useful to adopt a simpler approach as a way to approximate *get closer to* better methods\n-   Box also advises:\n\n> Since all models are wrong the scientist must be alert to what is importantly wrong. It is inappropriate to be concerned about mice when there are tigers abroad.\n\n-   Here, we focus on validity, measurement, generalizability and *critical thinking*\n:::\n\n### Summary\n\n1.  Linear models\n\n-   Linear models are a very general, flexible, and powerful analysis method\n-   We can use assuming that prediction outcomes (residuals) are normally distributed\n-   With potentially multiple predictor variables\n\n2.  Thinking about linear models\n\n-   Closing the loop: when we plan an analysis we should try to use contextual information -- theory and measurement understanding -- to specify our model\n-   Closing the loop: when we critically evaluate our or others' findings, we should consider validity, measurement, and generalizability\n\n3.  Reporting linear models\n\n-   When we report an analysis, we should report:\n\n1.  Explain what I did, specifying the method (linear model), the outcome variable (accuracy) and the predictor variables (health literacy, reading strategy, reading skill and vocabulary)\n2.  Report the model fit statistics overall ($F, R^2$)\n3.  Report the significant effects ($\\beta, t, p$) and describe the nature of the effects (does the outcome increase or decrease?)\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}