{
  "hash": "c7340e9a1c579c7a5bf8f351ec358b28",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Week 7. Hypotheses and associations\nsubtitle: Written by Rob Davies\norder: 10\nbibliography: references.bib\ncsl: psychological-bulletin.csl\n---\n\n\n\n\n## 7.1 Overview {#sec-associations-overview}\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\nWelcome to your overview of the work we will do together in **Week 7**.\n\nThis week, we focus on methods that allow us to make sense of the evidence for **associations**.\n\nLooking ahead to your professional lives, our aim is to help you to build the understanding *and* to learn the skills that will ensure that you can practise, inspire and manage the most effective ways to make sense of associations.\n\nWe will work in the context of a live research project with potential real world impacts: the **Clearly understood** project.\nWorking in a concrete **context** will help you to make sense of what you are doing, even if you are interested in other topics.\n\n::: callout-tip\nThe **Clearly understood** project aims to fix the problem that we are not sure how health information should be communicated so that everyone can understand it. \n\nWe ask the research questions:\n\n1.  What person attributes predict success in understanding?\n2.  Can people accurately evaluate whether they correctly understand written health information?\n:::\n\nAs we work together, we will be revisiting some of the ideas and techniques you have seen in previous classes, so that you can *consolidate* your learning.\nThen, we will *extend* your development with some new ideas to strengthen your skills.\n\n## 7.2 Our learning goals {#sec-associations-goals}\n\nThis week, we develop your critical thinking and we strengthen your practical skills.\n\n**1. Critical thinking**\n\n-   *Concepts*: how we go from ideas and questions to hypotheses\n\n**2. Practical skills**\n\n-   *Concepts* -- associations: correlations, estimates and hypothesis tests\n-   *Skills* -- visualizing covariation\n-   *Skills* -- writing the code\n-   *Skills* -- estimating correlations\n-   *Skills* -- hypothesis tests for correlations\n-   *Skills* -- interpreting and reporting correlations\n\n## 7.3 Learning resources {#sec-associations-resources}\n\nYou will see, next, the lectures we share to explain the concepts behind the critical thinking and analysis skills you will develop, then you will see information about the practical materials you can use to practise your skills.\n\n::: callout-tip\nWe think you will learn best if you *first* watch the lectures *then* do the practical exercises.\n:::\n\n### 7.3.1 Lectures {#sec-associations-lectures}\n\nThe lecture materials for this week are presented in five short parts. \n\nClick on a link and your browser should open a tab showing the *Panopto* video for the lecture part.\n\n1. Part 1 (12 minutes) **Overview**: The concepts and skills we will learn about in weeks 6-10, and why it helps to embed the classes in the context of a research project.\n\n\n\n\n```{=html}\n<iframe src=\"https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=768a9621-a440-4a1a-a3f8-b22200c1d4e2&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all\" height=\"405\" width=\"720\" style=\"border: 1px solid #464646;\" allowfullscreen allow=\"autoplay\" aria-label=\"Panopto Embedded Video Player\" aria-description=\"PSYC411-associations-1\" ></iframe>\n```\n\n\n\n\n2. Part 2 (18 minutes): Hypotheses, measurements and associations -- how you can think critically.\n\n\n\n\n```{=html}\n<iframe src=\"https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=9a10462c-e185-4069-b72a-af5000cc076a&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all\" height=\"405\" width=\"720\" style=\"border: 1px solid #464646;\" allowfullscreen allow=\"autoplay\" aria-label=\"Panopto Embedded Video Player\" aria-description=\"PSYC411-associations-2\" ></iframe>\n```\n\n\n\n\n3. Part 3 (14 minutes): The live research project we will use to put our practical skills exercises and critical thinking challenges into context.\n\n\n\n\n```{=html}\n<iframe src=\"https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=1653a285-fa5b-45c4-a850-af5000d1c8d5&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all\" height=\"405\" width=\"720\" style=\"border: 1px solid #464646;\" allowfullscreen allow=\"autoplay\" aria-label=\"Panopto Embedded Video Player\" aria-description=\"PSYC411-associations-3\" ></iframe>\n```\n\n\n\n\n4. Part 4 (20 minutes): Seeing, thinking and talking about associations, correlations.\n\n\n\n\n```{=html}\n<iframe src=\"https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=ca174423-d385-40d5-9068-af5000d60688&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all\" height=\"405\" width=\"720\" style=\"border: 1px solid #464646;\" allowfullscreen allow=\"autoplay\" aria-label=\"Panopto Embedded Video Player\" aria-description=\"PSYC411-associations-4\" ></iframe>\n```\n\n\n\n\n5. Part 5 (12 minutes): How we use R to estimate and test correlations. How we write about correlation results\n\n\n\n\n```{=html}\n<iframe src=\"https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=9d53628e-3133-43aa-b78f-af5000dc0d0b&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all\" height=\"405\" width=\"720\" style=\"border: 1px solid #464646;\" allowfullscreen allow=\"autoplay\" aria-label=\"Panopto Embedded Video Player\" aria-description=\"PSYC411-associations-5\" ></iframe>\n```\n\n\n\n\n### 7.3.2 Lecture slides {#sec-associations-lectures-slides}\n\n::: callout-tip\n## Download the lecture slides\nThe slides presented in the videos can be downloaded here:\n\n- [The slides](files/411-hypotheses-assocations.html) exactly as presented (22 MB). \n\nYou can download the web page `.html` file and click on it to open it in any browser (e.g., Chrome, Edge or Safari). The slide images are high quality so the file is quite big and may take a few seconds to download.\n:::\n\nWe are going to work through some practical exercises, next, to stimulate your thinking and learn the practical skills you need to see, test and talk about correlation analyses of the associations between variables.\n\n### 7.4 Practical materials: data and R-Studio {#sec-associations-practical}\n\nWe will work with two data files which you can download by clicking on their names (below):\n\n-   [study-one-general-participants.csv](files/study-one-general-participants.csv).\n-   [study-two-general-participants.csv](files/study-two-general-participants.csv).\n\nOnce you have downloaded the files, you will need to upload them to the R-Studio server to access and use the R files.\n\n::: callout-important\nHere is a link to the sign-in page for [R-Studio Server](https://psy-rstudio.lancaster.ac.uk/auth-sign-in?appUri=%2F)\n:::\n\n### 7.4.1 Practical materials guide {#sec-associations-practical-guide}\n\nYou will find that the practical exercises are simpler to do if you follow these steps in order.\n\n1. **The data** --- We will take a quick look at what is inside the data files so you know what everything means.\n2. **The `how-to` guide** --- We will go through the practical analysis and visualization coding steps, showing all the code required for each step.\n3. **The `practical` exercises** --- We will set out the tasks, questions and challenges that you should complete to learn the practical skills we target this week.\n\n::: callout-tip\nWe show you how to do everything you need to do in the `practical` exercises, first, in the `how-to` guide.\n\n- Start by looking at the `how-to` guide to understand what steps you need to follow in the lab activity.\n\nIf you want to make it more challenging for yourself, go straight to Step 3.\n:::\n\nWe will take things *step-by-step*:  \n\n- different parts for different phases of the analysis workflow;\n- different tasks for different things you need to do;\n- different questions to examine different ideas or coding challenges.\n\n#### 7.4.1.1 The data files {#sec-associations-practical-data}\n\nEach of the data files we will work with has a similar structure.\n\nHere are what the first few rows in the data file `study.one.gen` looks like:\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|participant_ID | mean.acc| mean.self|study    | AGE| SHIPLEY| HLVA| FACTOR3| QRITOTAL|GENDER     |EDUCATION |ETHNICITY |\n|:--------------|--------:|---------:|:--------|---:|-------:|----:|-------:|--------:|:----------|:---------|:---------|\n|studyone.1     |     0.49|      7.96|studyone |  34|      33|    7|      53|       11|Non-binary |Higher    |White     |\n|studyone.10    |     0.85|      7.28|studyone |  25|      33|    7|      60|       11|Female     |Higher    |White     |\n|studyone.100   |     0.82|      7.36|studyone |  43|      40|    8|      46|       12|Male       |Further   |White     |\n|studyone.101   |     0.94|      7.88|studyone |  46|      33|   11|      51|       15|Male       |Higher    |White     |\n|studyone.102   |     0.58|      6.96|studyone |  18|      32|    3|      51|       12|Male       |Secondary |Mixed     |\n|studyone.103   |     0.84|      7.88|studyone |  19|      37|   13|      45|       19|Female     |Further   |Asian     |\n\n\n:::\n:::\n\n\n\n\n::: callout-tip\nThe webpage has a slider under the data table window, so you can scroll across the columns: move your cursor over the window to show the slider.\n:::\n\nWhen you look at the data table, you can see the columns:\n\n-   `participant_ID` participant code\n-   `mean.acc` average accuracy of response to questions testing understanding of health guidance\n-   `mean.self` average self-rated accuracy of understanding of health guidance\n-   `study` variable coding for what study the data were collected in\n-   `AGE` age in years\n-   `HLVA` health literacy test score\n-   `SHIPLEY` vocabulary knowledge test score\n-   `FACTOR3` reading strategy survey score\n-   `GENDER` gender code\n-   `EDUCATION` education level code\n-   `ETHNICITY` ethnicity (Office National Statistics categories) code\n\n### 7.4.2 The how-to guide {#sec-associations-practical-how-to}\n\nWe will take things *step-by-step*.\n\nWe split .Rmd scripts by steps, tasks and questions:  \n\n- different parts for different phases of the analysis workflow;\n- different tasks for different things you need to do;\n- different questions to examine different ideas or coding challenges.\n\n::: callout-tip\n- Make sure you start and work your way, in order, through each part, task and question.\n- Complete each task before you move on to the next task.\n:::\n\nIn the `how-to` guide, we hide example code and answer information in boxes so that you can test yourself first. Click on the box to then reveal the code or the answer.\n\n#### 7.4.2.1 How-to Part 1: Set-up\n\nTo begin, we set up our environment in R.\n\n##### How-to Task 1 -- Run code to empty the R environment\n\n:::{.callout-tip collapse=\"true\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list=ls())                            \n```\n:::\n\n\n\n:::\n\n##### How-to Task 2 -- Run code to load libraries\n\nLoad libraries using `library()`.\n\n:::{.callout-tip collapse=\"true\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"tidyverse\")\n```\n:::\n\n\n\n:::\n\n#### 7.4.2.2 How-to Part 2: Load and examine the data\n\n##### How-to Task 3 -- Read in the data file we will be using\n\nThe code in the `how-to` guide was written to work with the data file:\n\n- `study-one-general-participants.csv`.\n\nRead in the data file -- using `read_csv()`.\n\n:::{.callout-tip collapse=\"true\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudy.one.gen <- read_csv(\"study-one-general-participants.csv\")\n```\n:::\n\n\n\n:::\n\n::: callout-tip\nYou can choose your own file name, but be sure to give the data-set a *distinct* name, e.g., `study.one.gen` so that R can distinguish between the different data you will work with.\n:::\n\n##### How-to Task 4 -- Inspect the data file\n\nUse the `summary()` function to take a look.\n\n:::{.callout-tip collapse=\"true\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(study.one.gen)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n participant_ID        mean.acc        mean.self        study          \n Length:169         Min.   :0.3600   Min.   :3.440   Length:169        \n Class :character   1st Qu.:0.7600   1st Qu.:6.080   Class :character  \n Mode  :character   Median :0.8400   Median :7.080   Mode  :character  \n                    Mean   :0.8163   Mean   :6.906                     \n                    3rd Qu.:0.9000   3rd Qu.:7.920                     \n                    Max.   :0.9900   Max.   :9.000                     \n      AGE           SHIPLEY           HLVA           FACTOR3     \n Min.   :18.00   Min.   :23.00   Min.   : 3.000   Min.   :34.00  \n 1st Qu.:24.00   1st Qu.:33.00   1st Qu.: 7.000   1st Qu.:46.00  \n Median :32.00   Median :35.00   Median : 9.000   Median :51.00  \n Mean   :34.87   Mean   :34.96   Mean   : 8.905   Mean   :50.33  \n 3rd Qu.:42.00   3rd Qu.:38.00   3rd Qu.:10.000   3rd Qu.:55.00  \n Max.   :76.00   Max.   :40.00   Max.   :14.000   Max.   :63.00  \n    QRITOTAL        GENDER           EDUCATION          ETHNICITY        \n Min.   : 6.00   Length:169         Length:169         Length:169        \n 1st Qu.:12.00   Class :character   Class :character   Class :character  \n Median :13.00   Mode  :character   Mode  :character   Mode  :character  \n Mean   :13.36                                                           \n 3rd Qu.:15.00                                                           \n Max.   :19.00                                                           \n```\n\n\n:::\n:::\n\n\n\n:::\n\n::: callout-tip\n- `summary()` will give you either descriptive statistics for variable columns classified as numeric or will tell you that columns in the dataset are not numeric.\n- `summary(...)` is a function and, again, you put the name of the dataset inside the brackets to view it.\n:::\n\n> Q.1. What is the mean of `mean.acc`?\n\n:::{.callout-tip collapse=\"true\"}\n> A.1. 0.8163  \n:::\n\n> Q.2. What class is the variable `study`?\n\n:::{.callout-tip collapse=\"true\"}\n> A.2. `character`\n:::\n\n> Q.3. Does the summary indicate if any variable has missing values (`NA`)?\n\n:::{.callout-tip collapse=\"true\"}\n> A.3. No\n:::\n\n##### How-to Task 5 -- Change the class or type of a variable\n\nYou can use the `as.factor()` function you used in Week 5.\n\n:::{.callout-tip collapse=\"true\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudy.one.gen$study <- as.factor(study.one.gen$study)\n```\n:::\n\n\n\n:::\n\n> Q.4. After you have done this, what information does `summary()` give you about the variable `study`?\n\n:::{.callout-tip collapse=\"true\"}\n> A.4. We can see the number 169 beside the word `studyone`: this tells us that there are 169\nobservations, in the column, each one is a value: the word or character string `studyone`.\n:::\n\n::: callout-tip\nRemember from Week 3 that we can only count how many times a category value (or factor level) occurs: here, we are counting how many times the word `studyone` occurs in the factor column `study`.\n:::\n\n#### 7.4.2.3 How-to Part 3: Visualize associations\n\n##### How-to Task 6 -- Draw scatterplots to examine associations between variables\n\nYou have seen these code moves before, in previous classes (weeks 3 and 4): we are **consolidating** skills by practising your coding in different contexts, using different data.\n\nWe **extend** your skills by adding some new moves.\n\nCreate scatterplots to examine the association between some variables.\n\n::: callout-tip\nWe are working with `geom_point()` and you need `x` and `y` aesthetic mappings.\n:::\n\nFor example, we can draw a scatterplot to examine the association between `mean.self` and `mean.acc`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one.gen, aes(x = mean.self, y = mean.acc)) + \n    geom_point()\n```\n\n::: {.cell-output-display}\n![](hypotheses-associations_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n\nExamine this plot --- it shows: the possible association between x-axis variable `mean.self` and y-axis variable `mean.acc`.\n\nYou have seen this kind of code before but it will help your learning if, now, we take a look at the code step-by-step.\n\nThe plot code moves through the following steps:  \n\n1. `ggplot(...)` makes a plot.\n2. `ggplot(data = study.one.gen, ...)` uses the `study.one.gen` data-set.\n3. `ggplot(...aes(x = mean.self, y = mean.acc))` uses two aesthetic mappings.\n4. `geom_point()` show the mappings as points.\n\n::: callout-tip\nWhat are *aesthetic mappings*?\n\nAesthetic mappings translate data information -- numbers or values in column variables -- into things you can see in plots.\n\nFor a scatterplot, we need to translate values for two variables into the position of each point in the plot.\n\nHere:\n\n- `x = mean.self` maps `mean.self` values to x-axis (horizontal, left to right) positions.\n- `y = mean.acc` maps `mean.acc` values to y-axis (vertical, bottom to top) positions.\n:::\n  \nNow do scatterplots with any pair of numeric variables you like. \n\nRemember that we saw with `summary()` that not every variable consists of numbers.\n\n:::{.callout-tip collapse=\"true\"}\nCheck out the example code.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one.gen, aes(y = mean.self, x = mean.acc)) +\n    geom_point()  \n\nggplot(data = study.one.gen, aes(x = AGE, y = mean.self)) +\n  geom_point()  \n  \nggplot(data = study.one.gen, aes(x = SHIPLEY, y = mean.self)) +\n  geom_point()  \n\nggplot(data = study.one.gen, aes(x = HLVA, y = mean.self)) +\n  geom_point()  \n```\n:::\n\n\n\n:::\n\n##### How-to Task 7 -- Edit the scatterplots to change how they look\n\nEdit the appearance of a plot step-by-step.\n\nWe are going to edit:\n\n1. the appearance of the points using alpha and size;\n2. the colour of the background using `theme_bw()`;\n3. the appearance of the labels using `labs()`.\n\nWe make the changes, one change at a time.\n\nYou have seen one of these moves before and you can guess at how to do the others.\nClick on the drop-down view to see the code but, if you want a challenge, try first to write the code on your own.\n\n1. the appearance of the points using alpha and size\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one.gen, aes(x = HLVA, y = mean.self)) +\n  geom_point(alpha = 0.5, size = 2) \n```\n\n::: {.cell-output-display}\n![](hypotheses-associations_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n:::\n\n2. the colour of the background using `theme_bw()`\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one.gen, aes(x = HLVA, y = mean.self)) +\n  geom_point(alpha = 0.5, size = 2)  +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](hypotheses-associations_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n:::\n\n3. the appearance of the labels using `labs()`\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one.gen, aes(x = HLVA, y = mean.self)) +\n  geom_point(alpha = 0.5, size = 2)  +\n  theme_bw() +\n  labs(x = \"HLVA\", y = \"mean self rated accuracy\")\n```\n\n::: {.cell-output-display}\n![](hypotheses-associations_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n\n:::\n\n::: callout-tip\nThe arguments `alpha` and `size` can change the appearance of most geometric objects (geoms) in ggplot:\n\n- in the code example, here, we vary the `alpha` number to change how opaque or transparent the points are;\n- and we vary the size number to vary the size of the points.\n:::\n\n##### How-to Task 8 -- Now experiment\n\nThere are no right answers here: edit the appearance of your plots by changing alpha, size and colour of points.\n\n::: callout-tip\nPlay is an important part of learning.\n\n- Experimenting with how plots look is a key element in becoming a master at data visualization. You won't know what looks good to you unless you try different things.\n:::\n\nIf you really want to extend your skills, it is really important that you learn how to find useful online help.\n\n> Q.5. Can you find the ggplot reference page on scatterplots? \n\n:::{.callout-tip collapse=\"true\"}\n## Hint\nDo a search with the keywords: `ggplot reference geom_point`\n:::\n\n:::{.callout-tip collapse=\"true\"}\n## Answer\n> A.5. You can find reference information here: <https://ggplot2.tidyverse.org/reference/geom_point.html>\n:::\n\n> Q.6. Can you change the colour of the points to a colour you like?\n\n:::{.callout-tip collapse=\"true\"}\n## Hint\nDo a search with the keywords: `ggplot colours`.\n\nUseful information on colour can be found here:\n\n<https://r-graphics.org/recipe-colors-setting>\n\nor \n\n<http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/>\n:::\n\n:::{.callout-tip collapse=\"true\"}\n## Answer\n> A.6. Here is how you do it: R will recognize many English colour names.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one.gen, aes(x = HLVA, y = mean.self)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"hotpink\")  +\n  theme_bw() +\n  labs(x = \"HLVA\", y = \"mean self rated accuracy\")\n```\n:::\n\n\n\n:::\n\n::: callout-important\nNow you: experiment!\n:::\n\n#### 7.4.2.4 How-to Part 4: Analyse associations\n\n##### How-to Task 9 -- Use correlation to to answer a research question\n\nExamine associations between variables using correlation.\n\nOne of our research questions is:\n\n2. Can people accurately evaluate whether they correctly understand written health information?\n\nWe can answer this question by examining whether mean self-rated accuracy of understanding correlates with mean accuracy of understanding.\nThe logic is that if we can accurately rate our own understanding (from bad to good) then that rating should be associated -- should be correlated with -- how accurately we can actually respond to questions that test that understanding.\n\n> Q.7. How do we examine the correlation between mean self-rated accuracy (`mean.self`) and mean accuracy (`mean.acc`)?\n\n:::{.callout-tip collapse=\"true\"}\n## Hint\nRemember from the lecture, that we use `cor.test()`:\n:::\n\nCan you figure out how to code a correlation test?\nIt helps with your learning if you first try to anticipate what the code will look like.\nThen reveal the code, below, to see what you guessed right.\n(Getting some things right, and some things wrong, is part of the learning process.)\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n> A.7. Here is how you do it: take a look at the code and the results of the correlation test.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(study.one.gen$mean.acc, study.one.gen$mean.self, method = \"pearson\",  alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  study.one.gen$mean.acc and study.one.gen$mean.self\nt = 7.1936, df = 167, p-value = 2.026e-11\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.3619961 0.5937425\nsample estimates:\n      cor \n0.4863771 \n```\n\n\n:::\n:::\n\n\n\n:::\n\n> Q.8. What is r, the correlation coefficient?\n\n:::{.callout-tip collapse=\"true\"}\n## Answer\n> A.8. r = 0.4863771\n:::\n\n> Q.9. Is the correlation significant?\n\n:::{.callout-tip collapse=\"true\"}\n## Answer\n> A.9. r is significant\n:::\n\n> Q.10. What are the values for t and p for the significance test for the correlation?\n\n:::{.callout-tip collapse=\"true\"}\n## Answer\n> A.10. t = 7.1936, p = 2.026e-11\n:::\n\n> Q.11. What do you conclude, given the correlation results?\n\n:::{.callout-tip collapse=\"true\"}\n## Hint\nReview the scatterplot you drew earlier (or draw one now) to examine the shape of the association between these variables.\n:::\n\n:::{.callout-tip collapse=\"true\"}\n## Answer\n> A.11. `mean.acc` and `mean.self` are positively correlated suggesting that as \n# `mean.acc` scores increase so also do `mean.self` scores\n:::\n\n#### 7.4.3 The practical exercises {#sec-associations-practical-workbook}\n\nNow you will progress through a series of tasks, and challenges, to test what you have learnt.\n\n::: callout-warning\nNow we will work with the data file\n\n-   `study-two-general-participants.csv`\n:::\n\nWe again split the steps into into parts, tasks and questions.\n\nWe are going to work through the following workflow steps:\n\n1.  Empty the R environment\n2.  Load relevant libraries\n3.  Read in the data file\n4.  Inspect the data\n5.  Change the type classification of variables if necessary\n6.  Draw scatterplots to visualize the association between pairs of variables\n8.  Estimate and test the correlations between pairs of variables\n\n::: callout-tip\n- The `how-to` guide showed you what functions you needed and how you should write the function code.\n- Use the code structure you have seen and *change* it to use the data required for these `practical exercises`: you will need to change the data-set name, the variable names, to get the code to work for the following exercises.\n- In learning how to code, the process of adapting example code is a key skill: we are learning what can change, and what has to stay the same.\n:::\n\nIn the following, we will guide you through the tasks and questions step by step.\n\n::: callout-important\nAn answers version of the workbook will be provided after the practical class.\n:::\n\n#### 7.4.3.1 Practical Part 1: Set-up\n\nTo begin, we set up our environment in R.\n\n##### Practical Task 1 -- Run code to empty the R environment\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list=ls())\n```\n:::\n\n\n\n\n##### Practical Task 2 -- Run code to load relevant libraries\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"tidyverse\")\n```\n:::\n\n\n\n\n#### 7.4.3.2 Practical Part 2: Load the data\n\n##### Practical Task 3 -- Read in the data file we will be using\n\nThe data file for the practical exercises is:\n\n- `study-two-general-participants.csv`\n\nUse the `read_csv()` function to read the data file into R.\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudy.two.gen <- read_csv(\"study-two-general-participants.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 172 Columns: 12\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (5): participant_ID, study, GENDER, EDUCATION, ETHNICITY\ndbl (7): mean.acc, mean.self, AGE, SHIPLEY, HLVA, FACTOR3, QRITOTAL\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n\n:::\n\nWhen you code this, you can choose your own file name, but be sure to give the data object you create a distinct name e.g. `study.two.gen`.\n\n##### Practical Task 4 -- Inspect the data file\n\nUse the `summary()` or `head()` functions to take a look\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(study.two.gen)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n participant_ID        mean.acc        mean.self        study          \n Length:172         Min.   :0.4107   Min.   :3.786   Length:172        \n Class :character   1st Qu.:0.6786   1st Qu.:6.411   Class :character  \n Mode  :character   Median :0.7679   Median :7.321   Mode  :character  \n                    Mean   :0.7596   Mean   :7.101                     \n                    3rd Qu.:0.8393   3rd Qu.:7.946                     \n                    Max.   :0.9821   Max.   :9.000                     \n      AGE           SHIPLEY           HLVA           FACTOR3     \n Min.   :18.00   Min.   :23.00   Min.   : 3.000   Min.   :29.00  \n 1st Qu.:25.00   1st Qu.:32.75   1st Qu.: 7.750   1st Qu.:47.00  \n Median :32.50   Median :36.00   Median : 9.000   Median :51.00  \n Mean   :35.37   Mean   :35.13   Mean   : 9.064   Mean   :51.24  \n 3rd Qu.:44.00   3rd Qu.:39.00   3rd Qu.:11.000   3rd Qu.:56.25  \n Max.   :76.00   Max.   :40.00   Max.   :14.000   Max.   :63.00  \n    QRITOTAL        GENDER           EDUCATION          ETHNICITY        \n Min.   : 6.00   Length:172         Length:172         Length:172        \n 1st Qu.:12.00   Class :character   Class :character   Class :character  \n Median :14.00   Mode  :character   Mode  :character   Mode  :character  \n Mean   :13.88                                                           \n 3rd Qu.:16.00                                                           \n Max.   :20.00                                                           \n```\n\n\n:::\n:::\n\n\n\n:::\n\n>**Pract.Q.1.** What is the median of `AGE`?\n\n> Pract.A.1. 32.50\n\n>**Pract.Q.2.** What class is the variable `ETHNICITY`?\n\n> Pract.A.2. character\n\n>**Pract.Q.3.** Does the summary indicate if any variable has missing values (NAs)?\n\n> Pract.A.3. No\n\n##### Practical Task 5 -- Change the class or type of the variable `ETHNICITY` to factor\n\nYou can use the `as.factor()` function you have used before: how do you write the code for these data?\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudy.two.gen$ETHNICITY <- as.factor(study.two.gen$ETHNICITY)\n```\n:::\n\n\n\n:::\n\n>**Pract.Q.4.** After you have done this, what information does `summary()` give you \nabout the variable `ETHNICITY`?\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(study.two.gen)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n participant_ID        mean.acc        mean.self        study          \n Length:172         Min.   :0.4107   Min.   :3.786   Length:172        \n Class :character   1st Qu.:0.6786   1st Qu.:6.411   Class :character  \n Mode  :character   Median :0.7679   Median :7.321   Mode  :character  \n                    Mean   :0.7596   Mean   :7.101                     \n                    3rd Qu.:0.8393   3rd Qu.:7.946                     \n                    Max.   :0.9821   Max.   :9.000                     \n      AGE           SHIPLEY           HLVA           FACTOR3     \n Min.   :18.00   Min.   :23.00   Min.   : 3.000   Min.   :29.00  \n 1st Qu.:25.00   1st Qu.:32.75   1st Qu.: 7.750   1st Qu.:47.00  \n Median :32.50   Median :36.00   Median : 9.000   Median :51.00  \n Mean   :35.37   Mean   :35.13   Mean   : 9.064   Mean   :51.24  \n 3rd Qu.:44.00   3rd Qu.:39.00   3rd Qu.:11.000   3rd Qu.:56.25  \n Max.   :76.00   Max.   :40.00   Max.   :14.000   Max.   :63.00  \n    QRITOTAL        GENDER           EDUCATION         ETHNICITY  \n Min.   : 6.00   Length:172         Length:172         Asian: 15  \n 1st Qu.:12.00   Class :character   Class :character   Black:  5  \n Median :14.00   Mode  :character   Mode  :character   Mixed:  7  \n Mean   :13.88                                         White:145  \n 3rd Qu.:16.00                                                    \n Max.   :20.00                                                    \n```\n\n\n:::\n:::\n\n\n\n:::\n\n> Pract.A.4. We can see that ETHNICITY lists observations following UK Office National Statistics ethnicity grouping:\n\n- Asian: 15\n- Black: 5\n- Mixed: 7\n- White: 145\n\n#### 7.4.3.3 Practical Part 3: Visualise the associations between variables\n\n##### Practical Task 6 -- Create a scatterplot to examine the association between some variables\n\nFor this practical exercise, you always want to use the outcome `mean.acc` as the y-axis variable so:\n\n- `y = mean.acc`\n\nThen you can use each numeric predictor variable as the x-axis variable so:\n\n- `x = mean.self`\n\nProduce scatterplots with *every* numeric predictor variable in the `study.two.gen` dataset\n\n::: callout-tip\nRemember what we saw with `summary()`: not every variable consists of numbers\n\nIf the `summary()` does not show you a mean for a variable, then R does not think\nthat variable is numeric\n:::\n\nNow, let's build some intuition.\n\nScientists often use scatterplots to get an intuitive understanding of the relationships between variables.\n\n::: callout-tip\nYou can read a scatterplot to learn about the size and the direction of an association between two variables (see the week 6 lecture):\n\n- Is the cloud of points more diffuse (the association is weaker) or more tightly clustered (the association is stronger)?\n- Does the cloud of points slope upwards (the association is more positive) or slope downwards (the association is negative).\n:::\n\nThe following questions ask you to look at plots, and make some judgments about what the plots tell you.\n\nIt can be hard to decide what an association looks like so make a decision based on **what you see.**\n\nRight now, we are working to build your intuitions so: reflect, trust your intuition, and make a decision.\n\n::: callout-tip\nFirst draw the plot, then answer the question.\n:::\n\n>**Pract.Q.5.** What is the shape (direction) of the association between `mean.self` and `mean.acc`?\n\n> Pract.A.5. Increase in `mean.self` is associated with increase in `mean.acc`\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = mean.self, y = mean.acc)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](hypotheses-associations_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n\n:::\n\n>**Pract.Q.6.** What is the shape (direction) of the association between `AGE` and `mean.acc`?\n\n> Pract.A.6. There is no clear association between `AGE` and `mean.acc`\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = AGE, y = mean.acc)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](hypotheses-associations_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n\n:::\n\n>**Pract.Q.7.** What is the shape (direction) of the association between `SHIPLEY`\nand `mean.acc`?\n\n> Pract.A.7. Increase in `SHIPLEY` is associated with increase in `mean.acc`\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = SHIPLEY, y = mean.acc)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](hypotheses-associations_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n\n:::\n\n>**Pract.Q.8.** What is the shape (direction) of the association between `HLVA`\nand `mean.acc`?\n\n> Pract.A.8. Increase in `HLVA` is associated with increase in `mean.acc`\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = HLVA, y = mean.acc)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](hypotheses-associations_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n\n:::\n\n>**Pract.Q.9.** What is the shape (direction) of the association between `FACTOR3`\nand `mean.acc`?\n\n> Pract.A.9. Increase in `FACTOR3` is associated with increase in `mean.acc`\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = FACTOR3, y = mean.acc)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](hypotheses-associations_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n\n:::\n\n>**Pract.Q.10.** What is the shape (direction) of the association between `QRITOTAL`\nand `mean.acc`?\n\n> Pract.A.10. Increase in `QRITOTAL` is associated with increase in `mean.acc`\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = QRITOTAL, y = mean.acc)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](hypotheses-associations_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n\n:::\n\n#### 7.4.3.4 Practical Part 4: Learn how to edit plotting code\n\n##### Practical Task 7 -- Edit the appearance of one plot step-by-step\n\nEdit your plotting code to make plots with a professional appearance.\n\nEdit a scatterplot to adjust\n\n1. the appearance of the points using `alpha`, `size` and `colour`;\n2. the colour of the background using `theme_bw()`;\n3. the appearance of the labels using `labs()`.\n\nIn the following, we ask you to edit one plot element at a time.\nYou can work out what to do.\n\n>**Pract.Q.11.** Can you edit the appearance of the points in a scatterplot using alpha, size and colour?\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = HLVA, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"red\")\n```\n\n::: {.cell-output-display}\n![](hypotheses-associations_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n\n:::\n\n>**Pract.Q.12.** Can you edit the appearance of the plot background?\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = HLVA, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"red\")   +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](hypotheses-associations_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n\n:::\n\n>**Pract.Q.13.** Can you edit the appearance of the labels using `labs()`?\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = HLVA, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"red\")   +\n  theme_bw() +\n  labs(x = \"HLVA\", y = \"mean accuracy\")\n```\n\n::: {.cell-output-display}\n![](hypotheses-associations_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n\n:::\n\n>**Pract.Q.14.** Can you find online information about colour blind palettes?\n\nTry doing a search with the keywords: `ggplot colour blind`\n\n> Pract.A.14. -- Here is one:\n\n<http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/>\n\n::: callout=tip\nNow it's your turn: experiment!\n\n- What about different colour words? Replace `\"red\"` with `\"...\"`?\n- What about a different size? Replace `size = 2` with `size =  ...` using a different number.\n- What about a different level of transparency (alpha)? Replace `alpha = 0.5` with `alpha =  ...` using a different fraction.\n:::\n\n#### 7.4.3.5 Practical Part 5: Use correlation to to answer the research questions\n\n##### Practical Task 8 -- Examine the correlation between mean accuracy (mean.acc) and some numeric predictor variables\n\n>**Pract.Q.15.** What is r (given as `cor` in the output) for the correlation between `HLVA` and `mean.acc`?\n\nCan you figure out the code to do the calculation?\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(study.two.gen$HLVA, study.two.gen$mean.acc, method = \"pearson\",  alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  study.two.gen$HLVA and study.two.gen$mean.acc\nt = 7.5288, df = 170, p-value = 2.866e-12\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.3787626 0.6044611\nsample estimates:\n      cor \n0.5000559 \n```\n\n\n:::\n:::\n\n\n\n:::\n\n> Pract.A.15. r = 0.5000559\n\n>**Pract.Q.16.** Is the correlation significant?\n\n> Pract.A.16. r is significant\n\n>**Pract.Q.17.** What are the values for t and p for the significance test for the correlation?\n\n> Pract.A.17. t = 7.5288, p = 2.866e-12\n\n>**Pract.Q.18.** What do you conclude, given the correlation results? \n\nMaybe draw a scatterplot to examine the shape of the association.\n\n> Pract.A.18. `HLVA` and `mean.acc` are positively correlated suggesting that as `HLVA` scores increase so also do `mean.acc` scores\n\n>**Pract.Q.19.** What is r (given as `cor` in the output) for the correlation between `mean.self` and `mean.acc`?\n\n> Pract.A.19. r = 0.5460792\n\nCan you figure out the code to do the calculation?\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(study.two.gen$mean.self, study.two.gen$mean.acc, method = \"pearson\",  alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  study.two.gen$mean.self and study.two.gen$mean.acc\nt = 8.4991, df = 170, p-value = 9.356e-15\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.4317217 0.6431596\nsample estimates:\n      cor \n0.5460792 \n```\n\n\n:::\n:::\n\n\n\n:::\n\n>**Pract.Q.20.** Is the correlation between `AGE` and `mean.acc` significant?\n\n> Pract.A.20. r is not significant\n\nCan you figure out the code to do the calculation?\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(study.two.gen$AGE, study.two.gen$mean.acc, method = \"pearson\",  alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  study.two.gen$AGE and study.two.gen$mean.acc\nt = 0.30121, df = 170, p-value = 0.7636\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.1269774  0.1721354\nsample estimates:\n       cor \n0.02309589 \n```\n\n\n:::\n:::\n\n\n\n:::\n\n>**Pract.Q.21.** What are the values for t and p for the significance test for the correlation between `QRITOTAL` and `mean.acc`?\n\n> Pract.A.21. t = 6.4711, p = 9.993e-10\n\nCan you figure out the code to do the calculation?\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(study.two.gen$QRITOTAL, study.two.gen$mean.acc, method = \"pearson\",  alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  study.two.gen$QRITOTAL and study.two.gen$mean.acc\nt = 6.4711, df = 170, p-value = 9.993e-10\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.3159538 0.5571417\nsample estimates:\n    cor \n0.44457 \n```\n\n\n:::\n:::\n\n\n\n:::\n\n>**Pract.Q.22.** What do you conclude, given the correlation results, about the association between `SHIPLEY` and `mean.acc`?\n\n> Pract.A.22. `SHIPLEY` and `mean.acc` are positively correlated suggesting that as HLVA scores increase so also do mean.acc scores\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(study.two.gen$SHIPLEY, study.two.gen$mean.acc, method = \"pearson\",  alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  study.two.gen$SHIPLEY and study.two.gen$mean.acc\nt = 6.8493, df = 170, p-value = 1.299e-10\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.3390103 0.5746961\nsample estimates:\n      cor \n0.4650537 \n```\n\n\n:::\n:::\n\n\n\n:::\n\n### 7.4.4 The answers\n\nAfter the practical class, we will reveal the answers that are currently hidden.\n\nThe answers version of the webpage will present my answers for questions, and some extra information where that is helpful.\n\n### 7.4.5 Look ahead: growing in independence\n\n::: callout-important\n-   Every problem you ever have: someone has had it before, solved it, and written a blog (or tweet or toot) about it.\n-   R is *free open statistical software*: everything you use is contributed, discussed and taught by a community of R users online, in open forums.\n-   Learning to navigate this knowledge is an introduction to the future of knowledge sharing.\n:::\n\n### 7.4.6 Optional exercises: to stretch you\n\nOne of the convenient and powerful things about R plotting code is that you can create a series of plots and put them together in a grid of plots for east comparison: we do that here.\n\nWe will use the patchwork library: check it out\n\n<https://patchwork.data-imaginist.com/articles/patchwork.html>\n\nWe get the library like this:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(patchwork)\n```\n:::\n\n\n\n\nHere's an example:\n\nFirst create two plots: give them both names\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np.AGE <- ggplot(data = study.two.gen, aes(x = AGE, y = mean.acc)) +\n  geom_point() \n#\np.SHIPLEY <- ggplot(data = study.two.gen, aes(x = SHIPLEY, y = mean.acc)) +\n  geom_point()  \n```\n:::\n\n\n\n  \nSecond put the two plots together by calling their names.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np.AGE  + p.SHIPLEY\n```\n\n::: {.cell-output-display}\n![](hypotheses-associations_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\n\n\nNow you try it: \n\n1. Create two plots, using `QRITOTAL` and `SHIPLEY` as predictors, and `mean.acc` as the outcome\n2. Then make a grid to present them side by side.\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np.QRITOTAL <- ggplot(data = study.two.gen, aes(x = QRITOTAL, y = mean.acc)) +\n  geom_point()\n#\np.SHIPLEY <- ggplot(data = study.two.gen, aes(x = SHIPLEY, y = mean.acc)) +\n  geom_point()\n\n# -- second put them together\np.QRITOTAL  + p.SHIPLEY\n```\n\n::: {.cell-output-display}\n![](hypotheses-associations_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\n\n:::\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}