{
  "hash": "81476242a8c40e89201792f9b37bb342",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"PSYC122-w19-how-to\"\nauthor: Rob Davies\noutput: word_document\n---\n\n\n\n\n\n\n\n# Introduction\n\n\nIn Week 19, we aim to *further develop* skills in working with the linear model.\n\nWe do this to learn how to answer research questions like:\n\n1. What person attributes predict success in understanding?\n2. Can people accurately evaluate whether they correctly understand written \nhealth information?\n\nIn this class, what is new is our focus on critically evaluating the ways in which people, effects or results can vary using *interaction* analyses.\n\n- This work simulates the kinds of interaction analyses that psychologists must often do in professional research.\n\n## Naming things\n\nI will format dataset names like this: \n\n- `all.data.csv`\n\nI will also format variable (data column) names like this: `variable` \n\nI will also format value or other data object (e.g. cell value) names like this: `all.data`\n\nI will format functions and library names like this: e.g. function `ggplot()` or e.g. library `{tidyverse}`.\n\n## The data we will be using\n\nIn this how-to guide, we use data from:\n\n(1.) two 2020 studies of the response of adults from a UK national sample to written health information\n\n- `study-one-general-participants.csv`\n- `study-two-general-participants.csv`\n\n(2.) along with data recently collected from PSYC122 students.\n\nThese data have been joined together to create a dataset of over 400 observations. This is because it often requires a lot of evidence to be able to draw precise or accurate conclusions about potential interaction effects.\n\n\n# Answers\n\n\n## Step 1: Set-up\n\n\nTo begin, we set up our environment in R.\n\n\n### Task 1 -- Run code to empty the R environment\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list=ls())                            \n```\n:::\n\n\n\n\n\n### Task 2 -- Run code to load relevant libraries\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"ggeffects\")\nlibrary(\"sjPlot\")\nlibrary(\"tidyverse\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.0     ✔ readr     2.1.6\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.2     ✔ tibble    3.3.1\n✔ lubridate 1.9.4     ✔ tidyr     1.3.2\n✔ purrr     1.2.1     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter()      masks stats::filter()\n✖ dplyr::lag()         masks stats::lag()\n✖ ggplot2::set_theme() masks sjPlot::set_theme()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n:::\n\n\n\n\n\n## Step 2: Load the data\n\n\n### Task 3 -- Read in the data file we will be using\n\nThe data file is called:\n\n- `all-data.csv`\n\nUse the `read_csv()` function to read the data file into R:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall.data <- read_csv(\"all.data.csv\")  \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 478 Columns: 11\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (5): participant_ID, study, GENDER, EDUCATION, ETHNICITY\ndbl (6): mean.acc, mean.self, AGE, SHIPLEY, HLVA, FACTOR3\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n\n\n\n### Task 4 -- Inspect the data file\n\nUse the `summary()` function to take a look at the dataset.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(all.data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n participant_ID        mean.acc        mean.self        study          \n Length:478         Min.   :0.3600   Min.   :2.250   Length:478        \n Class :character   1st Qu.:0.7500   1st Qu.:6.200   Class :character  \n Mode  :character   Median :0.8300   Median :7.200   Mode  :character  \n                    Mean   :0.8066   Mean   :6.967                     \n                    3rd Qu.:0.9000   3rd Qu.:7.910                     \n                    Max.   :1.0000   Max.   :9.000                     \n      AGE           SHIPLEY           HLVA           FACTOR3     \n Min.   :18.00   Min.   :19.00   Min.   : 2.000   Min.   : 9.00  \n 1st Qu.:21.00   1st Qu.:31.00   1st Qu.: 7.000   1st Qu.:46.00  \n Median :29.00   Median :35.00   Median : 9.000   Median :50.00  \n Mean   :32.85   Mean   :34.19   Mean   : 8.929   Mean   :49.84  \n 3rd Qu.:43.00   3rd Qu.:38.00   3rd Qu.:10.000   3rd Qu.:55.00  \n Max.   :76.00   Max.   :40.00   Max.   :14.000   Max.   :63.00  \n    GENDER           EDUCATION          ETHNICITY        \n Length:478         Length:478         Length:478        \n Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character  \n                                                         \n                                                         \n                                                         \n```\n\n\n:::\n:::\n\n\n\n\nNotice that we conducted a series of studies using the same online survey methods.\n\n- Our data include the responses made by *PSYC122* students.\n\n\n## Step 3: Work with different kinds of variables\n\n\nIt is an important skill in psychological data analysis to be able to: \n\n(1.) identify the different kinds of data variables we are working with;\n(2.) adapt our methods depending on differences in kind (variable `Class` or type).\n\nWe learn about these skills, next, in exercises that combine some revision with\nsome new moves.\n\n\n## Revise: consolidate what you know\n\n\n### Task 5 -- Use summaries or plots to examine variables\n\n\n- Q.1. What is the mean of the `AGE` variable in the dataset?\n- A.1. You can use the `summary()` function to calculate that the mean `AGE` is 32.85\n\n- Q.2. Draw a histogram of the age distribution.\n- A.2. You can write the code as you have been shown to do previously (e.g., in week 16):\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = all.data, aes(x = AGE)) + \n  geom_histogram(binwidth = 1) +\n  theme_bw() +\n  labs(x = \"Age (years)\", y = \"frequency count\")\n```\n\n::: {.cell-output-display}\n![](PSYC122-w19-how-to_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n\n- Q.3. Examine the age distribution: what does it tell you about the ages of the participants in the sample?\n- A.3. The histogram shows that most participants are around 20 years in age but\nthere is a \"long tail\" of small numbers of older participants.\n\n\n## Extend: make some new moves\n\n\nWe can tell from the summary and the distribution that the `AGE` variable consists\nof numbers (participant ages in years). \n\nAnother way to identify what kind of variable we have is by using a check question:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nis.factor(all.data$AGE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\nis.numeric(all.data$AGE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n\n\nThe `is._()` family of functions act like identity checks: what is this variable? \nThese functions work like questions with TRUE or FALSE answers.\n\n- Is this variable a factor? [TRUE or FALSE] \n- Is this variable numeric? [TRUE or FALSE]\n\n\n## Revise: consolidate what you know\n\n\n### Task 6 -- Identify (and change) what kind of variable -- numeric or factor -- a variable is\n\n#### Hint: Task 6 -- The `is._()` functions are available to ask what kind a variable is\n#### Hint: Task 6 -- The `as._()` functions can be used to change variable types\n\n- Q.4. What kind of variable is `EDUCATION`?\n- A.4. Use the same functions but change the variable name:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nis.factor(all.data$EDUCATION)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\nis.numeric(all.data$EDUCATION)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\n\n\n- Q.5. What do the `is._()` functions tell us?\n- A.5. The function calls tell us that `EDUCATION` is not a factor and is not numeric.\n\n- Q.6. If you look at the `summary()` results, what does it tell you the `Class` of `EDUCATION` is?\n- A.6. The summary shows that `EDUCATION` is identified as `Class: character`. \n\nYou can check this by doing the `is._()` test again.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nis.character(all.data$EDUCATION)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n\n\n- Q.7. How do you change the class or type of the variable `EDUCATION`? Change the variable's type (`Class`) into a factor.\n- A.7. The `as._()` functions can be used to change variable type, as you have done\npreviously (e.g., in week 16).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall.data$EDUCATION <- as.factor(all.data$EDUCATION)\n```\n:::\n\n\n\n\n- Q.8. What does a `summary()` tell us about `EDUCATION`?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(all.data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n participant_ID        mean.acc        mean.self        study          \n Length:478         Min.   :0.3600   Min.   :2.250   Length:478        \n Class :character   1st Qu.:0.7500   1st Qu.:6.200   Class :character  \n Mode  :character   Median :0.8300   Median :7.200   Mode  :character  \n                    Mean   :0.8066   Mean   :6.967                     \n                    3rd Qu.:0.9000   3rd Qu.:7.910                     \n                    Max.   :1.0000   Max.   :9.000                     \n      AGE           SHIPLEY           HLVA           FACTOR3     \n Min.   :18.00   Min.   :19.00   Min.   : 2.000   Min.   : 9.00  \n 1st Qu.:21.00   1st Qu.:31.00   1st Qu.: 7.000   1st Qu.:46.00  \n Median :29.00   Median :35.00   Median : 9.000   Median :50.00  \n Mean   :32.85   Mean   :34.19   Mean   : 8.929   Mean   :49.84  \n 3rd Qu.:43.00   3rd Qu.:38.00   3rd Qu.:10.000   3rd Qu.:55.00  \n Max.   :76.00   Max.   :40.00   Max.   :14.000   Max.   :63.00  \n    GENDER            EDUCATION    ETHNICITY        \n Length:478         Further:224   Length:478        \n Class :character   Higher :254   Class :character  \n Mode  :character                 Mode  :character  \n                                                    \n                                                    \n                                                    \n```\n\n\n:::\n:::\n\n\n\n\n- A.8. The summary will show how many different participants report themselves\nas belonging to one of the different `EDUCATION` level groups in the corresponding \nsurvey question.\n\nYou should see counts of the numbers of people in different `EDUCATION` level \ngroups in the total survey sample:\n\nEDUCATION\nFurther:224\nHigher :254\n\nWe can see that 224 participants reported in the survey that they had attained\na `Further` level of education (corresponding to A-level or Sixth Form).\n\n254 participants reported a `Higher` level of education (corresponding to\nuniversity level).\n\n\n## Step 4: Now draw plots to examine associations between variables and to visualize interactions\n\n\nHere, we are going to build on previous work to use plots to:\n\n(1.) Examine the associations between pairs of variables, an outcome and a predictor\n(2.) Examine how the association between two variables can be different for\ndifferent levels of a third variable\n\nScenario (2.) comes up if we are thinking about or working with *interaction* effects.\n\n\n### Consolidation: practice to strengthen skills\n\n\n### Task 7 -- Create a scatterplot to examine the association between two numeric variables \n\n#### Hint: Task 7 -- We are working with `geom_point()` and you need x and y aesthetic mappings.\n\nRun a chunk of code to make the plot.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = all.data, aes(x = HLVA, y = mean.acc)) +\n  geom_point() +\n  theme_bw() +\n  labs(y = \"Accuracy of understanding (mean.acc)\", \n       x = \"Health literacy (HLVA)\") +\n  xlim(0, 16) + ylim(0, 1)\n```\n\n::: {.cell-output-display}\n![](PSYC122-w19-how-to_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\n\nThis plot shows:\n\n- the possible association between x-axis variable `HLVA` and y-axis \nvariable `mean.acc`.\n\nThe plot code moves through the following steps:  \n\n1. `ggplot(...)` make a plot;\n2. `ggplot(data = all.data, ...)` with the `all.data` dataset;\n3. `ggplot(...aes(x = HLVA, y = mean.acc))` using two aesthetic mappings\n\n- `x = HLVA` map `HLVA` values to x-axis (horizontal, left to right) \npositions;\n- `y = mean.acc` map `mean.acc` values to y-axis (vertical, bottom to top) \npositions;\n\n4. `geom_point()` show the mappings as points.\n5. `theme_bw()` changes the theme to a white background.\n6. `labs(y = \"Accuracy of understanding (mean.acc)\", x = \"Health literacy (HLVA)\")` changes axis labels.\n7. `xlim(0, 6) + ylim(0, 1)` changes axis limits.\n\n\n#### Questions: Task 7\n\n- Q.9. What do you notice about the distribution of `mean.acc` scores at\nincreasing values of health literacy (`HLVA`) scores?\n- A.9. The scatterplot shows that, for increasing health literacy (`HLVA`) scores,\nthere is an associated rise in accuracy of understanding (`mean.acc`) scores.\n\n\n### Introduce: make some new moves\n\n\nIn the next sequence of exercises, we are going to take the `all.data` dataset and split it into parts (sub-sets) in different ways.\n\n- We split the dataset vertically, into different sets of rows or observations.\n\n\n#### Why are we learning how to do this?\n  \nThe capacity to do this kind of split-analyse operation is *extremely* useful.\n\nWe are going to do this so that we can examine how the effects of interest to us\n(here, associations) can vary between different groups of people.\n\n- Remember, observations about different people are on different rows in `all.data`.\n\n- We are going to focus on an association between two column variables (`mean.acc`, `HLVA`).\n- We are going to identify different groups (sub-sets) of observations using values on a third variable.\n\n\n### Task 8 -- Create a scatterplot to examine the association between two numeric variables, showing how the association is different for different values of a third variable\n\n#### Hint: Task 8 -- We are working with `geom_point()` again.\n\n\n#### Hint: Task 8 -- We can show how the association between two variables (`mean.acc`, `HLVA`) is different for different values of a third, categorical (factor), variable (`EDUCATION`) by splitting the plot so that we see the association for different levels of `EDUCATION`.\n\nHere, we are splitting the dataset into:\n\n- observation data from people with just `EDUCATION` level `Further`\n- observation data from people with just `EDUCATION` level `Higher`\n\nand we are then producing a different scatterplot for each sub-set of data produced by the split.\n\nRun the following chunk of code to make the plot.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = all.data, aes(x = HLVA, y = mean.acc)) +\n  geom_point() +\n  geom_smooth(method = 'lm') +\n  theme_bw() +\n  labs(y = \"Accuracy of understanding (mean.acc)\", \n       x = \"Health literacy (HLVA)\") +\n  xlim(0, 16) + ylim(0, 1) +\n  facet_wrap(~ EDUCATION)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](PSYC122-w19-how-to_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n\n\nThis plot shows:\n\n- the possible association between x-axis variable `HLVA` and y-axis \nvariable `mean.acc`\n- for different groups of people -- people with `Further` or people with `Higher` levels of `EDUCATION`.\n\nThe plot code moves through steps we have seen before. What is new here is this bit:\n\n`facet_wrap(~ EDUCATION)`\n\nThe function `facet_wrap()` splits the dataset into sub-sets (different parts): different sets of rows, where different sets are defined according to different values of the variable identified inside the brackets `(~ EDUCATION)`.\n\nHere, we are asking for different scatterplots for the dataset split by whether\nparticipants are coded as people with `Further` or people with `Higher` levels of `EDUCATION`.\n\nYou can see a general guide to the function here:\n\n<https://ggplot2.tidyverse.org/reference/facet_wrap.html>\n\n\n#### Questions: Task 8\n\n- Q.10. What do you notice about the distribution of `mean.acc` scores at\nincreasing values of health literacy (`HLVA`) scores, for different sub-sets of the data: for people with `Further` compared to people with `Higher` levels of `EDUCATION`?\n- A.10. You can see that the association between `mean.acc` and `HLVA` scores appears to be similar for different levels of education: the distribution of points is different but the shape is similar overall, and the trend line representing the association between `mean.acc` and `HLVA` looks similar too.\n\n\n#### Hint: Task 8 -- We can show how the association between two variables (`mean.acc`, `HLVA`) is different for different values of a third numeric variable (`SHIPLEY`) by splitting the dataset\n\nHere, we are first creating a new variable to code for (distinguish between) different sub-sets of observations (different rows in the dataset) based on `SHIPLEY` scores, and then second drawing different plots based on different subsets.\n\nWe do this in two steps, as follows.\n\nFirst, run a chunk of code to divide (`cut`) the dataset into parts:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall.data$SHIPLEY_splits <- cut_number(all.data$SHIPLEY, 3)\n```\n:::\n\n\n\n\nThe code works bit-by-bit like this:\n\n1. `all.data$SHIPLEY_splits <-` create a new variable, `SHIPLEY_splits` and add it to the dataset `all.data` given the work done by the bit of code on the right of the arrow `<-`.\n\nOn the right of the arrow `<-` ...\n\n2. `cut_number(all.data$SHIPLEY, 3)` uses the `cut_number(...)` to divide the dataset observations into three sets based on the values in the `all.data$SHIPLEY` variable named inside the brackets.\n\nThe function works by ordering all the observations (the rows) in the dataset according to the values in the named variable `all.data$SHIPLEY`, then splitting the dataset (here, into three sub-sets) based on values in that named variable.\n\n- Given this code, we are going to get three sub-sets of the data, observations corresponding to (1.) low (2.) mid or (3.) high `SHIPLEY` values.\n- We split the data into data about people with:\n\n(1.) low `SHIPLEY` values, scores between 19-33 on the `SHIPLEY` test;\n(2.) mid `SHIPLEY` values, scores between 33-37 on the `SHIPLEY` test;\n(3.) high `SHIPLEY` values, scores between 37-40 on the `SHIPLEY` test.\n\nYou can see a guide to the function here:\n\n<https://ggplot2.tidyverse.org/reference/cut_interval.html>\n\nNote that *where* we split the data (what ranges of scores we use) will depend on the sample.\n\nSecond, we draw a plot to examine if the association between two variables (`mean.acc`, `HLVA`) is different for different values of a third variable (`SHIPLEY`) by splitting the data:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = all.data, aes(x = HLVA, y = mean.acc)) +\n  geom_point() +\n  geom_smooth(method = 'lm') +\n  facet_wrap(~ SHIPLEY_splits, nrow = 1, labeller = label_both) +\n  labs(y = \"Accuracy of understanding (mean.acc)\", \n       x = \"Health literacy (HLVA)\") +\n  theme_bw() \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](PSYC122-w19-how-to_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n\nThe plot code moves through the scatterplot production steps we have seen before.  \n\nThe bit that is new is here:\n\n`facet_wrap(~ SHIPLEY_splits, nrow = 1, labeller = label_both)` which is included to use the data split, constructed earlier.\n\nThis addition allows us to show:\n\n- the nature of the association between two variables (`mean.acc`, `HLVA`) \n- for different values of the third variable (`SHIPLEY`)\n- by splitting the data into three sub-sets according to `SHIPLEY` score (19-33 low, 33-37 mid, 37-40 high).\n\n#### Questions: Task 8\n\n- Q.11. What do you notice about the distribution of `mean.acc` scores at\nincreasing values of health literacy (`HLVA`) scores, for different sub-sets of the data: for (1.) low (2.) mid (3.) high `SHIPLEY` values?\n- A.11. You can see that the association between `mean.acc` and `HLVA` scores appears to vary (the slope differs) given different values of the third variable (`SHIPLEY`).\n\n- Q.12. What do you think the values in the grey labels at the top of the facets (the plot panels) tell us?\n- A.12. The values tell us what values (e.g., `19,33`) are used to identify the range of `SHIPLEY` scores that have been used to define the sub-set of observations for which the plot below shows the association between `mean.acc` and `HLVA` scores.\n\n\n## Step 5: Use linear models with multiple predictors, to estimate the effects of factors as well as numeric variables\n\n\n### Consolidation: practice to strengthen skills\n\n\nAs we saw in weeks 17 and 18, we can use linear models to predict outcome variables. \n\n- Linear models can include numeric variables (like `HLVA`) as predictors. \n- Linear models can also include categorical variables or factors (like `EDUCATION`) as predictors.\n\n\n### Task 9 -- First, fit a linear model including just numeric variables as predictors\n\n#### Hint: Task 9 -- We use the `lm()` function to fit a model with `mean.acc` as the outcome and `HLVA` and `SHIPLEY` as predictors.\n\nNote that in this model:\n\n- `HLVA` is a measure of health literacy -- numeric scores correspond to a test of knowledge of health-related words\n- `SHIPLEY` is a measure of vocabulary knowledge -- numeric scores correspond to a test of knowledge of vocabulary\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.acc ~ HLVA + SHIPLEY, \n            data = all.data)\n\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ HLVA + SHIPLEY, data = all.data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.38048 -0.06818  0.01317  0.07672  0.30910 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.448687   0.040197  11.162  < 2e-16 ***\nHLVA        0.019132   0.002555   7.488 3.43e-13 ***\nSHIPLEY     0.005471   0.001252   4.370 1.53e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1127 on 475 degrees of freedom\nMultiple R-squared:  0.2003,\tAdjusted R-squared:  0.1969 \nF-statistic: 59.48 on 2 and 475 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nIf you look at the model summary you can answer the following questions.\n\n- Q.13. What is the estimate for the coefficient of the effect of the predictor, `SHIPLEY` (vocabulary knowledge)?\n- A.13. 0.005471 \n\n- Q.14. Is the effect significant?\n- A.14. It is significant. Because `Pr(>|t|)` equals `1.53e-05` for the `Estimate` of the effect of `SHIPLEY` (vocabulary knowledge): this means that  p < .05, and so the effect is significant.\n\n#### Hint: Task 9 -- Do you know how to intepret numbers like `1.53e-05`? If you are unsure you can find out about scientific notation here:\n\n<https://www.calculatorsoup.com/calculators/math/scientific-notation-converter.php>\n\n- Q.15. What are the values for t and p for the significance test for the \nestimated coefficient of the effect of `HLVA` (health literacy)?\n- A.15. t = 7.488, p = 3.43e-13\n\n- Q.16. What do you conclude are the effects of the `SHIPLEY` (vocabulary knowledge) and `HLVA` (health literacy) variables, as predictors of outcome `mean.acc` (accuracy of understanding of health information)?\n- A.16. The model slope estimates suggests that both predictors are significant, and that as both `SHIPLEY` (vocabulary knowledge) and `HLVA` (health literacy) increase, so `mean.acc` scores are predicted to increase also.\n\n\n### Task 10 -- Second, fit a linear model including a numeric variable and a factor as predictors\n\n#### Hint: Task 10 -- We use the `lm()` function to fit a model with `mean.acc` as the outcome and `FACTOR3` and `EDUCATION` as predictors.\n\nNote that in this model:\n\n- `FACTOR3` is a measure of reading strategy -- numeric scores correspond to a test of strategy awareness\n- `EDUCATION` is a measure of education level -- factor levels correspond to self-reported education\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.acc ~ FACTOR3 + EDUCATION, \n            data = all.data)\n\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ FACTOR3 + EDUCATION, data = all.data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.42828 -0.06774  0.02177  0.09198  0.31055 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     0.6032460  0.0415482  14.519  < 2e-16 ***\nFACTOR3         0.0040226  0.0008266   4.866 1.55e-06 ***\nEDUCATIONHigher 0.0053666  0.0113014   0.475    0.635    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1229 on 475 degrees of freedom\nMultiple R-squared:  0.04889,\tAdjusted R-squared:  0.04489 \nF-statistic: 12.21 on 2 and 475 DF,  p-value: 6.75e-06\n```\n\n\n:::\n:::\n\n\n\n\nIf you look at the model summary you can answer the following questions.\n\n- Q.17. What is the estimate for the coefficient of the effect of the predictor, `FACTOR3` (strategy)?\n- A.17. 0.0040226\n\n- Q.18. Is the effect significant?\n- A.18. It is significant. Because `Pr(>|t|)` equals `1.55e-06` for the `Estimate` of the effect of `FACTOR3` (strategy): this means that  p < .05, and so the effect is significant.\n\n- Q.19. What are the values for t and p for the significance test for the \nestimated coefficient of the effect of `EDUCATION` (level, `Further` compared to `Higher`)?\n- A.19. t = .475, p = .635\n\n- Q.20. Is the effect of `EDUCATION` significant?\n- A.20. It is not significant. Because `Pr(>|t|)` equals `0.635` for the `Estimate` of the effect of `EDUCATION` level this means that  p > .05, and so the effect is not significant.\n\n#### Hint: Task 10 -- How do we know how to interpret estimates for the effects of factors? We discussed how R deals with factors in week 18, and discuss factors, and the effects of factors, in the week 19 lecture.\n\n- Q.21. How should we interpret the coefficient estimate for the effect of `EDUCATION`?\n- A.21. Though the effect is not significant, we can say that, on average, outcome `mean.acc` is 0.0053666 (slightly) higher for people with `Higher` (compared to `Further`) level of education.\n\n- Q.22. What do you conclude are the effects of the `FACTOR3` (strategy) and `EDUCATION` (level, `Further` compared to `Higher`) variables, as predictors of outcome `mean.acc` (accuracy of understanding of health information)?\n- A.22. The model slope estimates suggest that education level does not have a significant effect but that as `FACTOR3` (strategy) scores increase, so `mean.acc` scores are predicted to increase. \n\n\n## Step 6: Use linear models with multiple predictors, including interaction effects\n\n\n### Introduce: make some new moves\n\n\nAs we saw through Task 8, it is possible that:\n\n- the association between two variables (`mean.acc`, `HLVA`) can be different for different values of a third categorical (factor) variable (`EDUCATION`);\n- the association between two variables (`mean.acc`, `HLVA`) can be different for different values of a third variable (`SHIPLEY`)\n\nWhile we can examine these possibilities using visualizations, we often need to conduct statistical analyses to test *interaction effects*, or the ways in which the association between two variables can be different for different levels of a third variable.\n\nWe can extend linear models to include terms that allow us to test or to estimate *interaction effects*.\n\n\n### Task 11 -- Center numeric variables before using them as predictors\n\n### Hint: Task 11\n\nWhen we include numeric variables (e.g., `HLVA, SHIPLEY`) in linear models, it can cause problems of interpretation or of estimation if we include the variables as they first come to us in datasets (as *raw* variables).\n\n- It often helps our analyses to *center* variables on their means.\n- Centering a variable means calculating its mean, and then subtracting that mean from every value in the variable column.\n\nFor example, to center values of the `FACTOR3` variable, we create a new column `data$FACTOR3_centered` by first calculating the mean of the `data$FACTOR3` variable, and then subtracting that mean from every row value in `data$FACTOR3`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall.data$FACTOR3_centered <- all.data$FACTOR3 - mean(all.data$FACTOR3, na.rm = TRUE)\n```\n:::\n\n\n\n\n- Q.23. Can you check what is going on when we center variables?\n- Q.23. Hint: You can see what is happening when you run this code by first calculating the mean for `FACTOR3`\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(all.data$FACTOR3, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 49.841\n```\n\n\n:::\n:::\n\n\n\n\nthen looking at column values in the new `FACTOR3_centered` column, compared to the original `FACTOR3` column:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall.data %>%\n  select(FACTOR3_centered, FACTOR3) %>%\n  print(n = 20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 478 × 2\n   FACTOR3_centered FACTOR3\n              <dbl>   <dbl>\n 1           10.2        60\n 2           -3.84       46\n 3            1.16       51\n 4           -4.84       45\n 5           13.2        63\n 6            6.16       56\n 7            3.16       53\n 8          -15.8        34\n 9            5.16       55\n10           10.2        60\n11            0.159      50\n12            9.16       59\n13           11.2        61\n14           -9.84       40\n15           -6.84       43\n16            5.16       55\n17            8.16       58\n18           -7.84       42\n19           -3.84       46\n20           -2.84       47\n# ℹ 458 more rows\n```\n\n\n:::\n:::\n\n\n\n\nWhat is the difference between the `FACTOR3` and `FACTOR3_centered` columns?\n\n- A.23. You can see that every value in the `FACTOR3_centered` column equals the value, on the same row, in the `FACTOR3` column, minus the mean for `FACTOR3`.\n\n- Q.24. Can you center the variable `HLVA`?\n- A.24. You can use the same code to center `HLVA`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall.data$HLVA_centered <- all.data$HLVA - mean(all.data$HLVA, na.rm = TRUE)\n```\n:::\n\n\n\n\n- Q.25. Can you center the variable `SHIPLEY`?\n- A.25. You can use the same code to center `SHIPLEY`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall.data$SHIPLEY_centered <- all.data$SHIPLEY - mean(all.data$SHIPLEY, na.rm = TRUE)\n```\n:::\n\n\n\n\n\n#### Why are we learning how to do this?\n\nIt is common in data analysis to want to transform variables before using them in analyses.\n\n- Here, we are transforming predictor variables by centering them on their mean values.\n\nThe practical reason for doing this transformation now is because if we use uncentered (raw) numeric variables as predictors in linear models that involve interactions the model can find it difficult to distinguish between the effects of those predictors and the effect of their interaction.\n\n\n### Task 12 -- Specify models to include interaction effects: interactions between two numeric predictor variables\n\n### Hint: Task 12 \n\nWe use `lm()` to specify models, as we have been doing. \n\n- What changes is that we now use the `*` operator in our model code to specify interaction effects.\n\nFor example, let's suppose that we want to examine the possibility that the effect of health literacy (`HLVA`) on accuracy understanding (`mean.acc`) is different for different values of vocabulary knowledge (`SHIPLEY`).\n\n- Here, we are considering the possibility that the association between health literacy (`HLVA`) and accuracy of understanding (`mean.acc`) *varies*.\n- We are considering the possibility that the the association between health literacy (`HLVA`) and accuracy of understanding (`mean.acc`) is different for different groups of people.\n- We are considering the possibility that the effect of health literacy (`HLVA`) on accuracy of understanding (`mean.acc`) is different for people who differ, also, in vocabulary knowledge (`SHIPLEY`).\n\nIn examining the possibility that the effect of health literacy (`HLVA`) on accuracy of understanding (`mean.acc`) is different for different values of vocabulary knowledge (`SHIPLEY`), we are examining a possible *interaction* between the effects of health literacy (`HLVA`) and vocabulary knowledge (`SHIPLEY`).\n\n\n**Let's go through this step-by-step.**\n\n\nFirst, consider: if we ignored the possibility of an interaction, we would fit a model with just the predictors: health literacy (`HLVA`) and vocabulary knowledge (`SHIPLEY`).\n\nWe can fit the same model that we fit before (for Task 9).\n\n- We vary the code a little, by using the centered variables we have just created:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.acc ~ HLVA_centered + SHIPLEY_centered, \n            data = all.data)\n\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ HLVA_centered + SHIPLEY_centered, data = all.data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.38048 -0.06818  0.01317  0.07672  0.30910 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      0.806587   0.005155 156.453  < 2e-16 ***\nHLVA_centered    0.019132   0.002555   7.488 3.43e-13 ***\nSHIPLEY_centered 0.005471   0.001252   4.370 1.53e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1127 on 475 degrees of freedom\nMultiple R-squared:  0.2003,\tAdjusted R-squared:  0.1969 \nF-statistic: 59.48 on 2 and 475 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n- Q.26. Can you compare the summary of results for this model with the model, using the same (but not centered) predictors, that you fitted for Task 9 -- compare the estimates, what do you see?\n- A.26. If we compare the results of the models we can see that the estimates, t-test values and probability values are the same for `HLVA` compared to `HLVA_centered` or for `SHIPLEY` compared to `SHIPLEY_centered`. \n\n- This shows that centering predictors only changes the scaling of the predictor variables so that their centers are 0.\n\n\nSecond, now consider: we aim to test or estimate the interactions between the effects of health literacy (`HLVA_centered`) and vocabulary knowledge (`SHIPLEY_centered`).\n\n- We vary the code a little, again, this time by separating the predictors by `*` not by `+`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.acc ~ HLVA_centered*SHIPLEY_centered, \n            data = all.data)\n\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ HLVA_centered * SHIPLEY_centered, data = all.data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.37986 -0.06840  0.01342  0.07652  0.29872 \n\nCoefficients:\n                                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                    0.8061527  0.0054951 146.703  < 2e-16 ***\nHLVA_centered                  0.0191754  0.0025645   7.477 3.70e-13 ***\nSHIPLEY_centered               0.0055241  0.0012742   4.335 1.78e-05 ***\nHLVA_centered:SHIPLEY_centered 0.0001132  0.0004922   0.230    0.818    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1128 on 474 degrees of freedom\nMultiple R-squared:  0.2004,\tAdjusted R-squared:  0.1953 \nF-statistic: 39.59 on 3 and 474 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n- Q.27. Can you compare the summary of results for this model with the results for the previous model (which uses the same predictors but without an interaction)?\n\n- What do you see?\n\n- A.27. If we compare the results of the models we can see that now the summary gives us estimates for the effects of:\n\n- `HLVA_centered` -- this is the effect of `HLVA_centered` when `SHIPLEY_centered` is 0\n- `SHIPLEY_centered` -- this is the effect of `SHIPLEY_centered` when `HLVA_centered` is 0\n- `HLVA_centered:SHIPLEY_centered` -- this is the interaction, and reflects the change in the effect of `HLVA_centered` on outcome `mean.acc`, given different values of `SHIPLEY_centered`.\n\n- Notice that the effect of the interaction is not significant, suggesting, for this sample, that the effects of these predictor variables are at least approximately independent of each other. \n\nThe `*` symbol (the `*` operator) is used here to code for a model including the effects of the two variables separated by the symbol, here, as well as the effect of the interaction between these two variables.\n\n\n### Task 13 -- Specify models to include interaction effects: interactions between a numeric predictor variable and a factor predictor variable\n\n### Hint: Task 13 -- We follow the same approach that we followed through Task 12.\n\nNow consider: we aim to test or estimate the interactions between the effects of reading strategy (`FACTOR3`) and education level (`EDUCATION`).\n\n- We vary the code to change the predictor variables but the structure otherwise stays the same:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.acc ~ FACTOR3_centered*EDUCATION, \n            data = all.data)\n\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ FACTOR3_centered * EDUCATION, data = all.data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.43422 -0.06111  0.01700  0.09208  0.23754 \n\nCoefficients:\n                                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                      0.802704   0.008193  97.977   <2e-16 ***\nFACTOR3_centered                 0.002210   0.001100   2.008   0.0452 *  \nEDUCATIONHigher                  0.005249   0.011241   0.467   0.6408    \nFACTOR3_centered:EDUCATIONHigher 0.004104   0.001656   2.479   0.0135 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1223 on 474 degrees of freedom\nMultiple R-squared:  0.06106,\tAdjusted R-squared:  0.05512 \nF-statistic: 10.28 on 3 and 474 DF,  p-value: 1.45e-06\n```\n\n\n:::\n:::\n\n\n\n\n- Q.28. Can you identify what effects are shown in the model summary?\n- A.28. We can see that now the summary gives us estimates for the effects of:\n\n- `FACTOR3_centered` -- this is the effect of reading strategy (`FACTOR3`) when `EDUCATION` level is `Further`\n- `EDUCATIONHigher` -- this is the effect of `EDUCATION` when `FACTOR3_centered` is 0. \n\nNote that the effect of `EDUCATION` is the estimated difference in outcome when `EDUCATION` level is `Further` (not shown, treated as the baseline) compared to when `EDUCATION` level is `Higher`.\n\n- `FACTOR3_centered:EDUCATIONHigher` -- this is the interaction, and reflects the change in the effect of `FACTOR3_centered` on outcome `mean.acc`, given different values of `EDUCATION`, here, when `EDUCATION` is `Higher` instead of `Further`.\n\n\n#### What are we learning here?\n\nRemember from week 18:\n\nCategorical variables or **factors** and reference levels.\n\n- If you have a categorical variable like `EDUCATION` then when you use it in\nan analysis, R will look at the different categories (called `levels) e.g., here,\n`Higher, Further` and it will pick one\nlevel to be the *reference* or baseline level. \n- The *reference* is the the level against which other levels are compared. \n- Here, the reference level is `Further` (education) simply because, unless\nyou tell R otherwise, it picks the level with a category name that begins\nearlier in the alphabet as the reference level.\n\n\n#### How do we interpret interactions?\n\n- It helps to plot the effects estimates, given the model.\n\nWe can do this in a two-step sequence, similar to the sequence we trialled through weeks 17 and 18:\n\n1. First fit the model\n2. Second, use the model information to plot the predictions, given the effects\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# -- first fit the model\nmodel <- lm(mean.acc ~ FACTOR3_centered*EDUCATION, \n            data = all.data)\n\n# -- make plot\nplot_model(model, type = \"pred\", \n           terms = c(\"FACTOR3_centered\", \"EDUCATION\")) +\n  theme_bw() +\n  ylim(0, 1)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nScale for y is already present.\nAdding another scale for y, which will replace the existing scale.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](PSYC122-w19-how-to_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n\n\n- Q.29. Can you identify how the effects of reading strategy (`FACTOR3`) and education level (`EDUCATION`) interact, given the model results summary and this plot?\n- A.29. The plot, and the estimate for the interaction `FACTOR3_centered:EDUCATIONHigher`, together show that the coefficient for the effect of reading strategy (`FACTOR3_centered`) is larger (the slope is steeper) when `EDUCATION` is `Higher` instead of `Further`.\n\n- Notice that, for this sample, the interaction is not significant, suggesting that there is no difference between education levels in the relative effectiveness of reading strategy.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}