{
  "hash": "734b43bcfc80a16b13508faaf8483ca0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: 3. Multiple Regression Models that Include Interactions (Moderated Variables)\nsubtitle: Emma Mills\norder: 4\neditor: \n  markdown: \n    wrap: 72\n---\n\n\n\n\n\n\n\n# Lecture\n\n[Lecture\nLink](https://lancaster.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=7718c2a4-2676-4b85-ac17-b26d014265c0)\n\n## Slides\n\n[Slides Link](data/Wk3/PSYC234_Week_13_Slides_Student.zip)\n\n## Materials\n\nThere are two zipped folders to download for week 13:\n\n-   The first folder is a zipped folder called `Lecture_3_Materials.zip`.\n    It can be downloaded [here](data/Wk3/Lecture_3_Materials.zip). This has the\n    model lecture script and the `KidIQ.txt` file that was demonstrated in the lecture\n-   The second folder is called `Lab_3_Materials.zip`. In this folder is the \n    `WorldHappinessReportData.csv` and a half prepared .Rmd file for the lab in week 13.  I did this because it is a really interesting dataset but the tidying and visualisation would take forever....please download it [here](data/Wk3/Lab_3_Materials.zip).\n    \n## Lab Task\n\nWe are working with the `WorldHappinessReportData.csv` from the folder listed above.  Upload it to the R server, (preferably before you come to the lab) and complete the `Multiple_Regression_Interactions_Student.Rmd` file using that data.\n\nThe model output you are aiming to match is below\n\n![Model output](Images/Wk3/Model%20Output.png)\n\n## Pre-Lab Activity\n\n1.  Watch the lecture before you attempt anything!\n2.  Download the zip files and upload to your R account\n3.  Look at the model outout above, begin by interpreting the model summary, \n    as far as you can (as we did in Lab in week 11 & 12).\n4.  Next get the analysis work flow diagram and begin to think about\n    what piece of code do you need for each stage\n5.  Start a script and import the dataset. Use the lecture and the model\n    script as a guide\n6.  Write a plan of how you might approach an analysis to get to this\n    model\n-   you could write bullet points against the stages of the analysis\n    workflow diagram\n7.  You might want to stop at this point - wanting some confirmation\n    from your peers or staff; you could:\n\n-   post to the discussion forum at this point and we could discuss it\n\n-   talk amongst your peers and work together on it in independent study\n    time - forming a small study group for this process\n\n-   wait until the lab and bring ideas then...\n\n::: callout-tip\n## My predictor labels and suffixes\n\nThe model output has several predictors with suffixes, demarcated by and\nunderscore '\\_' and a letter e.g. '\\_h'; I explain these in the R Studio\ndemonstrations in the lecture and you can use these as a guide to which\nkind of processes you may choose to use to transform any variables.\n:::\n\n## Test Yourself\n\nThe link to this week's multiple choice quiz, WBA 3, is [here](https://modules.lancaster.ac.uk/mod/quiz/view.php?id=2506930)\n\n\n## Interactions\n\nSo far we have considered models with multiple variables - of both\ncategorical and continuous types. One property of all these predictors\nin these models has been that they are functionally independent of each\nother.  \nWhat does functionally independent of each other mean? This means that,\nirrespective of any correlated relationship that we may have visualised\nas we got to know the data, when it came to coding the model, we did not\nlet the variables talk to each other. We only let them talk to the\noutcome variable.  \nYou have met interactions in PSYC214.  The focus of this week's lecture and lab\nis to introduce interactions in the context of a multiple regression model.\n\nI am also going to introduce a concept called nested modelling.  This is where \na researcher builds a series of models and with each step, the model takes the previous\nmodel and builds directly onto it.  In this way, the previous model is contained, or nested,\nin the latest model.\n\nThis strategy of building a model has immediate benefits because you can test\nfor a significant difference between the two models. For instance, when you are unsure about what\npredictors may make the best fitting model. Or if you were in an \nexploratory research framework.  It can also have benefits for when you have \ncollected confounding or third variables. Finally, if you are unsure that using\nan interaction term in your model has resulted in a better fit for the data,\nhaving two models, with the first model also existing within the larger second \nmodel, gives you the opportunity to test for the utility of that interaction term\n\nIn summary, this week we are learning about and applying:\n\n - interaction terms within a multiple regression model\n - nested modelling\n - a principled method for saying that one model is a better fit for the data than another\n \nWhile also thinking about the workflow of a good analysis.  \n\n![Workflow](Images/Wk3/Wrangle.png)\n\nThinking and acting systematically will a) help your writing of any results section and b) help with your interpretation of models and ideas to write for your discussion section.\n \n### Import\n\nBefore beginning, I will introduce the dataset to you:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd <- read_csv(\"data/Wk3/Lecture_3_Materials/KidIQ.txt\", col_types = cols(mom_work = col_skip()))\n\n#d <- read_csv(\"KidIQ.txt\", col_types = cols(mom_work = col_skip()))\n\nsummary(d)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   kid_score         mom_hs           mom_iq          mom_age     \n Min.   : 20.0   Min.   :0.0000   Min.   : 71.04   Min.   :17.00  \n 1st Qu.: 74.0   1st Qu.:1.0000   1st Qu.: 88.66   1st Qu.:21.00  \n Median : 90.0   Median :1.0000   Median : 97.92   Median :23.00  \n Mean   : 86.8   Mean   :0.7857   Mean   :100.00   Mean   :22.79  \n 3rd Qu.:102.0   3rd Qu.:1.0000   3rd Qu.:110.27   3rd Qu.:25.00  \n Max.   :144.0   Max.   :1.0000   Max.   :138.89   Max.   :29.00  \n```\n\n\n:::\n:::\n\n\n\nThere are 434 observations over four variables.  A simple dataset for our demonstration.  We have:\n\n - `kid_score`: a continuous variable of test scores for children at 3 years-of-age; this is the outcome variable for this dataset\n - `mom_hs`: a categorical variable describing whether the mother of the 3-year-old \n complete their high school education or not. Two levels: 0 = no; 1 = yes\n - `mom_iq`: a continuous variable of IQ scores of the mothers in this sample.  The mean\n in this sample is 100 - which reflects the wider population average\n - `mom_age`: a continuous variable of age in years, captured at the time of testing of the child.\n \n### Tidy\n\nFrom the summary above, it appears to be a tidy dataset in as much as there are no missing observations. Woohoo!  \n\nHowever, `mom_hs` is currently viewed by R as a numerical variable, when it is a \ncategorical variable. For clarity, lets transform this now before visualising the \ndataset\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd$mom_hs <- as.factor(d$mom_hs)\nsummary(d)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   kid_score     mom_hs      mom_iq          mom_age     \n Min.   : 20.0   0: 93   Min.   : 71.04   Min.   :17.00  \n 1st Qu.: 74.0   1:341   1st Qu.: 88.66   1st Qu.:21.00  \n Median : 90.0           Median : 97.92   Median :23.00  \n Mean   : 86.8           Mean   :100.00   Mean   :22.79  \n 3rd Qu.:102.0           3rd Qu.:110.27   3rd Qu.:25.00  \n Max.   :144.0           Max.   :138.89   Max.   :29.00  \n```\n\n\n:::\n:::\n\n\nWith that small change, we can see the `mom_hs` much more clearly.  But still, a picture speaks a thousand words...\n\n\n### Visualise\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# bar charts for categorical variables\np_hs <- ggplot(d, aes(x = mom_hs, fill = mom_hs)) + geom_bar() + theme_classic()\n\n# (so called) continuous variables\np_score <- ggplot(d, aes(x = kid_score)) + geom_histogram()+ theme_classic()\np_iq <- ggplot(d, aes(x = mom_iq)) + geom_histogram()+ theme_classic()\np_age <- ggplot(d, aes(mom_age)) + geom_histogram()+ theme_classic()\ngrid.arrange(p_score, p_hs, p_iq, p_age)\n```\n\n::: {.cell-output-display}\n![](Week3_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\nI have visualised the outcome variable here aswell, to help us get to know a little more about it. Notice also how\nI have used histograms rather than a smooth density plot for the continuous variables, because they are measured in\nwhole points; there are no fractions of points in these measures. So we can still see the distributoin of the values,\nbut using a histogram may remind you that the granularity of the measurement is in whole units, with no decimal values (not like something like milliseconds, for instance).\n\nHopefully, after last week's lecture you will see that the continuous variables all show a pretty tolerable normal curve. You might say that there is a slight negative skew on the kid score and a slight positive skew on the mom_iq, but nothing too drastic.  \n\nBut look at the `mom_hs` variable.  It is unbalanced - thankfully.  Within the group, I hope we all appreciate the value of a basic education.  So, within the sample, the mother's who completed their high school education are represented more than mothers who did not complete thrie high shcool education, at an approximate ratio of 3:1.  Quick check - what kind of transformation is indicated here (based on last week's learning)?\n\n### Correlations between continuous variables\n\nBecause we have multiple predictors of a continuous variables, we may choose to look at (and put a less garish version of) a correlation matrix to understand correlations between pairs of variables before modelling.\n\nHere, I have left in the outcome variable `kid_score`.  You can leave it in or out. It is just for getting to know the data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchart.Correlation(d[, c(1, 3, 4)], histogram=TRUE, pch=19)\n```\n\n::: {.cell-output-display}\n![](Week3_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-tip}\n### Reading the correlation matrix\n\nStarting from the top left: From `kid_score`, move one square to the right and you get *r* = .45; then move one square down and you hit `mom_iq`. *r* = .45 is the correlation between those two variables\n\nFrom `kid_score`, move two squares to the right and you get *r* = .092; then move two squares down and you hit `mom_age`. *r* = .092 is the correlation between those two variables\n\nHowever many squares you count across, count the same amount of squares down to find the paired variable.\n:::\n\nI am going to leave the majority of the interpretation of this matrix to you for practice, but note one thing.  The predictor `mom_age` is only weakly correlated with both `mom_iq` and the outcome variable, `kid_score`.  Any thoughts on the whether it will be a significant predictor in a multiple regression model?\n\n### Transform\n\nI have an unbalanced variable, `mom_hs`, so I want to transform this variable.  I choose to `centre` the variable.  And by doing so, I should do it for `mom_iq` and `mom_age`, to aid with interpretation.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(d$mom_hs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  0   1 \n 93 341 \n```\n\n\n:::\n:::\n\n\n\nCompleting high school = 1 here.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# make mom_hs a numeric variable\nd$mom_hs_c <- ifelse(d$mom_hs == \"1\", 1, 0)\n\nsummary(d$mom_hs_c)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.0000  1.0000  1.0000  0.7857  1.0000  1.0000 \n```\n\n\n:::\n:::\n\n\n\nThe mean is quite high because of the greater quantity of 1 values in the variable; so when we mean centre, we will subtract 0.7857 from every observation.  Consequently, the group of mothers who did not complete high school will be negative values (0-0.7857), while the mothers who did complete high school will be positive numbers (1-0.7857).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# now complete the rescaling by taking the mean away from every observation\nd$mom_hs_c <- d$mom_hs_c - mean(d$mom_hs_c)\nsummary(d$mom_hs_c)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n-0.7857  0.2143  0.2143  0.0000  0.2143  0.2143 \n```\n\n\n:::\n:::\n\n\n\nRepeat the centring with the two continuous variables.  You don't need to do the `ifelse` command in this case, as they are already numeric variables\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd$mom_iq_c <- d$mom_iq - mean(d$mom_iq)\nd$mom_age_c <- d$mom_age - mean(d$mom_age)\n```\n:::\n\n\n\n::: {.callout-tip}\n### What do the predictor variables mean now\n\nRemember under raw data, any regression coefficient is the change in the outcome variable for a one unit / level increase in the predictor variable *when all other predictors are at zero*\n\nNow we have mean centred, the interpretation changes:  any regression coefficient now represents a change in the outcome variable for a one unit / level increase in the predictor variable *when all other predictors are at their sample average*\n:::\n\nScroll back up to the visualisations for the raw data to look for the average IQ score and Age, from the middle of the plots' x-axes.  It is good to have a real number in your head to make sense of the models.\n\nWe are ready to build our first model.\n\n### Model\n\nI said I was going to introduce you to the practice of nested modelling in this lecture. We start this by building the first model: The intercept only model, or an empty model.  It is also sometimes called the null model, however the definition of a null model is not fixed.  A null model can also be a baseline model from which you measure change, and does not necessarily have to be an empty model.  While an empty model will always be an empty model because it has no predictors.  An intercept model will always be an intercept only model because it only models the intercept.\n\n#### The Empty / Intercept Only Model\n\nWe can express an empty or intercept only model like this:\n\n$$\nY = b_0 + e\n$$\n\nThe empty or intercept only model for any dataset expresses its mean value of the outcome variable:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(d$kid_score)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 86.79724\n```\n\n\n:::\n:::\n\n\n\nAnd here is the model as a regression model:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m0 <- lm(kid_score ~ 1, d))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = kid_score ~ 1, data = d)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-66.797 -12.797   3.203  15.203  57.203 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  86.7972     0.9797   88.59   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 20.41 on 433 degrees of freedom\n```\n\n\n:::\n:::\n\n\nThe regression coefficient matches the raw mean value I called above. So at this point, we can say that in the sample, the average score for a 3 year old child is approximately 87 points.\n\n#### A Simple Regression - one predictor\n\nLet's add `mom_iq`.  To demonstrate how model `m0` is nested inside this larger model,\nI will write the formula out in words\n\n$$\nModel zero: Kid\\_score = Intercept + error\n$$\n\n$$\nmodel one: Kid\\_score = Intercept + Mom's IQ + error\n$$\n\nHopefully, you can see how the first model is in the second model.  The change in the second model is the addition of one variable. I call my model `m1_c` because it has one predictor and it is a centred model.\n\nHere is the equation for the model - for those of you that like the numbers part:\n\n$$\nY = b_0 + b_1 * X_{mom\\_iq} + e\n$$\n\n\n\nHere is the code for this one predictor model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m1_c <- lm(kid_score ~ 1 + mom_iq_c, d))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = kid_score ~ 1 + mom_iq_c, data = d)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-56.753 -12.074   2.217  11.710  47.691 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 86.79724    0.87680   98.99   <2e-16 ***\nmom_iq_c     0.60997    0.05852   10.42   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 18.27 on 432 degrees of freedom\nMultiple R-squared:  0.201,\tAdjusted R-squared:  0.1991 \nF-statistic: 108.6 on 1 and 432 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nWhere are your eyes looking as you first scan the model output?  The bottom line first:\n\nThe model is significant (*F*(1, 432) = 108.6, *p* <.001) and explains approximately 20% of the variance in children's test scores.\n\nNext the regression coefficient:\n\nFor every one point increase in Mother's IQ, a child's test score increases by 0.61 of a point (*t* = 10.42, *p* < .001).\n\n#### How do we judge that any model is a better fit than any other model?\n\nFor models that are based **on the same data**, we can perform a test to see if the change in amount of variance explained from the smaller model to the larger model is significantly different.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(m0, m1_c)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: kid_score ~ 1\nModel 2: kid_score ~ 1 + mom_iq_c\n  Res.Df    RSS Df Sum of Sq      F    Pr(>F)    \n1    433 180386                                  \n2    432 144137  1     36249 108.64 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThis is how we do it - we call an `anova` on the two models.  Look at the output\n\nFrom the top of the output, we have \n\n - the title of the output\n - the next two lines repeat the model formulae\n - Beginning with the fourth line, we are presented with an ANOVA table\n   -  What is important in these lines is:\n    - the number 1 line is for Model 1 in the table (not your model 1)\n    - the number 2 line is for Model 2 in th table\n    - you want to look at the *p* value; if the *p* value is lower than < .05, then the difference in the amount of variance explained on the outcome variable between the two models is larger than zero.  And the addition of that new variable (here `mom_iq`) is warranted.\n    \n#### A Multiple Regression with Two Independent Predictors\n\nBased upon the model comparison that we conducted, `m1_c` has greater predictive value than `m0`, so we will carry `m1_c` forward and introduce another predictor in `m2_c`.  We could now think of `m1_c` as a null model, because it is the base model with which we will eventually compare `m2_c`.\n\nWe continue with our nesting principle, incrementally building a model, one predictor at a time so that the smaller mode is always present in the larger model.  Importantly, we are running all of these models on the same data so that we can use the model comparison technique.\n\n$$\nmodel one: Kid\\_score = Intercept + Mom's IQ + error\n$$\n\n$$\nmodel two: Kid\\_score = Intercept + Mom's IQ + Mom's Age + error\n$$\n\nThese two predictors are independent of each other. We are hoping they will each predict a singificant amount of *unique* variance on Children's test scores. We can express a model with two independent predictors like this\n\n$$\nY = b_0 + b_1 * X_{mom\\_iq} + b_2*X_{mom\\_age} + e\n$$\n\nAnd we can draw it like this:\n\n![Diagram of Independent\nPredictors](Images/Wk3/Diagram_Ind_Predictors.png)\n\nAnd the code for a model could look like this:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m2_c <- lm(kid_score ~ 1 + mom_iq_c + mom_age_c, d))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = kid_score ~ 1 + mom_iq_c + mom_age_c, data = d)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-56.941 -12.493   2.257  11.614  46.711 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 86.79724    0.87638   99.04   <2e-16 ***\nmom_iq_c     0.60357    0.05874   10.28   <2e-16 ***\nmom_age_c    0.38813    0.32620    1.19    0.235    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 18.26 on 431 degrees of freedom\nMultiple R-squared:  0.2036,\tAdjusted R-squared:  0.1999 \nF-statistic: 55.08 on 2 and 431 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nBecause I am building multiple models, before I rush to formally interpret this, I am \ngoing to perform my model comparison.  This time I am going to compare `m1_c` with `m2_c`. We don't need to worry about comparing the intercept only model because it was shown to be the weaker model in our last model comparison.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(m1_c, m2_c)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: kid_score ~ 1 + mom_iq_c\nModel 2: kid_score ~ 1 + mom_iq_c + mom_age_c\n  Res.Df    RSS Df Sum of Sq      F Pr(>F)\n1    432 144137                           \n2    431 143665  1     471.9 1.4157 0.2348\n```\n\n\n:::\n:::\n\n\nAs before, from the top of the table:\n\n  - the first line is the title\n  - the second line is the formula for the base model in this comparison\n  - the third line is the formula for the larger model in this comparison\n  - then we have the table itself - look for the *p* value:\n    - if it is lower than < .05, then the difference in the amount of change in the outcome variable between the two models is significant and the addition of the extra variable is warranted.\n    \nThis comparison between models `m1_c` and `m2_c` shows a *p* value of 0.235.  The difference between the models is non-significant. The addition of `mom_age_c` to the model does not significantly increase the amount of variance explained and so to include this variable in the next stage of model building is not warranted.\n\n::: {.callout-warning}\n### Is you non-significant predictor included in your hypotheses?\n\nIf your non-significant predictor is included in any of your hypotheses, then, by design, you have to keep them in your model and fully report them as non-significant.\n:::\n\nSo we will leave out `mom_age_c` in our next model.  The next model, therefore, add the final predictor variable in our dataset, `mom_hs_c`, the variable that describes whether a child's mom complete their high school education.  We will reuse the `m2_c` label for the model because we still only have two independent predictors here.\n\n$$\nmodel one: Kid\\_score = Intercept + Mom's IQ + error\n$$\n\n$$\nmodel two: Kid\\_score = Intercept + Mom's IQ + Mom's HS status + error\n$$\n\nThese two predictors are still independent of each other. We are hoping they will each predict a significant amount of *unique* variance on Children's test scores. We can express this particular model with these two independent predictors like this\n\n$$\nY = b_0 + b_1 * X_{mom\\_iq} + b_2*X_{mom\\_hs} + e\n$$\n\nHere is the code:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m2_c <- lm(kid_score ~ 1 + mom_iq_c + mom_hs_c, d))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = kid_score ~ 1 + mom_iq_c + mom_hs_c, data = d)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-52.873 -12.663   2.404  11.356  49.545 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 86.79724    0.87054  99.705  < 2e-16 ***\nmom_iq_c     0.56391    0.06057   9.309  < 2e-16 ***\nmom_hs_c     5.95012    2.21181   2.690  0.00742 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 18.14 on 431 degrees of freedom\nMultiple R-squared:  0.2141,\tAdjusted R-squared:  0.2105 \nF-statistic: 58.72 on 2 and 431 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nAnd as before, because I am building a series of models, I will perform my model comparison before interpreting the model.  This is a time-saving measure, as you may not want to spend time interpreting a larger model if the change in variance explained for the model is not significantly different from the smaller model.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(m1_c, m2_c)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: kid_score ~ 1 + mom_iq_c\nModel 2: kid_score ~ 1 + mom_iq_c + mom_hs_c\n  Res.Df    RSS Df Sum of Sq      F   Pr(>F)   \n1    432 144137                                \n2    431 141757  1    2380.2 7.2369 0.007419 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nI will forego running through the layout of the table this time.  Suffice to say that the line that begins with \"2\" is the line with the *p* value for the comparison.  It is less than .05 so we can conclude that the change in the amount of variance explained between the two models is significant and the inclusion of the variable `mom_hs_c` is warranted. As we continue to build larger models, we should carry this verion of model `m2_c` forward.\n\nSo now we can interpret it  - for practice. Let's call the summary of model `m2_c` again to reduce the need for scrolling.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m2_c)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = kid_score ~ 1 + mom_iq_c + mom_hs_c, data = d)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-52.873 -12.663   2.404  11.356  49.545 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 86.79724    0.87054  99.705  < 2e-16 ***\nmom_iq_c     0.56391    0.06057   9.309  < 2e-16 ***\nmom_hs_c     5.95012    2.21181   2.690  0.00742 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 18.14 on 431 degrees of freedom\nMultiple R-squared:  0.2141,\tAdjusted R-squared:  0.2105 \nF-statistic: 58.72 on 2 and 431 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe model is significant (*F*(2, 431) = 58.72, *p* < .001) and the amount of variance explained for Children's test scores is approximately 21%.\n\nMother's IQ and children's test scores are positively associated.  A one unit increase in IQ is significantly associated with an increase in test scores of 0.56 test points (*t* = 9.31, *p* < .001). Whether the child's mother completed high school or not is also positively related to test scores.  The difference in test scores for a child whose mother did not complete high school and a child whose mother did complete high school is 5.95 points (*t* = 2.69, *p* = .007).\n\nIf we run the mulitple regression model above, we may expect a plot of\nthe regression to look something like this:\n\n![Regression with no interaction](Images/Wk3/Ind_Mul_Regression.png)\n\nI have put the raw data values on the X-axis for the best way to communicate the scale.\nI have also used the raw mom_hs factor here, again for simplicity.  Remember that the transformations we performed do not change the information within the data. So this is okay. \n\nAs soon as we see a plot, lets take a moment to interpret it. What do we\nsee:\n\n-   a scatterplot with two groups - signified by the two colours of\n    black and grey dots\n    -   the legend shows black as 0 - the reference level here = mothers who did not complete high school\n    -   and grey as 1 = mothers who completed high school\n-   Mother's IQ score on the X-axis is predicting Child Test Score on\n    the Y-axis\n-   The black line is lower than the grey line: the black line is for test scores\n    of children whose mothers did not finish high school\n-   The grey line is higher than the black line: the grey line is for test scores\n    of children whose mothers did finish high school\n    \nWe know two pieces of information, from looking at this plot:\n\n1) For all children, irrespective of whether their mom finished high school or not, as the mom's IQ score increases, so does the child's test score.\n\n2) For children whose mothers finished high school, they get higher test scores than children whose mothers did not finish high school.\n\nEarlier, I said that these two predictors were independent of each other. We can see this in the plot because the effect for the difference in scores is constant across the range of IQ scores.  The black and grey lines are parallel. And remain parallel across the span of the plot.\n\n#### A Multiple Regression with Independent Predictors and an Interaction Term\n\nWhat if we built a model that asked `mom_iq_c` and `mom_hs_c` to jointly predict some variance in the outcome variable.  To do this, we need the variables to share their information with each other. \n\nWe are still only adding one predictor, and the smaller model will be nested inside the larger model.  We are still using the same data.\n\n$$\nmodel two: Kid\\_score = Intercept + Mom's IQ + Mom's HS status + error\n$$\n\n$$\nmodel three: Kid\\_score = Intercept + Mom's IQ + Mom's HS status + IQ * HS + error\n$$\n\nThese two predictors are still in the model as independent predictors, but we also include a term where the two predictors look like they are multiplied together.  This is what an interaction term is - the product of two or more variables added as an additional predictor in a model.  Now we are hoping to see some *unique* variance from the independent predictors and also some joint prediction of variance from our interaction term. We can express the interaction model like this\n\n$$\nY = b_0 + b_1 * X_{mom\\_iq} + b_2*X_{mom\\_hs} + b_3 * (X_{mom\\_iq} * X_{mom\\_hs}) + e\n$$\n\nHere is the code:  I am calling it `m3_c_int` because it has 3 predictors, and contains an interaction term\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m3_c_int <- lm(kid_score ~ 1 + mom_iq_c + mom_hs_c + mom_iq_c:mom_hs_c, d))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = kid_score ~ 1 + mom_iq_c + mom_hs_c + mom_iq_c:mom_hs_c, \n    data = d)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-52.092 -11.332   2.066  11.663  43.880 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       87.63892    0.90756  96.565  < 2e-16 ***\nmom_iq_c           0.58839    0.06058   9.712  < 2e-16 ***\nmom_hs_c           2.84076    2.42667   1.171  0.24239    \nmom_iq_c:mom_hs_c -0.48427    0.16222  -2.985  0.00299 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 17.97 on 430 degrees of freedom\nMultiple R-squared:  0.2301,\tAdjusted R-squared:  0.2247 \nF-statistic: 42.84 on 3 and 430 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nBefore going any further, lets compare:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(m2_c, m3_c_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: kid_score ~ 1 + mom_iq_c + mom_hs_c\nModel 2: kid_score ~ 1 + mom_iq_c + mom_hs_c + mom_iq_c:mom_hs_c\n  Res.Df    RSS Df Sum of Sq      F   Pr(>F)   \n1    431 141757                                \n2    430 138879  1    2878.4 8.9123 0.002994 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nMy eyes have gone straight to the *p* value now:  *p* = .003. It is smaller than .05 so we can conclude that the difference in the amount of variance explained in the outcome variable is significantly different in the larger model.  The inclusion of the interaction term is warranted.  If we were to build a larger model, then this larger model is the model that should be carried forward to the next step.\n\nBut we are not building any more models, as this dataset was a compact dataset and we have used up our variables.\n\nWhen you come to the end of the line with model building in this incremental, step-wise fashion, you will interpret and present:\n\n - the model that you hypothesised you would build\n - if there were several possible models from your hypotheses, you would present the one that was significantly the best predictor of variance.\n  - Note - this may not be the model with the most variables!\n\nThe model plot, with the addition of the interaction between mother's IQ and high school education, looks like this:\n\n![Regression with an interaction](Images/Wk3/Int_Mul_Regression.png)\n\n#### Interpreting a Model with an Interaction Term\n\nUp until now, we have been working with models of multiple independent predictors.  Now we have a model with independent predictors and interaction terms.  These take a little more interpretation.  We will look at how to do that here.\n\nWhen interpreting any interaction term, you will need:\n\n  - The regression coefficients for the  independent predictors upon which the interaction term is based\n  - The regression coefficient(s) for the interaction term.\n  \nFirst of all, do a model summary inspection as you would with any other model: Is the model significant?  How much variance in the outcome variable does the model explain? What does the intercept represent? \n\nThen move on to the predictors.  Interpret your independent predictors first.  Our demonstration model is a very simple model.  When you have models with more predictors, some of which may only be in the model as independent predictor, I suggest you look at those first before looking at the predictors that are involved in any interaction term.\n\nWhen you are ready to interpret the interaction term,  I suggest the following approach:\n\n 1) look at your first predictor and interpret it\n 2) look at the second predictor and intpret it\n 3) then look at the interaction term.  Look at the sign of the regression coefficient first.\n    - a positive coefficient suggests that at some point, the effect gets stronger than for the independent predictor\n    - a negative coefficient suggests that at some point, the effect gets weaker than the independent predictor.\n    \nLets do this for the `m3_c_int`. Lets call the summary here again to reduce the need for scrolling:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m3_c_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = kid_score ~ 1 + mom_iq_c + mom_hs_c + mom_iq_c:mom_hs_c, \n    data = d)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-52.092 -11.332   2.066  11.663  43.880 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       87.63892    0.90756  96.565  < 2e-16 ***\nmom_iq_c           0.58839    0.06058   9.712  < 2e-16 ***\nmom_hs_c           2.84076    2.42667   1.171  0.24239    \nmom_iq_c:mom_hs_c -0.48427    0.16222  -2.985  0.00299 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 17.97 on 430 degrees of freedom\nMultiple R-squared:  0.2301,\tAdjusted R-squared:  0.2247 \nF-statistic: 42.84 on 3 and 430 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n`mom_iq_c` is significant; for a one point increase in IQ points, a child's test scores increase by 0.58 points (*t* = 9.71, *p* <.001).\n`mom_hs_c` is not significant. Notice that this is a change from the independent predictor model of `m2_c`.  But we still need to understand what the coefficient suggests because we are going to interpret the interaction term. And this variable is also in the interaction term.  This model predicts that for a mother who has completed high school, a child's score increases by 2.84\npoints. \nThe interaction term `mom_iq_c:mom_hs_c` is significant.  It is negative. For one of the levels of high school completion, as IQ increases, that predicted 2.84 point increase for the independent predictor `mom_hs_c` is diminished or decreases by 0.48 points.\n\nSo lets now express this in plain(er) English:\n\nAs mom IQ increases, then a child's test score increases and if mom completed high school, initially, those child test scores are stronger than test scores for children whos mom didn't increase high school.  But, and here is the impact of what the interaction coefficient is describing....that 2.84 initial advantage gets smaller and smaller (by about 0.48 point each time) with every increase in IQ.\n\nTo aid interpretation, look at the plot once more:\n\n![Regression with an interaction](Images/Wk3/Int_Mul_Regression.png)\n\nInterpret once more:\n\n-   Still a scatterplot using raw data with two groups - signified by the two colours of black and grey dots\n    -   the legend shows black as 0 - the reference level here and grey as 1\n    -   0 refers to mothers who did not finish high school in America\n    -   1 refers to mothers who did finish high school\n-   Still with Mother's IQ score on the X-axis is predicting Child Test Score on the Y-axis\n-   The two lines are still showing that advantage for the group whose mothers completed high school because the grey line is higher than the black line to begin with\n- but now, as we move from left to right across the plot, moving up the IQ scale, the grey line is not parallel to the black line.The grey line appears to be a shallower line - or have a slower rate of change - for every point increase in IQ, than the black line. This is the effect of losing 0.48 of a point as we increase in IQ.\n    -   The black line appears to be a steeper line - or have a faster rate of change - for every point increase in IQ than the grey line.  This is because with every increase in IQ they are not feeling that loss of 0.48 of a point. It only applies to the group of children whose mothers completed high school.\n    \nThe two pieces of information from the earlier plot, that we thought we knew have changed from looking at this plot:\n\n1) The statement \"For all children, irrespecitve of whether their mom finished high school or not, as the mom's IQ score increases, so does the child's test score\" is still true but is not the entire interpretation.  We now need to consider that the slopes are no longer parallel - they have different gradients...\n\n2a) The statement \"For children whose mothers finished high school (grey line and dots), they get higher test scores than children whose mothers did not finish high school (black line and dots)\" is only true for some of those children.  And looking at the plot, I would say this is true for IQ levels that are lower than 100 (visual inspection of the plot).\n2b) The inverse is true:  \"For children whose mothers finished high school (grey line and dots), they get lower test scores than children whose mothers did not finish high school (black line and dots)\" is only true for some of those children.  And looking at the plot, I would say this is true for IQ levels that are higher than 100 (visual inspection of the plot).\n\n3a) We could add this:  For children whose mothers did not finish high school (black line and dots), they get lower test scores than children whose mothers finished high school (grey line and dots) when the mom's IQ level is lower than 100.\n3b) For children whose mothers did not finish high school (black line and dots), they get higher test scores than children whose mothers finished high school (grey line and dots) when the mom's IQ level higher than 100.\n\nSo the a child's test score does not depend only on the mom's IQ score or whether they finished their own education.  Mom's IQ score and high school education status interact with each other such that any child whose mom has an IQ scores higher than 100 is predicted to get a higher score than a child with a mom's who has a lower than 100 IQ score, but for children in the group with mom's who dropped out, the higher IQ scores seems to predict even higher scores than for those children whose mom finished their education.\n\nThis is the nature of an interaction.  The effect of one predictor variable, or the rate of change or the size of the coefficient for one prediction variable may be different across the levels of a second predictor variable.\n\nThe two variables work together, rather than independently, on the outcome variable.\n\nLets look at the model summary that gave us this plot:\n\nLets do the math to show this numerically:\n\nFirst look again at the high school variable\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(d$mom_hs_c)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n-0.7857  0.2143  0.2143  0.0000  0.2143  0.2143 \n```\n\n\n:::\n:::\n\n\nBecause this variable has been centred, the negative `Min` value represents the level of the variable for not finishing high school (-0.7857), the positive `Max` value represents the level of the variable for finishing high school (0.2143).  You will put these values into some of the sums below.\n\nThe model says that at lower IQ scores, the children whose mum did finish high school have higher scores than children whose mum did not finish high school\n\nLets do the maths for 20 points below the average:  We can model 80 IQ points as a prediction for lower IQ (modelled as -20 here as the sample average is 100 and 100 - 20 = 80)\n\nTest score for a child with a mum who did not finish high school and an IQ of 80 (black line on the plot)\nIntercept + not_finishing high school + IQ 80 + Interaction term\n\n\n::: {.cell}\n\n```{.r .cell-code}\n87.63892 + (0.58839*-20) + (2.84076*-0.7857) + -0.48427*(-0.7857*-20) # -0.7857 = represents mothers who did not finish high school\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 66.02932\n```\n\n\n:::\n:::\n\n\n\n\nTest score for a child with a mum who did  finish high school and an IQ of 80 (grey line on the plot)\nIntercept + not_finishing high school + IQ 80 + Interaction term\n\n\n::: {.cell}\n\n```{.r .cell-code}\n87.63892 +  (0.58839*-20) + (2.84076*0.2143) + -0.48427*(0.2143*-20) # 0.2143 = represents mothers who did finish high school\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 78.55548\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n(78.55548 - 66.02932)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 12.52616\n```\n\n\n:::\n:::\n\n\n\nAs the model predicts, the advantage is for the children whos mothers did finish high school.  The size of the advantage, when mums IQ is at 80, is approximately 12.5 points.\n\nLets look at what the scores are like for an IQ of 81...we should see a difference of 12.52616-0.48...the size of the advantage has gotten smaller by about 0.48 points\n\nIQ is now -19 (because 100-19 = 81)\n\nTest score for a child with a mum who did not finish high school and an IQ of 81 (black line on the plot)\nIntercept + not_finishing high school + IQ 81 + Interaction term\n\n\n::: {.cell}\n\n```{.r .cell-code}\n87.63892 + (0.58839*-19) + (2.84076*-0.7857) + -0.48427*(-0.7857*-19) # -0.7857 = represents mothers who did not finish high school\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 66.9982\n```\n\n\n:::\n:::\n\n\n\nTest score for a child with a mum who did  finish high school and an IQ of 81 (grey line on the plot)\nIntercept + not_finishing high school + IQ 81 + Interaction term\n\n\n::: {.cell}\n\n```{.r .cell-code}\n87.63892 + (0.58839*-19) + (2.84076*0.2143) + -0.48427*(0.2143*-19) # 0.2143 = represents mothers who did finish high school\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 79.04009\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# point difference between groups\n(79.04009 -  66.9982)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 12.04189\n```\n\n\n:::\n:::\n\n\nthe point score difference at 80 IQ points, is 12.53, the point score difference at 81 IQ points is 12.04\n\nIf we take 12.52616 from 12.04189, we get:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(12.04189-12.52616)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.48427\n```\n\n\n:::\n:::\n\n\nWhich is the negative regression coefficient for the interaction term.  As we increase the IQ points from 80 to 81, the difference in scores decreases between the groups by about half a point.\n\nLets look at the size of hte gap at the sample IQ points of 101:  if you look back at the plot, the lines are almost meeting at this point, any advantage that any group has will be much smaller.\n\nIQ is now expressed in this sum as 1, because the IQ variable in the model is centred at the sample average for IQ which is 100.  So and IQ of 101 = +1\n\nFinding the Test score for a child with a mum who did not finish high school and an IQ of 101 (black line on the plot)\nIntercept + not_finishing high school + IQ 101 + Interaction term\n\n\n::: {.cell}\n\n```{.r .cell-code}\n87.63892 + (0.58839*1) + (2.84076*-0.7857) + -0.48427*(-0.7857*1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 86.37582\n```\n\n\n:::\n:::\n\n\n\n\nTest score for a child with a mum who did  finish high school and an IQ of 101 (grey line on the plot)\nIntercept + not_finishing high school + IQ 101 + Interaction term\n\n\n::: {.cell}\n\n```{.r .cell-code}\n87.63892 + (0.58839*1) + (2.84076*0.2143) + -0.48427*(0.2143*1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 88.73231\n```\n\n\n:::\n:::\n\n\nThe difference at IQ 101 is much smaller than at IQ 81,  but there does still seem to be a slight advantage for the group whose mum finished high school.\n\nAnd once more Lets move the IQ a bit higher: to 120\n\nTest score for a child with a mum who did not finish high school and an IQ of 120 (black line on the plot)\nIntercept + not_finishing high school + IQ 120 + Interaction term\n\n\n::: {.cell}\n\n```{.r .cell-code}\n87.63892 + (0.58839*20) + (2.84076*-0.7857) + -0.48427*(-0.7857*20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 104.7846\n```\n\n\n:::\n:::\n\n\n\nTest score for a child with a mum who did  finish high school and an IQ of 120 (grey line on the plot)\nIntercept + not_finishing high school + IQ 120 + Interaction term\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n87.63892 + (0.58839*20) + (2.84076*0.2143) + -0.48427*(0.2143*20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 97.93991\n```\n\n\n:::\n:::\n\n\n\nAt IQ of 101, the children with mothers who had finished high school were slightly higher than children whose mothers had not finished high school, but the effect of that advantage has decreased as IQ increased. At IQ 120, the group whose mum did not finish high school (black line) are now showing a score advantage over the group whose mum did finish high school with the difference being approximately 7 points between the two groups).\n\n\n### Model diagnostics\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2)) # display plots in a 2 x 2 panel\nplot(m3_c_int)\n```\n\n::: {.cell-output-display}\n![](Week3_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\nThis model looks pretty healthy on the residuals!\n\n### Communicate\n\nA sample text for communicating this model:\n\nWe ran a multiple regression model to predict children's test scores at age 3-years, from mother's IQ score, whether they had completed high school or not and the interaction between the two. We centred the predictors before putting them into the model.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m3_c_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = kid_score ~ 1 + mom_iq_c + mom_hs_c + mom_iq_c:mom_hs_c, \n    data = d)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-52.092 -11.332   2.066  11.663  43.880 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       87.63892    0.90756  96.565  < 2e-16 ***\nmom_iq_c           0.58839    0.06058   9.712  < 2e-16 ***\nmom_hs_c           2.84076    2.42667   1.171  0.24239    \nmom_iq_c:mom_hs_c -0.48427    0.16222  -2.985  0.00299 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 17.97 on 430 degrees of freedom\nMultiple R-squared:  0.2301,\tAdjusted R-squared:  0.2247 \nF-statistic: 42.84 on 3 and 430 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nThe model was significant (*F*(3, 430) = 42.84, *p* < .001) and explained 23% of the variance in the children's test scores.\nMother's IQ is positively related to children's test scores, with each increase in IQ, test scores increased by 0.58 of a point (*t* = 9.71, *p* < .001). The predictor for whether or not a mother had completed their high school education was not significant (*b* = 2.84, *t* = 1.17, *p* = 0.242) however the interaction term for mother's IQ and education status was significant (*b* = -0.48, *t* = -2.99, *p* = .003). This indicates that while the test scores for children whose mothers completed high school show an initial advantage of 2.84 points, this advantage decreases with each increase of an IQ point by 0.48 of a test point.  Indeed, Figure 1 shows that at the higher levels of IQ in this sample, the group of children whose mothers did not finish high school, have higher test scores than those children whose mothers did finish high school.\n\n### What are interaction terms?\n\n-   We interpret each predictor as representing a value of the\n    variable’s influence on the outcome variable while holding all other\n    predictors constant\n-   The coefficient for each predictor tells us how the outcome variable\n    increases or decreases over incremental increases of a predictor - a\n    constant rate of change...adding one unit each time, increases or\n    decreases the outcome variable by the values of the coefficient\n\n\n\n\n\n\n\n\n\nInteractions are the product term of two (or more) predictors. There are several ways to create them:\n\n - We can do a maths sum: multiply two (or more) variables together and save them to your dataset then call that predictor in your model\n + You can use R code to write the interaction term into your model (so it is not a physical varaible in your dataset)\n   - we did this in model `m3_c_int`.\n   \nPutting it into your model formula can be expressed in two ways.  There is the use of a colon (:) as here:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm3_c_int_colon <- lm(kid_score ~ 1 + mom_iq_c + mom_hs_c + mom_iq_c:mom_hs_c, d)\n```\n:::\n\n\n\nOr, an equivalent model to `m3_c_int` is expressed using a shorter form of code, using an asterisk (*)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm3_c_int_Asterisk <- lm(kid_score ~ 1 + mom_iq_c*mom_hs_c, d)\n```\n:::\n\n\n\n\nboth of these types of model code give the exact same model output:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m3_c_int_colon)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = kid_score ~ 1 + mom_iq_c + mom_hs_c + mom_iq_c:mom_hs_c, \n    data = d)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-52.092 -11.332   2.066  11.663  43.880 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       87.63892    0.90756  96.565  < 2e-16 ***\nmom_iq_c           0.58839    0.06058   9.712  < 2e-16 ***\nmom_hs_c           2.84076    2.42667   1.171  0.24239    \nmom_iq_c:mom_hs_c -0.48427    0.16222  -2.985  0.00299 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 17.97 on 430 degrees of freedom\nMultiple R-squared:  0.2301,\tAdjusted R-squared:  0.2247 \nF-statistic: 42.84 on 3 and 430 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m3_c_int_Asterisk)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = kid_score ~ 1 + mom_iq_c * mom_hs_c, data = d)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-52.092 -11.332   2.066  11.663  43.880 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       87.63892    0.90756  96.565  < 2e-16 ***\nmom_iq_c           0.58839    0.06058   9.712  < 2e-16 ***\nmom_hs_c           2.84076    2.42667   1.171  0.24239    \nmom_iq_c:mom_hs_c -0.48427    0.16222  -2.985  0.00299 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 17.97 on 430 degrees of freedom\nMultiple R-squared:  0.2301,\tAdjusted R-squared:  0.2247 \nF-statistic: 42.84 on 3 and 430 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n### When are interaction terms used?\n\n - Theory may predict them, and so research questions/hypotheses may\npredict them.\n - Study design may implicitly suggest them (groups?)\n - Results may suggest them\n   - Regression coefficients that seem large when\nmodelled independently may suggest the need for an interaction term\n\n### Statistical Power of Interactions\n\nMany effect sizes in psychology hover around Cohen’s *d* = 0.4\n\nBased upon an effect size like this: \n\n - The power of an interaction can be a small as 1/16th of the independent effects within a model (Gelman\net al. 2020)\n - This is for ANOVA and regression methods\n - This is when all the assumptions of the model are met\n   + Most models violate model assumptions in some way \n   - Although relatively tolerant of violations: Power of the effects are thus reduced further...\n\n### Preparation of data for using interactions\n\nCentre or standardise your continuous variables as standardising puts\nboth predictors on the same scale. So interpreting the effect of one\npredictor on the other will be using the same scale of units\n\nConsider how to use your categorical variables:\n  - Dummy coding..?\n  - Sum coding..?\n  - Making new binary variables…?\n  - Coercing a binary variable to numeric class and mean centring\n\n### Building a model with interactions\n\nPlan to build the model suggested by your research\nquestions/hypotheses/theory. If that includes the interaction term,\nbuild it as the first model. If not, build an independent predictor\nmodel first and then build a further model that includes independent and\ninteraction terms.  Perform a model comparison as above to see if your interaction term has\ngiven you more explained variance at a significant level.\n\nHow are we doing in our list of things to think about - We need to look\nat:\n\n-   a model with some significant predictors! - done\n-   correlation matrices - done\n-   centering predictors - done\n-   standardising predictors - done\n-   models with categorical predictors - done & ongoing\n    -   interpreting models with categorical predictors - done & ongoing\n-   models with interaction terms - done\n-   the properties of multicollinearity - week 15\n-   choosing between different models - done & ongoing\n-   reporting models - ongoing",
    "supporting": [
      "Week3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/viz-1.8.2/viz.js\"></script>\n<link href=\"../../site_libs/DiagrammeR-styles-0.2/styles.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/grViz-binding-1.0.12/grViz.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}