{
  "hash": "5f065d600bfe31437279db92de78eafe",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"PSYC122-w19-workbook-answers\"\nauthor: Rob Davies\noutput: word_document\n---\n\n\n\n\n\n\n\n# Introduction\n\n\nIn Week 19, we aim to *further develop* skills in working with the linear model.\n\nWe do this to learn how to answer research questions like:\n\n1. What person attributes predict success in understanding?\n2. Can people accurately evaluate whether they correctly understand written \nhealth information?\n\nIn this class, what is new is our focus on critically evaluating the ways in which people, effects or results can vary using *interaction* analyses.\n\n- This work simulates the kinds of interaction analyses that psychologists must often do in professional research.\n\n## Naming things\n\nI will format dataset names like this: \n\n- `all.data.csv`\n\nI will also format variable (data column) names like this: `variable` \n\nI will also format value or other data object (e.g. cell value) names like this: `all.data`\n\nI will format functions and library names like this: e.g. function `ggplot()` or e.g. library `{tidyverse}`.\n\n## The data we will be using\n\nIn this how-to guide, we use data from:\n\n(1.) two 2020 studies of the response of adults from a UK national sample to written health information\n\n- `study-one-general-participants.csv`\n- `study-two-general-participants.csv`\n\n(2.) along with data recently collected from PSYC122 students.\n\nThese data have been joined together to create a dataset of over 400 observations. This is because it often requires a lot of evidence to be able to draw precise or accurate conclusions about potential interaction effects.\n\n\n# Answers\n\n\n## Step 1: Set-up\n\n\nTo begin, we set up our environment in R.\n\n\n### Task 1 -- Run code to empty the R environment\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list=ls())                            \n```\n:::\n\n\n\n\n\n### Task 2 -- Run code to load relevant libraries\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"ggeffects\")\nlibrary(\"sjPlot\")\nlibrary(\"tidyverse\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.0     ✔ readr     2.1.6\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.2     ✔ tibble    3.3.1\n✔ lubridate 1.9.4     ✔ tidyr     1.3.2\n✔ purrr     1.2.1     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter()      masks stats::filter()\n✖ dplyr::lag()         masks stats::lag()\n✖ ggplot2::set_theme() masks sjPlot::set_theme()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n:::\n\n\n\n\n\n## Step 2: Load the data\n\n\n### Task 3 -- Read in the data file we will be using\n\nThe data file is called:\n\n- `all-data.csv`\n\nUse the `read_csv()` function to read the data file into R:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall.data <- read_csv(\"all.data.csv\")  \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 478 Columns: 11\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (5): participant_ID, study, GENDER, EDUCATION, ETHNICITY\ndbl (6): mean.acc, mean.self, AGE, SHIPLEY, HLVA, FACTOR3\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n\n\n\n### Task 4 -- Inspect the data file\n\nUse the `summary()` function to take a look at the dataset.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(all.data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n participant_ID        mean.acc        mean.self        study          \n Length:478         Min.   :0.3600   Min.   :2.250   Length:478        \n Class :character   1st Qu.:0.7500   1st Qu.:6.200   Class :character  \n Mode  :character   Median :0.8300   Median :7.200   Mode  :character  \n                    Mean   :0.8066   Mean   :6.967                     \n                    3rd Qu.:0.9000   3rd Qu.:7.910                     \n                    Max.   :1.0000   Max.   :9.000                     \n      AGE           SHIPLEY           HLVA           FACTOR3     \n Min.   :18.00   Min.   :19.00   Min.   : 2.000   Min.   : 9.00  \n 1st Qu.:21.00   1st Qu.:31.00   1st Qu.: 7.000   1st Qu.:46.00  \n Median :29.00   Median :35.00   Median : 9.000   Median :50.00  \n Mean   :32.85   Mean   :34.19   Mean   : 8.929   Mean   :49.84  \n 3rd Qu.:43.00   3rd Qu.:38.00   3rd Qu.:10.000   3rd Qu.:55.00  \n Max.   :76.00   Max.   :40.00   Max.   :14.000   Max.   :63.00  \n    GENDER           EDUCATION          ETHNICITY        \n Length:478         Length:478         Length:478        \n Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character  \n                                                         \n                                                         \n                                                         \n```\n\n\n:::\n:::\n\n\n\n\nNotice that we conducted a series of studies using the same online survey methods.\n\n- Our data include the responses made by *PSYC122* students.\n\n\n## Step 3: Work with different kinds of variables\n\n\nIt is an important skill in psychological data analysis to be able to: \n\n(1.) identify the different kinds of data variables we are working with;\n(2.) adapt our methods depending on differences in kind (variable `Class` or type).\n\nWe learn about these skills, next, in exercises that combine some revision with\nsome new moves.\n\n\n## Revise: consolidate what you know\n\n\n### Task 5 -- Use summaries or plots to examine variables\n\n\n- Q.1. What is the median of the `FACTOR3` variable in the dataset?\n- A.1. You can use the `summary()` function to calculate that the median `FACTOR3` score is 50.00\n\n- Q.2. Draw a histogram of the `FACTOR3` distribution.\n- A.2. You can write the code as you have been shown to do previously (e.g., in week 16):\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = all.data, aes(x = FACTOR3)) + \n  geom_histogram(binwidth = 1) +\n  theme_bw() +\n  labs(x = \"Reading strategy (FACTOR3)\", y = \"frequency count\")\n```\n\n::: {.cell-output-display}\n![](PSYC122-w19-workbook-answers_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n\n- Q.3. Examine the reading strategy (`FACTOR3`) scores distribution: what does it tell you about the variation in the reading strategies of the participants in the sample?\n- A.3. The histogram shows that most participants present scores varying somewhere between 40-60 but there is a \"long tail\" of smaller numbers of participants with low or very low scores on the reading strategy (`FACTOR3`) measure.\n\n\n## Extend: make some new moves\n\n\nWe can tell from the summary and the distribution that the `FACTOR3` variable consists of numbers. \n\nAnother way to identify what kind of variable we have is by using a check question:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nis.factor(all.data$FACTOR3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\nis.numeric(all.data$FACTOR3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n\n\nThe `is._()` family of functions act like identity checks: what is this variable? \nThese functions work like questions with TRUE or FALSE answers.\n\n- Is this variable a factor? [TRUE or FALSE] \n- Is this variable numeric? [TRUE or FALSE]\n\n\n## Revise: consolidate what you know\n\n\n### Task 6 -- Identify (and change) what kind of variable -- numeric or factor -- a variable is\n\n#### Hint: Task 6 -- The `is._()` functions are available to ask what kind a variable is\n#### Hint: Task 6 -- The `as._()` functions can be used to change variable types\n\n- Q.4. What kind of variable is `GENDER`?\n- A.4. Use the same functions but change the variable name:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nis.factor(all.data$GENDER)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\nis.numeric(all.data$GENDER)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\n\n\n- Q.5. What do the `is._()` functions tell us?\n- A.5. The function calls tell us that `GENDER` is not a factor and is not numeric.\n\n- Q.6. If you look at the `summary()` results, what does it tell you the `Class` of `GENDER` is?\n- A.6. The summary shows that `GENDER` is identified as `Class: character`. \n\nYou can check this by doing the `is._()` test again.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nis.character(all.data$GENDER)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n\n\n- Q.7. How do you change the class or type of the variable `GENDER`? Change the variable's type (`Class`) into a factor.\n- A.7. The `as._()` functions can be used to change variable type, as you have done\npreviously (e.g., in week 16).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall.data$GENDER <- as.factor(all.data$GENDER)\n```\n:::\n\n\n\n\n- Q.8. What does a `summary()` tell us about `GENDER`?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(all.data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n participant_ID        mean.acc        mean.self        study          \n Length:478         Min.   :0.3600   Min.   :2.250   Length:478        \n Class :character   1st Qu.:0.7500   1st Qu.:6.200   Class :character  \n Mode  :character   Median :0.8300   Median :7.200   Mode  :character  \n                    Mean   :0.8066   Mean   :6.967                     \n                    3rd Qu.:0.9000   3rd Qu.:7.910                     \n                    Max.   :1.0000   Max.   :9.000                     \n      AGE           SHIPLEY           HLVA           FACTOR3         GENDER   \n Min.   :18.00   Min.   :19.00   Min.   : 2.000   Min.   : 9.00   Female:323  \n 1st Qu.:21.00   1st Qu.:31.00   1st Qu.: 7.000   1st Qu.:46.00   Male  :155  \n Median :29.00   Median :35.00   Median : 9.000   Median :50.00               \n Mean   :32.85   Mean   :34.19   Mean   : 8.929   Mean   :49.84               \n 3rd Qu.:43.00   3rd Qu.:38.00   3rd Qu.:10.000   3rd Qu.:55.00               \n Max.   :76.00   Max.   :40.00   Max.   :14.000   Max.   :63.00               \n  EDUCATION          ETHNICITY        \n Length:478         Length:478        \n Class :character   Class :character  \n Mode  :character   Mode  :character  \n                                      \n                                      \n                                      \n```\n\n\n:::\n:::\n\n\n\n\n- A.8. The summary will show how many different participants report themselves\nas belonging to one of the different `GENDER` self-identification groups in the corresponding survey question.\n\nYou should see counts of the numbers of people in different `GENDER` level \ngroups in the total survey sample:\n\nGENDER\nFemale:323\nMale  :155\n\nWe can see that 323 participants identified themselves as `Female` in the survey.\n\nWe can see that 155 participants identified themselves as `Male` in the survey.\n\n##### Gender identity representation in survey samples\n\nWe note, here, that in addition to the numbers shown in the summary, six participants in the survey data entered the `Non-Binary` identification response option, and two participants entered the `Prefer not to say` option, in response to the gender identification question in the survey.\n\nIn the present exercises, we are looking at the way in which the effect on outcomes of variables -- like variation in health literacy (`HLVA`) or reading strategy (`FACTOR3`) score -- vary for different values of a categorical variable (like `GENDER`). These kinds of interactions become more complicated to analyse where there are more than two categories or levels in a factor, especially when the numbers of participants in one or more categories or levels is relatively small. \n\nWe think it is important to ensure representation of the responses and experiences of the full range of diversity among the populations we study. In future work, we hope to have collected sufficient numbers of observations from groups of participants like those entering responses like `Non-Binary` or `Prefer not to say` in order to be able to incorporate all possible between-group comparisons in analyses.\n\nFor now, we enter this explanation as a promise to to examine more representative samples in future work. Here is a link, for those who are interested, to reports of analyses of data from a survey conducted by a leading research organization (Pew Research Center). Follow the link to \"Methodology\" for information on how this organization exemplify good practice in obtaining representative samples.\n\n<https://www.pewresearch.org/social-trends/2025/05/29/the-experiences-of-lgbtq-americans-today/>\n\n\n## Step 4: Now draw plots to examine associations between variables and to visualize interactions\n\n\nHere, we are going to build on previous work to use plots to:\n\n(1.) Examine the associations between pairs of variables, an outcome and a predictor\n(2.) Examine how the association between two variables can be different for\ndifferent levels of a third variable\n\nScenario (2.) comes up if we are thinking about or working with *interaction* effects.\n\n\n### Consolidation: practice to strengthen skills\n\n\n### Task 7 -- Create a scatterplot to examine the association between two numeric variables \n\n#### Hint: Task 7 -- We are working with `geom_point()` and you need x and y aesthetic mappings.\n\nHere, we can look at the potential association between variation in reading strategy (using the `FACTOR3` measure) and accuracy of understanding of health information (`mean.acc`).\n\nRun a chunk of code to make the plot.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = all.data, aes(x = FACTOR3, y = mean.acc)) +\n  geom_point() +\n  theme_bw() +\n  labs(y = \"Accuracy of understanding (mean.acc)\", \n       x = \"Reading strategy (FACTOR3)\") +\n  xlim(0, 65) + ylim(0, 1)\n```\n\n::: {.cell-output-display}\n![](PSYC122-w19-workbook-answers_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\n\nThis plot shows:\n\n- the possible association between x-axis variable `FACTOR3` and y-axis \nvariable `mean.acc`.\n\nThe plot code moves through the following steps:  \n\n1. `ggplot(...)` make a plot;\n2. `ggplot(data = all.data, ...)` with the `all.data` dataset;\n3. `ggplot(...aes(x = FACTOR3, y = mean.acc))` using two aesthetic mappings\n\n- `x = FACTOR3` map `FACTOR3` values to x-axis (horizontal, left to right) \npositions;\n- `y = mean.acc` map `mean.acc` values to y-axis (vertical, bottom to top) \npositions;\n\n4. `geom_point()` show the mappings as points.\n5. `theme_bw()` changes the theme to a white background.\n6. `labs(y = \"Accuracy of understanding (mean.acc)\", x = \"Reading strategy (FACTOR3)\")` changes axis labels.\n7. `xlim(0, 65) + ylim(0, 1)` changes axis limits.\n\n\n#### Questions: Task 7\n\n- Q.9. What do you notice about the distribution of `mean.acc` scores at\nincreasing values of reading strategy (`FACTOR3`) scores?\n- A.9. The scatterplot shows that, for increasing reading strategy (`FACTOR3`) scores, there is an associated rise in accuracy of understanding (`mean.acc`) scores.\n\n- There is extra credit for noticing that variation in outcome and predictor variable values is not tightly coupled: it is possible to have low reading strategy (`FACTOR3`) scores and high accuracy of understanding (`mean.acc`).\n\n\n### Introduce: make some new moves\n\n\nIn the next sequence of exercises, we are going to take the `all.data` dataset and split it into parts (sub-sets) in different ways.\n\n- We split the dataset vertically, into different sets of rows or observations.\n\n#### Why are we learning how to do this?\n  \nThe capacity to do this kind of split-analyse operation is *extremely* useful.\n\nWe are going to do this so that we can examine how the effects of interest to us\n(here, associations) can vary between different groups of people.\n\n- Remember, observations about different people are on different rows in `all.data`.\n\n- We are going to focus on an association between two column variables (`mean.acc`, `FACTOR3`).\n- We are going to identify different groups (sub-sets) of observations using values on a third variable.\n\n\n### Task 8 -- Create a scatterplot to examine the association between two numeric variables, showing how the association is different for different values of a third variable\n\n#### Hint: Task 8 -- We are working with `geom_point()` again.\n\n\n#### Hint: Task 8 -- We can show how the association between two variables (`mean.acc`, `FACTOR3`) is different for different values of a third, categorical (factor), variable (`GENDER`) by splitting the plot so that we see the association for different levels of `GENDER`.\n\nHere, we are splitting the dataset into:\n\n- observation data from people with just `GENDER` level `Female`\n- observation data from people with just `GENDER` level `Male`\n\nand we are then producing a different scatterplot for each sub-set of data produced by the split.\n\nRun the following chunk of code to make the plot.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = all.data, aes(x = FACTOR3, y = mean.acc)) +\n  geom_point() +\n  geom_smooth(method = 'lm') +\n  theme_bw() +\n  labs(y = \"Accuracy of understanding (mean.acc)\", \n       x = \"Reading strategy (FACTOR3)\") +\n  xlim(0, 65) + ylim(0, 1) +\n  facet_wrap(~ GENDER)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](PSYC122-w19-workbook-answers_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n\n\nThis plot shows:\n\n- the possible association between x-axis variable `FACTOR3` and y-axis \nvariable `mean.acc`\n- for different groups of people -- people with self-reported `GENDER` responses of `Female` or `Male`.\n\nThe plot code moves through steps we have seen before. What is new here is this bit:\n\n`facet_wrap(~ GENDER)`\n\nThe function `facet_wrap()` splits the dataset into sub-sets (different parts): different sets of rows, where different sets are defined according to different values of the variable identified inside the brackets `(~ GENDER)`.\n\nHere, we are asking for different scatterplots for the dataset split by whether\nparticipants are coded as `Female` or `Male` for this survey.\n\nYou can see a general guide to the function here:\n\n<https://ggplot2.tidyverse.org/reference/facet_wrap.html>\n\n\n#### Questions: Task 8\n\n- Q.10. What do you notice about the distribution of `mean.acc` scores at\nincreasing values of reading strategy (`FACTOR3`) scores, for different sub-sets of the data: for people with `Female` or `Male` `GENDER` coding?\n- A.10. You can see that the association between `mean.acc` and `FACTOR3` scores appears to be *mostly* similar for different `GENDER` codes.\n\n- The distribution of scores is different: we have more `Female` participants; their scores vary more widely.\n- But the trend is similar overall: the trend line representing the association between `mean.acc` and `FACTOR3` looks similar such that for both sub-groups in the sample, increasing `FACTOR3` scores are associated with higher `mean.acc` scores.\n\n\n#### Hint: Task 8 -- We can show how the association between two variables (`mean.acc`, `FACTOR3`) is different for different values of a third numeric variable (`HLVA`) by splitting the dataset\n\nHere, we are first creating a new variable to code for (distinguish between) different sub-sets of observations (different rows in the dataset) based on `HLVA` scores, and then second drawing different plots based on different subsets.\n\nWe do this in two steps, as follows.\n\nFirst, run a chunk of code to divide (`cut`) the dataset into parts:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall.data$HLVA_splits <- cut_number(all.data$HLVA, 3)\n```\n:::\n\n\n\n\nThe code works bit-by-bit like this:\n\n1. `all.data$HLVA_splits <-` create a new variable, `HLVA_splits` and add it to the dataset `all.data` given the work done by the bit of code on the right of the arrow `<-`.\n\nOn the right of the arrow `<-` ...\n\n2. `cut_number(all.data$HLVA, 3)` uses the `cut_number(...)` to divide the dataset observations into three sets based on the values in the `all.data$HLVA` variable named inside the brackets.\n\nThe function works by ordering all the observations (the rows) in the dataset according to the values in the named variable `all.data$HLVA`, then splitting the dataset (here, into three sub-sets) based on values in that named variable.\n\n- Given this code, we are going to get three sub-sets of the data, observations corresponding to (1.) low (2.) mid or (3.) high `HLVA` values.\n- We split the data into data about people with:\n\n(1.) low `HLVA` values, scores between 2-8 on the `HLVA` test;\n(2.) mid `HLVA` values, scores between 8-10 on the `HLVA` test;\n(3.) high `HLVA` values, scores between 10-14 on the `HLVA` test.\n\nYou can see a guide to the function here:\n\n<https://ggplot2.tidyverse.org/reference/cut_interval.html>\n\nNote that *where* we split the data (what ranges of scores we use) will depend on the sample.\n\nSecond, we draw a plot to examine if the association between two variables (`mean.acc`, `HLVA`) is different for different values of a third variable (`SHIPLEY`) by splitting the data:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = all.data, aes(x = FACTOR3, y = mean.acc)) +\n  geom_point() +\n  geom_smooth(method = 'lm') +\n  facet_wrap(~ HLVA_splits, nrow = 1, labeller = label_both) +\n  labs(y = \"Accuracy of understanding (mean.acc)\", \n       x = \"Reading strategy (FACTOR3)\") +\n  theme_bw() \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](PSYC122-w19-workbook-answers_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n\nThe plot code moves through the scatterplot production steps we have seen before.  \n\nThe bit that is new is here:\n\n`facet_wrap(~ HLVA_splits, nrow = 1, labeller = label_both)` which is included to use the data split, constructed earlier.\n\nThis addition allows us to show:\n\n- the nature of the association between two variables (`mean.acc`, `FACTOR3`) \n- for different values of the third variable (`HLVA`)\n- by splitting the data into three sub-sets according to `HLVA` score (2-8 low, 8-10 mid, 10-14 high).\n\n#### Questions: Task 8\n\n- Q.11. What do you notice about the distribution of `mean.acc` scores at\nincreasing values of reading strategy (`FACTOR3`) scores, for different sub-sets of the data: for (1.) low (2.) mid (3.) high `HLVA` values?\n- A.11. You can see that the association between `mean.acc` and `FACTOR3` scores appears to vary (the slope differs) given different values of the third variable (`HLVA`).\n\n- Q.12. What do you think the values in the grey labels at the top of the facets (the plot panels) tell us?\n- A.12. The values tell us what values (e.g., `2,8`) are used to identify the range of `HLVA` scores that have been used to define the sub-set of observations for which the plot below shows the association between `mean.acc` and `FACTOR3` scores.\n\n\n## Step 5: Use linear models with multiple predictors, to estimate the effects of factors as well as numeric variables\n\n\n### Consolidation: practice to strengthen skills\n\n\nAs we saw in weeks 17 and 18, we can use linear models to predict outcome variables. \n\n- Linear models can include numeric variables (like `FACTOR3` or `HLVA`) as predictors. \n- Linear models can also include categorical variables or factors (like `GENDER` or `EDUCATION`) as predictors.\n\n\n### Task 9 -- First, fit a linear model including just numeric variables as predictors\n\n#### Hint: Task 9 -- We use the `lm()` function to fit a model with `mean.acc` as the outcome and `FACTOR3` and `HLVA` as predictors.\n\nNote that in this model:\n\n- `FACTOR3` is a measure of reading strategy -- numeric scores correspond to a test of the relative effectiveness of the strategies participants use to read and understand written information;\n- `HLVA` is a measure of health literacy -- numeric scores correspond to a test of knowledge of health-related words.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.acc ~ FACTOR3 + HLVA, \n            data = all.data)\n\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ FACTOR3 + HLVA, data = all.data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.38243 -0.06507  0.01136  0.07686  0.27637 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.4956473  0.0403305  12.290   <2e-16 ***\nFACTOR3     0.0023489  0.0007874   2.983    0.003 ** \nHLVA        0.0217126  0.0024504   8.861   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1139 on 475 degrees of freedom\nMultiple R-squared:  0.1834,\tAdjusted R-squared:   0.18 \nF-statistic: 53.35 on 2 and 475 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nIf you look at the model summary you can answer the following questions.\n\n- Q.13. What is the estimate for the coefficient of the effect of the predictor, `FACTOR3` (reading strategy)?\n- A.13. 0.0023489\n\n- Q.14. Is the effect significant?\n- A.14. It is significant. Because `Pr(>|t|)` equals `0.003` for the `Estimate` of the effect of `FACTOR3` (reading strategy): this means that  p < .05, and so the effect is significant.\n\n- Q.15. What are the values for t and p for the significance test for the \nestimated coefficient of the effect of `HLVA` (health literacy)?\n- A.15. t = 8.861, p = <2e-16\n\n#### Hint: Task 9 -- Do you know how to intepret numbers like `<2e-16`? If you are unsure you can find out about scientific notation here:\n\n<https://www.calculatorsoup.com/calculators/math/scientific-notation-converter.php>\n\n- Q.16. What do you conclude are the effects of the `FACTOR3` (reading strategy) and `HLVA` (health literacy) variables, as predictors of outcome `mean.acc` (accuracy of understanding of health information)?\n- A.16. The model slope estimates suggests that both predictors are significant, and that as both `FACTOR3` (reading strategy) and `HLVA` (health literacy) increase, so `mean.acc` scores are predicted to increase also.\n\n\n### Task 10 -- Second, fit a linear model including a numeric variable and a factor as predictors\n\n#### Hint: Task 10 -- We use the `lm()` function to fit a model with `mean.acc` as the outcome and `FACTOR3` and `GENDER` as predictors.\n\nNote that in this model:\n\n- `FACTOR3` is a measure of reading strategy -- numeric scores correspond to a test of strategy awareness\n- `GENDER` is a self-report measure of gender identity\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.acc ~ FACTOR3 + GENDER, \n            data = all.data)\n\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ FACTOR3 + GENDER, data = all.data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.43448 -0.06809  0.02190  0.09104  0.30596 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.6074530  0.0415532  14.619  < 2e-16 ***\nFACTOR3      0.0040658  0.0008237   4.936  1.1e-06 ***\nGENDERMale  -0.0108184  0.0120051  -0.901    0.368    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1228 on 475 degrees of freedom\nMultiple R-squared:  0.05007,\tAdjusted R-squared:  0.04607 \nF-statistic: 12.52 on 2 and 475 DF,  p-value: 5.036e-06\n```\n\n\n:::\n:::\n\n\n\n\nIf you look at the model summary you can answer the following questions.\n\n- Q.17. What is the estimate for the coefficient of the effect of the predictor, `FACTOR3` (strategy)?\n- A.17. 0.0040658\n\n- Q.18. Is the effect significant?\n- A.18. It is significant. Because `Pr(>|t|)` equals `1.1e-06` for the `Estimate` of the effect of `FACTOR3` (strategy): this means that  p < .05, and so the effect is significant.\n\n- Q.19. What are the values for t and p for the significance test for the \nestimated coefficient of the effect of `GENDER` (level, `Male` compared to `Female`)?\n- A.19. t = -0.901, p = 0.368\n\n- Q.20. Is the effect of `GENDER` significant?\n- A.20. It is not significant. Because `Pr(>|t|)` equals `0.635` for the `Estimate` of the effect of `GENDER` this means that  p > .05, and so the effect is not significant.\n\n#### Hint: Task 10 -- How do we know how to interpret estimates for the effects of factors? We discussed how R deals with factors in week 18, and discuss factors, and the effects of factors, in the week 19 lecture.\n\n- Q.21. How should we interpret the coefficient estimate for the effect of `GENDER`?\n- A.21. Though the effect is not significant, we can say that, on average, outcome `mean.acc` is -0.0108184 (slightly) lower for `Male` compared to `Female` coded people.\n\n- Q.22. What do you conclude are the effects of the `FACTOR3` (strategy) and `GENDER` (`Female` compared to `Male`) variables, as predictors of outcome `mean.acc` (accuracy of understanding of health information)?\n- A.22. The model slope estimates suggest that gender does not have a significant effect but that as `FACTOR3` (strategy) scores increase, so `mean.acc` scores are predicted to increase. \n\n\n## Step 6: Use linear models with multiple predictors, including interaction effects\n\n\n### Introduce: make some new moves\n\n\nAs we saw through Task 8, it is possible that:\n\n- the association between two variables (`mean.acc`, `FACTOR3`) can be different for different values of a third categorical (factor) variable (`GENDER`);\n- the association between two variables (`mean.acc`, `FACTOR3`) can be different for different values of a third variable (`HLVA`)\n\nWhile we can examine these possibilities using visualizations, we often need to conduct statistical analyses to test *interaction effects*, or the ways in which the association between two variables can be different for different levels of a third variable.\n\nWe can extend linear models to include terms that allow us to test or to estimate *interaction effects*.\n\n\n### Task 11 -- Center numeric variables before using them as predictors\n\n### Hint: Task 11\n\nWhen we include numeric variables (e.g., `FACTOR3, HLVA, SHIPLEY`) in linear models, it can cause problems of interpretation or of estimation if we include the variables as they first come to us in datasets (as *raw* variables).\n\n- It often helps our analyses to *center* variables on their means.\n- Centering a variable means calculating its mean, and then subtracting that mean from every value in the variable column.\n\nFor example, to center values of the `HLVA` variable, we create a new column `data$HLVA_centered` by first calculating the mean of the `data$HLVA` variable, and then subtracting that mean from every row value in `data$HLVA`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall.data$HLVA_centered <- all.data$HLVA - mean(all.data$HLVA, na.rm = TRUE)\n```\n:::\n\n\n\n\n- Q.23. Can you check what is going on when we center variables?\n\n- Hint: You can see what is happening when you run this code by first calculating the mean for `HLVA`\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(all.data$HLVA, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8.92887\n```\n\n\n:::\n:::\n\n\n\n\nthen looking at column values in the new `HLVA_centered` column, compared to the original `HLVA` column:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall.data %>%\n  select(HLVA_centered, HLVA) %>%\n  print(n = 20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 478 × 2\n   HLVA_centered  HLVA\n           <dbl> <dbl>\n 1       -1.93       7\n 2       -0.929      8\n 3        2.07      11\n 4        4.07      13\n 5        0.0711     9\n 6       -2.93       6\n 7       -1.93       7\n 8       -0.929      8\n 9        1.07      10\n10        4.07      13\n11        1.07      10\n12        2.07      11\n13       -0.929      8\n14        1.07      10\n15        1.07      10\n16        1.07      10\n17        3.07      12\n18        1.07      10\n19       -1.93       7\n20       -2.93       6\n# ℹ 458 more rows\n```\n\n\n:::\n:::\n\n\n\n\n- What is the difference between the `HLVA` and `HLVA_centered` columns?\n\n- A.23. You can see that every value in the `HLVA_centered` column equals the value, on the same row, in the `HLVA` column, minus the mean for `HLVA`.\n\n- Q.24. Can you center the variable `FACTOR3`?\n- A.24. You can use the same code to center `FACTOR3`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall.data$FACTOR3_centered <- all.data$FACTOR3 - mean(all.data$FACTOR3, na.rm = TRUE)\n```\n:::\n\n\n\n\n- Q.25. Can you center the variable `SHIPLEY`?\n- A.25. You can use the same code to center `SHIPLEY`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall.data$SHIPLEY_centered <- all.data$SHIPLEY - mean(all.data$SHIPLEY, na.rm = TRUE)\n```\n:::\n\n\n\n\n#### Why are we learning how to do this?\n\nIt is common in data analysis to want to transform variables before using them in analyses.\n\n- Here, we are transforming predictor variables by centering them on their mean values.\n\nThe practical reason for doing this transformation now is because if we use uncentered (raw) numeric variables as predictors in linear models that involve interactions the model can find it difficult to distinguish between the effects of those predictors and the effect of their interaction.\n\n\n### Task 12 -- Specify models to include interaction effects: interactions between two numeric predictor variables\n\n### Hint: Task 12 \n\nWe use `lm()` to specify models, as we have been doing. \n\n- What changes is that we now use the `*` operator in our model code to specify interaction effects.\n\nFor example, let's suppose that we want to examine the possibility that the effect of reading strategy (`FACTOR3`) on accuracy understanding (`mean.acc`) is different for different values of health literacy (`HLVA`).\n\n- Here, we are considering the possibility that the association between reading strategy (`FACTOR3`) and accuracy of understanding (`mean.acc`) *varies*.\n- We are considering the possibility that the the association between reading strategy (`FACTOR3`) and accuracy of understanding (`mean.acc`) is different for different groups of people.\n- We are considering the possibility that the effect of reading strategy (`FACTOR3`) on accuracy of understanding (`mean.acc`) is different for people who differ, also, in health literacy (`HLVA`).\n\nIn examining the possibility that the effect of reading strategy (`FACTOR3`) on accuracy of understanding (`mean.acc`) is different for different values of health literacy (`HLVA`), we are examining a possible *interaction* between the effects of reading strategy (`FACTOR3`) and health literacy (`HLVA`).\n\n\nLet's go through this step-by-step.\n\n\nFirst, consider: if we ignored the possibility of an interaction, we would fit a model with just the predictors: reading strategy (`FACTOR3`) and health literacy (`HLVA`).\n\nWe can fit the same model that we fit before (for Task 9).\n\n- We vary the code a little, by using the centered variables we have just created:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.acc ~ FACTOR3_centered + HLVA_centered, \n            data = all.data)\n\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ FACTOR3_centered + HLVA_centered, data = all.data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.38243 -0.06507  0.01136  0.07686  0.27637 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      0.8065870  0.0052095 154.830   <2e-16 ***\nFACTOR3_centered 0.0023489  0.0007874   2.983    0.003 ** \nHLVA_centered    0.0217126  0.0024504   8.861   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1139 on 475 degrees of freedom\nMultiple R-squared:  0.1834,\tAdjusted R-squared:   0.18 \nF-statistic: 53.35 on 2 and 475 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n- Q.26. Can you compare the summary of results for this model with the model, using the same (but not centered) predictors, that you fitted for Task 9 -- compare the estimates, what do you see?\n- A.26. If we compare the results of the models we can see that the estimates, t-test values and probability values are the same for `FACTOR3` compared to `FACTOR3_centered` or for `HLVA` compared to `HLVA_centered`. \n\n- This shows that centering predictors only changes the scaling of the predictor variables so that their centers are 0.\n\n\nSecond, now consider: we aim to test or estimate the interactions between the effects of reading strategy (`FACTOR3_centered`) and health literacy (`HLVA_centered`).\n\n- We vary the code a little, again, this time by separating the predictors by `*` not by `+`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.acc ~ FACTOR3_centered*HLVA_centered, \n            data = all.data)\n\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ FACTOR3_centered * HLVA_centered, data = all.data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.36935 -0.06267  0.01487  0.07646  0.32573 \n\nCoefficients:\n                                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                     0.8086743  0.0053507 151.133  < 2e-16 ***\nFACTOR3_centered                0.0022694  0.0007874   2.882  0.00413 ** \nHLVA_centered                   0.0213896  0.0024537   8.717  < 2e-16 ***\nFACTOR3_centered:HLVA_centered -0.0005713  0.0003452  -1.655  0.09857 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1137 on 474 degrees of freedom\nMultiple R-squared:  0.1881,\tAdjusted R-squared:  0.183 \nF-statistic: 36.61 on 3 and 474 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n- Q.27. Can you compare the summary of results for this model with the results for the previous model (which uses the same predictors but without an interaction)?\n\n- What do you see?\n\n- A.27. If we compare the results of the models we can see that now the summary gives us estimates for the effects of:\n\n- `FACTOR3_centered` -- this is the effect of `SHIPLEY_centered` when `HLVA_centered` is 0\n- `HLVA_centered` -- this is the effect of `HLVA_centered` when `FACTOR3_centered` is 0\n- `FACTOR3_centered*HLVA_centered` -- this is the interaction, and reflects the change in the effect of `FACTOR3_centered` on outcome `mean.acc`, given different values of `HLVA_centered`.\n\n- Notice that the effect of the interaction is not significant but that the results suggest a very slight tendencey for the effect of reading strategy to be different (smaller) for increasing values of `HLVA_centered`.\n\n#### What are we learning here?\n\nThe `*` symbol (the `*` operator) is used here to code for a model including the effects of the two variables separated by the symbol, here, as well as the effect of the interaction between these two variables.\n\n\n### Task 13 -- Plot model predictions to help with interpretation of interaction effects\n\n### Hint: Task 13 \n\nHow do we interpret interactions?\n\n- It helps to plot model predictions, given the effects estimates that we derive from our sample using the linear model.\n\nWe can do this in a two-step sequence, similar to the sequence we trialled through weeks 17 and 18:\n\n1. First fit the model\n2. Second, use the model information to plot the predictions, given the effects\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# -- first fit the model\nmodel <- lm(mean.acc ~ FACTOR3_centered*HLVA_centered, \n            data = all.data)\n\n# -- make plot\nplot_model(model, type = \"pred\", \n           terms = c(\"FACTOR3_centered\", \"HLVA_centered\")) +\n  theme_bw() +\n  ylim(0, 1)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nScale for y is already present.\nAdding another scale for y, which will replace the existing scale.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](PSYC122-w19-workbook-answers_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n\n\n- Q.28. Can you compare the summary of results for the model with the plot to develop an interpretation of the `FACTOR3_centered*HLVA_centered` interaction?\n\n- What do you see?\n\n- A.28. We can build an interpretation in steps:\n\n- If we look at the coefficient estimate for the `FACTOR3_centered*HLVA_centered` interaction, we can see that it is negative (`-0.0005713`). \n- If we look at the plot of the model predictions, we can see that there are three slopes for the `FACTOR3_centered` effect, one each for different levels of `HLVA_centered`: for `HLVA_centered` = -2.19; `HLVA_centered` = 0; and `HLVA_centered` = 2.19.\n\n- Notice that the steepness of the slope of the `FACTOR3_centered` effect decreases (the slope gets less steep) from `HLVA_centered` = -2.19 to `HLVA_centered` = 2.19.\n- This tells us that the interaction (though not significant) operates so that the effect of reading strategy tends to be smaller for people with higher levels of health literacy.\n\n- Returning to the fact that the coefficient estimate for the `FACTOR3_centered*HLVA_centered` is negative, we can now understand that it is negative because the interaction operates so that the slope of the `FACTOR3_centered` gets smaller as scores on `HLVA_centered` increase.\n\n\n### Task 14 -- Specify models to include interaction effects: interactions between a numeric predictor variable and a factor predictor variable\n\n### Hint: Task 14 -- We follow the same approach that we followed through Task 12.\n\n\nNow consider: we aim to test or estimate the interactions between the effects of reading strategy (`FACTOR3`) and gender (`GENDER`).\n\n- We vary the code to change the predictor variables but the structure otherwise stays the same:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.acc ~ FACTOR3_centered*GENDER, \n            data = all.data)\n\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ FACTOR3_centered * GENDER, data = all.data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.43542 -0.07087  0.02173  0.09156  0.29573 \n\nCoefficients:\n                              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                  0.8100751  0.0068412 118.412  < 2e-16 ***\nFACTOR3_centered             0.0038150  0.0009700   3.933 9.64e-05 ***\nGENDERMale                  -0.0109063  0.0120160  -0.908    0.365    \nFACTOR3_centered:GENDERMale  0.0009027  0.0018404   0.490    0.624    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1229 on 474 degrees of freedom\nMultiple R-squared:  0.05055,\tAdjusted R-squared:  0.04454 \nF-statistic: 8.412 on 3 and 474 DF,  p-value: 1.86e-05\n```\n\n\n:::\n:::\n\n\n\n\n- Q.29. Can you identify what effects are shown in the model summary?\n- A.29. We can see that now the summary gives us estimates for the effects of:\n\n- `FACTOR3_centered` -- this is the effect of reading strategy (`FACTOR3`) when `GENDER` level is `Female`\n- `GENDERMale` -- this is the effect of `GENDER` when `FACTOR3_centered` is 0. \n\nNote that the effect of `GENDER` is the estimated difference in outcome when `GENDER` level is `Female` (not shown, treated as the baseline) compared to when `GENDER` level is `Male`.\n\n- `FACTOR3_centered*GENDER` -- this is the interaction, and reflects the change in the effect of `FACTOR3_centered` on outcome `mean.acc`, given different values of `GENDER`, here, when `GENDER` is `Male` instead of `Female`.\n\n#### What are we learning here?\n\nRemember from week 18:\n\nCategorical variables or **factors** and reference levels.\n\n- If you have a categorical variable like `GENDER` then when you use it in\nan analysis, R will look at the different categories (called `levels) e.g., here,\n`Female, Male` and it will pick one level to be the *reference* or baseline level. \n- The *reference* is the the level against which other levels are compared. \n- Here, the reference level is `Female` simply because, unless\nyou tell R otherwise, it picks the level with a category name that begins\nearlier in the alphabet as the reference level.\n\n#### How do we interpret interactions?\n\n- It helps to plot the effects estimates, given the model.\n\nWe can do this in a two-step sequence, similar to the sequence we trialled through weeks 17 and 18:\n\n1. First fit the model\n2. Second, use the model information to plot the predictions, given the effects\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# -- first fit the model\nmodel <- lm(mean.acc ~ FACTOR3_centered*GENDER, \n            data = all.data)\n\n# -- make plot\nplot_model(model, type = \"pred\", \n           terms = c(\"FACTOR3_centered\", \"GENDER\")) +\n  theme_bw() +\n  ylim(0, 1)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nScale for y is already present.\nAdding another scale for y, which will replace the existing scale.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](PSYC122-w19-workbook-answers_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n\n\n- Q.30. Can you identify how the effects of reading strategy (`FACTOR3`) and gender (`GENDER`) interact, given the model results summary and this plot?\n- A.30. The plot, and the estimate for the interaction `FACTOR3_centered:GENDERMale`, together show that the coefficient for the effect of reading strategy (`FACTOR3_centered`) is slightly larger (the slope is slightly steeper) when `GENDER` is `Male` instead of `Female.\n\n- Notice that, for this sample, the interaction is not significant, suggesting that there is no difference between genders in the relative effectiveness of reading strategy.\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}