{
  "hash": "2d9ee4a5074e25f16ffb8dd5048535dd",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Week 8. Introduction to the linear model\nsubtitle: Written by Rob Davies\norder: 11\nbibliography: references.bib\ncsl: psychological-bulletin.csl\n---\n\n\n\n## 8.1 Overview {#sec-lm-intro-overview}\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n\nWelcome to your overview of the work we will do together in **Week 8**.\n\nThis week, we focus on learning **how to predict** people: predicting observations about us (e.g., our attributes) or about the things we make or do.\nTo do this, we will learn to think about and work with **linear models**.\n\nLooking ahead to your professional lives, learning about linear models will equip you to do behavioural analysis in a wide range of contexts, from clinical research to business intelligence. \n\nAs students, now, learning about linear model analyses in the context of the **Clearly understood** project will help you to understand how to critically evaluate research when you read about it (or write about it) in research reports.\n\nYou will see that the linear model is *very* flexible and powerful so learning to use it effectively involves not only learning to code analyses but also learning to think critically about what it is you want to do with it.\n\n## 8.2 Our learning goals {#sec-lm-intro-goals}\n\nWe continue to develop your critical thinking while we strengthen your practical skills.\n\n**1. Critical thinking**\n\n-   *Concepts*: how we go from ideas and questions to hypotheses.\n\nAs psychologists, we often want to ask questions like these:\n\n- Does variation in one measure (X) predict variation in another variable (Y)?\n- What are the factors that influence outcome Y?\n- Is a theoretical model consistent with observed behaviour?\n\n**2. Practical skills**\n\nTo enable you to answer questions like these, you will learn how to:\n\n-   *Skills* -- code linear models;\n-   *Skills* -- identify and interpret model statistics;\n-   *Concepts and skills* -- critically evaluate the results;\n-   *Concepts and skills* -- communicate the results.\n\nAs we progress, we will continue to strengthen your skills in building *professional visualizations*.\n\n## 8.3 Learning resources {#sec-lm-intro-resources}\n\nYou will see, next, the lectures we share to explain the concepts behind the critical thinking and analysis skills you will develop, then you will see information about the practical materials you can use to practise your skills.\n\nEvery week, you will learn best if you *first* watch the lectures *then* do the practical exercises.\n\n::: callout-tip\n## Linked resources\n- In [the chapter for week 7](../part2/hypotheses-associations.qmd#sec-associations-overview), we share materials to support your development of critical thinking about associations, and your development of practical skills in working with correlation-based analyses.\n:::\n\n### 8.3.1 Lectures {#sec-lm-intro-lectures}\n\nThe lecture materials for this week are presented in four short parts. \n\nClick on a link and your browser should open a tab showing the *Panopto* video for the lecture part.\n\n1. Part 1 (12 minutes) **Focus on the linear model**: The concepts and skills we will learn about in week 8: our aims, the kind of questions we can answer with linear models, and how we get from those questions to sensible linear model analyses.\n\n\n\n```{=html}\n<iframe src=\"https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=eaf1c87a-87bb-491e-b33b-b22e0102965f&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all\" height=\"405\" width=\"720\" style=\"border: 1px solid #464646;\" allowfullscreen allow=\"autoplay\" aria-label=\"Panopto Embedded Video Player\" aria-description=\"PSYC411-lm-intro-1\" ></iframe>\n```\n\n\n\n2. Part 2 (15 minutes): the first key concept --- how we use linear models to predict average outcomes.\n\n\n\n```{=html}\n<iframe src=\"https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=71eaffe1-5066-425c-9ce2-af5f00b79730&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all\" height=\"405\" width=\"720\" style=\"border: 1px solid #464646;\" allowfullscreen allow=\"autoplay\" aria-label=\"Panopto Embedded Video Player\" aria-description=\"PSYC411-lm-intro-2\" ></iframe>\n```\n\n\n\n3. Part 3 (12 minutes): the second key concept --- how we ensure that linear models make the best predictions given the data we have.\n\n\n\n```{=html}\n<iframe src=\"https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=a08f12af-606a-4be0-90ae-af5f00bc1491&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all\" height=\"405\" width=\"720\" style=\"border: 1px solid #464646;\" allowfullscreen allow=\"autoplay\" aria-label=\"Panopto Embedded Video Player\" aria-description=\"PSYC411-lm-intro-3\" ></iframe>\n```\n\n\n\n4. Part 4 (14 minutes): the key skills --- coding linear models, reading model results, and writing reports of those results.\n\n\n\n```{=html}\n<iframe src=\"https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=a16c627e-609b-49db-b683-af5f00bfb15f&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all\" height=\"405\" width=\"720\" style=\"border: 1px solid #464646;\" allowfullscreen allow=\"autoplay\" aria-label=\"Panopto Embedded Video Player\" aria-description=\"PSYC411-lm-intro-4\" ></iframe>\n```\n\n\n\n### 8.3.2 Lecture slides {#sec-lm-intro-lectures-slides}\n\n::: callout-tip\n## Download the lecture slides\nThe slides presented in the videos can be downloaded here:\n\n- [The slides](files/411-linear-model-intro.html) exactly as presented (12 MB). \n\nYou can download the web page `.html` file and click on it to open it in any browser (e.g., Chrome, Edge or Safari). The slide images are high quality so the file is quite big and may take a few seconds to download.\n:::\n\nWe are going to work through some practical exercises, next, to develop your critical thinking and practical skills for working with linear models.\n\n## 8.4 Practical materials: data and R-Studio {#sec-lm-intro-practical}\n\nWe will work with two data files which you can download by clicking on their names (below):\n\n-   [study-one-general-participants.csv](files/study-one-general-participants.csv).\n-   [study-two-general-participants.csv](files/study-two-general-participants.csv).\n\nOnce you have downloaded the files, you will need to upload them to the R-Studio server to access and use the R files.\n\n::: callout-important\nHere is a link to the sign-in page for [R-Studio Server](https://psy-rstudio.lancaster.ac.uk/auth-sign-in?appUri=%2F)\n:::\n\n### 8.4.1 Practical materials guide {#sec-lm-intro-practical-guide}\n\nYou will find that the practical exercises are simpler to do if you follow these steps in order.\n\n1. **The data** --- We will take a quick look at what is inside the data files so you know what everything means.\n2. **The `how-to` guide** --- We will go through the practical analysis and visualization coding steps, showing all the code required for each step.\n3. **The `practical` exercises** --- We will set out the tasks, questions and challenges that you should complete to learn the practical skills we target this week.\n\nThis week --- **Week 8** --- we consolidate what you have been learning, so your critical thinking and practical skills have a firm foundation *then* we extend your skills by learning how to do new things.\n\n::: callout-tip\n## Week 8 parts\n\n1. Set-up\n2. Load the data\n3. **Revision**: developing histograms to examine the distributions of variables.\n4. **Revision**: developing scatterplots to examine associations between variables.\n5. **Revision**: using correlations to to answer research questions, making sure you are comfortable.\n6. **New**: using a linear model to answer research questions.\n7. **New**: using a linear model to make predictions.\n:::\n\nWe learn these skills so that we can answer research questions like:\n\n1. What person attributes predict success in understanding?\n2. Can people accurately evaluate whether they correctly understand written health information?\n  \nThese kinds of research questions can often be answered through analyses using linear models.\nWe typically use linear models to estimate the association between predictors and outcomes.\n\nWhen we do these analyses, we need to think about how we report the results:  \n\n- We usually need to report information about the kind of model we specify;\n- We will need to report the nature of the association estimated in our model;\n- We usually need to decide if (i.) the association is significant? (ii.) does the association reflect a positive or negative relationship between outcome and predictor? (iii.) is the association we see in our sample data relatively strong or weak?\n\nWe will consolidate and extend learning on data visualization so that we can produce eye-catching, appealing, plots for professional audiences.\n\n#### 8.4.1.1 The data files {#sec-lm-intro-practical-data}\n\nEach of the data files we will work with has a similar structure.\n\nHere are what the first few rows in the data file `study.two.gen` looks like:\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|participant_ID |  mean.acc| mean.self|study    | AGE| SHIPLEY| HLVA| FACTOR3| QRITOTAL|GENDER |EDUCATION |ETHNICITY |\n|:--------------|---------:|---------:|:--------|---:|-------:|----:|-------:|--------:|:------|:---------|:---------|\n|studytwo.1     | 0.4107143|  6.071429|studytwo |  26|      27|    6|      50|        9|Female |Higher    |Asian     |\n|studytwo.10    | 0.6071429|  8.500000|studytwo |  38|      24|    9|      58|       15|Female |Secondary |White     |\n|studytwo.100   | 0.8750000|  8.928571|studytwo |  66|      40|   13|      60|       20|Female |Higher    |White     |\n|studytwo.101   | 0.9642857|  8.500000|studytwo |  21|      31|   11|      59|       14|Female |Higher    |White     |\n|studytwo.102   | 0.7142857|  7.071429|studytwo |  74|      35|    7|      52|       18|Male   |Higher    |White     |\n|studytwo.103   | 0.7678571|  5.071429|studytwo |  18|      40|   11|      54|       15|Female |Further   |White     |\n\n\n:::\n:::\n\n\n\n::: callout-tip\nThe webpage has a slider under the data table window, so you can scroll across the columns: move your cursor over the window to show the slider.\n:::\n\nWhen you look at the data table, you can see the columns:\n\n-   `participant_ID` participant code\n-   `mean.acc` average accuracy of response to questions testing understanding of health guidance\n-   `mean.self` average self-rated accuracy of understanding of health guidance\n-   `study` variable coding for what study the data were collected in\n-   `AGE` age in years\n-   `HLVA` health literacy test score\n-   `SHIPLEY` vocabulary knowledge test score\n-   `FACTOR3` reading strategy survey score\n-   `GENDER` gender code\n-   `EDUCATION` education level code\n-   `ETHNICITY` ethnicity (Office National Statistics categories) code\n\n### 8.4.2 The how-to guide {#sec-lm-intro-practical-how-to}\n\nWe will take things *step-by-step*.\n\nMake sure you complete each part, task and question, in order, before you move on to the next one.\n\n#### 8.4.2.1 How-to Part 1: Set-up\n\nTo begin, we set up our environment in R.\n\n##### How-to Task 1 -- Run code to empty the R environment\n\n:::{.callout-tip collapse=\"true\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list=ls())                            \n```\n:::\n\n\n:::\n\n##### How-to Task 2 -- Run code to load libraries\n\nLoad libraries using `library()`.\n\n:::{.callout-tip collapse=\"true\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"patchwork\")\nlibrary(\"tidyverse\")\n```\n:::\n\n\n:::\n\n#### 8.4.2.2 How-to Part 2: Load the data\n\n##### How-to Task 3 -- Read in the data file we will be using\n\nThe code in the `how-to` guide was written to work with the data file:\n\n- `study-one-general-participants.csv`.\n\nRead in the data file -- using `read_csv()`.\n\n:::{.callout-tip collapse=\"true\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudy.one.gen <- read_csv(\"study-one-general-participants.csv\")\n```\n:::\n\n\n:::\n\n::: callout-tip\nLast week, we started working with the **online help** information on R functions. \n\nLet's build on that.\n\nYou can read the technical information about the `read_csv()` function here:\n\n<https://readr.tidyverse.org/reference/read_delim.html>\n\n- Take a look around the `{tidyverse}` webpages: expert professionals use information like this whenever they try to figure out how to do something.\n:::\n\n##### How-to Task 4 -- Inspect the data file\n\nUse the `summary()` function to take a look.\n\n:::{.callout-tip collapse=\"true\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(study.one.gen)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n participant_ID        mean.acc        mean.self        study          \n Length:169         Min.   :0.3600   Min.   :3.440   Length:169        \n Class :character   1st Qu.:0.7600   1st Qu.:6.080   Class :character  \n Mode  :character   Median :0.8400   Median :7.080   Mode  :character  \n                    Mean   :0.8163   Mean   :6.906                     \n                    3rd Qu.:0.9000   3rd Qu.:7.920                     \n                    Max.   :0.9900   Max.   :9.000                     \n      AGE           SHIPLEY           HLVA           FACTOR3     \n Min.   :18.00   Min.   :23.00   Min.   : 3.000   Min.   :34.00  \n 1st Qu.:24.00   1st Qu.:33.00   1st Qu.: 7.000   1st Qu.:46.00  \n Median :32.00   Median :35.00   Median : 9.000   Median :51.00  \n Mean   :34.87   Mean   :34.96   Mean   : 8.905   Mean   :50.33  \n 3rd Qu.:42.00   3rd Qu.:38.00   3rd Qu.:10.000   3rd Qu.:55.00  \n Max.   :76.00   Max.   :40.00   Max.   :14.000   Max.   :63.00  \n    QRITOTAL        GENDER           EDUCATION          ETHNICITY        \n Min.   : 6.00   Length:169         Length:169         Length:169        \n 1st Qu.:12.00   Class :character   Class :character   Class :character  \n Median :13.00   Mode  :character   Mode  :character   Mode  :character  \n Mean   :13.36                                                           \n 3rd Qu.:15.00                                                           \n Max.   :19.00                                                           \n```\n\n\n:::\n:::\n\n\n:::\n\n::: callout-tip\n- `summary()` will give you either descriptive statistics for variable columns classified as numeric or will tell you that columns in the dataset are not numeric.\n:::\n\n#### 8.4.2.3 How-to Part 3: Developing histograms to examine the distributions of variables\n\n##### How-to Task 5 -- Edit histogram plotting code to visualize distributions like a pro\n\nYou have seen how to produce histograms before, in a previous class (week 3): here we are **consolidating** skills by practising them in different contexts, using different data.\n\nWe **extend** your skills by adding some new moves.\n\nWhen we learn about creating a plot, it helps us to identify what each code element is doing.  Here's an example: run the line of code and see the result in the Plots window in R-Studio:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one.gen, aes(x = mean.acc)) + geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\nThese are the plotting code elements and what they are doing:\n\n1. `ggplot(...)` you tell R you want to make a plot using the `ggplot()` function;\n2. `ggplot(data = study.one.gen ...)` you tell R you want to make a plot with the `study.one.gen` data;\n3. `ggplot(..., aes(x = mean.acc))` you tell R that you want to make a plot with the variable `mean.acc`;\n3. here, you specify the aesthetic mapping, `x = mean.acc`;\n4. `ggplot(...) + geom_histogram()` you tell R you want to show the distribution of values of `mean.acc` as a geometric object: a histogram.\n\nYou have seen the plotting code arranged in two different ways, in one line, as above, or in a series of steps, like this:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one.gen, aes(x = mean.acc)) + \n  geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n::: callout-tip\nNotice that it has no impact whether you write the plotting code in one line, or in a series of lines.\n\n- R cares *very much* about how you spell function or variable names.\n\n- R does not usually care about line breaks.\n\nLearning what does or does not matter is a key lesson, when you learn a language, whatever the language.\n:::\n\nIf we break the plotting code into steps, it makes the code easier for you to read, and it will make it easier to add edits, one at a time.\nLet's see how that works, next.\n\nTo help you learn, we are going to work on editing the code to do things, and we are going to explain *why* we want to be able to do these things.\n\nThese are the things we want to do:\n\n1. **new** -- the appearance of the bars using `binwidth`;\n2. **revision** -- the colour of the background using `theme_bw()`;\n3. **revision** -- the appearance of the labels using `labs()`;\n4. **new** -- setting the x-axis limits to reflect the full range of possible scores on the x-axis variable using `xlim()`;\n5. **new** -- adding annotation -- here, a vertical line using `geom_vline()` -- to focus the attention of the audience for a plot on specific information about the variable distribution (here, the sample average for the variable).\n\n::: callout-tip\n- Click on each `Code` tab to see how the code changes, and to see how the plot changes as a result.\n- Click on each `Why` tab for an explanation of why we want to do this.\n\n**You may need to hover your cursor over the space to the right of the `Code` tab to see the `Why` tab.**\n:::\n\n1. **new** -- the appearance of the bars using `binwidth`\n\n::: panel-tabset\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one.gen, aes(x = SHIPLEY)) + \n  geom_histogram(binwidth = 2)\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n## Why\nHistogram `binwidth` has to be a number. The best way to learn what the number tells R to do is to experiment with different values.\n\n- Notice that in the code we set the `binwidth` to 2.\n- If you are producing a histogram, `binwidth` has to be a number larger than the potential minimum and smaller than the potential maximum for the variable you are plotting: *so* for the `SHIPLEY` vocabulary test, because the test scores can only range between 0-40, the `binwidth` number you use in your plotting code has to be bigger than 0 but smaller than 40.\n\nIn general, the larger (wider) the `binwidth`, the less detail you see about the distribution of values in the variable. \n\n- In a histogram, each bar you draw represents a collection of values. The `binwidth` tells R how many values to collect together, for each bar. So, the bigger the width, the bigger (wider and taller) the bar because it represents more observations.\n\nWhether or not you want to present detail is then a question concerning your communication aims: do you want to give an impression, or identify a specific detail?\n:::\n\n2. **revision** -- the colour of the background using `theme_bw()`\n\n::: panel-tabset\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one.gen, aes(x = SHIPLEY)) + \n  geom_histogram(binwidth = 2) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n## Why\nIn general, a grey background is argued to be a good way to present information visually but we often use a white background because it helps the plot elements to be visible, especially, for example, if we are giving a presentation.\n:::\n\n3. **revision** -- the appearance of the labels using `labs()`\n\n::: panel-tabset\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one.gen, aes(x = SHIPLEY)) + \n  geom_histogram(binwidth = 2) +\n  theme_bw() +\n  labs(x = \"Vocabulary (SHIPLEY)\", y = \"frequency count\")\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n## Why\nYou cannot assume that the audience for your plots will understand what you are referring to, if you just use data-set variable names e.g. `SHIPLEY`. They may not be familiar with your data-set. This means you need to use axis labels that will make sense to most people in your audience.\n:::\n\n4. **new** -- setting the x-axis limits using `xlim()`\n\n::: panel-tabset\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one.gen, aes(x = SHIPLEY)) + \n  geom_histogram(binwidth = 2) +\n  theme_bw() +\n  labs(x = \"Vocabulary (SHIPLEY)\", y = \"frequency count\") +\n  xlim(0,40)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing missing values or values outside the scale range\n(`geom_bar()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n\n## Why\n1. It is often useful to set the axis limits like this: because we want to show the audience where the sample values are distributed compared to where they *could* be distributed, given the measure. \n2. This makes sense, e.g., if you want to see the relative age distribution of a sample compared to the population, or because we want to give the audience a more accurate picture of the data.\n:::\n\n5. **new** -- adding annotation -- here, a vertical line\n\n::: panel-tabset\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one.gen, aes(x = SHIPLEY)) + \n  geom_histogram(binwidth = 2) +\n  theme_bw() +\n  labs(x = \"Vocabulary (SHIPLEY)\", y = \"frequency count\") +\n  xlim(0,40) +\n  geom_vline(xintercept = mean(study.one.gen$SHIPLEY), colour = \"red\", linewidth = 1.5)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing missing values or values outside the scale range\n(`geom_bar()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\nNotice that we used the `geom_vline()` element to plot a vertical line at the location on the x-axis we define.\n\nWe do this in the steps:\n\n1. `geom_vline(...)` -- draw a vertical line;\n2. `...xintercept...` -- draw the line so it hits the x-axis (intercepts the x-axis);\n3. `...xintercept = mean(study.one.gen$SHIPLEY... ` -- at a location defined by the mean of the variable `mean(study.one.gen$SHIPLEY)`;\n4. `...colour = \"red\", size = 1.5..` -- make the line red and one and a half times the default thickness.\n\n## Why\nWe can use annotations, like this vertical line, when we want to draw the attention of the audience for our plot to a specific feature of the data.\n:::\n\n**What are we learning here?**\n\nYou can see that while the data stays the same, the appearance of the plot changes, as we add each edit to the plotting code.\n\nThe lesson that we are learning, here, is not just that you can arrange plotting code in steps but that *in general* in R you can build things (like plots) one action at a time.\n\n::: callout-tip\n## Further information you can explore\n\nWe can define the limits on the x-axis and on the y-axis, see the `{ggplot2}` library reference information on setting limits is here:\n\n<https://ggplot2.tidyverse.org/reference/lims.html>\n\nThe `{ggplot2}` reference information for drawing lines is here:\n\n<https://ggplot2.tidyverse.org/reference/geom_abline.html>\n:::\n\n#### 8.4.2.4 How-to Part 4: Developing scatterplots to examine associations between variables\n\n##### How-to Task 6 -- Edit scatterplot code to visualize associations like a pro\n\nYou have seen these code moves before, in previous classes (weeks 3 and 4): we are **consolidating** skills by practising your coding in different contexts, using different data.\n\nWe **extend** your skills by adding some new moves.\n\nWe create scatterplots to examine the association between pairs of variables.\nFor example, we can draw a scatterplot to examine the association between variation in the values of `SHIPLEY` and of `mean.acc`.\n\n:::{.callout-tip collapse=\"true\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one.gen, aes(x = SHIPLEY, y = mean.acc)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n:::\n\nThe plot code moves through the following steps:  \n\n1. `ggplot(...)` makes a plot.\n2. `ggplot(data = study.one.gen, ...)` uses the `study.one.gen` data-set.\n3. `ggplot(...aes(x = SHIPLEY, y = mean.acc))` uses two aesthetic mappings.\n4. `geom_point()` show the mappings as points.\n\nWe are now going to edit:\n\n1. **revision and new** -- the appearance of the points using alpha, size, **shape**, and **colour**;\n2. **revision** -- the colour of the background using `theme_bw()`;\n3. **revision** -- the appearance of the labels using `labs()`;\n4. **new** -- the x-axis and y-axis limits using `lim()`.\n\nWe make the changes, one change at a time.\n\nClick on the drop-down view to see the code but, if you want a challenge, first try to write the code on your own, using what you have learned so far.\n\n1. **revision and new** -- the appearance of the points using alpha, size, **shape**, and **colour**\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one.gen, aes(x = SHIPLEY, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square') \n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n:::\n\n2. **revision** -- the colour of the background using `theme_bw()`\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one.gen, aes(x = SHIPLEY, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')   +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n:::\n\n3. **revision** -- the appearance of the labels using `labs()`\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one.gen, aes(x = SHIPLEY, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')   +\n  theme_bw() +\n  labs(x = \"Vocabulary (SHIPLEY)\", y = \"mean accuracy\")\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n:::\n\n4. **new** -- the x-axis and y-axis limits using `lim()`\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one.gen, aes(x = SHIPLEY, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')   +\n  theme_bw() +\n  labs(x = \"SHIPLEY\", y = \"mean accuracy\") +\n  xlim(0, 40) + ylim(0, 1)\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n\nNotice that:\n\n- I set the x-axis limits to the minimum (0) and maximum (40) possible values for the `SHIPLEY` variable.\n\n- I set the y-axis limits to the minimum (0) and maximum (1) possible values for the mean accuracy variable `mean.acc`.\n:::\n\n**What are we learning here?**\n\nIt is generally a good idea to show the minimum value (the origin) for each variable.\n\n- Not doing this, i.e., showing a more narrow slice of the sample range is an easy way to exaggerate the strength of associations or to imply incorrectly the breadth in variation.\n\nYou can change the transparency (alpha), size, colour and shape of important parts of a plot.\nHere, we are changing the appearance of the points.\nBut you can also change the transparency (alpha), size, colour and shape of reference lines\nadded to a plot.\n\n::: callout-tip\n## Further information you can explore\n\nThe `{ggplot2}` `geom_point()` reference information is here: \n\n<https://ggplot2.tidyverse.org/reference/geom_point.html>\n\n- where you can see some examples of the edits we have done.\n\nSome useful information about shape options is here:\n\n<http://www.cookbook-r.com/Graphs/Shapes_and_line_types/>\n\nSome useful information about colour options is here:\n\n<http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/>\n:::\n\n::: callout-important\nNow you: experiment!\n:::\n\n#### 8.4.2.5 How-to Part 5: Using correlations to to answer research questions\n\n##### How-to Task 7 -- Examine the correlation between a pair of variables\n\nIn the **Clearly understood** project, one of our research questions is:\n\n1. What person attributes predict success in understanding?\n\nWe can answer this question by doing a correlation analysis.\nThis is because we can expect that *if* vocabulary knowledge predicts success in understanding *then* variation in vocabulary knowledge should be associated with variation in success of understanding.\nWe measured how successful study participants were in understanding health information: recording outcome `mean.acc` as the accuracy of response to questions designed to examine understanding.\nWe measured a key person attribute, vocabulary knowledge using the `SHIPLEY` vocabulary test.\nWe can then examine the association between this pair of variables using correlation.\n\nHere, we examine the correlation between the mean accuracy (`mean.acc`) of understanding of health information, and vocabulary (`SHIPLEY`) knowledge, for each person in our participant sample.\n\nCan you figure out how to code the correlation analysis?\n\nIt helps with your learning if you first try to predict what the code will look like.\nThen reveal the code, below, to see what you guessed right.\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(study.one.gen$SHIPLEY, study.one.gen$mean.acc, method = \"pearson\",  alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  study.one.gen$SHIPLEY and study.one.gen$mean.acc\nt = 4.5855, df = 167, p-value = 8.846e-06\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.1931990 0.4620413\nsample estimates:\n     cor \n0.334406 \n```\n\n\n:::\n:::\n\n\n:::\n\n> Q.1. What is r, the correlation coefficient?\n\n:::{.callout-tip collapse=\"true\"}\n## Answer\n> A.1. r = 0.334406\n:::\n\n> Q.2. Is the correlation significant?\n\n:::{.callout-tip collapse=\"true\"}\n## Answer\n> A.2. r is significant, p < .05\n:::\n\n> Q.3. What are the values for t and p for the significance test for the correlation?\n\n:::{.callout-tip collapse=\"true\"}\n## Answer\n> A.3. t = 4.5855, p = 8.846e-06\n:::\n\n> Q.4. What do you conclude is the answer to the research question, given the correlation results?\n\n:::{.callout-tip collapse=\"true\"}\n## Hint\nReview the scatterplot you drew earlier (or draw one now) to examine the shape of the association between these variables.\n:::\n\n:::{.callout-tip collapse=\"true\"}\n## Answer\n> A.4. Vocabulary and `mean.acc` are positively correlated suggesting that as `SHIPLEY` scores increase so also do `mean.acc` scores.\n:::\n\n#### 8.4.2.6 How-to Part 6: **New**: using a linear model to answer research questions\n\n##### How-to Task 8 -- Code and read the results from a linear model analysis\n\nAs we have seen, one of our research questions is:\n\n1. What person attributes predict success in understanding?\n\nWe can examine the relation between outcome mean accuracy (`mean.acc`) of understanding and vocabulary (`SHIPLEY`) knowledge by testing if person vocabulary score predicts understanding.\n\nWe do this through a linear model analysis.\n\nWe complete the analysis using the `lm()` function.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.acc ~ SHIPLEY, data = study.one.gen)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ SHIPLEY, data = study.one.gen)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.42871 -0.04921  0.02079  0.07480  0.18430 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.44914    0.08053   5.577 9.67e-08 ***\nSHIPLEY      0.01050    0.00229   4.585 8.85e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1115 on 167 degrees of freedom\nMultiple R-squared:  0.1118,\tAdjusted R-squared:  0.1065 \nF-statistic: 21.03 on 1 and 167 DF,  p-value: 8.846e-06\n```\n\n\n:::\n:::\n\n\n\nLet's work through the elements of the linear model code so we can see what everything does:\n\n1. `model <- lm(...)` -- fit the model using `lm(...)`, giving the model a name \nhere, we just call it \"model\".\n2. `...lm(mean.acc ~ SHIPLEY...)` -- tell R you want a model of the outcome \n`mean.acc` predicted `~` by the predictor `SHIPLEY`.\n3. `...data = study.one)` -- tell R that the variables you name in the \n formula are in the `study.one` dataset.\n4. `summary(model)` -- ask R for a summary of the model you called \"model\": **this is how you get the results**.\n\n::: callout-tip\nNotice that R has a general formula syntax: `outcome ~ predictor` *or* `y ~ x`\n\n- and uses the same format across a number of different functions;\n- each time, on the left of the tilde symbol `~` you identify the output or outcome variable;\n- but on the right of the tilde `~` you identify an input or predictor variable or set of predictor variables.\n:::\n  \nIf you look at the model summary you can answer the following questions.\n\n> Q.5. What is the estimate for the coefficient of the effect of the predictor, SHIPLEY?\n\n:::{.callout-tip collapse=\"true\"}\n## Answer\n> A.5. 0.01050 \n:::\n\n> Q.6. Is the effect significant?\n\n:::{.callout-tip collapse=\"true\"}\n## Answer\n> A.6. It is significant, p < .05\n:::\n\n> Q.7. What are the values for t and p for the significance test for the coefficient?\n\n:::{.callout-tip collapse=\"true\"}\n## Answer\n> A.7. t = 4.585, p = 8.85e-06\n:::\n\n> Q.8. What do you conclude is the answer to the research question, given the linear model results?\n\n:::{.callout-tip collapse=\"true\"}\n## Answer\n> A.8. The model slope estimate suggests that as `SHIPLEY` scores increase so also do `mean.acc` scores.\n:::\n\n#### 8.4.2.7 How-to Part 7: **New**: using a linear model to generate predictions\n\n##### How-to Task 9 -- Fit a linear model and plot the model predictions\n\nWe can use the model we have just fitted to plot the model predictions.\n\n- The estimates of the coefficients (given in summary results) are the information we need to generate predictions.\n- What we are predicting is how values of the outcome variable change, on average, given different values in one or more predictor variables.\n- We can produce predictions by working with linear model estimates of (1.) the intercept and (2.) the coefficient of the effect of each predictor variable.\n- The effect of a predictor tells you *how* the outcome changes (how much the outcome increases or decreases), given different values of the predictor.\n\nWe are going to do this prediction in two steps:\n\n1. **revision** -- fit a linear model to estimate the relationship between the outcome and the predictor variables.\n2. **new** -- draw a scatterplot and add a line to show the model predictions, given the model estimates.\n\nWe work through these steps in turn.\n\n**Step 1. First fit a linear model and get a summary of the estimates**\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.acc ~ SHIPLEY, data = study.one.gen)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ SHIPLEY, data = study.one.gen)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.42871 -0.04921  0.02079  0.07480  0.18430 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.44914    0.08053   5.577 9.67e-08 ***\nSHIPLEY      0.01050    0.00229   4.585 8.85e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1115 on 167 degrees of freedom\nMultiple R-squared:  0.1118,\tAdjusted R-squared:  0.1065 \nF-statistic: 21.03 on 1 and 167 DF,  p-value: 8.846e-06\n```\n\n\n:::\n:::\n\n\n:::\n\n> Q.9. What is the coefficient estimate for the intercept?\n\n:::{.callout-tip collapse=\"true\"}\n## Answer\n> A.9. 0.44914\n:::\n\n> Q.10. What is the coefficient estimate for the slope of SHIPLEY?\n\n:::{.callout-tip collapse=\"true\"}\n## Answer\n> A.10. 0.01050\n:::\n\n**Step 2. Second, draw a scatterplot and add a line to show the model predictions**\n\nWe use the `geom_abline()` function to draw the line.\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one.gen, aes(x = SHIPLEY, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')   +\n  geom_abline(intercept = 0.44914, slope = 0.01050, colour = \"red\", linewidth = 1.5) +\n  theme_bw() +\n  labs(x = \"SHIPLEY\", y = \"mean accuracy\") +\n  xlim(0, 40) + ylim(0, 1)\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n:::\n\nYou can see that the only **new** thing we do here is to:\n\n1. add the `geom_abline(...)` function;\n2. and, inside the brackets, add information about the intercept and the slope estimates.\n\nNote that we can get the prediction line drawn for us automatically.\n\n:::{.callout-tip collapse=\"true\"}\n## Hint\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one.gen, aes(x = SHIPLEY, y = mean.acc)) +\n  # geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')   +\n  geom_smooth(method = 'lm', colour = \"purple\", alpha = .2, linewidth = 2.5, se = FALSE) +\n  geom_abline(intercept = 0.44914, slope = 0.01050, colour = \"red\", linewidth = 1) +\n  theme_bw() +\n  labs(x = \"SHIPLEY\", y = \"mean accuracy\") +\n  xlim(0, 40) + ylim(0, 1)  \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n\nHere, I turned the points off by commenting them out, adding `#` to the start of the line.\n\n- I added `geom_smooth(method = 'lm', ...)` to draw a prediction line.\n\nYou can compare the red prediction line I drew using the model estimates with the purple line I used `geom_smooth()` to draw automatically, to see that they are identical.\n\nYou have seen `geom_smooth()` before: this shows you how it works.\n:::\n\n**What are we learning here?**\n\nWe want to generate model predictions because doing this unlocks a key concept in understanding why we use linear models and what we do.\n\n- Linear models are an analysis method based on the *prediction* of the average change in outcome variable values, given different values of one or more predictor variables.\n\n::: callout-tip\n## Further information you can explore\nYou can get `{ggplot2}` reference information to see what `geom_smooth()` does:\n\n<https://ggplot2.tidyverse.org/reference/geom_smooth.html>\n\nYou can see reference information on drawing lines here:\n\n<https://ggplot2.tidyverse.org/reference/geom_abline.html>\n:::\n\n#### 8.4.3 The practical exercises {#sec-lm-intro-practical-workbook}\n\nNow you will progress through a series of tasks, and challenges, to test what you have learnt.\n\n::: callout-warning\nNow we will work with the data file\n\n-   `study-two-general-participants.csv`\n:::\n\nWe again split the steps into into parts, tasks and questions.\n\nWe are going to work through the following workflow steps: **each step is labelled as a practical part**.\n\n1. Set-up\n2. Load the data\n3. Revision: developing histograms to examine the distributions of variables.\n4. Revision: developing scatterplots to examine associations between variables.\n5. Revision: using correlations to to answer research questions --- making sure you are comfortable with the calculation and interpretation of correlation analyses.\n6. **New**: using a linear model to answer research questions.\n7. **New**: using a linear model to make predictions.\n\n::: callout-tip\n- The `how-to` guide showed you what functions you needed and how you should write the function code.\n- Use the code structure you have seen and *change* it to use the data required for these `practical exercises`: you will need to change the data-set name, the variable names, to get the code to work for the following exercises.\n- Identify what code elements must change, and what code elements have to stay the same.\n:::\n\nIn the following, we will guide you through the tasks and questions step by step.\n\n::: callout-important\nAn answers version of the workbook will be provided after the practical class.\n:::\n\n#### 8.4.3.1 Practical Part 1: Set-up\n\nTo begin, we set up our environment in R.\n\n##### Practical Task 1 -- Run code to empty the R environment\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list=ls())\n```\n:::\n\n\n:::\n\n##### Practical Task 2 -- Run code to load relevant libraries\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"tidyverse\")\n```\n:::\n\n\n:::\n\n#### 8.4.3.2 Practical Part 2: Load the data\n\n##### Practical Task 3 -- Read in the data file we will be using\n\nThe data file for the practical exercises is:\n\n- `study-two-general-participants.csv`\n\nUse the `read_csv()` function to read the data file into R.\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudy.two.gen <- read_csv(\"study-two-general-participants.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 172 Columns: 12\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (5): participant_ID, study, GENDER, EDUCATION, ETHNICITY\ndbl (7): mean.acc, mean.self, AGE, SHIPLEY, HLVA, FACTOR3, QRITOTAL\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n:::\n\nWhen you code this, you can choose your own file name, but be sure to give the data object you create a distinct name e.g. `study.two.gen`.\n\n##### Practical Task 4 -- Inspect the data file\n\nUse the `summary()` function to take a look.\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(study.two.gen)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n participant_ID        mean.acc        mean.self        study          \n Length:172         Min.   :0.4107   Min.   :3.786   Length:172        \n Class :character   1st Qu.:0.6786   1st Qu.:6.411   Class :character  \n Mode  :character   Median :0.7679   Median :7.321   Mode  :character  \n                    Mean   :0.7596   Mean   :7.101                     \n                    3rd Qu.:0.8393   3rd Qu.:7.946                     \n                    Max.   :0.9821   Max.   :9.000                     \n      AGE           SHIPLEY           HLVA           FACTOR3     \n Min.   :18.00   Min.   :23.00   Min.   : 3.000   Min.   :29.00  \n 1st Qu.:25.00   1st Qu.:32.75   1st Qu.: 7.750   1st Qu.:47.00  \n Median :32.50   Median :36.00   Median : 9.000   Median :51.00  \n Mean   :35.37   Mean   :35.13   Mean   : 9.064   Mean   :51.24  \n 3rd Qu.:44.00   3rd Qu.:39.00   3rd Qu.:11.000   3rd Qu.:56.25  \n Max.   :76.00   Max.   :40.00   Max.   :14.000   Max.   :63.00  \n    QRITOTAL        GENDER           EDUCATION          ETHNICITY        \n Min.   : 6.00   Length:172         Length:172         Length:172        \n 1st Qu.:12.00   Class :character   Class :character   Class :character  \n Median :14.00   Mode  :character   Mode  :character   Mode  :character  \n Mean   :13.88                                                           \n 3rd Qu.:16.00                                                           \n Max.   :20.00                                                           \n```\n\n\n:::\n:::\n\n\n:::\n\nThis time:\n\n- Pay attention to what you see, for the numeric variables, in the information about minimum `Min.` and maximum `Max.` values.\n\n#### 8.4.3.3 Practical Part 3: Revision -- developing histograms to examine the distributions of variables\n\n##### Practical Task 5 -- Practise editing the appearance of a histogram plot step-by-step\n\nStart by constructing a basic histogram.\n\n- Draw a histogram plot to visualize the distribution of *any* numeric variable from the `study.two.gen` data-set.\n\n:::{.callout-tip collapse=\"true\"}\n## Hint\n- Use the line-by-line format to break the plot code into steps.\n- It will make it easier to read, and it will make it easier to add edit.\n:::\n\n1. Pick a numeric variable in the dataset.\n2. Run the code to produce a histogram to show the distribution of values for that variable in the data.\n\nCan you work out how to do it without looking at the code example?\n\nClick on the button to see the code example: compare it to the code you wrote.\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = SHIPLEY)) + \n  geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n:::\n\nNext, we are going to edit:\n\n1. **new** -- the appearance of the bars using `binwidth`;\n2. **revision** -- the appearance of the background;\n3. **revision** -- the appearance of the labels using `labs()`;\n4. **new** -- setting the x-axis limits to reflect the full range of possible scores on the x-axis variable using `xlim()`;\n5. **new** -- adding annotation -- here, a vertical line using `geom_vline()`.\n\n>**Pract.Q.1.** Can you edit the appearance of the bars by specifying a `binwidth` value?\n\n:::{.callout-tip collapse=\"true\"}\n## Hint\nRemember: \n\n- The `binwidth` number has to be a value between the smallest possible value and the largest possible value for the variable. For example, if the variable is `AGE` then the smallest possible value will be 0. So `binwidth` has to be some number bigger than 0.\n- You can experiment with different numbers to find a balance between a histogram that shows detail (more, narrow, bars) and a histogram that shows an impression (fewer, wider, bars).\n:::\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = SHIPLEY)) +\n  geom_histogram(binwidth = 2)\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n:::\n\n>**Pract.Q.2.** Can you edit the appearance of the background?\n\n:::{.callout-tip collapse=\"true\"}\n## Hint\nThere are a range of themes that you can use.  Why not pick one of the options shown here:\n\n<https://ggplot2.tidyverse.org/reference/ggtheme.html>\n:::\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = SHIPLEY)) +\n  geom_histogram(binwidth = 2) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n:::\n\n>**Pract.Q.3.** Can you edit the appearance of the labels?\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = SHIPLEY)) +\n  geom_histogram(binwidth = 2) +\n  theme_bw() +\n  labs(x = \"SHIPLEY\", y = \"frequency count\")\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n:::\n\n>**Pract.Q.4.** Can you edit the x-axis limits?\n\n:::{.callout-tip collapse=\"true\"}\n## Hint\nWhat you want to do, here, is to show the smallest possible value (often, not always 0) for values in the variable.\n\n- The idea is that you want to see the distribution of values in the sample (the histogram), for the variable, in the context of the full possible range of values for that variable.\n- You can use the `summary()` information to make your choice of limits.\n\nDrawing a histogram like this allows you to show the reader how the sample compares to the wider population.\n:::\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = SHIPLEY)) +\n  geom_histogram(binwidth = 2) +\n  theme_bw() +\n  labs(x = \"Vocabulary (SHIPLEY)\", y = \"frequency count\") +\n  xlim(0,40)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing missing values or values outside the scale range\n(`geom_bar()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n:::\n\n>**Pract.Q.5.** Can you add annotation: a vertical line to show the mean value of \nthe variable you are plotting?\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = SHIPLEY)) +\n  geom_histogram(binwidth = 2) +\n  theme_bw() +\n  labs(x = \"Vocabulary (SHIPLEY)\", y = \"frequency count\") +\n  xlim(0,40) +\n  geom_vline(xintercept = mean(study.two.gen$SHIPLEY), colour = \"red\", size = 1.5)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing missing values or values outside the scale range\n(`geom_bar()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n:::\n\n>**Pract.Q.6.** Where can you find information on how to define the limits on the x-axis \nand on the y-axis?\n\n:::{.callout-tip collapse=\"true\"}\n## Hint\nYou can see the information in this week's `how-to` guide but try a search online for the keywords: `ggplot reference xlim`.\n:::\n\n> Pract.A.6. See ggplot reference information on setting limits here:\n\n<https://ggplot2.tidyverse.org/reference/lims.html>\n\n>**Pract.Q.7.** Where can you find information on how to draw a reference line?\n\n:::{.callout-tip collapse=\"true\"}\n## Hint\nYou can see the information in this week's `how-to` but try a search online for the keywords: `ggplot reference vline`.\n:::\n\n> Pract.A.7. See ggplot reference information on adding lines here:\n\n<https://ggplot2.tidyverse.org/reference/geom_abline.html>\n\n#### 8.4.3.4 Practical Part 4: Developing scatterplots to examine associations between variables\n\n##### Practical Task 6 -- Create a scatterplot to examine the association between some variables\n\nCreate three scatterplots to visualize the relationship between (1.) the outcome `mean.acc` and (2.) each of three numeric potential predictor variables `SHIPLEY`, `HLVA` and `AGE`.\n\nCheck first if you can write the code you need to produce each scatterplot.\nClick on the button to see the code example: compare it to the code you wrote.\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\nCheck out the example code for each of the scatterplots we are asking you to do.\n\n- Notice what changes and what stays the same.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = SHIPLEY, y = mean.acc)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = HLVA, y = mean.acc)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-32-2.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = AGE, y = mean.acc)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-32-3.png){width=672}\n:::\n:::\n\n\n:::\n\n##### Practical Task 7 -- Edit the appearance of *each* plot step-by-step\n\n1. You may want to use the same plot edit choices for all plots.\n\n- Producing plots with a consistent appearance will make it easier for \nyour audience to read your plots.\n\n2. You can find links to relevant information on options in the `how-to` guide.\n\n- Use the information to make the plots pleasing in appearance to you.\n\n:::{.callout-tip collapse=\"true\"}\n## Hints\n- Do not be afraid to select, copy then paste code to re-use it and *save yourself* the effort of typing out the code over and over again.\n- But be careful to make sure that you change variable names, and that things like axis values are sensible for each variable.\n:::\n\n>**Pract.Q.8.** Can you edit the appearance of the points using `alpha`, `size`, `shape`, and `colour`?\n\n:::{.callout-tip collapse=\"true\"}\n## Code\nCheck out the example code for each of the scatterplots.\n\n- Notice what changes and what stays the same.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = SHIPLEY, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = HLVA, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-33-2.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = AGE, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-33-3.png){width=672}\n:::\n:::\n\n\n:::\n\n>**Pract.Q.9.** Can you edit the appearance of the background?\n\n:::{.callout-tip collapse=\"true\"}\n## Code\nCheck out the example code for each of the scatterplots.\n\n- Notice what changes and what stays the same.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = SHIPLEY, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')   +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = HLVA, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')   +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-34-2.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = AGE, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')   +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-34-3.png){width=672}\n:::\n:::\n\n\n:::\n\n>**Pract.Q.10.** Can you edit the appearance of the labels?\n\n:::{.callout-tip collapse=\"true\"}\n## Code\nCheck out the example code for each of the scatterplots.\n\n- Notice what changes and what stays the same.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = SHIPLEY, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')   +\n  theme_bw() +\n  labs(x = \"SHIPLEY\", y = \"mean accuracy\")\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = HLVA, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')   +\n  theme_bw() +\n  labs(x = \"HLVA\", y = \"mean accuracy\")\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-35-2.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = AGE, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')   +\n  theme_bw() +\n  labs(x = \"Age (Years)\", y = \"mean accuracy\")\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-35-3.png){width=672}\n:::\n:::\n\n\n:::\n\n>**Pract.Q.11.** Can you set the x-axis and y-axis limits to 0 (as the minimum) versus the sample data maximum values for the variables you are plotting?\n\n:::{.callout-tip collapse=\"true\"}\n## Hint\n- For these plots the y-axis limits will be the same because the outcome stays the same across plots.\n- The x-axis limits will be different for each different predictor variable.\n- Check out the information in the `summary()` of the dataset.\n- The minimum values for the variables will often be 0, e.g., if you are looking at data from ability tests and people who do the tests can get 0. But if you are looking at, e.g., ratings data then the minimum value could be 1, e.g., because people are asked to rate something on a scale from 1-9.\n:::\n\nCheck first if you can write the code you need to produce each scatterplot.\nClick on the button to see the code example: compare it to the code you wrote.\n\n:::{.callout-tip collapse=\"true\"}\n## Code\nCheck out the example code for each of the scatterplots.\n\n- Notice what changes and what stays the same.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = SHIPLEY, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')   +\n  theme_bw() +\n  labs(x = \"SHIPLEY\", y = \"mean accuracy\") +\n  xlim(0, 40) + ylim(0, 1)\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = HLVA, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')   +\n  theme_bw() +\n  labs(x = \"HLVA\", y = \"mean accuracy\") +\n  xlim(0, 16) + ylim(0, 1)\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-36-2.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = AGE, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')   +\n  theme_bw() +\n  labs(x = \"Age (Years)\", y = \"mean accuracy\") +\n  xlim(0, 80) + ylim(0, 1)\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-36-3.png){width=672}\n:::\n:::\n\n\n:::\n\n#### 8.4.3.5 Practical Part 5: Using correlations to to answer research questions --- making sure you are comfortable\n\nOne of our research questions is:\n\n1. What person attributes predict success in understanding?\n\n##### Practical Task 8 -- Examine the correlations between the outcome variable and predictor variables\n\nRun three correlations to look at this question: \n\n1. between mean accuracy and `SHIPLEY`;\n2. between mean accuracy and `HLVA`; \n3. between mean accuracy and `AGE`.\n\nCheck first if you can write the code you need to complete each correlation analysis.\nClick on the button to see the code example: compare it to the code you wrote.\n\n:::{.callout-tip collapse=\"true\"}\n## Code\nCheck out the example code for doing each of the correlation analyses.\n\n- Notice what changes and what stays the same.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(study.two.gen$SHIPLEY, study.two.gen$mean.acc, method = \"pearson\",  alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  study.two.gen$SHIPLEY and study.two.gen$mean.acc\nt = 6.8493, df = 170, p-value = 1.299e-10\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.3390103 0.5746961\nsample estimates:\n      cor \n0.4650537 \n```\n\n\n:::\n\n```{.r .cell-code}\ncor.test(study.two.gen$HLVA, study.two.gen$mean.acc, method = \"pearson\",  alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  study.two.gen$HLVA and study.two.gen$mean.acc\nt = 7.5288, df = 170, p-value = 2.866e-12\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.3787626 0.6044611\nsample estimates:\n      cor \n0.5000559 \n```\n\n\n:::\n\n```{.r .cell-code}\ncor.test(study.two.gen$AGE, study.two.gen$mean.acc, method = \"pearson\",  alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  study.two.gen$AGE and study.two.gen$mean.acc\nt = 0.30121, df = 170, p-value = 0.7636\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.1269774  0.1721354\nsample estimates:\n       cor \n0.02309589 \n```\n\n\n:::\n:::\n\n\n:::\n\nNow use the results from the correlations to answer the following questions.\n\n>**Pract.Q.12.** What is `r`, the coefficient for the correlation between `mean.acc` and `SHIPLEY`?\n\n> Pract.A.12. r = 0.4650537\n\n>**Pract.Q.13.** Is the correlation between `mean.acc` and `HLVA`  significant?\n\n> Pract.A.13. -- r is significant, p < .05\n\n>**Pract.Q.14.** What are the values for t and p for the significance test for the correlation between `mean.acc` and `AGE`?\n\n> Pract.A.14. t = 0.30121, p = 0.7636\n\n>**Pract.Q.15.** For which pair of outcome-predictor variables is the correlation the largest?\n\n> Pract.A.15. -- The correlation is the largest between `mean.acc` and `HLVA`.\n\n>**Pract.Q.16.** What is the sign or direction of each of the correlations?\n\n> Pract.A.16. -- All the correlations are positive.\n\n#### 8.4.3.6 Practical Part 6: Using a linear model to to answer research questions\n\nNow we can use linear models to try to answer the question:\n\n1. What person attributes predict success in understanding?\n\n##### Practical Task 9 -- Examine the relation between outcome mean accuracy (`mean.acc`) and each of the predictors: `SHIPLEY`, `HLVA` and `AGE`\n\nYou need to run three separate `lm()` analyses:\n\n1. with mean accuracy `mean.acc` as the outcome and `SHIPLEY` as the predictor;\n2. with mean accuracy `mean.acc` as the outcome and `HLVA` as the predictor; \n3. with mean accuracy `mean.acc` as the outcome and `AGE` as the predictor.\n\n:::{.callout-tip collapse=\"true\"}\n## Hints\nYou need to use `lm()` to do the analyses.\n\n1. Be careful to identify the outcome and predictor variables correctly.\n2. Remember that analysis code is arranged like this:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(outcome.variable ~ predictor.variable, data = data.set)\n```\n:::\n\n\n\nWith:\n\n- `lm()` asking R to do the linear model analysis;\n- `outcome.variable ~ ...` specified on the *left* of the `~`;\n- the `predictor.variable ~ ...` specified on the *right* of the `~`;\n- and `data.set` identifying to R what dataset you are working with.\n:::\n\nCheck first if you can write the code you need to complete each linear model analysis.\nClick on the button to see the code example: compare it to the code you wrote.\n\n:::{.callout-tip collapse=\"true\"}\n## Code\nCheck out the example code for each of the models.\n\n- Notice what changes and what stays the same.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel.1 <- lm(mean.acc ~ SHIPLEY, data = study.two.gen)\nsummary(model.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ SHIPLEY, data = study.two.gen)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.285771 -0.076662  0.002099  0.079416  0.257793 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.308027   0.066426   4.637 7.01e-06 ***\nSHIPLEY     0.012854   0.001877   6.849 1.30e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.107 on 170 degrees of freedom\nMultiple R-squared:  0.2163,\tAdjusted R-squared:  0.2117 \nF-statistic: 46.91 on 1 and 170 DF,  p-value: 1.299e-10\n```\n\n\n:::\n\n```{.r .cell-code}\nmodel.2 <- lm(mean.acc ~ HLVA, data = study.two.gen)\nsummary(model.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ HLVA, data = study.two.gen)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.27457 -0.06777  0.01474  0.08025  0.23146 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.522016   0.032544  16.040  < 2e-16 ***\nHLVA        0.026207   0.003481   7.529 2.87e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1047 on 170 degrees of freedom\nMultiple R-squared:  0.2501,\tAdjusted R-squared:  0.2456 \nF-statistic: 56.68 on 1 and 170 DF,  p-value: 2.866e-12\n```\n\n\n:::\n\n```{.r .cell-code}\nmodel.3 <- lm(mean.acc ~ AGE, data = study.two.gen)\nsummary(model.3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ AGE, data = study.two.gen)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.34684 -0.08464  0.01084  0.08323  0.21968 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.7519965  0.0267206  28.143   <2e-16 ***\nAGE         0.0002136  0.0007092   0.301    0.764    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1208 on 170 degrees of freedom\nMultiple R-squared:  0.0005334,\tAdjusted R-squared:  -0.005346 \nF-statistic: 0.09073 on 1 and 170 DF,  p-value: 0.7636\n```\n\n\n:::\n:::\n\n\n:::\n\nIf you look at the model summary you can answer the following questions.\n\n>**Pract.Q.17.** What is the estimate for the coefficient of the effect of the predictor `HLVA` on `mean.acc`?\n\n> Pract.A.17. 0.026207\n\n>**Pract.Q.18.** Is the effect significant?\n\n> Pract.A.18. It is significant, p < .05\n\n>**Pract.Q.19.** What are the values for t and p for the significance test for the coefficient?\n\n> Pract.A.19. t = 7.529, p = 2.87e-12\n\n>**Pract.Q.20.** How would you describe in words the shape or direction of the association between `HLVA` and `mean.acc`?\n\n> Pract.A.20. The slope coefficient -- and a scatterplot (draw it) -- suggest that as HLVA scores increase so also do mean accuracy scores.\n\n>**Pract.Q.21.** How how would you describe the relations apparent between the predictor and outcome in all three models?\n\n> Pract.A.21. It is possible to see, given coefficient estimates, that the association between predictor and outcome is positive for each model: mean accuracy appears to increase for increasing values of SHIPLEY vocabulary, HLVA health literacy, and age.\n\n#### 8.4.3.7 Practical Part 7: Using a linear model to make predictions\n\n##### Practical Task 10 -- Fit a linear model and use the results to plot the model predictions\n\nWe are going to draw a scatterplot and add a line.\n\n- The line will show the model predictions, given the model intercept and effect \ncoefficient estimates.\n\n**Step 1. First fit a linear model and get a summary of the estimates**\n\nFit a model with mean accuracy `mean.acc` as the outcome and `HLVA` as the predictor.\n\nCheck if you can write the code you need to complete the linear model analysis.\nClick on the button to see the code example: compare it to the code you wrote.\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.acc ~ HLVA, data = study.two.gen)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ HLVA, data = study.two.gen)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.27457 -0.06777  0.01474  0.08025  0.23146 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.522016   0.032544  16.040  < 2e-16 ***\nHLVA        0.026207   0.003481   7.529 2.87e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1047 on 170 degrees of freedom\nMultiple R-squared:  0.2501,\tAdjusted R-squared:  0.2456 \nF-statistic: 56.68 on 1 and 170 DF,  p-value: 2.866e-12\n```\n\n\n:::\n:::\n\n\n:::\n\nYou will need to record some information from the model summary so you can use it next.\n\n>**Pract.Q.22.** What is the coefficient estimate for the intercept?\n\n> Pract.A.22. 0.522016\n\n>**Pract.Q.23.** What is the coefficient estimate for the slope of `HLVA`?\n\n> Pract.A.23. 0.026207\n\n**Step 2. Second, draw a scatterplot and add a line to show the model predictions**\n\nCheck first if you can write the code you need to produce the prediction plot.\nClick on the button to see the code example: compare it to the code you wrote.\n\n:::{.callout-tip collapse=\"true\"}\n## Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = HLVA, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')   +\n  geom_abline(intercept = 0.522016, slope = 0.026207,\n              colour = \"red\", size = 1.5) +\n  theme_bw() +\n  labs(x = \"HLVA\", y = \"mean accuracy\") +\n  xlim(0, 15) + ylim(0, 1)\n```\n\n::: {.cell-output-display}\n![](lm-intro_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n\n:::\n\n#### You have now completed the Week 8 practical exercises and questions\n\n::: callout-important\nPredicting human behaviour is at the heart of:\n\n- Psychological science, and our collective attempt to understand ourselves.\n- Behavioural analytics, and the ways businesses work with what we know about people.\n\nThis is an important step in your developmental journey: **Well done!**\n\n- We will continue to deepen and extend your skills and understanding but everything builds on the key lessons we have been learning here.\n:::\n\n### The answers\n\nAfter the practical class, we will reveal the answers that are currently hidden.\n\nThe answers version of the webpage will present my answers for questions, and some extra information where that is helpful.\n\n### Look ahead: growing in independence\n\n::: callout-important\nEvery professional using R spends *a lot* of time on one or two R information websites. The most useful include:\n\n- the `{tidyverse}` webpages;\n- `StackOverflow`;\n- the `R bloggers` aggregator webpages.\n\nCan you find them?\n\nIs there a question that has been puzzling you about what you are doing? Can you find the answer on one of these websites?\n:::\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}