<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Week 17. Workbook introduction to mixed-effects models – Archive: Statistics for Psychologists</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../Images/favicon.png" rel="icon" type="image/png">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script language="JavaScript" type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script>window.onload = function() {document.getElementById("autocomplete-0-input").placeholder = "Search the Archive";};</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="https://lu-psy-r.github.io/">
    <span class="navbar-title">Archive: Statistics for Psychologists</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io"> 
<span class="menu-text">Back to the Current Materials</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#sec-mixed-effects-workbook-overview" id="toc-sec-mixed-effects-workbook-overview" class="nav-link active" data-scroll-target="#sec-mixed-effects-workbook-overview">Week 17 Mixed-effects models workbook overview</a>
  <ul class="collapse">
  <li><a href="#sec-mixed-effects-workbook-targets" id="toc-sec-mixed-effects-workbook-targets" class="nav-link" data-scroll-target="#sec-mixed-effects-workbook-targets">Targets</a></li>
  <li><a href="#sec-mixed-effects-workbook-resources" id="toc-sec-mixed-effects-workbook-resources" class="nav-link" data-scroll-target="#sec-mixed-effects-workbook-resources">Learning resources</a>
  <ul class="collapse">
  <li><a href="#sec-mixed-effects-workbook-lectures" id="toc-sec-mixed-effects-workbook-lectures" class="nav-link" data-scroll-target="#sec-mixed-effects-workbook-lectures">Lectures</a></li>
  <li><a href="#sec-mixed-effects-workbook-slides" id="toc-sec-mixed-effects-workbook-slides" class="nav-link" data-scroll-target="#sec-mixed-effects-workbook-slides">Lecture slides</a></li>
  <li><a href="#sec-mixed-effects-workbook-practical" id="toc-sec-mixed-effects-workbook-practical" class="nav-link" data-scroll-target="#sec-mixed-effects-workbook-practical">Practical materials: data and R-Studio</a></li>
  <li><a href="#the-answers" id="toc-the-answers" class="nav-link" data-scroll-target="#the-answers">The answers</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Week 17. Workbook introduction to mixed-effects models</h1>
<p class="subtitle lead">Written by Rob Davies</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-mixed-effects-workbook-overview" class="level1">
<h1>Week 17 Mixed-effects models workbook overview</h1>
<p>Welcome to your overview of the work we will do together in <strong>Week 17</strong>.</p>
<p>Many Psychologists conduct studies with <strong>repeated-measures designs</strong> where the experimenter presents a sample of multiple stimuli, for response, to each participant in a sample of multiple participants. Studies with repeated-measures designs will produce data with a structure that requires the use of mixed-effects models.</p>
<p>We are going to learn about this kind of data, and build on the analysis methods we learned about in the <a href="../../../2425/PSYC412/part2/01-multilevel.html#sec-intro-multilevel">conceptual introduction to multilevel data</a> and the <a href="../../../2425/PSYC412/part2/01-multilevel-workbook.html#sec-multilevel-workbook-overview">workbook introduction to multilevel data</a>.</p>
<p>We use the same procedure we did for multilevel data but with <strong>one significant change</strong> which we shall explore and seek to understand in-depth.</p>
<section id="sec-mixed-effects-workbook-targets" class="level2">
<h2 class="anchored" data-anchor-id="sec-mixed-effects-workbook-targets">Targets</h2>
<p>Our learning objectives again include the development of both concepts and skills.</p>
<ol type="1">
<li><strong>skills</strong> – practice how to tidy experimental data for mixed-effects analysis.</li>
<li><strong>concepts</strong> – begin to develop an understanding of crossed random effects of participants and stimuli.</li>
<li><strong>skills and concepts</strong> – practice fitting linear mixed-effects models incorporating random effects of participants and stimuli.</li>
</ol>
</section>
<section id="sec-mixed-effects-workbook-resources" class="level2">
<h2 class="anchored" data-anchor-id="sec-mixed-effects-workbook-resources">Learning resources</h2>
<p>You will see, next, the lectures we share to explain the concepts you will learn about, and the practical data analysis skills you will develop. Then you will see information about the practical materials you can use to build and practise your skills.</p>
<p>Every week, you will learn best if you <em>first</em> watch the lectures <em>then</em> do the practical exercises.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Linked resources
</div>
</div>
<div class="callout-body-container callout-body">
<p>To help your learning, you can read about the ideas and the practical coding required for analyses in the chapters I wrote for this course.</p>
<ul>
<li>The <a href="../../../2425/PSYC412/part2/02-mixed.html#sec-intro-mixed">chapter: Introduction to linear mixed-effects models</a></li>
</ul>
</div>
</div>
<section id="sec-mixed-effects-workbook-lectures" class="level3">
<h3 class="anchored" data-anchor-id="sec-mixed-effects-workbook-lectures">Lectures</h3>
<p>The lecture materials for this week are presented in three short parts.</p>
<p>Click on a link and your browser should open a tab showing the <em>Panopto</em> video for the lecture part.</p>
<ol type="1">
<li>Part 1 (17 minutes) <strong>Mixed-effects models</strong>: Repeated measures data and the what, when and how of mixed-effects models.</li>
</ol>
<iframe src="https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=2fa60b12-2eca-4412-8672-acd60104da1d&amp;autoplay=false&amp;offerviewer=true&amp;showtitle=true&amp;showbrand=true&amp;captions=false&amp;interactivity=all" height="405" width="720" style="border: 1px solid #464646;" allowfullscreen="" allow="autoplay" aria-label="Panopto Embedded Video Player" aria-description="02-mixed-1-of-3"></iframe>
<ol start="2" type="1">
<li>Part 2 (21 minutes): Working with an example from a study with a repeated measures design, recognizing how people or how stimuli vary, and identifying the motivation for using mixed-effects models, compared to alternative methods.</li>
</ol>
<iframe src="https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=7f31cef0-1e39-4712-b2a1-acd601195c78&amp;autoplay=false&amp;offerviewer=true&amp;showtitle=true&amp;showbrand=true&amp;captions=false&amp;interactivity=all" height="405" width="720" style="border: 1px solid #464646;" allowfullscreen="" allow="autoplay" aria-label="Panopto Embedded Video Player" aria-description="02-mixed-2-of-3"></iframe>
<ol start="3" type="1">
<li>Part 3 (15 minutes): What mixed-effects models can do for us, how we can describe the logic, how we code mixed-effects models, what the bits of code do, what the results look like, what the results tell us, and how we should report our models and our findings.</li>
</ol>
<iframe src="https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=58ab0c0c-37be-491f-a9e5-acd6011c38dd&amp;autoplay=false&amp;offerviewer=true&amp;showtitle=true&amp;showbrand=true&amp;captions=false&amp;interactivity=all" height="405" width="720" style="border: 1px solid #464646;" allowfullscreen="" allow="autoplay" aria-label="Panopto Embedded Video Player" aria-description="02-mixed-3-of-3"></iframe>
</section>
<section id="sec-mixed-effects-workbook-slides" class="level3">
<h3 class="anchored" data-anchor-id="sec-mixed-effects-workbook-slides">Lecture slides</h3>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Download the lecture slides
</div>
</div>
<div class="callout-body-container callout-body">
<p>The slides presented in the videos can be downloaded here:</p>
<ul>
<li><a href="files/402-week-18-LME-2.pdf">402-week-18-LME-2.pdf</a>: high resolution .pdf, exactly as delivered [6 MB];</li>
<li><a href="files/402-week-18-LME-2_1pp-lo.pdf">402-week-18-LME-2_1pp-lo.pdf</a>: lower resolution .pdf, printable version, one-slide-per-page [about 900 KB];</li>
<li><a href="files/402-week-18-LME-2_6pp-lo.pdf">402-week-18-LME-2_6pp-lo.pdf</a>: lower resolution .pdf, printable version, six-slides-per-page [about 900 KB].</li>
</ul>
<p>The high resolution version is the version delivered for the lecture recordings. Because the images are produced to be high resolution, the file size is quite big (6 MB) so, to make the slides easier to download, I produced low resolution versions: 1pp and 6pp. These should be easier to download and print out if that is what you want to do.</p>
</div>
</div>
</section>
<section id="sec-mixed-effects-workbook-practical" class="level3">
<h3 class="anchored" data-anchor-id="sec-mixed-effects-workbook-practical">Practical materials: data and R-Studio</h3>
<p>We will be working with the <strong>CP reading study</strong> data-set. CP tested 62 children (aged 116-151 months) on reading aloud in English. In the experimental reading task, CP presented 160 words as stimuli. The same 160 words were presented to all children. The words were presented one at a time on a computer screen. Each time a word was shown, each child had to read the word out loud and their response was recorded. Thus, the CP reading study data-set comprised observations about the responses made by 62 children to 160 words.</p>
<p>You can read more about these data in the <a href="../../../2425/PSYC412/part2/02-mixed.html#sec-intro-mixed">chapter: Introduction to linear mixed-effects models</a>.</p>
<p>The critical features of the study are that:</p>
<ul>
<li>We have an outcome measure – the reading response – observed multiple times.</li>
</ul>
<ol type="1">
<li>We have <em>multiple responses recorded for each participant</em>: they make one response to each stimulus (here, each stimulus word), for the multiple stimuli that they see in the experimental reading task.</li>
<li>And we have <em>multiple responses recorded for each stimulus</em>: one response is made to each stimulus by each participant, for all the participants who completed the task, in a sample of multiple participants.</li>
</ol>
<p>The presence of these features is the reason why we need to use mixed-effects models in our analysis.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Get the data</strong>: get the data file and the .R script you can use to do the exercises that will support your learning.</p>
<ul>
<li>You can download the files folder for this chapter by clicking on the link <a href="files/02-mixed.zip">02-mixed.zip</a>.</li>
</ul>
</div>
</div>
<p>The practical materials folder includes data files and an <code>.R</code> script:</p>
<ul>
<li><code>CP study word naming rt 180211.dat</code></li>
<li><code>CP study word naming acc 180211.dat</code></li>
<li><code>words.items.5 120714 150916.csv</code></li>
<li><code>all.subjects 110614-050316-290518.csv</code></li>
<li><code>long.all.noNAs.csv</code></li>
<li><code>402-02-mixed-workbook.R</code> the workbook you will need to do the practical exercises.</li>
</ul>
<p>The <code>.dat</code> files are <em>tab delimited</em> files holding behavioural data: the latency or reaction time <code>rt</code> (in milliseconds) and the accuracy <code>acc</code> of response made by each participant to each stimulus.</p>
<p>The <code>.csv</code> files are <em>comma separated values</em> files. The <code>words.items</code> file holds information about the 160 stimulus words presented in the experimental reading (word naming) task. The <code>all.subjects</code> file holds information about the 62 participants who volunteered to take part in the experiment.</p>
<p>In the following, I will describe a series of steps through which we get the data ready for analysis. However, as we shall see, you can avoid these steps by using the pre-tidied data-set:</p>
<ul>
<li><code>long.all.noNAs.csv</code></li>
</ul>
<p>The data files are collected together through the steps set out in the .R script:</p>
<ul>
<li><code>402-02-mixed-workbook.R</code>.</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>You can access the sign-in page for <a href="https://psy-rstudio.lancaster.ac.uk/auth-sign-in?appUri=%2F">R-Studio Server here</a></p>
</div>
</div>
<section id="sec-mixed-effects-workbook-practical-guide" class="level4">
<h4 class="anchored" data-anchor-id="sec-mixed-effects-workbook-practical-guide">Practical materials guide</h4>
<p>Here, our learning targets are to:</p>
<ul>
<li>Practice how to tidy experimental data for mixed-effects analysis.</li>
<li>Begin to develop an understanding of crossed random effects of subjects and stimuli.</li>
<li>Practice fitting linear mixed-effects models incorporating random effects of subjects and stimuli.</li>
</ul>
<p>The aims of the lab session work are to:</p>
<ul>
<li>Get practice running the code required to tidy and prepare experimental data for analysis.</li>
<li>Exercise skills by varying model code – changing variables, changing options – so that you can see how the code works.</li>
<li>Use the opportunity to reflect on and evaluate results – so that we can support growth in development of understanding of main ideas.</li>
<li>Optional – get practice running the code: so that you can reproduce the figures and results from the lecture and in the book chapter.</li>
</ul>
</section>
<section id="sec-mixed-effects-workbook-practical-workbook" class="level4">
<h4 class="anchored" data-anchor-id="sec-mixed-effects-workbook-practical-workbook">The practical exercises</h4>
<p>Now you will progress through a series of tasks, and challenges, to aid your learning.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>We will work with the data files:</p>
<ul>
<li><code>CP study word naming rt 180211.dat</code></li>
<li><code>CP study word naming acc 180211.dat</code></li>
<li><code>words.items.5 120714 150916.csv</code></li>
<li><code>all.subjects 110614-050316-290518.csv</code></li>
<li><code>long.all.noNAs.csv</code></li>
</ul>
</div>
</div>
<p>We again split the steps into into parts, tasks and questions.</p>
<p>We are going to work through the following workflow steps: <strong>each step is labelled as a practical part</strong>.</p>
<ol type="1">
<li>Set-up</li>
<li>Load the data</li>
<li>Tidy the data</li>
<li>Read in pre-tidied data</li>
<li>Analyze data with lm</li>
<li>Analyze data with lmer</li>
<li>Optional: reproduce the plots in the chapter and slides</li>
</ol>
<p>In the following, we will guide you through the tasks and questions step by step.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>An answers version of the workbook will be provided after the practical class.</p>
</div>
</div>
</section>
<section id="practical-part-1-set-up" class="level4">
<h4 class="anchored" data-anchor-id="practical-part-1-set-up">Practical Part 1: Set-up</h4>
<p>To begin, we set up our environment in R.</p>
<section id="practical-task-1-run-code-to-load-relevant-libraries" class="level5">
<h5 class="anchored" data-anchor-id="practical-task-1-run-code-to-load-relevant-libraries">Practical Task 1 – Run code to load relevant libraries</h5>
<p>Use the <code>library()</code> function to make the functions we need available to you.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>here() starts at /Users/ivorym/Documents/PhD/Workbench/Full_Setup/previous-content</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Matrix</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.0     ✔ readr     2.1.6
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.2
✔ purrr     1.2.1     </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::combine()     masks gridExtra::combine()
✖ tidyr::expand()      masks Matrix::expand()
✖ dplyr::filter()      masks stats::filter()
✖ dplyr::lag()         masks stats::lag()
✖ tidyr::pack()        masks Matrix::pack()
✖ ggplot2::set_theme() masks sjPlot::set_theme()
✖ tidyr::unpack()      masks Matrix::unpack()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="practical-part-2-load-the-data" class="level4">
<h4 class="anchored" data-anchor-id="practical-part-2-load-the-data">Practical Part 2: Load the data</h4>
<section id="practical-task-2-read-in-the-data-file-we-will-be-using" class="level5">
<h5 class="anchored" data-anchor-id="practical-task-2-read-in-the-data-file-we-will-be-using">Practical Task 2 – Read in the data file we will be using</h5>
<p>Read the data files into R:</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>behaviour.rt <span class="ot">&lt;-</span> <span class="fu">read_tsv</span>(<span class="st">"CP study word naming rt 180211.dat"</span>, <span class="at">na =</span> <span class="st">"-999"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 160 Columns: 62
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr  (1): item_name
dbl (61): AislingoC, AlexB, AllanaD, AmyR, AndyD, AnnaF, AoifeH, ChloeBergin...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>behaviour.acc <span class="ot">&lt;-</span> <span class="fu">read_tsv</span>(<span class="st">"CP study word naming acc 180211.dat"</span>, <span class="at">na =</span> <span class="st">"-999"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 160 Columns: 62
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr  (1): item_name
dbl (61): AislingoC, AlexB, AllanaD, AmyR, AndyD, AnnaF, AoifeH, ChloeBergin...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>subjects <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"all.subjects 110614-050316-290518.csv"</span>, <span class="at">na =</span> <span class="st">"-999"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 62 Columns: 26
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (12): subjectID, WAIS_blocks, ART_truepos, ART_falsepos, handedness, gen...
dbl (14): age.months, TOWREW_acc, TOWREW_time, TOWRENW_acc, TOWRENW_time, sp...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>words <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"words.items.5 120714 150916.csv"</span>, <span class="at">na =</span> <span class="st">"-999"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 160 Columns: 50
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (3): item_name, corteseIMG, corteseAOA
dbl (47): Phono_N, OLD, OLDF, PLD, PLDF, NPhon, NMorph, regularity, Length, ...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Pract.Q.1.</strong> Can you identify the differences between the functions used to read different kinds of data files?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>These different functions respect the different ways in which the <code>.dat</code> and <code>.csv</code> file formats work.</p>
<ul>
<li>We need <code>read_tsv()</code> when data files consist of tab separated values.</li>
<li>We need <code>read_csv()</code> when data files consist of comma separated values.</li>
</ul>
<p>You can read more about the <code>{tidyverse}</code> <code>{readr}</code> library of helpful functions <a href="https://readr.tidyverse.org/">here</a>.</p>
<p>It is <em>very</em> common to get experimental data in all sorts of different formats. Learning to use <strong>tidyverse</strong> functions will make it easier to cope with this when you do research.</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Pract.Q.2.</strong> Can you explain what the <code>read_</code> functions are doing, or what you are doing with them when you code them?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It will help your understanding to examine an example. Take a look at what this line of code includes, element by element.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>behaviour.rt <span class="ot">&lt;-</span> <span class="fu">read_tsv</span>(<span class="st">"CP study word naming rt 180211.dat"</span>, <span class="at">na =</span> <span class="st">"-999"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol type="1">
<li>We write <code>behaviour.rt &lt;- read_tsv(...)</code> to create an object in the R environment, which we call <code>behaviour.rt</code>: the object with this name is the data-set we read into R using <code>read_tsv(...)</code>.</li>
<li>When we write the function <code>read_tsv(...)</code> we include two arguments inside it.</li>
<li><code>read_tsv("CP study word naming rt 180211.dat", ...</code> first, the name of the file, given in quotes <code>""</code> and then a comma.</li>
<li><code>read_tsv(..., na = "-999")</code> second, we tell R that there are some missing values <code>na</code> which are coded with the value <code>"-999"</code>.</li>
</ol>
</div>
</div>
</div>
</section>
</section>
<section id="practical-part-3-tidy-the-data" class="level4">
<h4 class="anchored" data-anchor-id="practical-part-3-tidy-the-data">Practical Part 3: Tidy the data</h4>
<p>Tidying the data involves a number of tasks, some essential and some things we do for our convenience.</p>
<section id="practical-task-3-transform-the-rt-and-acc-data-from-wide-to-long-using-pivot_longer" class="level5">
<h5 class="anchored" data-anchor-id="practical-task-3-transform-the-rt-and-acc-data-from-wide-to-long-using-pivot_longer">Practical Task 3 – Transform the <code>rt</code> and <code>acc</code> data from wide to long using <code>pivot_longer()</code></h5>
<p>To get ready for later analyses, we need to ensure that reaction time (<code>rt</code>) and accuracy (<code>acc</code>) observations are in <em>tidy</em> format.</p>
<p>When we first encounter the data files, the data are untidy because, here, the reaction time (<code>rt</code>) and accuracy (<code>acc</code>) observations are in separate multiple columns. We <em>pivot</em> the data to solve this problem.</p>
<ul>
<li>You can read more about what we are doing and why, here, in the <a href="../../../2425/PSYC412/part2/02-mixed.html#sec-intro-mixed-data-restructure">chapter: Introduction to linear mixed-effects models</a>.</li>
</ul>
<blockquote class="blockquote">
<p><strong>Pract.Q.3.</strong> How do we do this?</p>
</blockquote>
<ul>
<li>You can try out some solutions, based on what you have done before.</li>
<li>You can open the <code>Hint</code> box for a detailed walk-through of the process, and then adapt the hint information.</li>
<li>And you can open the <code>Code</code> box for the example code.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We use a function you may have seen before: <code>pivot_longer()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>rt.long <span class="ot">&lt;-</span> behaviour.rt <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>             <span class="fu">pivot_longer</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">62</span>, <span class="at">names_to =</span> <span class="st">"subjectID"</span>, <span class="at">values_to =</span> <span class="st">"RT"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The name of the function comes from the fact that we are starting with data in wide format e.g.&nbsp;<code>behaviour.rt</code> where we have what should be a single variable of observations (RTs) arranged in a wide series of multiple columns, side-by-side (one column for each participant). But we want to take those wide data and <em>lengthen</em> the data-set, increasing the number of rows and decreasing the number of columns.</p>
<p>Let’s look at this line of code bit by bit.</p>
<ol type="1">
<li><code>rt.long &lt;- behaviour.rt %&gt;%</code></li>
</ol>
<ul>
<li>At the start, I tell R that I am going to create a new longer data-set (more rows, fewer columns) that I shall call <code>rt.long</code>.</li>
<li>I will create this longer data-set from <code>&lt;-</code> the original wide data-set <code>behaviour.rt</code>.</li>
<li>and I will create the new longer data-set by taking the original wide data-set and piping it <code>%&gt;%</code> to the pivot function coded on the next line:</li>
</ul>
<ol start="2" type="1">
<li><code>pivot_longer(2:62, names_to = "subjectID", values_to = "RT")</code></li>
</ol>
<ul>
<li>On this next line, I tell R how to do the pivoting by using three arguments.</li>
</ul>
<ol type="a">
<li><code>pivot_longer(2:62...)</code></li>
</ol>
<ul>
<li>First, I tell R that I want to re-arrange all the columns that can be found in the data-set from the second column to the sixty-second column.</li>
<li>In a spreadsheet, we have a number of columns.</li>
<li>Columns can be identified by their position in the spreadsheet.</li>
<li>The position of a column in a spreadsheet can be identified by number, from the leftmost column (column number 1) to the rightmost column (here, column number 62) in our data-set.</li>
<li>So this argument tells R exactly which columns I want to pivot.</li>
</ul>
<ol start="2" type="a">
<li><code>pivot_longer(..., names_to = "subjectID", ...)</code></li>
</ol>
<ul>
<li>Second, I tell R that I want it to take the column labels and put them into a new column, called <code>subjectID</code>.</li>
<li>In the wide data-set <code>behaviour.rt</code>, each column holds a list of numbers (RTs) but begins with a word in the topmost cell, the name code for a participant, in the column label position.</li>
<li>We want to keep the information about which participant produces which response when we pivot the wide data to a longer structure.</li>
<li>We do this by asking R to take the column labels (the participant names) and listing them in a new column, called <code>subjectID</code> which now holds the names as participant ID codes.</li>
</ul>
<ol start="3" type="a">
<li><code>pivot_longer(...values_to = "RT")</code></li>
</ol>
<ul>
<li>Third, we tell R that all the RT values should be put in a single column.</li>
<li>We can understand that this new column <code>RT</code> will hold RT observations in a vertical stack, one cell for each response by a person to a word, with rows ordered by <code>subjectID</code>.</li>
</ul>
<p>There are 61 columns of data listed by participant though 62 children were tested because we lost one child’s data through an administrative error. As a result, in the wide data sets there are 62 columns, with the first column holding <code>item_name</code> data.</p>
<p>You can find more information about pivoting data <a href="https://tidyr.tidyverse.org/articles/pivot.html">here</a></p>
<p>And you can find more information specifically about the <code>pivot_longer()</code> operation <a href="https://tidyr.tidyverse.org/articles/pivot.html">here</a></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>rt.long <span class="ot">&lt;-</span> behaviour.rt <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>             <span class="fu">pivot_longer</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">62</span>, <span class="at">names_to =</span> <span class="st">"subjectID"</span>, <span class="at">values_to =</span> <span class="st">"RT"</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>acc.long <span class="ot">&lt;-</span> behaviour.acc <span class="sc">%&gt;%</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>              <span class="fu">pivot_longer</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">62</span>, <span class="at">names_to =</span> <span class="st">"subjectID"</span>, <span class="at">values_to =</span> <span class="st">"accuracy"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section>
<section id="practical-task-4-join-data-from-different-sources" class="level5">
<h5 class="anchored" data-anchor-id="practical-task-4-join-data-from-different-sources">Practical Task 4 – Join data from different sources</h5>
<p>To answer our research question, we next need to combine the <strong>RT</strong> with the <strong>accuracy</strong> data, and then the combined behavioural data with <strong>participant</strong> information and with <strong>stimulus</strong> information.</p>
<p>In common practice, in psychological research, we have to deal with the fact that information about behavioural responses, and about participant attributes or stimulus word properties, are located in separate files.</p>
<p>This is a problem where we need, as here, to analyse outcome behavioural responses using information about participant attributes or stimulus word properties.</p>
<blockquote class="blockquote">
<p><strong>Pract.Q.4.</strong> How do we solve this problem?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We need to join the data from the different sources:</p>
<ol type="1">
<li>join RT with accuracy then</li>
<li>join those response data with data about subject attributes</li>
<li>then join those response plus subjects data</li>
<li>with item properties data</li>
</ol>
<p>We can combine the data-sets, in the way that we need, using the <code>{tidyverse}</code> <code>full_join()</code> function.</p>
</div>
</div>
</div>
<p>First, we join RT and accuracy data together.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>long <span class="ot">&lt;-</span> rt.long <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>          <span class="fu">full_join</span>(acc.long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p>Then, we join subject and item information to the behavioural data.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>long.subjects <span class="ot">&lt;-</span> long <span class="sc">%&gt;%</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">full_join</span>(subjects, <span class="at">by =</span> <span class="st">"subjectID"</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>long.all <span class="ot">&lt;-</span> long.subjects <span class="sc">%&gt;%</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>              <span class="fu">full_join</span>(words, <span class="at">by =</span> <span class="st">"item_name"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Pract.Q.4.</strong> Can you explain what you are doing, or what the code you use is doing, to solve the problem of putting the separate sets of data together?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Here, in a series of steps, we take one data-set and join it (merge it) with the second data-set. Let’s look at an example element by element to better understand how this is accomplished.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>long <span class="ot">&lt;-</span> rt.long <span class="sc">%&gt;%</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>           <span class="fu">full_join</span>(acc.long)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code work as follows.</p>
<ol type="1">
<li><code>long &lt;- rt.long %&gt;%</code></li>
</ol>
<ul>
<li>We create a new data-set we call <code>long</code>.</li>
<li>We do this by taking one original data-set <code>rt.long</code> and <code>%&gt;%</code> piping it to the operation defined in the second step.</li>
</ul>
<ol start="2" type="1">
<li><code>full_join(acc.long)</code></li>
</ol>
<ul>
<li>In this second step, we use the function <code>full_join()</code> to add observations from a second original data-set <code>acc.long</code> to those already from <code>rt.long</code></li>
</ul>
<p>The addition of observations from one data-set joining to those from another happens through a matching process.</p>
<ul>
<li>R looks at the data-sets being merged.</li>
<li>It identifies if the two data-sets have columns in common. Here, the data-sets have <code>subjectID</code> and <code>item_name</code> in common).</li>
<li>R can use these common columns to identify rows of data. Here, each row of data will be identified by both <code>subjectID</code> and <code>item_name</code> i.e.&nbsp;as data about the response made by a participant to a word.</li>
<li>R will then do a series of identity checks, comparing one data-set with the other and, row by row, looking for matching values in the columns that are common to both data-sets.</li>
<li>If there is a match then R joins the corresponding rows of data together.</li>
<li>If there isn’t a match then it creates <code>NAs</code> where there are missing entries in one row for one data-set which cannot be matched to a row from the joining data-set.</li>
</ul>
</div>
</div>
</div>
<ul>
<li>You can read more about what we are doing here in <a href="../../../2425/PSYC412/part2/02-mixed.html#sec-intro-mixed-data-relational">the Introduction to linear mixed-effects models chapter section on relational data</a> and <a href="../../../2425/PSYC412/part2/02-mixed.html#sec-intro-mixed-data-join-functions">the same chapter section on join functions</a>.</li>
</ul>
</section>
<section id="practical-task-5-select-just-the-variables-we-need" class="level5">
<h5 class="anchored" data-anchor-id="practical-task-5-select-just-the-variables-we-need">Practical Task 5 – Select just the variables we need</h5>
<p>If the pivoting and joining steps have gone according to plan then we should now be looking at a big, long and wide, data-set. But we do not actually require all of the data-set for the analyses we are going to do.</p>
<p>For our own convenience, we are going to want to select just the variables we need.</p>
<p>We want the variables:</p>
<ul>
<li><code>item_name, subjectID, RT, accuracy</code></li>
<li><code>Lg.UK.CDcount, brookesIMG, AoA_Kup_lem</code></li>
<li><code>Ortho_N, regularity, Length, BG_Mean</code></li>
<li><code>Voice,   Nasal,  Fricative,  Liquid_SV</code><br>
</li>
<li><code>Bilabials,   Labiodentals,   Alveolars</code></li>
<li><code>Palatals,    Velars, Glottals, age.months</code></li>
<li><code>TOWREW_skill, TOWRENW_skill, spoonerisms, CART_score</code></li>
</ul>
<blockquote class="blockquote">
<p><strong>Pract.Q.5.</strong> How do we get to a data-set with just these variables in it?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We are going to select just the variables we need using the <code>select()</code> function.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>long.all.select <span class="ot">&lt;-</span> long.all <span class="sc">%&gt;%</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">select</span>(item_name, subjectID, RT, accuracy, </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>                               Lg.UK.CDcount, brookesIMG, AoA_Kup_lem, </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>                               Ortho_N, regularity, Length, BG_Mean, </span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>                               Voice,   Nasal,  Fricative,  Liquid_SV,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>                               Bilabials,   Labiodentals,   Alveolars,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>                               Palatals,    Velars, Glottals, </span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>                               age.months, TOWREW_skill, TOWRENW_skill, </span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>                               spoonerisms, CART_score)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Pract.Q.6.</strong> What if you wanted to analyze a different set of variables, could you select different variables?</p>
</blockquote>
</section>
<section id="practical-task-6-filter-the-observations" class="level5">
<h5 class="anchored" data-anchor-id="practical-task-6-filter-the-observations">Practical Task 6 – Filter the observations</h5>
<p>The data-set includes missing values, designated <code>NA</code>.</p>
<ul>
<li>Here, every error (coded <code>0</code>, in <code>accuracy</code>) corresponds to an <code>NA</code> in the <code>RT</code> column.</li>
</ul>
<p>The data-set also includes outlier data.</p>
<ul>
<li>In this context, <span class="math inline">\(RT &lt; 200\)</span> are probably response errors or equipment failures. We will want to analyse <code>accuracy</code> later, so we shall need to be careful about getting rid of <code>NAs</code>.</li>
</ul>
<blockquote class="blockquote">
<p><strong>Pract.Q.7.</strong> How do we exclude <code>NA</code>s and outliers so that we can do our analysis?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We can exclude two sets of observations:</p>
<ul>
<li>observations corresponding to correct response reaction times that are too short: <span class="math inline">\(RT &lt; 200\)</span>.</li>
<li>plus observations corresponding to the word <em>false</em> which (because of an Excel formatting problem) dropped item attribute data.</li>
</ul>
<p>We can do this using the <code>filter()</code> function, setting conditions on rows, as arguments.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># step 1</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>long.all.select.filter <span class="ot">&lt;-</span> long.all.select <span class="sc">%&gt;%</span> </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>                            <span class="fu">filter</span>(item_name <span class="sc">!=</span> <span class="st">'FALSE'</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="co"># step 2</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>long.all.select.filter <span class="ot">&lt;-</span> long.all.select.filter <span class="sc">%&gt;%</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>                            <span class="fu">filter</span>(RT <span class="sc">&gt;=</span> <span class="dv">200</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Pract.Q.8.</strong> Can you explain what is going on when you code R to exclude observations?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We can do the exclusions we need to do using the <code>filter()</code> function, setting conditions on rows, as arguments.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># step 1</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>long.all.select.filter <span class="ot">&lt;-</span> long.all.select <span class="sc">%&gt;%</span> </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>                            <span class="fu">filter</span>(item_name <span class="sc">!=</span> <span class="st">'FALSE'</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co"># step 2</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>long.all.select.filter <span class="ot">&lt;-</span> long.all.select.filter <span class="sc">%&gt;%</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>                            <span class="fu">filter</span>(RT <span class="sc">&gt;=</span> <span class="dv">200</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here, I am using the function <code>filter()</code> to …</p>
<ul>
<li>Create a new data-set <code>long.all.select.filter &lt;- ...</code> by</li>
<li>Using functions to work on the data named immediately to the right of the assignment arrow: <code>long.all.select</code></li>
<li>An observation is included in the new data-set if it matches the condition specified as an argument in the <code>filter()</code> function call, thus:</li>
</ul>
<ol type="1">
<li><code>filter(item_name !='FALSE')</code> means: include in the new data-set <code>long.all.select.filter</code> all observations from the old data-set <code>long.all.select</code> that are not <code>!=</code> (<code>!</code> not <code>=</code> equal to) the value <code>FALSE</code> in the variable <code>item_name</code>,</li>
<li>then recreate the <code>long.all.select.filter</code> as a version of itself (with no name change) by including in the new version only those observations where RT was greater than or equal to 200ms using <code>RT &gt;= 200</code>.</li>
</ol>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Pract.Q.9.</strong> Do you understand what the difference is between <code>=</code> and <code>==</code>.</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You need to be careful to distinguish these signs.</p>
<ul>
<li><code>=</code> assigns a value, so <code>x = 2</code> means “x equals 2”</li>
<li><code>==</code> tests a match so <code>x == 2</code> means: “is x equal to 2?”</li>
</ul>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Pract.Q.10.</strong> Can you vary the filter conditions: in different ways?</p>
</blockquote>
<ol type="1">
<li>Change the threshold for including RTs from <code>RT &gt;= 200</code> to something else?</li>
<li>Can you assess what impact the change has? Note that you can count the number of observations (rows) in a data-set using e.g.&nbsp;<code>length(data.set.name$variable.name)?</code>?</li>
</ol>
</section>
<section id="practical-task-7-remove-missing-na-values" class="level5">
<h5 class="anchored" data-anchor-id="practical-task-7-remove-missing-na-values">Practical Task 7 – Remove missing (<code>NA</code>) values</h5>
<p>The data-set includes missing values, designated <code>NA</code>. We have not yet dealt with these.</p>
<blockquote class="blockquote">
<p><strong>Pract.Q.11.</strong> How do you remove missing values?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We can remove missing values before we go any further, using the <code>na.omit()</code> function.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>long.all.noNAs <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(long.all.select.filter)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Pract.Q.12.</strong> Can you explain how the code function works, when we exclude missing <code>NA</code> values?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-25-contents" aria-controls="callout-25" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-25" class="callout-25-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The <code>na.omit()</code> function is powerful.</p>
<p>Look at the example code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>long.all.noNAs <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(long.all.select.filter)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>In using this function, I am asking R to create a new data-set <code>long.all.noNAs</code> from the old data-set <code>long.all.select.filter</code> in a process in which the new data-set will have <em>no</em> rows in which there is a missing value <code>NA</code> in <em>any</em> column.</li>
<li>You need to be reasonably sure, when you use this function, where your <code>NAs</code> may be because, otherwise, you may end the process with a new filtered data-set that has many fewer rows in it than you expected.</li>
</ul>
</div>
</div>
</div>
</section>
</section>
<section id="practical-part-4-read-in-pre-tidied-data" class="level4">
<h4 class="anchored" data-anchor-id="practical-part-4-read-in-pre-tidied-data">Practical Part 4: Read in pre-tidied data</h4>
<p>We have a learnt in following the process of tidying data, step-by-step.</p>
<p>If we wanted to, we could complete the process, check that what we have done is correct, and then write the final version of the data-set out to a new <code>.csv</code> using the <code>write_csv()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(long.all.noNAs, <span class="st">"long.all.noNAs.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="practical-task-8-read-in-.csv-of-pre-tidied-data" class="level5">
<h5 class="anchored" data-anchor-id="practical-task-8-read-in-.csv-of-pre-tidied-data">Practical Task 8 – Read in <code>.csv</code> of pre-tidied data</h5>
<blockquote class="blockquote">
<p><strong>Pract.Q.13.</strong> If you want to skip the tidying process steps, assuming you have written the tidied data-set out to a new <code>.csv</code> file, what would you do?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-26-contents" aria-controls="callout-26" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-26" class="callout-26-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>long.all.noNAs <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"long.all.noNAs.csv"</span>, </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">col_types =</span> <span class="fu">cols</span>(</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">subjectID =</span> <span class="fu">col_factor</span>(),</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>                             <span class="at">item_name =</span> <span class="fu">col_factor</span>()</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>                           )</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>                          ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Pract.Q.14.</strong> Take a look at the example code, can you explain what it is doing?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-27-contents" aria-controls="callout-27" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-27" class="callout-27-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>long.all.noNAs <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"long.all.noNAs.csv"</span>, </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">col_types =</span> <span class="fu">cols</span>(</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">subjectID =</span> <span class="fu">col_factor</span>(),</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>                             <span class="at">item_name =</span> <span class="fu">col_factor</span>()</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>                           )</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>                          ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Notice that I am using <code>read_csv()</code> with an additional argument <code>col_types = cols(...)</code>.</p>
<ul>
<li>Here, I am requesting that <code>read_csv()</code> treats <code>subjectID</code> and <code>item_name</code> as factors.</li>
<li>We use <code>col_types = cols(...)</code> to control how <code>read_csv()</code> interprets specific column variables in the data.</li>
</ul>
<p>Controlling the way that <code>read_csv()</code> handles variables is a very useful capacity, and a more efficient way to work than, say, first reading in the data and then using <em>coercion</em> to ensure that variables are assigned appropriate types.</p>
<p>You can read more about it <a href="https://readr.tidyverse.org/articles/readr.html">here</a>.</p>
</div>
</div>
</div>
</section>
</section>
<section id="practical-part-5-analyze-data-with-lm" class="level4">
<h4 class="anchored" data-anchor-id="practical-part-5-analyze-data-with-lm">Practical Part 5: Analyze data with lm</h4>
<p>We begin our data analysis by asking if reading reaction time <strong>RT</strong> varies in association with the estimated <strong>frequency</strong> of occurrence in language experience of the words we ask participants to read.</p>
<ul>
<li>We ignore, at first, the multilevel structure or clustering in the data.</li>
</ul>
<section id="practical-task-9-visualize-the-relationship-between-frequency-and-rt-ignoring-participant-differences" class="level5">
<h5 class="anchored" data-anchor-id="practical-task-9-visualize-the-relationship-between-frequency-and-rt-ignoring-participant-differences">Practical Task 9 – Visualize the relationship between frequency and RT, ignoring participant differences</h5>
<p>You need to do three things, here:</p>
<ol type="1">
<li>Draw a scatterplot.</li>
<li>Remember to map the outcome reaction time variable to the heights of points.</li>
<li>Remember in this data-set, word frequency information is located in the <code>Lg.UK.CDcount</code> variable.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-28-contents" aria-controls="callout-28" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-28" class="callout-28-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>long.all.noNAs <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Lg.UK.CDcount, <span class="at">y =</span> RT)) <span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">size =</span> <span class="fl">1.5</span>, <span class="at">colour=</span><span class="st">"red"</span>) <span class="sc">+</span> </span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Word frequency: log context distinctiveness (CD) count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-freq-all" class="quarto-float quarto-figure quarto-figure-center anchored" alt="The figure shows a scatterplot: each point represents the lexical frequency (on the x-axis) and the reaction time (RT, on the y-axis) of responses made by children to a set of words. A red line is drawn through the points, indicating that RT decreases for higher values of frequency.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-freq-all-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="02-mixed-workbook_files/figure-html/fig-freq-all-1.png" class="img-fluid figure-img" alt="The figure shows a scatterplot: each point represents the lexical frequency (on the x-axis) and the reaction time (RT, on the y-axis) of responses made by children to a set of words. A red line is drawn through the points, indicating that RT decreases for higher values of frequency." width="432">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-freq-all-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Reading reaction time compared to word frequency, all data
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="practical-task-10-estimate-the-relationship-between-frequency-and-rt-ignoring-participant-differences" class="level5">
<h5 class="anchored" data-anchor-id="practical-task-10-estimate-the-relationship-between-frequency-and-rt-ignoring-participant-differences">Practical Task 10 – Estimate the relationship between frequency and RT, ignoring participant differences</h5>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-29-contents" aria-controls="callout-29" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-29" class="callout-29-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You can use <code>lm()</code> to do this.</p>
<ul>
<li>Remember, we are ignoring random differences between participants or stimuli, at this point.</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-30-contents" aria-controls="callout-30" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-30" class="callout-30-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>lm.all.freq <span class="ot">&lt;-</span> <span class="fu">lm</span>(RT <span class="sc">~</span>  Lg.UK.CDcount, <span class="at">data =</span> long.all.noNAs)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm.all.freq)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = RT ~ Lg.UK.CDcount, data = long.all.noNAs)

Residuals:
    Min      1Q  Median      3Q     Max 
-346.62 -116.03  -38.37   62.05 1981.58 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    882.983     11.901   74.19   &lt;2e-16 ***
Lg.UK.CDcount  -53.375      3.067  -17.40   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 185.9 on 9083 degrees of freedom
Multiple R-squared:  0.03227,   Adjusted R-squared:  0.03216 
F-statistic: 302.8 on 1 and 9083 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="practical-task-11-estimate-the-relationship-between-length-and-rt-ignoring-participant-differences" class="level5">
<h5 class="anchored" data-anchor-id="practical-task-11-estimate-the-relationship-between-length-and-rt-ignoring-participant-differences">Practical Task 11 – Estimate the relationship between length and RT, ignoring participant differences</h5>
<p>Vary the linear model using different outcomes or predictors: now fit a model in which the outcome RT and the predictor is word length.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-31-contents" aria-controls="callout-31" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-31" class="callout-31-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>lm.all.length <span class="ot">&lt;-</span> <span class="fu">lm</span>(RT <span class="sc">~</span>  Length,</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> long.all.noNAs)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm.all.length)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = RT ~ Length, data = long.all.noNAs)

Residuals:
    Min      1Q  Median      3Q     Max 
-358.99 -117.89  -39.99   61.17 1944.07 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  600.149     11.734  51.145  &lt; 2e-16 ***
Length        18.369      2.706   6.789  1.2e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 188.5 on 9083 degrees of freedom
Multiple R-squared:  0.005049,  Adjusted R-squared:  0.00494 
F-statistic: 46.09 on 1 and 9083 DF,  p-value: 1.198e-11</code></pre>
</div>
</div>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Pract.Q.15.</strong> What is the estimate of the effect of Length on RT?</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Pract.A.15.</strong> The estimate for the Length effect is 18.369.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Pract.Q.16.</strong> What does the estimate tell you about how RT varies in relation to word length?</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Pract.A.16.</strong> This tells us that RT increases by about 18ms for each increase in word length by one letter.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Pract.Q.17.</strong> What is the R-squared for the model?</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Pract.A.17.</strong> The R-sq is .01.</p>
</blockquote>
<p>Change the predictor from frequency to something else: you choose.</p>
<blockquote class="blockquote">
<p><strong>Pract.Q.18.</strong> Produce a scatterplot to visualize the relationship between the two variables: does the relationship you see in the plot match the coefficient you see in the model estimates?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-32-contents" aria-controls="callout-32" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-32" class="callout-32-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You need to look at the model summary to do this. Specifically, you need to think about:</p>
<ul>
<li>The coefficients for the effect of the predictor variable you include in your model: focus on the sign and the magnitude of the effect coefficient.</li>
<li>Whether or how that sign and that magnitude do or do not match the slopes you see in the plot.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="practical-task-12-visualize-the-relationship-between-frequency-and-rt-separately-for-each-participant" class="level5">
<h5 class="anchored" data-anchor-id="practical-task-12-visualize-the-relationship-between-frequency-and-rt-separately-for-each-participant">Practical Task 12 – Visualize the relationship between frequency and RT, separately for each participant</h5>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-33-contents" aria-controls="callout-33" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-33" class="callout-33-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You can Use <code>facet_wrap()</code> to do this.</p>
<ul>
<li>We can visualize the frequency effect for each child in a grid of plots, with each plot representing the <span class="math inline">\(\text{RT} \sim \text{frequency}\)</span> relationship for the data for a child (see the lattice or trellis plot, following).</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-34-contents" aria-controls="callout-34" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-34" class="callout-34-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>long.all.noNAs <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Lg.UK.CDcount, <span class="at">y =</span> RT)) <span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">size =</span> <span class="fl">1.25</span>, <span class="at">colour =</span> <span class="st">"red"</span>) <span class="sc">+</span> </span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">"Word frequency (log10 UK SUBTLEX CD count)"</span>) <span class="sc">+</span> </span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span> subjectID)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-freqperchildtrellis" class="quarto-float quarto-figure quarto-figure-center anchored" alt="The figure shows a grid of scatterplots. In each plot, each point represents the lexical frequency (on the x-axis) and the reaction time (RT, on the y-axis) of responses made by children to a set of words. A red line is drawn through the points, indicating that RT decreases for higher values of frequency. A different plot is shown to represent the data for each child. Between plots, we can see that the potential association between RT and frequency can vary.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-freqperchildtrellis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="02-mixed-workbook_files/figure-html/fig-freqperchildtrellis-1.png" class="img-fluid figure-img" alt="The figure shows a grid of scatterplots. In each plot, each point represents the lexical frequency (on the x-axis) and the reaction time (RT, on the y-axis) of responses made by children to a set of words. A red line is drawn through the points, indicating that RT decreases for higher values of frequency. A different plot is shown to represent the data for each child. Between plots, we can see that the potential association between RT and frequency can vary." width="720">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-freqperchildtrellis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: RT vs.&nbsp;word frequency, considered separately for data for each child
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Pract.Q.19.</strong> Can you visualize the relationship between RT and Length, also, separately for each participant?</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-35-contents" aria-controls="callout-35" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-35" class="callout-35-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>long.all.noNAs <span class="sc">%&gt;%</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Length, <span class="at">y =</span> RT)) <span class="sc">+</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">size =</span> <span class="fl">1.25</span>, <span class="at">colour =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> subjectID)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-lengthperchildtrellis" class="quarto-float quarto-figure quarto-figure-center anchored" alt="The figure shows a grid of scatterplots. In each plot, each point represents the word length (on the x-axis) and the reaction time (RT, on the y-axis) of responses made by children to a set of words. A red line is drawn through the points, indicating that RT increases for higher values of length. A different plot is shown to represent the data for each child. Between plots, we can see that the potential association between RT and length can vary.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lengthperchildtrellis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="02-mixed-workbook_files/figure-html/fig-lengthperchildtrellis-1.png" class="img-fluid figure-img" alt="The figure shows a grid of scatterplots. In each plot, each point represents the word length (on the x-axis) and the reaction time (RT, on the y-axis) of responses made by children to a set of words. A red line is drawn through the points, indicating that RT increases for higher values of length. A different plot is shown to represent the data for each child. Between plots, we can see that the potential association between RT and length can vary." width="720">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lengthperchildtrellis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: RT vs.&nbsp;word length, considered separately for data for each child
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Pract.Q.19.</strong> What do you conclude from this plot about the Length effect, and about how the effect varies?</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Pract.A.19.</strong> We can conclude that the length effect is small and really only apparent for some participants.</p>
</blockquote>
</section>
</section>
<section id="practical-part-6-analyze-data-with-lmer" class="level4">
<h4 class="anchored" data-anchor-id="practical-part-6-analyze-data-with-lmer">Practical Part 6: Analyze data with lmer</h4>
<section id="practical-task-13-fit-a-linear-mixed-effects-model-including-the-random-effect-of-participants-on-intercepts-and-on-the-slope-of-the-frequency-effect" class="level5">
<h5 class="anchored" data-anchor-id="practical-task-13-fit-a-linear-mixed-effects-model-including-the-random-effect-of-participants-on-intercepts-and-on-the-slope-of-the-frequency-effect">Practical Task 13 – Fit a linear mixed-effects model, including the random effect of participants on intercepts and on the slope of the frequency effect</h5>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-36-contents" aria-controls="callout-36" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-36" class="callout-36-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You need to specify:</p>
<ul>
<li>the <code>lmer()</code> function;</li>
<li><code>RT</code> as the outcome;</li>
<li>frequency (<code>Lg.UK.CDcount</code>) as the fixed effects predictor;</li>
<li>plus random effects including the effect of participants (<code>subjectID</code>) on intercepts and on the slopes of the frequency effect (<code>Lg.UK.CDcount</code>).</li>
</ul>
<p>Check the chapter code examples if you need help, see also the explanations and examples in <a href="../../../2425/PSYC412/part2/02-mixed.html#ssec-intro-mixed-lmer">chapter: Introduction to linear mixed-effects models</a>.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-37-contents" aria-controls="callout-37" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-37" class="callout-37-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>lmer.all<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">lmer</span>(RT <span class="sc">~</span>  Lg.UK.CDcount <span class="sc">+</span> (Lg.UK.CDcount <span class="sc">+</span> <span class="dv">1</span><span class="sc">||</span>subjectID),</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>             </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> long.all.noNAs)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmer.all<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: RT ~ Lg.UK.CDcount + ((1 | subjectID) + (0 + Lg.UK.CDcount |  
    subjectID))
   Data: long.all.noNAs

REML criterion at convergence: 117805.3

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-3.7839 -0.5568 -0.1659  0.3040 12.4850 

Random effects:
 Groups      Name          Variance Std.Dev.
 subjectID   (Intercept)   87575    295.93  
 subjectID.1 Lg.UK.CDcount  2657     51.55  
 Residual                  23734    154.06  
Number of obs: 9085, groups:  subjectID, 61

Fixed effects:
              Estimate Std. Error t value
(Intercept)    950.913     39.216  24.248
Lg.UK.CDcount  -67.980      7.092  -9.586

Correlation of Fixed Effects:
            (Intr)
Lg.UK.CDcnt -0.093</code></pre>
</div>
</div>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Pract.Q.20.</strong> What are the differences between the <code>lm()</code> and the <code>lmer()</code> model results?</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Pract.A.20.</strong> The differences include:</p>
</blockquote>
<ul>
<li>The estimate for the coefficient of the frequency (Lg.UK.CDcount) effect changes from (lm) -53.375 to (lmer) -67.980.</li>
<li>The (lm) model includes just an estimate of residuals.</li>
<li>The (lmer) model includes estimates of the <code>Residual</code> variance plus the <code>subjectID</code> <code>(Intercept)</code> variance and the <code>subjectID</code> <code>(Lg.UK.CDcount)</code> variance.</li>
</ul>
</section>
<section id="practical-task-14-fit-a-linear-mixed-effects-model-including-the-random-effects-of-participants-on-intercepts-and-on-the-slope-of-the-frequency-effect-as-well-as-the-random-effect-of-items-on-intercepts" class="level5">
<h5 class="anchored" data-anchor-id="practical-task-14-fit-a-linear-mixed-effects-model-including-the-random-effects-of-participants-on-intercepts-and-on-the-slope-of-the-frequency-effect-as-well-as-the-random-effect-of-items-on-intercepts">Practical Task 14 – Fit a linear mixed-effects model, including the random effects of participants on intercepts and on the slope of the frequency effect, as well as the random effect of items on intercepts</h5>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-38-contents" aria-controls="callout-38" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-38" class="callout-38-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>lmer.all.si <span class="ot">&lt;-</span> <span class="fu">lmer</span>(RT <span class="sc">~</span>  Lg.UK.CDcount <span class="sc">+</span> </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>                         (Lg.UK.CDcount <span class="sc">+</span> <span class="dv">1</span><span class="sc">||</span>subjectID) <span class="sc">+</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>                         (<span class="dv">1</span><span class="sc">|</span>item_name),</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>             </span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> long.all.noNAs)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmer.all.si)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: RT ~ Lg.UK.CDcount + ((1 | subjectID) + (0 + Lg.UK.CDcount |  
    subjectID)) + (1 | item_name)
   Data: long.all.noNAs

REML criterion at convergence: 116976.7

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-4.1795 -0.5474 -0.1646  0.3058 12.9485 

Random effects:
 Groups      Name          Variance Std.Dev.
 item_name   (Intercept)     3398    58.29  
 subjectID   Lg.UK.CDcount   3624    60.20  
 subjectID.1 (Intercept)   112331   335.16  
 Residual                   20704   143.89  
Number of obs: 9085, groups:  item_name, 159; subjectID, 61

Fixed effects:
              Estimate Std. Error t value
(Intercept)     971.07      51.87  18.722
Lg.UK.CDcount   -72.33      10.79  -6.703

Correlation of Fixed Effects:
            (Intr)
Lg.UK.CDcnt -0.388</code></pre>
</div>
</div>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Pract.Q.21.</strong> Can you describe the differences between the models with vs.&nbsp;without the item term?</p>
</blockquote>
<ol type="1">
<li>How do the random effects differ?</li>
<li>How do the fixed effects estimates differ?</li>
</ol>
<blockquote class="blockquote">
<p><strong>Pract.A.21.</strong> We can compare models:</p>
</blockquote>
<pre><code>lmer.all.1 &lt;- lmer(RT ~  Lg.UK.CDcount + (Lg.UK.CDcount + 1||subjectID),

                    data = long.all.noNAs)</code></pre>
<pre><code>lmer.all.si &lt;- lmer(RT ~  Lg.UK.CDcount +
                      (Lg.UK.CDcount + 1||subjectID) +
                      (1|item_name),

                    data = long.all.noNAs)</code></pre>
<ol type="1">
<li>The models differ, obviously, in the inclusion of a random term corresponding to the effect of items on intercepts. We can also see that the residual variance is smaller where we include the item random effect.</li>
<li>The estimate for the <code>Lg.UK.CDcount</code> is now -72.33.</li>
</ol>
</section>
<section id="practical-task-15-now-fit-a-mixed-effects-model-for-the-effect-of-length-on-rt.-include-the-random-effects-of-participants-on-intercepts-and-on-the-slope-of-the-length-effect-as-well-as-the-random-effect-of-items-on-intercepts." class="level5">
<h5 class="anchored" data-anchor-id="practical-task-15-now-fit-a-mixed-effects-model-for-the-effect-of-length-on-rt.-include-the-random-effects-of-participants-on-intercepts-and-on-the-slope-of-the-length-effect-as-well-as-the-random-effect-of-items-on-intercepts.">Practical Task 15 – Now fit a mixed-effects model for the effect of Length on RT. Include the random effects of participants on intercepts and on the slope of the length effect, as well as the random effect of items on intercepts.</h5>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-39-contents" aria-controls="callout-39" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-39" class="callout-39-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>lmer.all<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">lmer</span>(RT <span class="sc">~</span>  Length <span class="sc">+</span> </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>                     (Length <span class="sc">+</span> <span class="dv">1</span><span class="sc">||</span>subjectID) <span class="sc">+</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>                     (<span class="dv">1</span><span class="sc">|</span>item_name),</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>                   </span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> long.all.noNAs)</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmer.all<span class="fl">.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: RT ~ Length + ((1 | subjectID) + (0 + Length | subjectID)) +  
    (1 | item_name)
   Data: long.all.noNAs

REML criterion at convergence: 117114.2

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-3.6205 -0.5443 -0.1641  0.3055 12.9620 

Random effects:
 Groups      Name        Variance Std.Dev.
 item_name   (Intercept)  4751.3   68.93  
 subjectID   Length        757.9   27.53  
 subjectID.1 (Intercept)  4994.3   70.67  
 Residual                21440.3  146.43  
Number of obs: 9085, groups:  item_name, 159; subjectID, 61

Fixed effects:
            Estimate Std. Error t value
(Intercept)  572.709     35.034  16.347
Length        28.361      8.534   3.323

Correlation of Fixed Effects:
       (Intr)
Length -0.867</code></pre>
</div>
</div>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Pract.Q.22.</strong> What are the random effects estimates: the variances?</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Pract.A.22.</strong> We see: <code>items/intercepts</code> variance of 4751, <code>subjects/Length</code> of 757, <code>subjects/intercepts</code> of 4994 and <code>residuals</code> of 21440.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Pract.Q.23.</strong> What is the estimate of the effect of length?</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Pract.A.23.</strong> The estimate is 28.361.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Pract.Q.24.</strong> What does the estimate tell you about how RT varies as Length varies?</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Pract.A.24.</strong> That RT increases by about 28ms for unit increase in word length.</p>
</blockquote>
</section>
</section>
<section id="practical-part-7-extension" class="level4">
<h4 class="anchored" data-anchor-id="practical-part-7-extension">Practical Part 7: Extension</h4>
<p>Reproduce the plots in the chapter and slides</p>
<p>This part is optional for you to view and work with.</p>
<ul>
<li>Run the code, and consider the code steps <em>only</em> if you are interested in how the materials for the book chapter were created.</li>
</ul>
<section id="practical-task-15-visualize-the-relationship-between-frequency-and-rt-separately-for-each-participant" class="level5">
<h5 class="anchored" data-anchor-id="practical-task-15-visualize-the-relationship-between-frequency-and-rt-separately-for-each-participant">Practical Task 15 – Visualize the relationship between frequency and RT, separately for each participant</h5>
<p>What we aim to do is:</p>
<ol type="1">
<li>Model the effect of word frequency for each child, for their data considered separately.</li>
<li>Extract the coefficient estimate for the frequency effect for each separate model (per child).</li>
<li>Then plot these estimates, together with</li>
</ol>
<p>Can you figure out how to code these steps?</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-40-contents" aria-controls="callout-40" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-40" class="callout-40-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># -- First fit the model for each child</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>freqperchildlm <span class="ot">&lt;-</span> long.all.noNAs <span class="sc">%&gt;%</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(subjectID) <span class="sc">%&gt;%</span> </span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">do</span>(<span class="fu">tidy</span>(<span class="fu">lm</span>(RT <span class="sc">~</span> Lg.UK.CDcount, <span class="at">data=</span>.)))</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a><span class="co"># -- What does freqperchildlm hold: take a look?</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a><span class="co"># -- Make sure you can treat term as a factor</span></span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>freqperchildlm<span class="sc">$</span>term <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(freqperchildlm<span class="sc">$</span>term)</span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a><span class="co"># -- Get the intercept and frequency effect estimates</span></span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>freqperchildlmint <span class="ot">&lt;-</span> <span class="fu">filter</span>(freqperchildlm, term <span class="sc">==</span> <span class="st">'(Intercept)'</span>)</span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a>freqperchildlmfreq <span class="ot">&lt;-</span> <span class="fu">filter</span>(freqperchildlm, term <span class="sc">==</span> <span class="st">'Lg.UK.CDcount'</span>)</span>
<span id="cb45-14"><a href="#cb45-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-15"><a href="#cb45-15" aria-hidden="true" tabindex="-1"></a><span class="co"># -- Make the intercepts plots: order by size</span></span>
<span id="cb45-16"><a href="#cb45-16" aria-hidden="true" tabindex="-1"></a>pfreqperchildlmint <span class="ot">&lt;-</span> freqperchildlmint <span class="sc">%&gt;%</span></span>
<span id="cb45-17"><a href="#cb45-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_reorder</span>(subjectID, estimate), <span class="at">y =</span> estimate, <span class="at">ymin =</span> estimate <span class="sc">-</span> std.error, <span class="at">ymax =</span> estimate <span class="sc">+</span> std.error)) <span class="sc">+</span> </span>
<span id="cb45-18"><a href="#cb45-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_linerange</span>() <span class="sc">+</span> </span>
<span id="cb45-19"><a href="#cb45-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb45-20"><a href="#cb45-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Intercepts in order of size"</span>) <span class="sc">+</span></span>
<span id="cb45-21"><a href="#cb45-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Estimated intercept +/- SE"</span>) <span class="sc">+</span> </span>
<span id="cb45-22"><a href="#cb45-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>), </span>
<span id="cb45-23"><a href="#cb45-23" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">5</span>), </span>
<span id="cb45-24"><a href="#cb45-24" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_blank</span>(), </span>
<span id="cb45-25"><a href="#cb45-25" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid =</span> <span class="fu">element_blank</span>())</span>
<span id="cb45-26"><a href="#cb45-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-27"><a href="#cb45-27" aria-hidden="true" tabindex="-1"></a><span class="co"># -- Make the slopes plots: order by size</span></span>
<span id="cb45-28"><a href="#cb45-28" aria-hidden="true" tabindex="-1"></a>pfreqperchildlmfreq <span class="ot">&lt;-</span> freqperchildlmfreq <span class="sc">%&gt;%</span></span>
<span id="cb45-29"><a href="#cb45-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_reorder</span>(subjectID, estimate), <span class="at">y =</span> estimate, <span class="at">ymin =</span> estimate <span class="sc">-</span> std.error, <span class="at">ymax =</span> estimate <span class="sc">+</span> std.error)) <span class="sc">+</span> </span>
<span id="cb45-30"><a href="#cb45-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_linerange</span>() <span class="sc">+</span> </span>
<span id="cb45-31"><a href="#cb45-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb45-32"><a href="#cb45-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Frequency effect coefficient in order of size"</span>) <span class="sc">+</span></span>
<span id="cb45-33"><a href="#cb45-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Estimated coefficient for the frequency effect +/- SE"</span>) <span class="sc">+</span> </span>
<span id="cb45-34"><a href="#cb45-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>), </span>
<span id="cb45-35"><a href="#cb45-35" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">5</span>), </span>
<span id="cb45-36"><a href="#cb45-36" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_blank</span>(), </span>
<span id="cb45-37"><a href="#cb45-37" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid =</span> <span class="fu">element_blank</span>())</span>
<span id="cb45-38"><a href="#cb45-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-39"><a href="#cb45-39" aria-hidden="true" tabindex="-1"></a><span class="co"># -- Make a grid to show the plots side by side: in 2 columns</span></span>
<span id="cb45-40"><a href="#cb45-40" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(pfreqperchildlmint, pfreqperchildlmfreq,</span>
<span id="cb45-41"><a href="#cb45-41" aria-hidden="true" tabindex="-1"></a>             <span class="at">ncol =</span> <span class="dv">2</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-mixed-workbook_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="practical-task-16-take-the-linear-mixed-effects-model-and-plot-the-model-predicted-differences-in-intercepts-or-slopes" class="level5">
<h5 class="anchored" data-anchor-id="practical-task-16-take-the-linear-mixed-effects-model-and-plot-the-model-predicted-differences-in-intercepts-or-slopes">Practical Task 16 – Take the linear mixed-effects model, and plot the model predicted differences in intercepts or slopes</h5>
<p>What we aim to do is:</p>
<ol type="1">
<li>Model the effect of word frequency for all the children, including random effects terms to take into account random differences between children in intercepts or in slopes.</li>
<li>Get the random effects estimates – the between-children differences – and plot them.</li>
</ol>
<p>Can you figure out how to code these steps?</p>
<p>First, fit the model.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-41-contents" aria-controls="callout-41" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-41" class="callout-41-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>lmer.all<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">lmer</span>(RT <span class="sc">~</span>  Lg.UK.CDcount <span class="sc">+</span> (Lg.UK.CDcount <span class="sc">+</span> <span class="dv">1</span><span class="sc">||</span>subjectID),</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>                   </span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> long.all.noNAs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p>Second, extract the random effects and plot them.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-42-contents" aria-controls="callout-42" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-42" class="callout-42-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Plot the distribution of random effects – usually called conditional modes.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-43-contents" aria-controls="callout-43" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-43" class="callout-43-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>BLUPS <span class="ot">&lt;-</span> <span class="fu">ranef</span>(lmer.all<span class="fl">.1</span>)<span class="sc">$</span>subjectID</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="co"># summary(BLUPS)</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>BLUPS.df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">subjectID =</span> <span class="fu">rownames</span>(BLUPS), </span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">intercepts =</span> BLUPS[,<span class="dv">1</span>], </span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>                       <span class="at">frequency =</span> BLUPS[,<span class="dv">2</span>])</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a><span class="co"># summary(BLUPS.df)</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a><span class="co"># str(BLUPS.df)</span></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>p.BLUPS.intercepts <span class="ot">&lt;-</span> BLUPS.df <span class="sc">%&gt;%</span></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> intercepts)) <span class="sc">+</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span> </span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"(a.) Adjustment by child"</span>) <span class="sc">+</span></span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"In the intercept"</span>) <span class="sc">+</span></span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">colour =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a>p.BLUPS.slopes <span class="ot">&lt;-</span> BLUPS.df <span class="sc">%&gt;%</span></span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> frequency)) <span class="sc">+</span></span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span> </span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"(b.) Adjustment by child"</span>) <span class="sc">+</span></span>
<span id="cb47-22"><a href="#cb47-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"In the frequency slope (coefficient)"</span>) <span class="sc">+</span></span>
<span id="cb47-23"><a href="#cb47-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">colour =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb47-24"><a href="#cb47-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb47-25"><a href="#cb47-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-26"><a href="#cb47-26" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p.BLUPS.intercepts, p.BLUPS.slopes,</span>
<span id="cb47-27"><a href="#cb47-27" aria-hidden="true" tabindex="-1"></a>             <span class="at">ncol =</span> <span class="dv">2</span></span>
<span id="cb47-28"><a href="#cb47-28" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-mixed-workbook_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="practical-task-17-fit-different-kinds-of-mixed-effects-model-then-plot-the-resulting-differences-in-model-predictions" class="level5">
<h5 class="anchored" data-anchor-id="practical-task-17-fit-different-kinds-of-mixed-effects-model-then-plot-the-resulting-differences-in-model-predictions">Practical Task 17 – Fit different kinds of mixed-effects model, then plot the resulting differences in model predictions</h5>
<p>What we aim to do is:</p>
<ol type="1">
<li>Model the effect of word frequency for all the children, including (in different models) different random effects terms to take into account (in different ways) random differences between children in intercepts or in slopes.</li>
<li>Get the random effects estimates – the between-children differences – and plot the model predictions.</li>
</ol>
<p>Can you figure out how to code these steps?</p>
<p>First, fit the models. We want to compare models with:</p>
<ol type="1">
<li>Random effects of participants on intercepts and on slopes.</li>
<li>Random effects of participants on intercepts.</li>
<li>Random effects of participants on slopes.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-44-contents" aria-controls="callout-44" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-44" class="callout-44-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># -- Fit different kinds of mixed-effects model, then plot the resulting differences in model predictions</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>lmer.all<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">lmer</span>(RT <span class="sc">~</span>  Lg.UK.CDcount <span class="sc">+</span> (Lg.UK.CDcount <span class="sc">+</span> <span class="dv">1</span><span class="sc">||</span>subjectID),</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>                   </span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> long.all.noNAs)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="co"># summary(lmer.all.1)</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>lmer.all<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">lmer</span>(RT <span class="sc">~</span>  Lg.UK.CDcount <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>subjectID),</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>                   </span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> long.all.noNAs)</span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a><span class="co"># summary(lmer.all.2)</span></span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a>lmer.all<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">lmer</span>(RT <span class="sc">~</span>  Lg.UK.CDcount <span class="sc">+</span> (Lg.UK.CDcount <span class="sc">+</span> <span class="dv">0</span><span class="sc">|</span>subjectID),</span>
<span id="cb49-16"><a href="#cb49-16" aria-hidden="true" tabindex="-1"></a>                   </span>
<span id="cb49-17"><a href="#cb49-17" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> long.all.noNAs)</span>
<span id="cb49-18"><a href="#cb49-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-19"><a href="#cb49-19" aria-hidden="true" tabindex="-1"></a><span class="co"># summary(lmer.all.3)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p>Then derive predictions of the change in outcome, given variation in predictor values, assuming different random effects structures.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-45-contents" aria-controls="callout-45" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-45" class="callout-45-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Plot random effect – per person predictions – following:</p>
<p><a href="https://bbolker.github.io/morelia_2018/notes/mixedlab.html" class="uri">https://bbolker.github.io/morelia_2018/notes/mixedlab.html</a></p>
<p>In lmer, predict has a <code>re.form</code> argument that specifies which random effects should be included (NA or ~0=none, population level; NULL (=all) or ~subject=prediction at the subject level; more complex models, might have additional nested levels).</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-46-contents" aria-controls="callout-46" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-46" class="callout-46-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># -- get predictions</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>long.all.noNAs<span class="sc">$</span>pred1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(lmer.all<span class="fl">.1</span>) <span class="do">## individual level</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>long.all.noNAs<span class="sc">$</span>pred2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(lmer.all<span class="fl">.2</span>) <span class="do">## individual level</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>long.all.noNAs<span class="sc">$</span>pred3 <span class="ot">&lt;-</span> <span class="fu">predict</span>(lmer.all<span class="fl">.3</span>) <span class="do">## individual level</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a><span class="co"># -- show predictions as slopes on top of raw data</span></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>p.slopes.intercepts <span class="ot">&lt;-</span> long.all.noNAs <span class="sc">%&gt;%</span></span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Lg.UK.CDcount, <span class="at">y =</span> RT)) <span class="sc">+</span></span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">25</span>, <span class="at">colour =</span> <span class="st">"darkgrey"</span>) <span class="sc">+</span></span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> pred1, <span class="at">group =</span> subjectID), <span class="at">colour=</span><span class="st">"red"</span>, <span class="at">alpha =</span> .<span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"(c.)</span><span class="sc">\n</span><span class="st">(Lg.UK.CDcount + 1||subjectID)"</span>) <span class="sc">+</span></span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Frequency (Lg.UK.CDcount)"</span>) <span class="sc">+</span></span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>,<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb50-16"><a href="#cb50-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb50-17"><a href="#cb50-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-18"><a href="#cb50-18" aria-hidden="true" tabindex="-1"></a>p.intercepts <span class="ot">&lt;-</span> long.all.noNAs <span class="sc">%&gt;%</span></span>
<span id="cb50-19"><a href="#cb50-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Lg.UK.CDcount, <span class="at">y =</span> RT)) <span class="sc">+</span></span>
<span id="cb50-20"><a href="#cb50-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">25</span>, <span class="at">colour =</span> <span class="st">"darkgrey"</span>) <span class="sc">+</span></span>
<span id="cb50-21"><a href="#cb50-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> pred2, <span class="at">group =</span> subjectID), <span class="at">colour=</span><span class="st">"red"</span>, <span class="at">alpha =</span> .<span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb50-22"><a href="#cb50-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"(a.)</span><span class="sc">\n</span><span class="st">(1|subjectID)"</span>) <span class="sc">+</span></span>
<span id="cb50-23"><a href="#cb50-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Frequency (Lg.UK.CDcount)"</span>) <span class="sc">+</span></span>
<span id="cb50-24"><a href="#cb50-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>,<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb50-25"><a href="#cb50-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb50-26"><a href="#cb50-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-27"><a href="#cb50-27" aria-hidden="true" tabindex="-1"></a>p.slopes <span class="ot">&lt;-</span> long.all.noNAs <span class="sc">%&gt;%</span></span>
<span id="cb50-28"><a href="#cb50-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Lg.UK.CDcount, <span class="at">y =</span> RT)) <span class="sc">+</span></span>
<span id="cb50-29"><a href="#cb50-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">25</span>, <span class="at">colour =</span> <span class="st">"darkgrey"</span>) <span class="sc">+</span></span>
<span id="cb50-30"><a href="#cb50-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> pred3, <span class="at">group =</span> subjectID), <span class="at">colour=</span><span class="st">"red"</span>, <span class="at">alpha =</span> .<span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb50-31"><a href="#cb50-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"(b.)</span><span class="sc">\n</span><span class="st">(Lg.UK.CDcount + 0|subjectID)"</span>) <span class="sc">+</span></span>
<span id="cb50-32"><a href="#cb50-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Frequency (Lg.UK.CDcount)"</span>) <span class="sc">+</span></span>
<span id="cb50-33"><a href="#cb50-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>,<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb50-34"><a href="#cb50-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb50-35"><a href="#cb50-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-36"><a href="#cb50-36" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p.intercepts, p.slopes, p.slopes.intercepts, </span>
<span id="cb50-37"><a href="#cb50-37" aria-hidden="true" tabindex="-1"></a>             <span class="at">ncol =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-mixed-workbook_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="practical-task-18-visualize-the-variation-between-items-in-intercepts-for-each-itemname-plots-ordered-by-meanrt" class="level5">
<h5 class="anchored" data-anchor-id="practical-task-18-visualize-the-variation-between-items-in-intercepts-for-each-itemname-plots-ordered-by-meanrt">Practical Task 18 – Visualize the variation between items in intercepts – for each <code>itemname</code>, plots ordered by <code>meanRT</code></h5>
<p>What we aim to do is:</p>
<ol type="1">
<li>Create a model for each item, including just the intercept.</li>
<li>Plot intercepts by-items – ordering items by item_name by estimated intercept size.</li>
</ol>
<p>Can you figure out how to code these steps?</p>
<p>First, create a model for each item, including just the intercept.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-47-contents" aria-controls="callout-47" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-47" class="callout-47-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>wperitemlm <span class="ot">&lt;-</span> long.all.noNAs <span class="sc">%&gt;%</span> </span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(item_name) <span class="sc">%&gt;%</span> </span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">do</span>(<span class="fu">tidy</span>(<span class="fu">lm</span>(RT <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data=</span>.)))</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>wperitemlm<span class="sc">$</span>term <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(wperitemlm<span class="sc">$</span>term)</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a><span class="co"># wperitemlm</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p>Then plot intercepts by-items – ordering items by item_name by estimated intercept size.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-48-contents" aria-controls="callout-48" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-48" class="callout-48-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>pwperitemlmint <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(wperitemlm, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_reorder</span>(item_name, estimate), <span class="at">y =</span> estimate, <span class="at">ymin =</span> estimate <span class="sc">-</span> std.error, <span class="at">ymax =</span> estimate <span class="sc">+</span> std.error))</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>pwperitemlmint <span class="sc">+</span> </span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_linerange</span>() <span class="sc">+</span> </span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Estimated coefficient +/- SE"</span>) <span class="sc">+</span> </span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Per-item estimates of intercept, ordered by intercept estimate size"</span>) <span class="sc">+</span></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>), </span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">5</span>), </span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_blank</span>(), <span class="at">panel.grid =</span> <span class="fu">element_blank</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="02-mixed-workbook_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="the-answers" class="level3">
<h3 class="anchored" data-anchor-id="the-answers">The answers</h3>
<p>After the practical class, we will reveal the answers that are currently hidden.</p>
<p>The answers version of the webpage will present my answers for questions, and some extra information where that is helpful.</p>


</section>
</section>
</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Website developed by Matthew Ivory</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>