{
  "hash": "3053ef51d8a7750be7a273691731adbe",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Week 4. Testing nominal data\nsubtitle: Written by Padraic Monaghan\norder: 5\n\n---\n\n\n\n\n## 4.1 Overview\n\nThis week, there are three mini lectures, and the practical workbook working with R-studio.\n\nBefore the practical on Tuesday, please try to work through the practical workbook in your group.\n\nBring your questions (and/or answers) to the practical.\n\n## 4.2 Learning Goals\n\n* Understand the value of conducting statistical tests and interpreting p-values\n\n* Understand null effects and null hypotheses\n\n* Understand the difference between parametric and non-parametric data\n\n* Understand when to apply the Chi-squared test\n\n* Understand the relation between Cramer’s V test and the Chi-squared test\n\n* Be able to apply the Chi-squared test to data and interpret the result\n\n* Be able to apply Cramer’s V test to data\n\n\n## 4.3 Lectures and slides\n\n### 4.3.1 Lectures\n\nWatch Lecture week 4 part 1:\n\n\n\n```{=html}\n<iframe src=\"https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=395fabc3-a8c7-4257-ba22-adce00ba6806&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all\" height=\"405\" width=\"720\" style=\"border: 1px solid #464646;\" allowfullscreen allow=\"autoplay\" aria-label=\"Panopto Embedded Video Player\" aria-description=\"psyc411_2024_w4_p1\" ></iframe>\n```\n\n\n\nWatch Lecture week 4 part 2:\n\n\n\n```{=html}\n<iframe src=\"https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=de7f2f84-3b15-4048-bf60-adce00befd8e&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all\" height=\"405\" width=\"720\" style=\"border: 1px solid #464646;\" allowfullscreen allow=\"autoplay\" aria-label=\"Panopto Embedded Video Player\" aria-description=\"psyc411_2024_w4_p2\" ></iframe>\n```\n\n\n\nWatch Lecture week 4 part 3:\n\n\n\n```{=html}\n<iframe src=\"https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=6276260f-a698-4ecc-a0f6-b09d00dcfde4&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=false&interactivity=all\" height=\"405\" width=\"720\" style=\"border: 1px solid #464646;\" allowfullscreen allow=\"autoplay\" aria-label=\"Panopto Embedded Video Player\" aria-description=\"psyc411 2024 w4 p3\" ></iframe>\n```\n\n\n\n\nTake the [quiz](https://modules.lancaster.ac.uk/mod/quiz/view.php?id=2530056){target=\"_blank\"} (not assessed) on the lecture materials.\n\n### 4.3.2 Slides\n\nDownload the lecture slides for:\n\n- [part 1](ppt/wk4/PSYC411 Lecture week4 part1 handout.pptx)\n\n- [part 2](ppt/wk4/PSYC411 Lecture week4 part2 handout.pptx)\n\n- [part 3](ppt/wk4/PSYC411 Lecture week4 part3 handout.pptx)\n\n\n\n## 4.4 Practical Materials\n\n### 4.4.1 Workbook\n\nThe materials in this workbook share some material with [Glasgow University Psychology Department Teaching in R website](https://psyteachr.github.io/quant-fun-v2)\n\nIn your group, work through this workbook, note any problems and questions you have, and come prepared to the online practical class to go through the tasks and ask your questions.\n\n#### 4.4.1.1 Part 1: Revision for last week\n\n##### Task 1: Your data from the paper in Psychological Science\n\n1. Your take-home task was to produce some graphs of the data set downloaded from a paper in Psychological Science. Show your graphs and R script to the rest of your group.\n\n#### 4.4.1.2 Part 2: Load in the Vocabulary Scores Data and Produce Graphs\n\n##### Task 2: Load in the Data\n\n2.  Remember to clear out R first and load the tidyverse library:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list=ls())\nlibrary(tidyverse)\n```\n:::\n\n\n\nThe data set on the Shipley and Gent vocabulary scores is now updated with the data from your group, so it now contains *eight* years of PSYC411 students' data. I've omitted Age as this might impact anonymity of the data. Download the data from here: [PSYC411-shipley-scores-anonymous-17_24.csv](data/wk4/PSYC411-shipley-scores-anonymous-17_24.csv) and read the data into an object in R studio called `vdat` (for vocabulary data).\n\n::: {.callout-warning icon=false collapse=\"false\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.0     ✔ readr     2.1.6\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.2     ✔ tibble    3.3.1\n✔ lubridate 1.9.4     ✔ tidyr     1.3.2\n✔ purrr     1.2.1     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nvdat <- read_csv(\"data/wk4/PSYC411-shipley-scores-anonymous-17_24.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 270 Columns: 8\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (2): english_status, Gender\ndbl (6): subject_ID, Age, Shipley_Voc_Score, Gent_1_score, Gent_2_score, aca...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n:::\n\n\n3. As a reminder, when we want to look at a particular variable (a column) in an object in R studio, we refer to it using the `$` notation. So, for the object vdat and the variable academic_year you would refer to it as `vdat$academic_year`. For this data set, we need to change academic year to be a nominal (factor) variable. Why are we setting academic year to be nominal and not interval/ratio?:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvdat$academic_year <- as.factor(vdat$academic_year)\n\nview(vdat) #view the data\n```\n:::\n\n\n\n::: {.callout-warning icon=false collapse=\"false\"}\n## Answer\nIt has to be nominal unless we have a hypothesis about the order of years of groups being important to the data. But that is very unlikely to have an effect (though you could look up the \"Flynn Effect\" in case you wanted to generate one...). But for now we want each year to be treated independently, rather than in order, in our analysis.\n:::\n\n\n4.  Make sure the tidyverse library is loaded. Select all the variables apart from Age and save as a new object called \"summaryvdat\". We will omit these variables because they are not complete for the dataset.\n\n::: {.callout-warning icon=\"false\" collapse=\"false\"}\n## Hint\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# there are two ways to do this, either list the variables you are omitting with a `-c(variables,variables,...)` command:\nsummaryvdat <- select(vdat, -c(Age))\n\n# or list the variables we do want to include:\nsummaryvdat <- select(vdat, subject_ID, english_status, Gender, Shipley_Voc_Score, Gent_1_score, Gent_2_score, academic_year)\n```\n:::\n\n\n:::\n\n\n5. Arrange the data according to Gent_2_score, from highest to lowest. Save this as a new object called \"summaryvdat_sort\"\n\n::: {.callout-warning icon=false collapse=\"false\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummaryvdat_sort <- arrange(summaryvdat, desc(Gent_2_score))\n```\n:::\n\n\n:::\n\n##### Task 3: Draw Graphs of the Vocabulary Data\n\n6. Draw graphs of the following relations:\n* English status and academic year\n* Gender and academic year\n* Vocabulary score and academic year\n\n::: {.callout-warning icon=false collapse=\"false\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(summaryvdat, aes(x = academic_year, fill = english_status)) + \n  geom_bar(position = \"dodge\")\n```\n\n::: {.cell-output-display}\n![](Week4_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(summaryvdat, aes(x = academic_year, fill = Gender)) + \n  geom_bar(position = \"dodge\")\n```\n\n::: {.cell-output-display}\n![](Week4_files/figure-html/unnamed-chunk-6-2.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(summaryvdat, aes(x = academic_year, y = Gent_1_score)) + \n  geom_boxplot()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 5 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Week4_files/figure-html/unnamed-chunk-6-3.png){width=672}\n:::\n:::\n\n\n:::\n\n7. Save your script file.\n\n#### 4.4.1.3 Part 3: Grouping data in R studio\n\n##### Task 4: Loading and joining data in R studio \n\n8. Now, let's clear out R-studio before we get started again using `rm(list=ls())`.\n\n9. Go to the data files from week 2 and load them into Rstudio again (\"ahicesd.csv\", and \"participantinfo.csv\"). If you need to download these again, you can get them here:  [ahicesd.csv](data/wk2/ahicesd.csv), [participantinfo.csv](data/wk2/participantinfo.csv).\n\n- Remember these data come from this study: Woodworth, R.J., O'Brien-Malone, A., Diamond, M.R. and Schuz, B. (2018). Data from, \"Web-based Positive Psychology Interventions: A Reexamination of Effectiveness\". Journal of Open Psychology Data, 6(1).\n- Remind yourself of the aim of the study and the variables that are in the data set (see end of this script file for repeat description on the study).\n\n10. Next, load and join the ahicesd.csv and participantinfo.csv data in R studio. Call the joined data set \"all_dat\" (see week 2 workbook for reminders about this)\n\n::: {.callout-warning icon=false collapse=\"false\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- read_csv(\"data/wk2/ahicesd.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 992 Columns: 50\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\ndbl (50): id, occasion, elapsed.days, intervention, ahi01, ahi02, ahi03, ahi...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\npinfo <- read_csv(\"data/wk2/participantinfo.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 295 Columns: 6\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\ndbl (6): id, intervention, sex, age, educ, income\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nall_dat <- inner_join(x = dat, y = pinfo, by = c(\"id\", \"intervention\"))\n```\n:::\n\n\n:::\n\n##### Task 5: Selecting and manipulating data\n\n11. We're not interested in the individual questionnaire items. So, let's select all the variables we want to keep (omitting the individual questionnaire items), and save this to an object called summary_all_dat (again see week 2 workbook for reminder)\n\n12. Next, we will add another variable to the data. We use the function `mutate()` for this. Let's scale the ahiTotal and cesdTotal values and add them to the summary_all_dat set.\n\n\n- What are the minimum and maximum values of the new variable ahiTotalscale?\n\n- What do these scale values mean? (reminder: they are Z scores).\n\n::: {.callout-warning icon=\"false\" collapse=\"false\"}\n## Hint\nhint: use the `arrange()` function, or the `min()` and `max()` functions.\n:::\n\n::: {.callout-warning icon=false collapse=\"false\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary_all_dat <- select(all_dat, c(\"id\", \"occasion\", \"intervention\", \"ahiTotal\",\"cesdTotal\",\"sex\", \"age\", \"educ\", \"income\"))\nsummary_all_dat_scale <- mutate(summary_all_dat, ahiTotalscale = scale(ahiTotal),\n                                cesdTotalscale = scale(cesdTotal))\nsummarise(summary_all_dat_scale, min(ahiTotalscale), max(ahiTotalscale))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  `min(ahiTotalscale)` `max(ahiTotalscale)`\n                 <dbl>                <dbl>\n1                -2.87                 2.90\n```\n\n\n:::\n:::\n\n\nThe values are z-scores so the numbers indicate how many standard deviations the values are from the mean\n:::\n\n13. The next way we will work with the data is to organise the observations into different groups.  We will use the function summarise(). So, instead of `mean(summary_all_dat_scale$ahiTotal)` you can use this, which turns out to be a much more powerful way of looking at the data:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummarise(summary_all_dat_scale, mean(ahiTotal))\n```\n:::\n\n\n\n- They should give the same results - check that they do. This function `summarise()` is more powerful because you can look at several values at the same time, e.g.:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummarise(summary_all_dat_scale, mean(ahiTotal), sd(ahiTotal), mean(cesdTotal), sd(cesdTotal))\n```\n:::\n\n\n\n- What is the result of this command?\n\n::: {.callout-warning icon=false collapse=\"false\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummarise(summary_all_dat_scale, mean(ahiTotal), sd(ahiTotal), \n          mean(cesdTotal), sd(cesdTotal))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  `mean(ahiTotal)` `sd(ahiTotal)` `mean(cesdTotal)` `sd(cesdTotal)`\n             <dbl>          <dbl>             <dbl>           <dbl>\n1             72.8           14.2              13.1            11.7\n```\n\n\n:::\n:::\n\n\n:::\n\n\n14. But now let's think about what kind of patterns we'd like to investigate in the data. There are four interventions conducted in this study. Let's look at each of these interventions and their effect of ahiTotal and cesdTotal. \n\nWe can look at subgroups of data either by using the `filter()` function, or by using the function `group_by()`. The advantage of `group_by()` is that we can look at several groups at the same time, rather than dividing up the data file into pieces. Let's organise by the different interventions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary_all_dat_scale_intervention <- group_by(summary_all_dat_scale, intervention)\n```\n:::\n\n\n\n- This command takes the data summary_all_dat_scale, and then groups it according to the four interventions in the data. We can't yet see any difference in summary_all_dat_scale_intervention but it's in there, lurking, just waiting. \n\nNow, we can look at the means for each intervention using the summarise function again. Run the `summarise` function on summarydata_scale_intervention. What happens?\n\n::: {.callout-warning icon=false collapse=\"false\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummarise(summary_all_dat_scale, mean(ahiTotal), sd(ahiTotal), \n          mean(cesdTotal), sd(cesdTotal))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  `mean(ahiTotal)` `sd(ahiTotal)` `mean(cesdTotal)` `sd(cesdTotal)`\n             <dbl>          <dbl>             <dbl>           <dbl>\n1             72.8           14.2              13.1            11.7\n```\n\n\n:::\n:::\n\n\nIt separates out the means and SDs by the group_by condition - i.e, by intervention.\n:::\n\n\n15. You can also group by several factors at the same time. We can group by intervention and get means and standard deviations, but that is not going to give us a huge amount of insight into how the interventions affect the happiness measure because we are combining the mean of ahiTotal across all occasions of testing, including testing before the intervention has been applied.\n\nSo, let's group by intervention and occasion of testing:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary_all_dat_intocc <- group_by(summary_all_dat_scale, intervention, occasion)\n```\n:::\n\n\n\n- Now produce the means and standard deviations of the happiness score (ahiTotal) for each intervention at each testing occasion. \n\n::: {.callout-warning icon=false collapse=\"false\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary_all_dat_intocc <- group_by(summary_all_dat_scale, intervention, occasion)\nsummarise(summary_all_dat_intocc, mean(ahiTotal), sd(ahiTotal))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`summarise()` has regrouped the output.\nℹ Summaries were computed grouped by intervention and occasion.\nℹ Output is grouped by intervention.\nℹ Use `summarise(.groups = \"drop_last\")` to silence this message.\nℹ Use `summarise(.by = c(intervention, occasion))` for per-operation grouping\n  (`?dplyr::dplyr_by`) instead.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 24 × 4\n# Groups:   intervention [4]\n   intervention occasion `mean(ahiTotal)` `sd(ahiTotal)`\n          <dbl>    <dbl>            <dbl>          <dbl>\n 1            1        0             68.4           14.0\n 2            1        1             69.5           13.4\n 3            1        2             70.3           15.7\n 4            1        3             75.0           12.8\n 5            1        4             76.5           16.2\n 6            1        5             75.5           14.5\n 7            2        0             68.8           13.0\n 8            2        1             71.6           12.5\n 9            2        2             73.0           14.0\n10            2        3             72.5           14.2\n# ℹ 14 more rows\n```\n\n\n:::\n:::\n\n\n:::\n\n\n16. This doesn't print all the lines out, so you can make a new object (e.g., called sum_output) and view that, or you can filter out some of the lines so we only look at the first and second occasion of testing.\n\n::: {.callout-warning icon=false collapse=\"false\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum_output <- summarise(summary_all_dat_intocc, mean(ahiTotal), sd(ahiTotal))\nView(sum_output)\n```\n:::\n\n\n:::\n\n#### 4.4.1.4 Part 4: Graphing groups\n\n##### Task 6: Graph some groups\n\n17. Draw a scatter plot of ahiTotal and cesdTotal values for the whole data set.\n\n::: {.callout-warning icon=\"false\" collapse=\"false\"}\n## Hint\nUse the `ggplot()` function with `geom_point() `\n\nAnd make it a bit more beautiful using the labs() addition.\n::: \n\n\n::: {.callout-warning icon=false collapse=\"false\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(summary_all_dat, aes(x = ahiTotal, y = cesdTotal)) + \n  geom_point() + \n  labs(title = \"Happiness and Depression Scores\", \n       x = \"Happiness Score\", \n       y = \"Depression Score\")\n```\n\n::: {.cell-output-display}\n![](Week4_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n:::\n\n\n18. Now redraw the plot, but colour the points according to whether they are first, second, third, etc occasion of testing. Add in `col = \"occasion\"` into the `aes()` part of the geom_point function, so that this part looks like this:  `aes(x = ahiTotal, y = cesdTotal, col = occasion)`\n\n::: {.callout-warning icon=false collapse=\"false\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(summary_all_dat, aes(x = ahiTotal, y = cesdTotal, col = occasion)) + \n  geom_point() + \n  labs(title = \"Happiness and Depression Scores\", \n       x = \"Happiness Score\", \n       y = \"Depression Score\")\n```\n\n::: {.cell-output-display}\n![](Week4_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n:::\n\n#### 4.4.1.5 Part 5: Working out whether nominal data is random or structured: Repeating the analyses from Lecture week4 part3\n\n#####  Task 7: Chi-squared and Cramer's V\n\n19. Let's now have a look at running Chi-squared and Cramer's V tests in R. Download the [titanic data](data/wk4/titanic.csv). \n\nRead the titanic.csv into an object called \"titanic\". \n\nView the data. It should correspond to the data in the overhead slides.\n\n20. Make a bar graph to count the numbers of survived and died by class.\n\n::: {.callout-warning icon=false collapse=\"false\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntitanic <- read_csv(\"data/wk4/titanic.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNew names:\nRows: 1309 Columns: 3\n── Column specification\n──────────────────────────────────────────────────────── Delimiter: \",\" chr\n(2): class, survival dbl (1): ...1\nℹ Use `spec()` to retrieve the full column specification for this data. ℹ\nSpecify the column types or set `show_col_types = FALSE` to quiet this message.\n• `` -> `...1`\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(titanic, aes(x = class, fill = survival)) + \n  geom_bar( position = \"dodge\")\n```\n\n::: {.cell-output-display}\n![](Week4_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n:::\n\n\n21. Now let's see if there is a significant relation between class and survival using Chi-squared: \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq.test(x = titanic$class, y = titanic$survival)\n```\n:::\n\n\n\n- The results give the chi-squared value, the number of degrees of freedom, and the p-value. P = 2.2e-16 means p = .0000000000000022. That's highly significant. That means the observations are divided across the categories in a way that is very unlikely to be due to chance (for this number (P = 2.2e-16), it means there's a 2 in a quadrillion chance that titanic survival was not related to class). \n\nIn a report, you would write: \n\nChi-squared(2, N= 1309) = 127.86, p < .001.\n\n22. To understand where the significant effect comes from, we need to look at where in our table of counts there is a big discrepancy between the expected frequency and the actual frequency. We can do this by analysing the \"standardised residuals\" of the chi-squared test.\n\nRepeat the chi-squared test on the titanic data set, and save the result of the test into a new object called \"titanic_chisq_result\".\n\nThen, look at the standardised residuals that are saved in the test results - the standardised residuals are saved in a variable called `stdres`.\n\n::: {.callout-warning icon=false collapse=\"false\"}\n## Hint\nHere is how you do it\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntitanic_chisq_result <- chisq.test(x = titanic$class, y = titanic$survival)\ntitanic_chisq_result$stdres\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             titanic$survival\ntitanic$class       died   survived\n       first  -10.110480  10.110480\n       second  -1.837589   1.837589\n       third   10.254442 -10.254442\n```\n\n\n:::\n:::\n\n\n:::\n\nNegative values indicate that actual counts are lower than expected, positive values indicate that actual counts are higher than expected. The standardised residuals indicate that there are fewer first class and more third class than expected that died, second class died at a level close to that expected from the overall numbers of deaths.\n\n23. Now, let's compute Cramer's V. First, we need to make sure we have the library lsr loaded in.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lsr)\n```\n:::\n\n\n\n- Then run the test:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncramersV(x = titanic$class, y = titanic$survival)\n```\n:::\n\n\n\n24. Your next task is to run some Chi-squared and Cramer's V tests on some of the other nominal data. Open the data \"PSYC411-shipley-scores-anonymous-17_24.csv\" again. Investigate the association between gender and year (are there different distributions of males and females in each of our masters' year cohorts) using Chi-squared and Cramer's V. Is it significant? \n\n::: {.callout-warning icon=false collapse=\"false\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lsr)\nvdat <- read_csv(\"data/wk4/PSYC411-shipley-scores-anonymous-17_24.csv\"); \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 270 Columns: 8\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (2): english_status, Gender\ndbl (6): subject_ID, Age, Shipley_Voc_Score, Gent_1_score, Gent_2_score, aca...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nvdat$academic_year <- as.factor(vdat$academic_year)\n\nchisq.test( x = vdat$Gender, vdat$academic_year)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in chisq.test(x = vdat$Gender, vdat$academic_year): Chi-squared\napproximation may be incorrect\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  vdat$Gender and vdat$academic_year\nX-squared = 11.79, df = 14, p-value = 0.6232\n```\n\n\n:::\n\n```{.r .cell-code}\ncramersV( x = vdat$Gender, vdat$academic_year)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in stats::chisq.test(..., correct = FALSE): Chi-squared approximation\nmay be incorrect\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1488686\n```\n\n\n:::\n:::\n\n\n\nit isn't significant, X-squared = 11.79, df = 14, p-value = .623, but there is < 5 in the \n\"Other\" gender category which gives us the error message \"Chi-squared approximation may be incorrect\".\nif we focus just on Male/Female data, if, for instance, we are interested for the purposes of \nour investigation only in these larger categories:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvdatmf <- filter(vdat, Gender == \"Male\" | Gender == \"Female\")\nchisq.test( x = vdatmf$Gender, vdatmf$academic_year)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  vdatmf$Gender and vdatmf$academic_year\nX-squared = 5.9864, df = 7, p-value = 0.5413\n```\n\n\n:::\n\n```{.r .cell-code}\ncramersV( x = vdatmf$Gender, vdatmf$academic_year)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1505847\n```\n\n\n:::\n:::\n\n\nIt still isn't significant, X-squared = 5.99, df = 7, p-value = .541\n:::\n\n\n25. What about the association between english_status and Gender? \n\n::: {.callout-warning icon=false collapse=\"false\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq.test( x = vdat$Gender, vdat$english_status)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in chisq.test(x = vdat$Gender, vdat$english_status): Chi-squared\napproximation may be incorrect\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  vdat$Gender and vdat$english_status\nX-squared = 2.086, df = 2, p-value = 0.3524\n```\n\n\n:::\n\n```{.r .cell-code}\ncramersV( x = vdat$Gender, vdat$english_status)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in stats::chisq.test(..., correct = FALSE): Chi-squared approximation\nmay be incorrect\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.08940014\n```\n\n\n:::\n:::\n\n\nnot significant, X-squared = 2.09, df = 2, p-value = .352.\n\nAnd just for Male/Female:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq.test( x = vdatmf$Gender, vdatmf$english_status)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  vdatmf$Gender and vdatmf$english_status\nX-squared = 0.62108, df = 1, p-value = 0.4306\n```\n\n\n:::\n\n```{.r .cell-code}\ncramersV( x = vdatmf$Gender, vdatmf$english_status)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05865846\n```\n\n\n:::\n:::\n\n\nStill not significant, X-squared = 0.62, df = 1, p-value = .431\n:::\n\n26. What about the association between english_status and academic year?\n\n::: {.callout-warning icon=false collapse=\"false\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq.test( x = vdat$english_status, vdat$academic_year)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  vdat$english_status and vdat$academic_year\nX-squared = 4.3238, df = 7, p-value = 0.7418\n```\n\n\n:::\n\n```{.r .cell-code}\ncramersV( x = vdat$english_status, vdat$academic_year)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1284637\n```\n\n\n:::\n:::\n\n\nNot significant, X-squared = 4.32, df = 7, p-value = .742\n:::\n\n\n#### 4.4.1.6 Part 6: More practice using Chi-squared and Cramer's V test\n\n##### Task 8: More Chi-squared and Cramer's V tests\n\n27. Look at the \"ahicesd.csv\" and \"participantinfo.csv\" data sets from week 2 again. Which nominal measures could you look at an association between? Report the Chi-squared test and Cramer's V results for these associations. Are these associations significant? How do you interpret the significant associations?\n\n\n::: {.callout-warning icon=false collapse=\"false\"}\n## Answer\nFor example, you could have a go at occasion and intervention. This would tell you whether the participants are unevenly distributed across the occasions and interventions:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\na <- group_by(all_dat, occasion, intervention)\nchisq.test( x = all_dat$occasion, all_dat$intervention)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  all_dat$occasion and all_dat$intervention\nX-squared = 9.7806, df = 15, p-value = 0.8333\n```\n\n\n:::\n\n```{.r .cell-code}\ncramersV( x = all_dat$occasion, all_dat$intervention)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05732779\n```\n\n\n:::\n:::\n\n\nchi2(15, N = 992) = 9.78, p = .833\n\nCramer's V = .06\n\nNot significant, X-squared = 2.73, df = 6, p-value = .842\n:::\n\n\n#### 4.4.1.7 Part 7: Extra practise downloading and analysing data\n\n28. Here is another dataset for you to investigate:\n\nPapoutsi, C., Zimianiti, E., Bosker, H. R., & Frost, R. L. (2024). Statistical learning at a virtual cocktail party. *Psychonomic Bulletin & Review, 31(2)*, 849-861. https://doi.org/10.3758/s13423-023-02384-1\n\nThe data are available on OSF, but also a cleaned version of the dataset is [available here](data/wk4/papatsou_cleaneddata.csv). \nIf this doesn't work when you try to upload into psy-rstudio.lancaster.ac.uk, then you can always get the data from the osf site using this command: \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- read_csv('https://osf.io/download/ky4u6/')\n```\n:::\n\n\n\nThere is also something in the osf site called a R-markdown file - Data_analysis_script.rmd\n\nThis is a special kind of R-script, a \"R-markdown\" file, which also stores the results alongside the commands.\n\nYou should be able to scroll through it and see some of the R studio commands that might be familiar.\n\nFor more information on R-markdown, you can see here: https://r4ds.had.co.nz/r-markdown.html\n\n29. Our challenge to you is to make a Figure that looks a bit like their Figure 2. e.g., construct a boxplot of some of these data (though the Figure they use is called a pirate plot).\nIf you're keen to learn, there is more information on pirate plots here: \n[pirateplots](https://cran.r-project.org/web/packages/yarrr/vignettes/pirateplot.html){target=\"_blank\"}\n\n::: {.callout-warning icon=false collapse=\"false\"}\n## Answer\nThis is the dataset you need\n\n\n::: {.cell}\n\n```{.r .cell-code}\npapitsou <- read_csv(\"data/wk4/papatsou_cleaneddata.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 10236 Columns: 24\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (13): participant, test, test_speaker, word1, word2, test_type, testpair...\ndbl (11): trialNo, tablerow, soundrow, correct_answer, rt, status, trialaccu...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n:::\n\n30. Have a further browse of Psychological Science for data sets that you can download and begin to explore. Practise applying the data manipulation and graphing functions to these data sets. Or here is another one you might find interesting:\n\nWoodworth, R. J., O'Brien‐Malone, A., Diamond, M. R., & Schüz, B. (2017). Web‐based positive psychology interventions: A reexamination of effectiveness. Journal of Clinical Psychology, 73(3), 218-232. \nData available [here](https://openpsychologydata.metajnl.com/articles/10.5334/jopd.35){target=\"_blank\"}\n\nDescription of their study:\n\nIn our study we attempted a partial replication of the study of Seligman, Steen,\nPark, and Peterson (2005) which had suggested that the web-based delivery of\npositive psychology exercises could, as the consequence of containing specific,\npowerful therapeutic ingredients, effect greater increases in happiness and greater\nreductions in depression than could a placebo control.\nParticipants (n=295) were randomly allocated to one of four intervention groups\nreferred to, in accordance with the terminology in Seligman et al. (2005) as\n1: Using Signature Strengths; 2: Three Good Things; 3: Gratitude Visit; 4: Early \nMemories (placebo control).\nAt the commencement of the study, participants provided basic demographic\ninformation (age, sex, education, income) in addition to completing a pretest\non the Authentic Happiness Inventory (AHI) and the Center for Epidemiologic\nStudies-Depression (CES-D) scale. Participants were asked to complete\nintervention-related activities during the week following the pretest. Futher\nmeasurements were then made on the AHI and CESD immediately after the\nintervention period ('posttest') and then 1 month after the posttest (day 38),\n3 months after the posttest (day 98), and 6 months after the posttest (day 189).\nParticipants were not able to to complete a follow-up questionnaire prior to\nthe time that it was due but might have completed at either at the time that\nit was due, or later. We recorded the date and time at which follow-up\nquestionnaires were completed.\n\n## 4.4.2 Data\n\nData referred to in this workbook:\n\n- [PSYC411-shipley-scores-anonymous-17_24.csv](data/wk4/PSYC411-shipley-scores-anonymous-17_24.csv) \n\n- [ahicesd.csv](data/wk2/ahicesd.csv)\n\n- [participantinfo.csv](data/wk2/participantinfo.csv)\n\n- [titanic data](data/wk4/titanic.csv)\n\n- [papatsou study data](data/wk4/papatsou_cleaneddata.csv)\n\n## 4.4.3 Answers\n\nAnswers now appear in this page, above.\n\n## 4.5 Extras\n\n\nSee the [guides to reporting numbers and statistical tests](https://apastyle.apa.org/instructional-aids/numbers-statistics-guide.pdf){target=\"_blank\"} in American Psychological Association format (the format that we use in Psychology for all reports).\n\nWatch the [clip of the Titanic film if you like](https://www.youtube.com/watch?v=1YGfrGKK9Mo){target=\"_blank\"} (not assessed!). Hosted on youtube.\n\nWatch the [clip of the Titanic film with a cat if you like](https://www.youtube.com/watch?v=kEPfM3jSoBw){target=\"_blank\"} (also not assessed!). Hosted on youtube.\n\n- Read [what is a p-value, on wikipedia](https://en.wikipedia.org/wiki/P-value){target=\"_blank\"}. On this topic, wikipedia is good at explaining this, and explaining misinterpretations of p-values as well.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}