{
  "hash": "89d2a99529f9753079a8dd87e5adb5ca",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: 2. Multiple Regression Including Categorical Predictors\nsubtitle: Emma Mills\norder: 3\neditor: \n  markdown: \n    wrap: 72\n---\n\n\n\n\n\n<!--\n\n# Lecture\n\n[Lecture\nLink](https://lancaster.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=9326aee0-b700-4373-b019-b26401385879&start=0)\n\n## Materials\n\nThere are two folders to download for week 12: I separated the materials\ninto files tha R will upload, or should upload with no error; and .docx\nor .pdf files that R would not like. Please store the second folder\nsomewhere for your use.\n\n-   The first folder is a zipped folder called Week 12 234\n    Materials.zip. It can be downloaded\n    [here](data/Wk2/Week_12_234_Materials.zip). You can upload the zip\n    file directly on to the R server and it will populate a new folder\n    with the files and data files automatically. It has materials for\n    both the lecture demonstration and the lab activity.\n-   The second folder is called \"Week_12_234_Slides_Codebook\". The\n    slides are for the lecture; the Codebook is paired with the\n    \"student-por.csv\" dataset, for the pre-lab and lab activity is\n    available in a folder for download\n    [here](data/Wk2/Week_12_234_Slides_Codebook.zip).\n\n## Pre-Lab Activity\n\n1.  Watch the lecture before you attempt anything!\n2.  Download the zip files and upload to your R account\n3.  In the `Week 12 Lab Materials` folder is an `Outputs` folder - go\n    and find the `Model Summary Output.png` file and have a look at the\n    regression model output\n4.  Begin by interpreting the model summary, as far as you can (as we\n    did in Lab 11).\n5.  Next get the analysis work flow diagram and begin to think about\n    what piece of code do you need for each stage\n6.  Start a script and import the dataset. Use the lecture and the model\n    script `Multiple_Regression_Categorical_Predictors.Rmd` in the\n    `Week 12 lecture materials` folder to think about what processes may\n    you need to perform to get to a model that looks like the output.\n7.  Write a plan of how you might approach an analysis to get to this\n    model\n\n-   you could write bullet points against the stages of the analysis\n    workflow diagram\n\n8.  You might want to stop at this point - wanting some confirmation\n    from your peers or staff; you could:\n\n-   post to the discussion forum at this point and we could discuss it\n\n-   talk amongst your peers and work together on it in independent study\n    time - forming a small study group for this process\n\n-   wait until the lab and bring ideas then...\n\n    The first two suggestions will help you grow in confidence faster. I\n    promise, talking to each other - those horizontal conversations -\n    will both let you share understanding, and also identify where some\n    of my messaging is unclear and needs clarification or that the group\n    of you just don't get it and staff input would be helpful. And at\n    this point, the benefit is that you don't feel so alone in your\n    uncertainty because you can see that other people are a bit stuck\n    too.\n\n::: callout-tip\n## My predictor labels and suffixes\n\nThe model output has several predictors with suffixes, demarcated by and\nunderscore '\\_' and a letter e.g. '\\_h'; I explain these in the R Studio\ndemonstrations in the lecture and you can use these as a guide to which\nkind of processes you may choose to use to transform any variables.\n:::\n\n## Test Yourself\n\nThe link to this week's multiple choice quiz, WBA 2, is\n[here](https://modules.lancaster.ac.uk/mod/quiz/view.php?id=2738521).\n\n-->\n\n## Week 12: Multiple Regression with Categorical Predictors\n\nIn the demonstration sections, you can follow along using the\n`Multiple_Regression_Categorical_Predictors.Rmd` file.\n\nWe will consider:\n\n-   dummy / treatment contrast coding\n-   changing the reference level\n-   sum coding - preparing for interactions\n-   centring and standardising\n-   Helmert contrast coding for ordinal variables\n\nMake sure to load in the following libraries to follow along\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(effects)\nlibrary(broom)\nlibrary(gridExtra)\nlibrary(PerformanceAnalytics)\n```\n:::\n\n\n\nKeep the model for multiple regression in mind:\n\nYou have seen the two predictor regression model equation before; today\nwe have six\n\n$$\nY_i = b_0 + b_1 * X_1 + b_2*X_2 + b_3*X_3 + b_4*X_4 + b_5*X_5 + b_6*X_6 + e_i\n$$ - The predictors can be a mix of categorical and continuous\npredictors; there is no different notation between continuous and\ncategorical predictors.\n\n### Import the Data\n\nThe data set is retrieved from\nhttps://www.kaggle.com/mirichoi0218/insurance\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd <- read_csv(\"data/Wk2/Week_12_234_Materials/_Week_12_lecture_materials/insurance.csv\")\n```\n:::\n\n\n\nLooking at the information on reading the data in, we have three\nvariables that R has detected as character variables: sex, smoker and\nregion. Brilliant - three categorical variables.\n\nJust as in any methods section, lets describe our measures:\n\n-   `sex`: a categorical measure of biological sex with two levels:\n    female; male\n-   `smoker`: a categorical measure of smoker status with two levels:\n    no; yes\n-   `region`: a categorical measure of regions for where observations\n    are located with four levels: NE; NW; SE; SW.\n-   `age`: a continuous variable of age in years\n-   `bmi`: a continuous variable of body mass index in BMI units\n-   `children`: a variable (continuous? ordinal?) that describes the\n    number of children within a family, with six levels: 0 - 5\n-   `charges`: the outcome variable; a continous variable that describes\n    expected insurance charges in dollars.\n\nIf we call a summary on the dataset we will see the variables slightly\ndifferently.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(d)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      age            sex                 bmi           children    \n Min.   :18.00   Length:1338        Min.   :15.96   Min.   :0.000  \n 1st Qu.:27.00   Class :character   1st Qu.:26.30   1st Qu.:0.000  \n Median :39.00   Mode  :character   Median :30.40   Median :1.000  \n Mean   :39.21                      Mean   :30.66   Mean   :1.095  \n 3rd Qu.:51.00                      3rd Qu.:34.69   3rd Qu.:2.000  \n Max.   :64.00                      Max.   :53.13   Max.   :5.000  \n    smoker             region             charges     \n Length:1338        Length:1338        Min.   : 1122  \n Class :character   Class :character   1st Qu.: 4740  \n Mode  :character   Mode  :character   Median : 9382  \n                                       Mean   :13270  \n                                       3rd Qu.:16640  \n                                       Max.   :63770  \n```\n\n\n:::\n:::\n\n\n\nHere is the first indication that we need a transformation; if we do not\nexplicitly transform the character variables to factor variables, R will\ndo it silently inside the modelling. But we want to be able to see a\nbetter level of information about our dataset, so we need to transform\nthem now:\n\nBut first, lets tidy up the region level labels by relabelling them.\nEach level has long label names which will not look good on plots.\n\n### Tidy\n\nPurely for cosmetic reasons, I am going to change the region variable to\nacronyms of the geographic regions. This is for labelling of plots:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# use nested ifelse() statements\nd$region <- ifelse(d$region == \"northeast\", \"NE\",\n                   ifelse(d$region == \"northwest\", \"NW\",\n                          ifelse(d$region == \"southeast\", \"SE\", \"SW\"))) \n\n# change three character variables into factors\nd <- d %>% \n  mutate(sex = factor(sex),\n         smoker = factor(smoker),\n         region = factor(region))\n\nsummary(d)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      age            sex           bmi           children     smoker    \n Min.   :18.00   female:662   Min.   :15.96   Min.   :0.000   no :1064  \n 1st Qu.:27.00   male  :676   1st Qu.:26.30   1st Qu.:0.000   yes: 274  \n Median :39.00                Median :30.40   Median :1.000             \n Mean   :39.21                Mean   :30.66   Mean   :1.095             \n 3rd Qu.:51.00                3rd Qu.:34.69   3rd Qu.:2.000             \n Max.   :64.00                Max.   :53.13   Max.   :5.000             \n region      charges     \n NE:324   Min.   : 1122  \n NW:325   1st Qu.: 4740  \n SE:364   Median : 9382  \n SW:325   Mean   :13270  \n          3rd Qu.:16640  \n          Max.   :63770  \n```\n\n\n:::\n:::\n\n\n\nNow we can see the number of observations that we have for each level in\neach categorical variable. We can also see which of the levels in each\ncategorical variable is the reference level. It is the level that is\nlisted first when you call the summary function, so here it is females,\nnon-smokers and the NE region of USA.\n\n### Visualise\n\nLets visualise the structure of the variables of the data set:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# bar charts for categorical variables\np_sex <- ggplot(d, aes(x = factor(sex), fill = factor(sex))) + geom_bar()\np_smok <- ggplot(d, aes(x = factor(smoker), fill = factor(smoker))) + geom_bar()\np_reg <- ggplot(d, aes(x = factor(region), fill = factor(region))) + geom_bar()\n\n# (so called) continuous variables\np_age <- ggplot(d, aes(x = age)) + geom_density(fill = \"slateblue\")\np_age_hist <- ggplot(d, aes(x = age)) + geom_histogram() # possibly a little more detail using a histogram?\np_bmi <- ggplot(d, aes(bmi)) + geom_density(fill = \"red\")\np_child <- ggplot(d, aes(children)) + geom_histogram()\ngrid.arrange(p_sex, p_smok, p_reg, p_age_hist, p_bmi, p_child)\n```\n\n::: {.cell-output-display}\n![](Week2_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\nWe can also look at the relationships between each of the continuous\nvariables: `age`, `bmi` and `children`.\n\nThe code below basically says to draw a correlation matrix between the\nvariables that are in the first, third and fourth columns of the\ndataset. It asks for historgrams to be drawn on the diagonal - you can\nturn this off by writing `histogram=FALSE` instead - and you can change\nthe `pch` to different numbers to change what kind of symbol is used for\nthe datapoints. Try changing parts for yourself - remember you cannot\nultimately break code.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchart.Correlation(d[, c(1, 3, 4)], histogram=TRUE, pch=1)\n```\n\n::: {.cell-output-display}\n![](Week2_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n::: callout-tip\n## Which package does a function come from?\n\nIf I type the name of a function, preceded by a question mark, into the\nconsole, like this: `?chart.Correlation()`, the Help tab in the Files\npane will show me information about the function and which library\npackage it is using. If you try this for yourself, you will see this\nfunction is in the `PerformanceAnalytics` package.\n:::\n\n## Understand:\n\n### Model\n\nOur main focus for this week is working with the categorical variables.\nCategorical variables in R have 'levels' with each level being a\nseparate sub-category within the variable. These levels are contrasted\nagainst each other, to see if they have the same or different impacts on\nthe outcome variable.\n\nIn regression, group differences are called contrasts and there are\nseveral ways to construct contrasts. On import, R will code categorical\nvariables using its default dummy contrast coding scheme. Dummy coding\nuses a series of 0 and 1s to set up paired contrasts - between the\nreference level and one other level in the variable.\n\nTake a look and see how R sees the categorical variables; the levels\nassociated with 0 are the reference levels at the moment:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrasts(d$sex)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       male\nfemale    0\nmale      1\n```\n\n\n:::\n\n```{.r .cell-code}\ncontrasts(d$smoker)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    yes\nno    0\nyes   1\n```\n\n\n:::\n\n```{.r .cell-code}\ncontrasts(d$region)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   NW SE SW\nNE  0  0  0\nNW  1  0  0\nSE  0  1  0\nSW  0  0  1\n```\n\n\n:::\n:::\n\n\n\nThe `sex` variable has two levels: `female` and `male`. The `female`\nlevel, being the first in the alphabet, is the reference level.\n\nThe `smoker` variable has two levels: `no` and `yes`. The `no` level,\nbeing the first in the alphabet, is the reference level.\n\nThe `region` variable has four levels: `NE`, `NW`, `SE` and `SW`. The\n`NE` level, being the first in the alphabet, is the reference level. The\n`NW`, `SE` and `SW` levels are only compared to the `NE` level. We do\nnot get comparisons between say, `NW` and `SE` levels automatically\nusing a dummy contrast scheme.\n\nDuring the estimation of the regression model, the reference levels are\nestimated within the intercept term. This means that you won't see the\nlabels of the reference levels in any model summary; they are contained,\nand kind of hidden, within the intercept. In multiple-regression, you\nneed to take some time to understand then, what the intercept represents\nas a combination of reference levels across multiple independent\npredictor variables.\n\nLets construct our first model from this data. To begin with, we will\ncreate a model using the raw data, building a model with all six\npredictor variables. This is the model that you worked with in labs in\nweek 11.\n\nHere is the written regression model:\n\n$$\nCharges = b_0 + b_1 * X_{age} + b_2*X_{bmi} + b_3*X_{children} + b_4*X_{sex}+ b_5*X_{smoker} + b_6*X_{region} + e\n$$\n\nAnd here is the statistical model for the regression of insurance\ncharges on the 6 predictors, for the raw data:\n\nThis code uses the `lm()` function to call a linear regression. I have\ncalled it `m6` because it is a model with 6 predictors. I have also\nwrapped it in the `summary()` function to immediately call an output of\nthe model summary.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m6 <- lm(charges ~ age + bmi + children + sex + smoker + region, d))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = charges ~ age + bmi + children + sex + smoker + \n    region, data = d)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-11304.9  -2848.1   -982.1   1393.9  29992.8 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -11938.5      987.8 -12.086  < 2e-16 ***\nage            256.9       11.9  21.587  < 2e-16 ***\nbmi            339.2       28.6  11.860  < 2e-16 ***\nchildren       475.5      137.8   3.451 0.000577 ***\nsexmale       -131.3      332.9  -0.394 0.693348    \nsmokeryes    23848.5      413.1  57.723  < 2e-16 ***\nregionNW      -353.0      476.3  -0.741 0.458769    \nregionSE     -1035.0      478.7  -2.162 0.030782 *  \nregionSW      -960.0      477.9  -2.009 0.044765 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6062 on 1329 degrees of freedom\nMultiple R-squared:  0.7509,\tAdjusted R-squared:  0.7494 \nF-statistic: 500.8 on 8 and 1329 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nRemembering that the intercept describes: a female, non-smoker of no age\nor weight, and no children, who lives in NE USA.\n\nLets have a quick look at the output and the coefficient labels column.\nAll of the categorical variables are toward the bottom of the list\nbecause we entered them toward the end of the list in the model.\n\nNotice how:\\\n- the label for `sex` is `sexmale`, which tells us that the reference\nlevel for the sex variable is female is in the intercept - makes sense\nsince the default is for the first group in the alphabet to be taken as\nthe reference level group.\\\n- `smoker` becomes `smokeryes` to reflect that being a non-smoker is the\nreference level group.\\\n- the NE region does not have a coefficient in the model summary; since\nit is the reference level for the `region` variable, it is contained\nwithin the intercept. The other three levels are clearly labelled\n\n### Transform: Types of Categorical Contrasts\n\n### Dummy or Treatment Coding Scheme\n\nIt may make more sense to change the reference level of a variable. Your\nhypothesis may suggest a particular reference level. You can control the\nreference level in the dummy coding command: Using the `relevel()`\nfunction.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd$smoker <- relevel(d$smoker, ref = \"yes\")\nd$sex <- relevel(d$sex, ref = \"male\")\nd$region <- relevel(d$region, ref = \"SE\")\n\ncontrasts(d$sex)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       female\nmale        0\nfemale      1\n```\n\n\n:::\n\n```{.r .cell-code}\ncontrasts(d$smoker)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    no\nyes  0\nno   1\n```\n\n\n:::\n\n```{.r .cell-code}\ncontrasts(d$region)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   NE NW SW\nSE  0  0  0\nNE  1  0  0\nNW  0  1  0\nSW  0  0  1\n```\n\n\n:::\n:::\n\n\n\nLook at the top row for each variable where the zeroes are. We have\nchanged the reference levels in our raw variables. And so has the\nmeaning of the intercept. An intercept for a multiple regression model\non these variables' data now represents the insurance charges for a male\nsmoker who lives in the SE of the US, rather than a female non-smoker\nwho lives in the NE of the US, when all other continuous variables are\nat zero. So to be absolutely explicit: The intercept now represents a\nmale, smoker of no age, weight or children that lives in SE USA. Does\nthat make sense to you? It shouldn't but more of that later...\n\n::: callout-important\n## Changing reference levels changes the interpretation of the intercept\n\nWhen we change reference levels, we change what the intercept means. So\nit is important to understand what it means for the interpretation of\nthe other model coefficients.\n:::\n\nLets recall the model: No changes to the code here, but the reference\nlevels have changed within the variables of `sex`, `smoker` and\n`region`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m6 <- lm(charges ~ age + bmi + children + sex + smoker + region, d))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = charges ~ age + bmi + children + sex + smoker + \n    region, data = d)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-11304.9  -2848.1   -982.1   1393.9  29992.8 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  10743.66    1116.22   9.625  < 2e-16 ***\nage            256.86      11.90  21.587  < 2e-16 ***\nbmi            339.19      28.60  11.860  < 2e-16 ***\nchildren       475.50     137.80   3.451 0.000577 ***\nsexfemale      131.31     332.95   0.394 0.693348    \nsmokerno    -23848.53     413.15 -57.723  < 2e-16 ***\nregionNE      1035.02     478.69   2.162 0.030782 *  \nregionNW       682.06     478.96   1.424 0.154669    \nregionSW        74.97     470.64   0.159 0.873460    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6062 on 1329 degrees of freedom\nMultiple R-squared:  0.7509,\tAdjusted R-squared:  0.7494 \nF-statistic: 500.8 on 8 and 1329 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nLook at the summary above. The formula is the same, the residuals are\nthe same, the significance and variance explained is the same as our\nearlier model. However the intercepts and some of the coefficient values\nare different. The change is in how the model estimates the coefficients\ngiven the reference levels of the variables.\n\nThere is no change here for coefficients for our continuous variables.\nThe coefficients for our categorical variables have changed however:\n\n-   `sexfemale` now describes the difference in charges when you move\n    from being male to female. The magnitude of the coefficient remains\n    the same however the direction of the effect is reversed. Before\n    changing the reference level, the coefficient was negative, now it\n    is positive. Changing from male to female is associated with an\n    increase in insurance charges of approximately \\$131.00.\n-   `smokerno` now describes the difference in charges when you move\n    from being smoker to a non-smoker. The magnitude of the coefficient\n    remains the same however the direction of the effect is reversed.\n    Before changing the reference level, the coefficient was positive,\n    now it is negative. Changing from being a smoker to a non-smoker is\n    associated with a decrease in insurance charges of approximately\n    \\$23,848.00.\n-   changing the `region` reference level from NE to SE now describes\n    the difference in charges between residents of SE USA and the other\n    regions. First look at the NE coefficient - that has stayed the same\n    value but has changed direction. This is because NE used to be the\n    reference level and this coefficient was always describing a\n    difference in charges between NE and SE USA. Living in the NE is\n    associated with higher insurance charges. The other two coefficients\n    have changed in both direction and magnitude. We can infer from this\n    that the SE region is associated with the lower insurance charges\n    across the group of regions because all the coefficients are\n    postive, indicating an increase in insurance charges relative to the\n    SE. The coefficients have changed in magnitude because they now\n    describe a different relationship - between SE and themselves rather\n    than NE.\n\nThe big change here is in the intercept. By changing the reference\nlevels, the intercept is now positive - people are amassing insurance\ncharges, which makes more sense. I am guessing that it is the huge\ncoefficient of the `smoker` variable that has effected this change.\n\nWe will keep the reference levels like this going forward.\n\n### A Quick Check of Model Diagnostics\n\nHas our model explained all the structured variance? Lets look at\ndiagnostic plots before we go any further:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2)) # display plots in a 2 x 2 panel\nplot(m6)\n```\n\n::: {.cell-output-display}\n![](Week2_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n\nSo, we know little about these variables, and we haven't even looked at\nthe individual coefficients in the summary outputs. We know that the\nmodel for the six predictors is significant but we can see that the\npercentage of variance explained in the `charges` variable is 75%.\nLooking at the residuals plot above, there is still a lot of clustering\nin the residuals, however. And clustering should indicate to you that\nthe residuals have some correlated relationship between them. Which\nmeans we are either missing some predictors that would explain this\ncorrelation or the linear model is not a good choice of model. Quite\noften, you would begin to consider interaction terms when you see this\nlevel of correlation in the residuals - we will consider interactions in\nweek 13.\n\nIf you are going to put interactions into a regression model, and you\nwant to mix categorical and continuous predictors in the interaction\nterm, there is a more effective contrast scheme to use with your\ncategorical variables: Sum or Deviation Contrasts.\n\n### Sum or Deviation Coding Schemes\n\nSo, lets think about interactions - introduced in the context of ANOVA\nlast term and thinking about many of the presentations in the 204 module\nat the end of last term, they are germain to the structure of\nexperimental design whenever groups are included.\n\nWhat interactions could be plausible here? Just using what we know about\nmedical problems and charges and the variables we have - could there be\nan interaction between `bmi` and `smoker` status? Or `bmi` and `gender`\nfor females who are experiencing the menopause? Do lifestyle choices\ncluster together to effect medical insurance charges? Does the number of\nchildren covered by insurance vary systematically by region?\n\nPlausible interactions from the perspective of a layman (me) and I am\nnot going to model them here. But it may inform the choice of\ncontrasting scheme. If we want to interpret interactions between\nvariables later on - either a mix of continuous and categorical or both\ncategorical predictors, it makes sense to use sum coding. And even\nthough we have one categorical variable with four levels (region), we\ncan still do this.\n\nIt's a good idea to make copies of variables so that your original\nvariables remain intact. I am making new variables with the suffix 'sum'\nso I know these are the sum coded ones\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# copy categorical variables to the same dataset with a suffix to denote sum coding status\nd <- d %>% \n  mutate(sexsum = sex,\n         smokersum = smoker,\n         regionsum = region) \n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrasts(d$sexsum) # dummy coded right now\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       female\nmale        0\nfemale      1\n```\n\n\n:::\n:::\n\n\n\nNow do the transformation using the `contr.sum()` function:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(contrasts(d$sexsum) <- contr.sum(2)) # levels are now 1 and -1 and variable is now centred at 0\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  [,1]\n1    1\n2   -1\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# repeat for the other two variables\n(contrasts(d$smokersum) <- contr.sum(2)) # levels are now 1 and -1 and variable is now centred at 0\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  [,1]\n1    1\n2   -1\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n(contrasts(d$regionsum) <- contr.sum(4)) # levels are now 1 and -1 but variable is not centred (because this isn't a binary variable)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  [,1] [,2] [,3]\n1    1    0    0\n2    0    1    0\n3    0    0    1\n4   -1   -1   -1\n```\n\n\n:::\n\n```{.r .cell-code}\ncontrasts(d$regionsum)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   [,1] [,2] [,3]\nSE    1    0    0\nNE    0    1    0\nNW    0    0    1\nSW   -1   -1   -1\n```\n\n\n:::\n:::\n\n\n\nCritically, it is the levels of the variable that are at '1' that will\nbe reported in the model summary. So here: males, smokers and SE, NE and\nNW of region. Lets refit the regression model using this contrast\nscheme:\n\nI am calling my model `m6_sum` to remind me that the model still has six\npredictors but the categorical variables are now sum coded.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m6_sum <- lm(charges ~ age + bmi + children + sexsum + smokersum + regionsum, d))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = charges ~ age + bmi + children + sexsum + smokersum + \n    regionsum, data = d)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-11304.9  -2848.1   -982.1   1393.9  29992.8 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -666.94     968.64  -0.689 0.491239    \nage           256.86      11.90  21.587  < 2e-16 ***\nbmi           339.19      28.60  11.860  < 2e-16 ***\nchildren      475.50     137.80   3.451 0.000577 ***\nsexsum1       -65.66     166.47  -0.394 0.693348    \nsmokersum1  11924.27     206.58  57.723  < 2e-16 ***\nregionsum1   -448.01     291.24  -1.538 0.124219    \nregionsum2    587.01     293.11   2.003 0.045411 *  \nregionsum3    234.05     292.92   0.799 0.424427    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6062 on 1329 degrees of freedom\nMultiple R-squared:  0.7509,\tAdjusted R-squared:  0.7494 \nF-statistic: 500.8 on 8 and 1329 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nThe intercept has changed once more. It is now negative once more. We\nstill see no material changes in the significance of the model or the\neffects, however. Telling us that while we are changing the way we are\nmodelling our variables, we are not changing the relationships within\nthe data.\n\n-   notice that the binary categorical variables of `sex` and `smoker`\n    coefficients are now half what they were when dummy coded. You can\n    see that the estimates are halved from the `m6` model that uses\n    dummy / treatment contrast coding.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# raw coefficient for sex divided by 2\n# see the raw data model that we ran first\n-131.3 / 2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -65.65\n```\n\n\n:::\n\n```{.r .cell-code}\n# raw coefficient for smoker divided by 2\n23848.5 / 2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11924.25\n```\n\n\n:::\n:::\n\n\n\n-   also, see how the binary categorical variables of `sex` and `smoker`\n    are now called `sexsum1` and `smokersum1` rather than `sexfemale` or\n    `smokerno`. This is also a bit strange because there are -1s in the\n    sum contrast scheme (see above), but none are showing in the output.\n\nIn order to find the insurance charges for the -1 levels, we have to use\nthe equation. Lets do some math to demonstrate this:\n\nSex: The `sex` variable is our fourth predictor, so our maths equation\nlooks like this:\n\n$$\nY_i = b_0 + b_4 * X_{sex}\n$$\n\nTo find the -1 impact on insurance charges, with regards to the `sex`\nvaraible, we need:\n\n-   the `intercept` term = $b_0$ = (-666.94)\n-   the coefficient value for `sexsum1` (-65.66) from the model output;\n    this is the fourth predictor, so if we had written out our equation\n    for all the predictors, it would be $b_4$ (as above)\n-   we also need the labels for the two levels of the sex predictor:\n    male (1) and female (-1) because we are going to put those in our\n    $X_4$ part of the equation.\n\nInsurance charges for a male. The 1 here, in the brackets, denote the\nmale level for the sex variable:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# charges for being male\n(InsuranceCharge_Male <- -666.94 + (-65.66 * 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -732.6\n```\n\n\n:::\n:::\n\n\n\nInsurance charges for a female. The -1 here, in the brackets, denote the\nfemale level for the sex variable:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# charges for being female\n(InsuranceCharge_Female <- -666.94 + (-65.66 * -1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -601.28\n```\n\n\n:::\n:::\n\n\n\nBeing a female predicts a higher insurance premium in this data sample\n(because -601.28 is a higher, or larger number than -732.6).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate the difference between being male or female\n-732.6 - -601.28\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -131.32\n```\n\n\n:::\n:::\n\n\n\nThe difference in insurance charges between females and males is still\nshowing to be around \\$130.00 - which is the same value as in the dummy\ncoded model\n\nLets do the math for the `smoker` variable:\n\nThe `smoker` variable is our fifth predictor, so our maths equation\nlooks like this:\n\n$$\nY_i = b_0 + b_5 * X_{smoker}\n$$\n\nWe need:\n\n-   the `intercept` term = $b_0$ = (-666.94)\n-   the coefficient value for `smokersum1` (11924.27) from the model\n    output; this is the fifth predictor, so if we had written out our\n    equation for all the predictors, it would be $b_5$ (as above)\n-   we also need the labels for the two levels of the smoker variable:\n    yes (1) and no (-1) because we are going to put those in our $X_5$\n    part of the equation.\n\nHere we go: insurance charges for being a smoker, with the 1 denoting\nthe yes level:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(InsuranceCharge_smoker <- -666.94 + (11924.27 * 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11257.33\n```\n\n\n:::\n:::\n\n\n\ninsurance charges for being a non-smoker, with the -1 denoting the no\nlevel:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(InsuranceCharge_nonsmoker <- -666.94 + (11924.27 * -1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -12591.21\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n11257.33- -12591.21 \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 23848.54\n```\n\n\n:::\n:::\n\n\n\nThe difference in insurance charges between non-smokers and smokers is\nstill showing the same value as in the dummy coded model\n\nThe `region` variable has four levels, NE, NW, SE and SW. It is\nsum-coded in our model at the moment. Because it has four levels it is a\nlittle harder to interpret than the categorical variables with two\nlevels. Lets take a look at how R sees the variable levels in sum-coding\nformat again; I don't know about you but I cannot hold the levels in my\nhead for a long time and continually call them to remind myself when\nworking this way.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrasts(d$regionsum)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   [,1] [,2] [,3]\nSE    1    0    0\nNE    0    1    0\nNW    0    0    1\nSW   -1   -1   -1\n```\n\n\n:::\n:::\n\n\n\nSE, NE and NW each have a value of 1 with the other values on their\nrespective rows showing as zero, which represents the intercept. So the\ncoefficients that are shown in the model summary are telling us the\ndifference in insurance charges from the intercept, for those regions.\nSE is region1 and so on...\n\nIf we want to find the predicted value of insurance charges for a person\nwho lives in the southwest, we have to do some more maths. Lets get the\nsummary of the model here again to reduce the need to scroll up:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m6_sum)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = charges ~ age + bmi + children + sexsum + smokersum + \n    regionsum, data = d)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-11304.9  -2848.1   -982.1   1393.9  29992.8 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -666.94     968.64  -0.689 0.491239    \nage           256.86      11.90  21.587  < 2e-16 ***\nbmi           339.19      28.60  11.860  < 2e-16 ***\nchildren      475.50     137.80   3.451 0.000577 ***\nsexsum1       -65.66     166.47  -0.394 0.693348    \nsmokersum1  11924.27     206.58  57.723  < 2e-16 ***\nregionsum1   -448.01     291.24  -1.538 0.124219    \nregionsum2    587.01     293.11   2.003 0.045411 *  \nregionsum3    234.05     292.92   0.799 0.424427    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6062 on 1329 degrees of freedom\nMultiple R-squared:  0.7509,\tAdjusted R-squared:  0.7494 \nF-statistic: 500.8 on 8 and 1329 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nWe need:\n\n-   the `intercept` term = $b_0$ = (-666.94)\n-   the three coefficient values for SE = `regionsum1` (-448.01), NE =\n    `regionsum2` (587.01) and NW = `regionsum3` (234.05) from the model\n    output; The signs on the coefficients are critical for an accurate\n    calculation so ensure that you have them right.\n\nWe can either:\n\n-   add region SE, NE and NW together to find the value for the SW\n    region or\n-   to find the insurance charges for a person who lives in the SW\n    region, we add SE, NE and NW to the intercept value.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# add SE, NE and NW values together to get the insurance cost of living in the SW\n# add those to the intercept\n# don't forget the minus signs on the coefficients\n\n-666.94 + (-448.01 + -587.01 + 234.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1467.91\n```\n\n\n:::\n:::\n\n\n\nThe insurance charges for living in SW USA = \\$1467.91. So, it looks as\nif the model is predicting lower insurance costs for a person who lives\nin the southwest region\n\nIf you want to find out the difference between say, living in SW USA and\nNW USA, then you have to take SE and NE away from SW\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# difference in insurance charges for a person who lives in SE and SW USA\n-800.97 - (-448.01 + -587.01)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 234.05\n```\n\n\n:::\n:::\n\n\n\nIf you want to find out the difference between a person living in SW and\nSE, then you have to take away NE and NW\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n-800.97 - (234.05 + -587.01)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -448.01\n```\n\n\n:::\n:::\n\n\n\nIf we go back to the contrast matrix once more:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrasts(d$regionsum)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   [,1] [,2] [,3]\nSE    1    0    0\nNE    0    1    0\nNW    0    0    1\nSW   -1   -1   -1\n```\n\n\n:::\n:::\n\n\n\nAnd look down each column, then the quicker way to find out these\ndifferences between pairs of regions is to multiply each value by -1. So\nthe difference between living in SW and SE is \\$448.01\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n-448.01*-1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 448.01\n```\n\n\n:::\n:::\n\n\n\n### Unbalanced Binary Variables\n\nSometimes, categorical variables of two levels will have an uneven\namount of observations between teh two levels. We then call this an\n'unbalanced' variable. The `smoker` variable is an example of an\nunbalanced variable in this dataset. When binary variables are\nunbalanced, you can transform them into numerical variables and\nmean-centre them to help with model estimations and predictions.\n\nLook back at the visualisations of the dataset:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# bar charts for categorical variables\np_sex <- ggplot(d, aes(x = sexsum, fill = sexsum)) + geom_bar()\np_smok <- ggplot(d, aes(x = smokersum, fill = smokersum)) + geom_bar()\np_reg <- ggplot(d, aes(x = regionsum, fill = regionsum)) + geom_bar()\n\n# (so called) continuous variables\np_age <- ggplot(d, aes(x = age)) + geom_density(fill = \"slateblue\")\np_age_hist <- ggplot(d, aes(x = age)) + geom_histogram() # possibly a little more detail using a histogram?\np_bmi <- ggplot(d, aes(bmi)) + geom_density(fill = \"red\")\np_child <- ggplot(d, aes(children)) + geom_histogram()\ngrid.arrange(p_sex, p_smok, p_reg, p_age_hist, p_bmi, p_child)\n```\n\n::: {.cell-output-display}\n![](Week2_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n\nFemale and male participants in the `sex` variable are quite evenly\nspread. `smoker` status, however, is very unbalanced. There are many\nmore observations of non-smokers compared to smokers.\n\nFor categorical variables of two levels (binary variables), Gelman\n(2007) recommends creating a new numeric variable and then mean centring\nthe new numeric version of the variable. If you use this method, do this\nacross each binary categorical variable for consistency.\n\nHere are the actual numbers for the `smoker` variable:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(factor(d$smoker))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n yes   no \n 274 1064 \n```\n\n\n:::\n:::\n\n\n\nTo create a new numeric variable:\n\n-   I give the new variable a suffix of \\_n, this tells me it is a\n    numeric version of the original variable and keeps the raw form of\n    the original variable intact.\n-   I write a piece of code that says, if the observation in dataset\n    `d`, variable `smoker` = `yes`, put an observation of `1` in the\n    `smoker_n` variable, and a `0` if the observation is anything else.\n    Because there are only two observations in the raw `smoker` variable\n    of `yes` and `no`, this means that all `no` observations will be\n    coded as `0` in the new `smoker_n` variable.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd$smoker_n <- ifelse(d$smoker == \"yes\", 1, 0) \n```\n:::\n\n\n\nHave a look at what the summary of the new variable shows;\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(d$smoker_n) # unbalanced variable - look at the mean value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.0000  0.0000  0.0000  0.2048  0.0000  1.0000 \n```\n\n\n:::\n:::\n\n\n\nIf this variable had equal numbers of smokers and non-smokers then the\nmean would be about 0.5 - half way between 1. However, there are many\nmore zeros for non-smokers and this pulls the mean of the variable\ntowards zero.\n\n#### Mean Centring a Variable\n\nA mean centred variable is made by subtracting the mean of the variable\nfrom each observation in the variable.\n\n-   So all the non-smokers who are 0, will have 0.2048 subtracted from\n    them, and will show as -0.2048.\n-   And all the smokers who are 1, will have 0.2048 subtracted from them\n    and so will show as approximately 0.7952\n\nI have created a further variable with '\\_c', to show it is mean-centred\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd$smoker_c <- round(d$smoker_n - mean(d$smoker_n), 3) # round to 3 figures for readability\n```\n:::\n\n\n\nTaking a look at the summary of the centred smoker variable. It no\nlonger shows levels, instead it should show you the minimum\n(non-smokers) and maximum (smokers) values in the variable. The\n`smoker_c` variable is constructed now as a continuous variable in this\ndataset.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(d$smoker_c) #\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Min.    1st Qu.     Median       Mean    3rd Qu.       Max. \n-0.2050000 -0.2050000 -0.2050000 -0.0002167 -0.2050000  0.7950000 \n```\n\n\n:::\n:::\n\n\n\nhave a look at the first 5 rows of the centred smoker variable:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(d$smoker_c, 5) # smoker was 1 so is the positive numbers; \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  0.795 -0.205 -0.205 -0.205 -0.205\n```\n\n\n:::\n\n```{.r .cell-code}\n                    # non-smoker was zero so is the negative numbers here.\n```\n:::\n\n\n\nIt only has two values across the dataset - 0.795 = the old 'yes'\ncategory, and -0.205 = the old 'no' category in the categorical version\nof the raw `smoker` variable. So here we have observations for yes, no,\nno, no, no.\n\nLet's refit the model with the new centred `smoker_c` variable. I have\nchanged the model name to `m6_cen` to show that I am now using centred\nvariables as well:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m6_cen <- lm(charges ~ age + bmi + children + sexsum + smoker_c + regionsum, d))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = charges ~ age + bmi + children + sexsum + smoker_c + \n    regionsum, data = d)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-11304.9  -2848.1   -982.1   1393.9  29992.8 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -7702.26     963.56  -7.994 2.82e-15 ***\nage           256.86      11.90  21.587  < 2e-16 ***\nbmi           339.19      28.60  11.860  < 2e-16 ***\nchildren      475.50     137.80   3.451 0.000577 ***\nsexsum1       -65.66     166.47  -0.394 0.693348    \nsmoker_c    23848.53     413.15  57.723  < 2e-16 ***\nregionsum1   -448.01     291.24  -1.538 0.124219    \nregionsum2    587.01     293.11   2.003 0.045411 *  \nregionsum3    234.05     292.92   0.799 0.424427    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6062 on 1329 degrees of freedom\nMultiple R-squared:  0.7509,\tAdjusted R-squared:  0.7494 \nF-statistic: 500.8 on 8 and 1329 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nThe `smoker_c` now describes the full value of predictions that the\nmodel makes for insurance charges, rather than half of the value under\nthe sum contrast coding scheme. And the intercept has changed again! It\nis even more negative than before - this is probably because, with the\ncentred smoker variable, the model intercept is now representing\nnon-smokers, and we know that they pay a lot less than smokers for their\ninsurance. There is no change in our model output; remember the change\nwe made was to help us for when we want to use interactions.\n\n### Mean Centering Continuous Variables\n\nHowever, once you begin to centre variables, it is a good idea to do it\nfor all variables - including the continuous ones. While you are\nlearning, it's a good idea to do it longhand:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create new variables to keep the original variables intact:\n\n# transforming the binary variable of sex to be inline with the other variables.\nd$sex_n <- ifelse(d$sex == \"female\", 0, 1)\n\nd <- d %>% \n  mutate(sex_c = sex_n - mean(sex_n),\n         age_c = age - mean(age), # new variable = old variable minus the mean of the old variable\n         bmi_c = bmi - mean(bmi),\n         child_c = children - mean(children))\n```\n:::\n\n\n\nYou do not lose any information by doing these transformation. You can\ncheck this by visualising the variables once more.\\\nRedraw the plots and check the x axis values.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# bar charts for categorical variables\np_sex <- ggplot(d, aes(x = sex_c, fill = sex_c)) + geom_bar()\np_smok <- ggplot(d, aes(x = smoker_c, fill = smoker_c)) + geom_bar()\np_reg <- ggplot(d, aes(x = regionsum, fill = regionsum)) + geom_bar()\n\n# (so called) continuous variables\np_age <- ggplot(d, aes(x = age_c)) + geom_density(fill = \"slateblue\")\np_age_hist <- ggplot(d, aes(x = age_c)) + geom_histogram() # possibly a little more detail using a histogram?\np_bmi <- ggplot(d, aes(bmi_c)) + geom_density(fill = \"red\")\np_child <- ggplot(d, aes(child_c)) + geom_histogram()\ngrid.arrange(p_sex, p_smok, p_reg, p_age_hist, p_bmi, p_child)\n```\n\n::: {.cell-output-display}\n![](Week2_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\n\n-   Note now that the axes are centred around zero for the now centred\n    continuous predictors. The mid-point of the distributions of\n    observations are also hovering around the zero mark. Note also how\n    no information has changed within and between the variables - all\n    relative relationships remain the same.\n\nLets plug the centred continuous variables and the `sex_c` centred\nvariable into the model:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m6_cen_all <- lm(charges ~ age_c + bmi_c + child_c + sex_c + smoker_c + regionsum, d))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = charges ~ age_c + bmi_c + child_c + sex_c + smoker_c + \n    regionsum, data = d)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-11304.9  -2848.1   -982.1   1393.9  29992.8 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  13289.1      165.9  80.079  < 2e-16 ***\nage_c          256.9       11.9  21.587  < 2e-16 ***\nbmi_c          339.2       28.6  11.860  < 2e-16 ***\nchild_c        475.5      137.8   3.451 0.000577 ***\nsex_c         -131.3      332.9  -0.394 0.693348    \nsmoker_c     23848.5      413.1  57.723  < 2e-16 ***\nregionsum1    -448.0      291.2  -1.538 0.124219    \nregionsum2     587.0      293.1   2.003 0.045411 *  \nregionsum3     234.1      292.9   0.799 0.424427    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6062 on 1329 degrees of freedom\nMultiple R-squared:  0.7509,\tAdjusted R-squared:  0.7494 \nF-statistic: 500.8 on 8 and 1329 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nRemember that by centring our continuous predictors, the intercepts now\nrepresents the continuous predictors at the sample average.\n\nSo what does the intercept represent now? A non-smoking female of\napproximately 40 year of age, with a BMI value of about 30 units, with\none child, who lives in SW USA. That makes more sense.\n\nYou'll notice that there is a change on the intercept value. The\nintercept is no longer a negative unit value. Although it would be nice\nto think that people could pay negative insurance charges - what does\nthat mean? That everyone is in debt? That the health treatment costs\nless than 0?\n\nAnd the centred variable of `sex_c` now describes the full value of\nmoving from female (in the intercept) to male for changes in insurance\ncharges.\n\n### Standardising Variables\n\nCreate some more variables to store the standardised variables, which we\nwill create next.\n\nRemember to create a standardised variable, we first centre the variable\nand then divide it by its standard deviation\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create new variables to store the standardised values\n# I use _z1 because they are z-scores that are made by dividing by 1 standard deviation\n# these are standardised by dividing by 1 x sd:\n\nd <- d %>% \n  mutate(age_z1 = (age - mean(age)) / sd(age), # new variable = centred variable divided by the standard deviation of the centred variable\n         bmi_z1 = (bmi - mean(bmi)) / sd(bmi),\n         child_z1 = (children - mean(children)) / sd(children),\n         sex_z1 = sex_c / sd(sex_c),\n         smoker_z1 = smoker_c / sd(smoker_c)\n         )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# bar charts for categorical variables\np_sex_c <- ggplot(d, aes(x = sex_z1, fill = sex_z1)) + geom_bar()\np_smok_c <- ggplot(d, aes(x = smoker_z1, fill = smoker_z1)) + geom_bar()\np_regsum <- ggplot(d, aes(x = regionsum, fill = regionsum)) + geom_bar()\n\n# frequency polygons for (so called) continuous variables\np_age_z1 <- ggplot(d, aes(x = age_z1)) + geom_histogram() # possibly a little more detail using a histogram?\np_bmi_z1 <- ggplot(d, aes(bmi_z1)) + geom_density(fill = \"red\")\np_child_z1 <- ggplot(d, aes(child_z1)) + geom_histogram()\ngrid.arrange(p_sex_c, p_smok_c, p_regsum, p_age_z1, p_bmi_z1, p_child_z1)\n```\n\n::: {.cell-output-display}\n![](Week2_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n:::\n\n\n\nOnly the axes have changed once more....the centre is still zero but the\nunits are now in standard deviations.\n\nThis line of code charts correlations between columns 18 - 20 of the\ndataset `d` - i.e. the standardised varaibles we just made. The\ncorrelation coefficients are exactly the same as those that are between\nthe raw variables (see earlier in the script).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchart.Correlation(d[, c(18:20)], histogram=TRUE, pch=19)\n```\n\n::: {.cell-output-display}\n![](Week2_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n\n\n#### Refit the Model with Standardised Variables\n\nWhat happens when we use the standardised variables with the centred\nbinary variables:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m6_z <- lm(charges ~ age_z1 + bmi_z1 + child_z1 + sex_z1 + smoker_z1 + regionsum, d))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = charges ~ age_z1 + bmi_z1 + child_z1 + sex_z1 + \n    smoker_z1 + regionsum, data = d)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-11304.9  -2848.1   -982.1   1393.9  29992.8 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 13289.09     165.95  80.079  < 2e-16 ***\nage_z1       3608.82     167.18  21.587  < 2e-16 ***\nbmi_z1       2068.47     174.40  11.860  < 2e-16 ***\nchild_z1      573.21     166.12   3.451 0.000577 ***\nsex_z1        -65.68     166.53  -0.394 0.693348    \nsmoker_z1    9627.51     166.79  57.723  < 2e-16 ***\nregionsum1   -448.01     291.24  -1.538 0.124219    \nregionsum2    587.01     293.11   2.003 0.045411 *  \nregionsum3    234.05     292.92   0.799 0.424427    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6062 on 1329 degrees of freedom\nMultiple R-squared:  0.7509,\tAdjusted R-squared:  0.7494 \nF-statistic: 500.8 on 8 and 1329 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nThe intercept is the same, because no reference levels have changed;\n`sex` and `smoker` are now smaller; the direction of effects remains\nsimilar: males are associated with less insurance charges, and smokers\nare associated with more than non-smokers. The `region` coefficients are\nthe same because we didn't change them; The magnitude of the\ncoefficients for `age`, `bmi` and `children` are now bigger, because we\nare predicting a change for one standard deviation, rather than one raw\nunit. But look at their *t* values - they have not changed. Nor has the\namount of variance explained.\n\nThe gift of standardisation is that is calms down the model - gone is\nthe huge \\$23,848 prediction for smokers. And now we *can* see the\nrelative strengths of predictors, because all the predictors are\nmeasuring changes on the same scale of an increase in one standard\ndeviation unit. We can see that `smoker` is the strongest predictor,\nfollowed by `age` and `bmi`, with each associated with a positive\nrelationship on insurance charges - as they increase, so does insurance\ncharges.\n\n#### Transform: Standardising by Two Standard Deviations - extra\n\nThis is useful to know if you want to have your continuous variables act\nas if they are a categorical variable of two levels, for instance,\ntransforming a continuous variable of age into two groups of young or\nold / high or low. This is not on the class test.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create new variables to store the standardised values\n# these are standardised by dividing by 1 x sd:\n\nd <- d %>% \n  mutate(age_z2 = (age - mean(age)) / (2*sd(age)), # new variable = centred variable divided by the standard deviation of the centred variable\n         bmi_z2 = (bmi - mean(bmi)) / (2*sd(bmi)),\n         child_z2 = (children - mean(children)) / (2*sd(children))\n         )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# bar charts for categorical variables\np_sex_c <- ggplot(d, aes(x = sex_c, fill = sex_c)) + geom_bar()\np_smok_c <- ggplot(d, aes(x = smoker_c)) + geom_bar()\np_regsum <- ggplot(d, aes(x = regionsum, fill = regionsum)) + geom_bar()\n\n# frequency polygons for (so called) continuous variables\np_age_z2 <- ggplot(d, aes(x = age_z2)) + geom_histogram() # possibly a little more detail using a histogram?\np_bmi_z2 <- ggplot(d, aes(bmi_z2)) + geom_density(fill = \"red\")\np_child_z2 <- ggplot(d, aes(child_z2)) + geom_histogram()\ngrid.arrange(p_sex_c, p_smok_c, p_regsum, p_age_z2, p_bmi_z2, p_child_z2)\n```\n\n::: {.cell-output-display}\n![](Week2_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n:::\n\n\n\nOnly the axes have changed once more....the centre is still zero, the\nunits are still in standard deviations and look how the range is from a\nminus to the centre and then a centre to the plus. Two jumps to move\nfrom one end of the values to other end - a little bit like the sum\ncoding procedure of moving from -1 to 1 in two jumps.\n\nAs I said, you may not use this very much, but it might be a handy\nlittle trick in your future - you never know!\n\n### Ordered Variables?\n\nConsider the `children` variable - so far I have treated it as a\ncontinuous variable but it's categorical: look at the histogram above\nagain. There are no values between the distinct categories.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(d$children) # summary as a continuous predictor\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  0.000   0.000   1.000   1.095   2.000   5.000 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(d$children_f <- factor(d$children)) # wrap the factorising command within a summary command for speed\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  0   1   2   3   4   5 \n574 324 240 157  25  18 \n```\n\n\n:::\n:::\n\n\n\nThe variable `children` could also be considered as ordinal in that\nwithin a family, birth order has meaning. This gives us an opportunity\nto look at a final level of contrast coding for ordinal variables -\n`helmert` contrast coding.\n\n`Helmert` contrasts can work forwards and backwards. The default\nfunction that we are going to use in R works backwards. This means that\neach coefficient represents the difference in Y for the level in the\nfactor, compared to all the previous levels (or the mean of the previous\nlevels) in the factor.\n\nLets look at an example to make this a little bit more clear:\n\nFirst we transform our `children` variable into a `helmert` contrasted\nvariable:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a new variable first\nd$children_h <- factor(d$children)\n\n# and then apply an ordered contrast scheme\n(contrasts(d$children_h) <- contr.helmert(6))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  [,1] [,2] [,3] [,4] [,5]\n1   -1   -1   -1   -1   -1\n2    1   -1   -1   -1   -1\n3    0    2   -1   -1   -1\n4    0    0    3   -1   -1\n5    0    0    0    4   -1\n6    0    0    0    0    5\n```\n\n\n:::\n\n```{.r .cell-code}\n# levels(d$children_h) # checking the order of levels in the children_h variable\n```\n:::\n\n\n\nYou don't have to fully understand this matrix. This level of detail\nwill not be on the class test. However, some of you will appreciate the\ndetail.\n\nLook at column \\[ ,1\\] first. This tells us that the first beta\ncoefficient for this variable in the model output will be the comparison\nbetween the first two categories of the `children_h` variable, which is\nbetween families with no children and families with one child.\n\nNow look at column \\[ ,2\\]. This tells us that the second beta\ncoefficient for the variable will show a comparison between families\nwith two children and families with either no children or one child and\nso on.\n\nLets fit the model one last time and include this helmert contrasted\nvariable\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m6_zh <- lm(charges ~ age_z1 + bmi_z1 + children_h + sex_z1 + smoker_z1 + regionsum, d))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = charges ~ age_z1 + bmi_z1 + children_h + sex_z1 + \n    smoker_z1 + regionsum, data = d)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-11689.4  -2902.6   -943.7   1492.2  30042.7 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 13893.32     337.07  41.218  < 2e-16 ***\nage_z1       3613.56     167.40  21.587  < 2e-16 ***\nbmi_z1       2054.53     174.48  11.775  < 2e-16 ***\nchildren_h1   195.49     210.68   0.928  0.35362    \nchildren_h2   480.10     148.35   3.236  0.00124 ** \nchildren_h3    72.19     130.47   0.553  0.58017    \nchildren_h4   439.92     245.53   1.792  0.07341 .  \nchildren_h5   -11.94     243.80  -0.049  0.96094    \nsex_z1        -64.10     166.47  -0.385  0.70025    \nsmoker_z1    9622.62     167.19  57.557  < 2e-16 ***\nregionsum1   -441.62     291.54  -1.515  0.13006    \nregionsum2    591.52     293.16   2.018  0.04382 *  \nregionsum3    211.47     293.68   0.720  0.47160    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6059 on 1325 degrees of freedom\nMultiple R-squared:  0.7519,\tAdjusted R-squared:  0.7497 \nF-statistic: 334.7 on 12 and 1325 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nThe `children_h` predictor has an separate coefficient for each level of\nthe categorical variable. Previously, we had entered the `children`\npredictor as continuous, and we were getting an even rate of change in\ncharges for each increase in one child to a family, which registered as\na significant impact on insurance charges.\n\nFirst of all, check the residuals and the significance of the model; the\nmaximum residual value is slightly bigger on this model. And the *F*\nratio is smaller. This indicates to me that there is now more\ninformation in the residuals - which tells me that this is not as good a\nfit for the data as the last model. The variance explained has not\nchanged, so we have estimated more coefficients, and generated more\nerror for no real increase in explanatory power.\n\nHowever, we want to understand a little bit about helmert contrasts so\nwe will carry on.\n\nNow that we have transformed the variable, our interpretation of the\nmodel needs to change somewhat. The rate of change in insurance charges\nacross the increase in children is not even (480.10 is not the same as\n72.19). This is not a linear relationship.\n\nLook at `children_h1`, the difference in insurance charges between\nfamilies with no children and families with one child is approximately\n\\$195.00.\n\nLook at `children_h2`: the difference in insurance charges for families\nwith two children and both families with one child *and* families with\nno children is approximately \\$480.00...and so on...\n\nThe only significantly different change in insurance charges is the\nchange from 0 or 1 child to two child families. Can you think of a\nreason why a familiy of two children is predicted to pay significantly\nhigher insurance charges than a family of one child?\n\n### Checking Model Assumptions and Diagnostics\n\nFor the purposes of model checking and reporting, we do not use this\nmodel; we revert back to the standardised model.\n\nEvery regression model is built upon the following assumptions:\n\n1.  The relationship between $X$ and $Y$ is assumed to be linear\n    (additive)\n2.  The residual errors are normally distributed\n3.  The residuals have constant variance (homoscedasticity)\n4.  The residuals are not correlated (assumption of independence)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2)) # display plots in a 2 x 2 panel\nplot(m6_z) # plot diagnostic plots for m6_zh\n```\n\n::: {.cell-output-display}\n![](Week2_files/figure-html/unnamed-chunk-52-1.png){width=672}\n:::\n:::\n\n\n\n**Residuals vs Fitted**: \"fitted\" here means the predicted values. We\nwant the pink line to align pretty closely with the horizontal dashed\nline. Comparing this plot with that from the simple regression, this\nplot looks better.\n\n**Normal Q-Q**: If the residual points (open circles) follow the dashed\nline, you can assume the residuals are normally distributed. It doesn't\nlook great on the right hand side, does it?\n\n**Scale-Location**: This is checking for constant variance in the\nresiduals - not much here. A good indication would be a horizontal pink\nline with equally spread points. Our graph is not good.\n\n**Residuals vs Leverage** - are there any points that are having a large\ninfluence on the regression results. They will be numbered and you can\nthen inspect them in your data file. Observations that show standardised\nresiduals (see the table above) above 3 would be problematic. As would\nobservations of a hat value above $2(p+1)/n$ where $p$ = is the number\nof predictors (but see below) and $n$ = is the number of observations\n\n#### A different way to observe points with high leverage and high influence:\n\nIn last week's script, with a small data set, we used a formula for\ncalculating hat values and Cook's Distance values and looked across some\nvalues after calling our residuals using the `augment` function.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(head(m6z_metrics <- augment(m6_z)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 13\n  charges age_z1 bmi_z1 child_z1 sex_z1 smoker_z1 regionsum .fitted  .resid\n    <dbl>  <dbl>  <dbl>    <dbl>  <dbl>     <dbl> <fct>       <dbl>   <dbl>\n1  16885. -1.44  -0.453  -0.908  -1.01      1.97  SW         25294. -8409. \n2   1726. -1.51   0.509  -0.0787  0.989    -0.508 SE          3449. -1723. \n3   4449. -0.798  0.383   1.58    0.989    -0.508 SE          6707. -2258. \n4  21984. -0.442 -1.31   -0.908   0.989    -0.508 NW          3755. 18230. \n5   3867. -0.513 -0.292  -0.908   0.989    -0.508 NW          5592. -1726. \n6   3757. -0.584 -0.807  -0.908  -1.01     -0.508 SE          3720.    36.8\n# ℹ 4 more variables: .hat <dbl>, .sigma <dbl>, .cooksd <dbl>, .std.resid <dbl>\n```\n\n\n:::\n:::\n\n\n\nColumns 1 - 7 are our variables. `fitted` and `residuals` are the\npredicted values of charges and the `error` values, respectively. And\nlast week we manually inspected the `.hat` and the `.cooksd` column for\nvalues that were above a certain threshold.\n\nBut this dataset has over 1000 observations. Plus, we are modelling both\ncontinuous and categorical predictors. It gets hard to manually inspect\ndataframes that have many observations and even harder to manage this\nfor complex models. So an easier way is to have R sort out your high\ninfluence and leverage values and then plot them:\n\n#### Graphing Model Hat Values and Observations with High Leverage:\n\n1.  calculate hat value using the formula\n2.  use the hat value and filter out any observations from the augmented\n    dataset that are above the threshold\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- length(coefficients(m6_z)) # number of parameters estimated by the model\nN <- nrow(d) # number of observations\n\n\n# 1) calulate the hat value\n(m6z_hat <- (2*(p+1))/N)  # model hat value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01494768\n```\n\n\n:::\n\n```{.r .cell-code}\n# 2) filter out observations that are above the hat value in the augmented dataset\nm6z_hatvalues <- m6z_metrics %>% \n  filter(.hat > 0.01494768) \n\n# 2) this is equivalent code, rather than hard coding the hat value, you put in the \n# object label that we just created for the hat value on line 663\nm6z_hatvalues_1 <- m6z_metrics %>% \n  filter(.hat > m6z_hat) \n```\n:::\n\n\n\nFour residuals are showing values of larger than the model hat value.\n\n3)  Plot them: `hat.plot` function taken from Kabacoff, (2022), R in\n    Action.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhat.plot <- function(fit) {\n              p <- length(coefficients(fit))\n              n <- length(fitted(fit))\n              plot(hatvalues(fit), main=\"Index Plot of Hat Values\")\n              abline(h=c(2,3)*p/n, col=\"red\", lty=2)\n              identify(1:n, hatvalues(fit), names(hatvalues(fit)))\n            }\n\nhat.plot(m6_z)\n```\n\n::: {.cell-output-display}\n![](Week2_files/figure-html/unnamed-chunk-55-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\ninteger(0)\n```\n\n\n:::\n:::\n\n\n\nChecking for observations that are influential follows a similar\npattern: observations that exceed the *Cook's distance* value =\n$4/(n-p-1)$ are likely to have high influence and the regression results\nmay change if you exclude them. In the presence of such observations\nthat exceed Cook's distance, unless you know the observation are errors,\nyou probably need to estimate the model without the observations and\nreport both sets of results.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(m6z_Cooks <- 4/(N-p-1)) # model Cook's distance value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.003012048\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nm6z_Cooksvalues <- m6z_metrics %>% \n  filter(.cooksd > 0.003012048) \n\n# or\n\nm6z_Cooksvalues_1 <- m6z_metrics %>% \n  filter(.cooksd > m6z_Cooks) \n\n# 83 residuals\n\n# make sure your dataset is in nrow() function\n# and your model is before $coefficients and in the plot line\n# here it is m6_z\n# when you are ready to draw the plot\n# select all three lines at once and press control and enter\n# or rerun the chunk by pressing the green arrow in the top right hand corner.\ncutoff <- 4/(nrow(d)-length(m6_z$coefficients)-1)\nplot(m6_z, which=4, cook.levels=cutoff)\nabline(h=cutoff, lty=2, col=\"red\")\n```\n\n::: {.cell-output-display}\n![](Week2_files/figure-html/unnamed-chunk-57-1.png){width=672}\n:::\n:::\n\n\n\nThere are 83 observations that appear to be influential within the\ndataset, however the three labelled here are particularly offensive. If\nwe were to continue our analysis at this point, we may be be filtering\nout some observations and running the model once more as a sensitivity\nanalysis.\n\n## Communicate:\n\nLets reprint the summary to save scrolling but also save the summary to\nan object so that we can call the values while interpreting and\nreporting the model\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(m6_z_summary <- summary(m6_z))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = charges ~ age_z1 + bmi_z1 + child_z1 + sex_z1 + \n    smoker_z1 + regionsum, data = d)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-11304.9  -2848.1   -982.1   1393.9  29992.8 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 13289.09     165.95  80.079  < 2e-16 ***\nage_z1       3608.82     167.18  21.587  < 2e-16 ***\nbmi_z1       2068.47     174.40  11.860  < 2e-16 ***\nchild_z1      573.21     166.12   3.451 0.000577 ***\nsex_z1        -65.68     166.53  -0.394 0.693348    \nsmoker_z1    9627.51     166.79  57.723  < 2e-16 ***\nregionsum1   -448.01     291.24  -1.538 0.124219    \nregionsum2    587.01     293.11   2.003 0.045411 *  \nregionsum3    234.05     292.92   0.799 0.424427    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6062 on 1329 degrees of freedom\nMultiple R-squared:  0.7509,\tAdjusted R-squared:  0.7494 \nF-statistic: 500.8 on 8 and 1329 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nA results section for multiple regression may have three parts\n\n-   Descriptive statistics for continuous variables and quantities of\n    observations in each categorty for categorical variables\n-   A correlation matrix that shows bivariate correlations between the\n    continuous predictors\n-   A model summary and some narrative text to communicate the\n    predictions from the model\n\n### Descriptive Statistics\n\nDepending on your hypothesis, you may report descriptive statistics\ndifferently from here. For instance if a hypothesis was present for an\ninteraction of any of the predictors with sex, then the descriptive\nstatistics section would be presented with means and sd and categories\nfor the other variables split by gender.\n\nIn this model, there is a flat structure, - i.e. no interactions, so we\nwill go for basic mean and sd values or number of observations per\ncategory. The code below pulls out all the relevant information; I leave\nit to you to manage the formatting for reporting in a results section.\nClick between the two boxes in the output to see the two kinds of\ninformation for a) the continuous variables and b) the categorical\nvariables.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(Desc_stat <- d %>% \n # group_by(sex) %>% \n  summarise(n = n(), # number of obs in each sex category\n            Age = round(mean(age),1),\n            `SD Age` = round(sd(age),1),\n            BMI = round(mean(bmi),1),\n            `SD BMI` = round(sd(bmi),1),\n            Children = round(mean(children),1),\n            `SD Children` = round(sd(children), 1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 7\n      n   Age `SD Age`   BMI `SD BMI` Children `SD Children`\n  <int> <dbl>    <dbl> <dbl>    <dbl>    <dbl>         <dbl>\n1  1338  39.2       14  30.7      6.1      1.1           1.2\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(d$children)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  0   1   2   3   4   5 \n574 324 240 157  25  18 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(d$smoker)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n yes   no \n 274 1064 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(d$sex)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  male female \n   676    662 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(d$region)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n SE  NE  NW  SW \n364 324 325 325 \n```\n\n\n:::\n\n```{.r .cell-code}\n# It would be up to you to choose how to arrange a table, given the different numbers of levels across the categorical variables.\n```\n:::\n\n\n\n### Correlations between (truly) continous predictors\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(d_cor <- d %>% \n  select(age, bmi, children) %>% \n  cor() %>% \n  as.dist() %>% \n  round(2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          age  bmi\nbmi      0.11     \nchildren 0.04 0.01\n```\n\n\n:::\n\n```{.r .cell-code}\n# The output here could be a second table\n```\n:::\n\n\n\n### Inferential Statistics - Model Coefficients, SEs, *t*-values and *p* values\n\nThere are some nice packages that will pull out coefficients for you,\nbut it is also a good idea to know how to build a model summary in\nlonghand. The code below is one example of a longhand approach. You can\ncompare the output here with the output given for the model above.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get model predictions / coefficients\nEstimate <- round(coef(m6_z), 2)\n# calculate the coefficient standard errors\nSE <- sqrt(diag(vcov(m6_z)))\n# calculate the t-value of the t-test for each predictors coefficient\nt <- round((Estimate / SE), 2)\n# Extract the p-values of the predictors from the model\np <- round(summary(m6_z)$coefficients[, \"Pr(>|t|)\"], 3)\n\n# Write a list of labels for your predictors - be sure you get them in the accurate order\nPredictor <- c(\"Intercept\", \"Age\", \"BMI\", \"No. of Children\",\n               \"Sex: Male\", \"Smoker: Yes\",\"Region: SE\",\n               \"Region: NE\", \"Region: NW\")\n\n# Arrange in a data frame, in the order of columns you want in your table\nModel_values <- data_frame(Predictor,Estimate, SE, t, p,)\n\n# tidy up p-values according to APA7 formatting\nModel_values$p <- ifelse(p == 0.000, \"< .001\", p)\n\n# print model output\nModel_values\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 5\n  Predictor       Estimate    SE     t p     \n  <chr>              <dbl> <dbl> <dbl> <chr> \n1 Intercept        13289.   166. 80.1  < .001\n2 Age               3609.   167. 21.6  < .001\n3 BMI               2068.   174. 11.9  < .001\n4 No. of Children    573.   166.  3.45 0.001 \n5 Sex: Male          -65.7  167. -0.39 0.693 \n6 Smoker: Yes       9628.   167. 57.7  < .001\n7 Region: SE        -448.   291. -1.54 0.124 \n8 Region: NE         587.   293.  2    0.045 \n9 Region: NW         234.   293.  0.8  0.424 \n```\n\n\n:::\n:::\n\n\n\nThe `broom` package does this also. However, on small models (for\nnumbers of predictors), I like the level of control to be able to do it\nlike this. You may find another way as you learn and that is good too.\n\nI leave it to you to format the `Model_values` dataframe into a table\nfor presentation. Remember to also report your F ratio for the model and\nits significance value along with the variance explained.\n\n### Reporting Text\n\nWe conducted a multiple regression for the association of several\npredictor variables with the outcome variable of insurance charges. We\nstandardised all continuous predictors as well as the predictors for Sex\nand Smoker Status. Region is a sum-coded variable, with South West being\nthe reference level variable.\n\nWithout engaging in any sensitivity analysis or outlier analysis, we\nreport a model with a full set of predictors. The model is significant\n($F(8, 1329)$ = 500.81, *p* \\<\n0.001). This set of predictors explains\n75.09% of the variance in insurance\ncharges.\n\nThe following details the significant predictors in this model. Each\nvalue represents the change in insurance charges for a one standard\ndeviation change in the predictor, holding all other variables constant.\n\nAge shows a positive association with insurance charges, with an\nincrease in approximately \\$3608 for a one standard deviation unit\nchange on the age scale (age: *t* =\n21.59, *p* \\< .001). A person's\nbody mass index (BMI) also shows a positive relationship and increases\ninsurance charges by approximately \\$2068 with a one standard deviation\nchange in BMI score (*t* =\n11.86, *p* \\< .001). An increase\nin number of children in a family was positively associated with an\nincrease in insurance charges (*b* = 573.21, *t* = 3.45, *p* \\< .001).\nBeing a male individual is negatively associated with insurance charges,\nlowering insurance costs by approximately \\$65, however this increase is\nnon-significant (*t* = -0.39,\n*p* = .693). Being a smoker is significantly and positively associated\nwith an increase in insurance charges, raising insurance costs by\napproximately \\$9,627 (*t* =\n57.72, *p* \\< .001). While\nliving in the northeast region of the country also shows a positive\nassociation with insurance charges compared to living in the southwest\nregion (reference level), showing an increase of around \\$587 (*t* =\n2, *p* =\n0.045).\n\nWe should be cautious with these interpretations as the residuals show\nthat there is unexplained variability and there are a number of\nobservations that are indicated as having high leverage or high\ninfluence so further terms and sensitivity analyses are warranted for a\nfuller understanding.\n\n### Plotting predictions\n\nPlotting an individual effect (or lack of it) is very simple if we are\nnot too worried about being pretty. Plus - because we haven't changed\nany of the essential information in any of the coding / centring\nschemes, you can choose how to plot them, based upon the model. This is\nthe skill of the communication part - which plot would make more sense\nto your reader - a plot with a standardised x-axis or a plot with raw\nunits on the x-axis?\n\nLook at the x-axis on the following two plots to compare and make your\nconsidered decision:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# standardised variable plot\nplot(predictorEffect(\"age_z1\", m6_z))\n```\n\n::: {.cell-output-display}\n![](Week2_files/figure-html/unnamed-chunk-62-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# raw unit plot\nplot(predictorEffect(\"age\", m6))\n```\n\n::: {.cell-output-display}\n![](Week2_files/figure-html/unnamed-chunk-62-2.png){width=672}\n:::\n:::\n\n\n\nHere are the plots for the predictors from the final model, but you\ncould change the code to reflect the predictor labels and the model\nlabels. Just be consistent - choose one scale rather than jumping\nbetween multiple scales for your plots.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(predictorEffect(\"age_z1\", m6_z))\n```\n\n::: {.cell-output-display}\n![](Week2_files/figure-html/unnamed-chunk-63-1.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(predictorEffect(\"bmi_z1\", m6_z))\n```\n\n::: {.cell-output-display}\n![](Week2_files/figure-html/unnamed-chunk-63-2.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(predictorEffect(\"child_z1\", m6_z))\n```\n\n::: {.cell-output-display}\n![](Week2_files/figure-html/unnamed-chunk-63-3.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(predictorEffect(\"sex_z1\", m6_z))\n```\n\n::: {.cell-output-display}\n![](Week2_files/figure-html/unnamed-chunk-63-4.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(predictorEffect(\"smoker_z1\", m6_z))\n```\n\n::: {.cell-output-display}\n![](Week2_files/figure-html/unnamed-chunk-63-5.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(predictorEffect(\"regionsum\", m6_z))\n```\n\n::: {.cell-output-display}\n![](Week2_files/figure-html/unnamed-chunk-63-6.png){width=672}\n:::\n:::\n\n\n\nI think plotting of the effects is probably much better for\ncommunication using the effects from the model with the raw data (the\nfirst model). I leave it to you to adapt the code to make this change.\n\nBut the model building is not complete. It is likely that there are\ninteractions that could be put into the model and age, as a variable,\nmay be nonlinear - how to deal with both of these is for the next\nlecture.\n\nThere are lots of things to do as we run a multiple regression model -\nboth before, while and after building the model, which will be the focus\nof the future lectures. We need to look at:\n\n-   a model with some significant predictors! - done\n-   correlation matrices - done\n-   centering predictors - done\n-   standardising predictors - done\n-   models with categorical predictors - done & ongoing\n    -   interpreting models with categorical predictors - done & ongoing\n-   models with interaction terms\n-   the properties of multicollinearity\n-   choosing between different models\n-   reporting models - ongoing\n\n## Week 11 - 12 Pre-Lab Activity and Week 12 Lab Task\n\nIn this lab, you will be working with the R script, data and Codebook\nstored [here](data/Wk2/Week_12_234_Materials.zip), and the accompanying\ncodebook is accessed in the slides and codebook folder,\n[here](data/Wk2/Week_12_234_Slides_Codebook.zip), called\n\"Data_Codebook.pdf\".\n\nWork through the Week12_R_Script.Rmd file and enter in your own code to\narrive at the following model summary and figures. All these images are\nstored in the Outputs folder that comes down in the Week 12 .zip file:\n\n![Model summary](Images/Wk2/Model%20Summary%20Output.png)\n\n![Visualise Predictors](Images/Wk2/Visualise_Predictors.png)\n\n![Visualise\nCorrelations](Images/Wk2/Visualise_Bivariate_Correlations.png)\n\n![Predictor Absence](Images/Wk2/Predictor_plot_absences_z1.png)\n![Predictor Health](Images/Wk2/Predictor_Plot_health_z1.png) ![Predictor\nSchool](Images/Wk2/Predictor_Plot_school_c.png) ![Predictor\nWalc](Images/Wk2/Predictor_plot_walc_h.png) ![Predictor\nSex](Images/Wk2/PredictorPlot_sex_c.png)\n\n### Submit Scripts\n\nif you want the chance to receive feedback on your scripts.\n\n## Model script\n\nA model script showing one way of answering the research questions above\nusing R will be available on the module moodle next week.\n",
    "supporting": [
      "Week2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}