{
  "hash": "a22b9df6bbf08583215e992078e94b49",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"2023-24-PSYC122-w16-workbook-answers\"\nauthor: Rob Davies\ndate: \"2024-02-12\"\noutput: word_document\n---\n\n\n\n\n\n\n# Introduction\n\n\nIn Week 16, we aim to develop skills in visualizing and testing the associations\nbetween variables in psychological data.\n\nWe do this to learn how to answer research questions like:\n\n1. What person attributes predict success in understanding?\n2. Can people accurately evaluate whether they correctly understand written\nhealth information?\n\nThese kinds of research questions can be answered using methods like **correlation**\nand **linear models**.\n\nWe will consolidate and extend learning on **data visualization**:\n\n- Use histograms to examine the distributions of variables;\n- Use scatterplots to examine the relationships we may observe or predict.\n\n## Naming things\n\nI will format dataset names like this: \n\n- `study-two-general-participants.csv`\n\nI will also format variable (data column) names like this: `variable` \n\nI will also format value or other data object (e.g. cell value) names like this: `studyone`\n\nI will format functions and library names like this: e.g. function `ggplot()` or e.g. library `{tidyverse}`.\n\n## The data we will be using\n\nIn this activity, we use data from *a second* 2020 study of the response\nof adults from a UK national sample to written health information:\n\n- `study-two-general-participants.csv`\n\n\n# Answers\n\n\n## Step 1: Set-up\n\n\nTo begin, we set up our environment in R.\n\n\n### Task 1 -- Run code to empty the R environment\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list=ls())                            \n```\n:::\n\n\n\n\n### Task 2 -- Run code to load relevant libraries\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"tidyverse\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.0     ✔ readr     2.1.6\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.2     ✔ tibble    3.3.1\n✔ lubridate 1.9.4     ✔ tidyr     1.3.2\n✔ purrr     1.2.1     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n:::\n\n\n\n\n## Step 2: Load the data\n\n\n### Task Task 3 -- Read in the data file we will be using\n\nThe data file is called:\n\n- `study-two-general-participants.csv`\n\nUse the `read_csv()` function to read the data file into R:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudy.two.gen <- read_csv(\"study-two-general-participants.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 172 Columns: 12\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (5): participant_ID, study, GENDER, EDUCATION, ETHNICITY\ndbl (7): mean.acc, mean.self, AGE, SHIPLEY, HLVA, FACTOR3, QRITOTAL\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n\nWhen you read the data file in, give the data object you create a clear name \ne.g. `study.two.gen`.\n\n\n### Task 4 -- Inspect the data file\n\nUse the `summary()` or `head()` functions to take a look\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(study.two.gen)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n participant_ID        mean.acc        mean.self        study          \n Length:172         Min.   :0.4107   Min.   :3.786   Length:172        \n Class :character   1st Qu.:0.6786   1st Qu.:6.411   Class :character  \n Mode  :character   Median :0.7679   Median :7.321   Mode  :character  \n                    Mean   :0.7596   Mean   :7.101                     \n                    3rd Qu.:0.8393   3rd Qu.:7.946                     \n                    Max.   :0.9821   Max.   :9.000                     \n      AGE           SHIPLEY           HLVA           FACTOR3     \n Min.   :18.00   Min.   :23.00   Min.   : 3.000   Min.   :29.00  \n 1st Qu.:25.00   1st Qu.:32.75   1st Qu.: 7.750   1st Qu.:47.00  \n Median :32.50   Median :36.00   Median : 9.000   Median :51.00  \n Mean   :35.37   Mean   :35.13   Mean   : 9.064   Mean   :51.24  \n 3rd Qu.:44.00   3rd Qu.:39.00   3rd Qu.:11.000   3rd Qu.:56.25  \n Max.   :76.00   Max.   :40.00   Max.   :14.000   Max.   :63.00  \n    QRITOTAL        GENDER           EDUCATION          ETHNICITY        \n Min.   : 6.00   Length:172         Length:172         Length:172        \n 1st Qu.:12.00   Class :character   Class :character   Class :character  \n Median :14.00   Mode  :character   Mode  :character   Mode  :character  \n Mean   :13.88                                                           \n 3rd Qu.:16.00                                                           \n Max.   :20.00                                                           \n```\n\n\n:::\n:::\n\n\n\n- Q.1. What is the median of `AGE`?\n\n- A.1. 32.50  \n\n- Q.2. What class is the variable `ETHNICITY`?\n\n- A.2. character  \n\n- Q.3. Does the summary indicate if any variable has missing values (NAs)?\n\n- Q.3. No\n\n\n### Task 5 -- Change the class or type of the variable `ETHNICITY` to factor\n\nYou can use the `as.factor()` function you have used before:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudy.two.gen$ETHNICITY <- as.factor(study.two.gen$ETHNICITY)\n```\n:::\n\n\n\n- Q.4. After you have done this, what information does `summary()` give you \nabout the variable `ETHNICITY`?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(study.two.gen)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n participant_ID        mean.acc        mean.self        study          \n Length:172         Min.   :0.4107   Min.   :3.786   Length:172        \n Class :character   1st Qu.:0.6786   1st Qu.:6.411   Class :character  \n Mode  :character   Median :0.7679   Median :7.321   Mode  :character  \n                    Mean   :0.7596   Mean   :7.101                     \n                    3rd Qu.:0.8393   3rd Qu.:7.946                     \n                    Max.   :0.9821   Max.   :9.000                     \n      AGE           SHIPLEY           HLVA           FACTOR3     \n Min.   :18.00   Min.   :23.00   Min.   : 3.000   Min.   :29.00  \n 1st Qu.:25.00   1st Qu.:32.75   1st Qu.: 7.750   1st Qu.:47.00  \n Median :32.50   Median :36.00   Median : 9.000   Median :51.00  \n Mean   :35.37   Mean   :35.13   Mean   : 9.064   Mean   :51.24  \n 3rd Qu.:44.00   3rd Qu.:39.00   3rd Qu.:11.000   3rd Qu.:56.25  \n Max.   :76.00   Max.   :40.00   Max.   :14.000   Max.   :63.00  \n    QRITOTAL        GENDER           EDUCATION         ETHNICITY  \n Min.   : 6.00   Length:172         Length:172         Asian: 15  \n 1st Qu.:12.00   Class :character   Class :character   Black:  5  \n Median :14.00   Mode  :character   Mode  :character   Mixed:  7  \n Mean   :13.88                                         White:145  \n 3rd Qu.:16.00                                                    \n Max.   :20.00                                                    \n```\n\n\n:::\n:::\n\n\n\n- A.4. We can see that ETHNICITY lists observations following UK Office National Statistics ethnicity grouping:\n\n- Asian: 15\n- Black: 5\n- Mixed: 7\n- White: 145\n\n\n## Step 3: Use histograms to examine the distributions of variables\n\n\n### Task 6 -- Draw histograms to examine the distributions of variables\n\n#### Hint: Task 6\n\nUse `ggplot()` with `geom_histogram()`.\n\nThe first time we do this, we take things step-by-step.\n\nHere's an example: run the line of code and see the result in the `Plots` window \nin `R-Studio`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = mean.acc)) + geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](2023-24-PSYC122-w16-workbook-answers_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\nThese are the steps, set out one at a time:\n\n1. `ggplot(...)` you tell R you want to make a plot using the `ggplot()` function\n2. `ggplot(data = study.two.gen ...)` you tell R you want to make a plot with the\n`study.two.gen` data\n3. `ggplot(..., aes(x = mean.acc))` you tell R that you want to make a plot with \nthe variable `mean.acc` -- here, you specify the aesthetic mapping, `x = mean.acc`\n4. `ggplot(...) + geom_histogram()` you tell R you want to plot values of `mean.acc` \nas a histogram\n\n#### Questions: Task 6\n\n- Q.5. Did you get a message in the `Console` window in `R-Studio`: \nwhat does it say?\n\n- A.5. The message says:\n\n- `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n\n- Q.6. Draw two different histograms to examine the distributions of two \ndifferent variables: `SHIPLEY` and `HLVA`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = SHIPLEY)) + geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](2023-24-PSYC122-w16-workbook-answers_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = HLVA)) + geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](2023-24-PSYC122-w16-workbook-answers_files/figure-html/unnamed-chunk-8-2.png){width=672}\n:::\n:::\n\n\n\n- Q.7. Now re-do both plots: can you change the binwidth in `geom_histogram()` to make the bars wider?\n\nIf you are going to change binwidth the number you use needs to be a number larger than   \nthe minimum and smaller than the maximum for the variable.\n\nRemember, min and max values are given for each numeric variable in `summary()`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = SHIPLEY)) + geom_histogram(binwidth = 2)\n```\n\n::: {.cell-output-display}\n![](2023-24-PSYC122-w16-workbook-answers_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = HLVA)) + geom_histogram(binwidth = 2)\n```\n\n::: {.cell-output-display}\n![](2023-24-PSYC122-w16-workbook-answers_files/figure-html/unnamed-chunk-9-2.png){width=672}\n:::\n:::\n\n\n\nWe adjust binwidth typically to improve the appearance of the plot.\n\nThis is a bit subjective so try different numbers and see how you feel about the \nchanges in appearance.\n\nWe want histograms that show us enough detail about the frequency of occurrence \nof groupings (bins) of values for each variable.\n\nBut we do not want histograms that show us so much detail it is difficult to see \nthe pattern for the distribution.\n\n- Q.8 -- How would you describe the distributions -- in a sentence -- of the distributions of the\n`SHIPLEY` and `HLVA` variable values for our sample?\n\n- A.8. The `SHIPLEY` values lie between about 25 and 40, and are skewed towards high scores.\n- A.8. The `HLVA` values lie between 4 and about 14, and peak in the middle (near 7).\n\n\n## Step 4: Edit your plots to make them look good\n\n\n### Task 7 -- Edit the appearance of a histogram plot for *one numeric variable* \n\nNote that `ggplot()` code does not all have to be on the same line.\n\nYou can create a new plot for each edit so you can see what difference your edits make.\n\n- Q.9. Edit the appearance of the bars using `binwidth`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = HLVA)) + \n  geom_histogram(binwidth = 2)\n```\n\n::: {.cell-output-display}\n![](2023-24-PSYC122-w16-workbook-answers_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n\n- Q.10. Edit the colour of the background using `theme_bw()`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = HLVA)) + \n  geom_histogram(binwidth = 2) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](2023-24-PSYC122-w16-workbook-answers_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\n- Q.11. Edit the appearance of the labels using `labs()`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = HLVA)) + \n  geom_histogram(binwidth = 2) +\n  theme_bw() +\n  labs(x = \"HLVA\", y = \"count\")\n```\n\n::: {.cell-output-display}\n![](2023-24-PSYC122-w16-workbook-answers_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n\nNotice how, if you are doing edits in steps, one line at a time, each line in your code **except the last one** ends in a +.\n\nWhat we are doing is telling R we want this + this + this ...\nEach line then adds an extra step.\n\nYou can *break* this code by not adding a + at the end of each bit (except the last line).\n\nNotice that how to break the code, and how to figure out how to fix the break, are discussed in the how-to .R\n\n\n## Step 5: Now draw scatterplots to examine associations between variables\n\n\n### Task 8 -- Create a scatterplot to examine the association between some variables \n\nWe are working with `geom_point()` and you need x and y aesthetic mappings\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = HLVA, y = mean.acc)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](2023-24-PSYC122-w16-workbook-answers_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\nThis plot shows the possible association between x-axis variable `HLVA` and y-axis variable\n`mean.acc`.\n\nThe plot code moves through the following steps:  \n\n1. `ggplot(...)` make a plot\n2. `ggplot(data = study.two.gen, ...)` with the `study.two.gen` dataset\n3. `ggplot(...aes(x = HLVA, y = mean.acc))` using two aesthetic mappings:\n\n- x = HLVA` map `HLVA` values to x-axis (horizontal, left to right) positions\n- y = mean.acc` map `meann.acc` values to y-axis (vertical, bottom to top) positions\n\n4. `geom_point()` show the mappings as points    \n\n\n### Task 9 -- Now do scatterplots with *every* numeric predictor variable in the `study.two.gen` dataset \n\nYou always want to use as the y-axis variable the outcome `mean.acc` so:\n\n- `y = mean.acc`\n\nThen you can use each numeric predictor variable as the x-axis variable so:\n\n- `x = mean.self`\n\nRemember what we saw with `summary()`: not every variable consists of numbers  \n\nIf the `summary()` does not show you a mean for a variable, then R does not think \nthat variable is numeric\n\nIt can be hard to decide what an association looks like: \n\n#### Draw the plot, answer the question\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = mean.self, y = mean.acc)) +\n  geom_point()  \n```\n\n::: {.cell-output-display}\n![](2023-24-PSYC122-w16-workbook-answers_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n- Q.12. What is the shape (direction) of the association between `mean.self` and `mean.acc`?\n\n- A.12. Increase in `mean.self` is associated with increase in `mean.acc` \n\n#### Draw the plot, answer the question\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = AGE, y = mean.acc)) +\n  geom_point() \n```\n\n::: {.cell-output-display}\n![](2023-24-PSYC122-w16-workbook-answers_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n- Q.13. What is the shape (direction) of the association between `AGE` and `mean.acc`?\n\n- A.13. There is no clear association between `AGE` and `mean.acc`\n\n#### Draw the plot, answer the question\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = SHIPLEY, y = mean.acc)) +\n  geom_point()  \n```\n\n::: {.cell-output-display}\n![](2023-24-PSYC122-w16-workbook-answers_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n\n- Q.14. What is the shape (direction) of the association between `SHIPLEY` \nand `mean.acc`?\n\n- A.14. Increase in `SHIPLEY` is associated with increase in `mean.acc`\n\n#### Draw the plot, answer the question\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = HLVA, y = mean.acc)) +\n  geom_point() \n```\n\n::: {.cell-output-display}\n![](2023-24-PSYC122-w16-workbook-answers_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\n- Q.15. -- What is the shape (direction) of the association between `HLVA` \nand `mean.acc`?\n\n- A.15. Increase in `HLVA` is associated with increase in `mean.acc`\n\n#### Draw the plot, answer the question\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = FACTOR3, y = mean.acc)) +\n  geom_point() \n```\n\n::: {.cell-output-display}\n![](2023-24-PSYC122-w16-workbook-answers_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n  \n- Q.16. What is the shape (direction) of the association between `FACTOR3` \nand `mean.acc`?\n\n- A.16. Increase in `FACTOR3` is associated with increase in `mean.acc`\n\n#### Draw the plot, answer the question\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = QRITOTAL, y = mean.acc)) +\n  geom_point() \n```\n\n::: {.cell-output-display}\n![](2023-24-PSYC122-w16-workbook-answers_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n \n- Q.17. What is the shape (direction) of the association between `QRITOTAL` \nand `mean.acc`?\n\n- A.17. Increase in `QRITOTAL` is associated with increase in `mean.acc`\n\n\n## Step 6: Edit the scatterplots to make them look good\n\n\n### Task 10 -- Edit the appearance of one plot step-by-step\n\n#### Hint: Task 10 -- We are going to edit:\n\n1. the appearance of the points using alpha, size and colour;\n2. the colour of the background using theme_bw();\n3. the appearance of the labels using labs().\n\nJust like with `geom_histogram()` there is `ggplot` reference \ninformation for the geom you can use here -- take a look:\n\n<https://ggplot2.tidyverse.org/reference/geom_point.html>\n\nYou can find some example code and come back here if you are unsure what to do\n\n#### Questions: Task 10\n\n- Q.18. Change the appearance of the points using alpha, size and colour:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = HLVA, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"red\") \n```\n\n::: {.cell-output-display}\n![](2023-24-PSYC122-w16-workbook-answers_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n\n- Q.19. Edit the colour of the background using `theme_bw()`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = HLVA, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"red\")   +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](2023-24-PSYC122-w16-workbook-answers_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n\n- Q.20. Edit the appearance of the labels using `labs()`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = HLVA, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"red\")   +\n  theme_bw() +\n  labs(x = \"HLVA\", y = \"mean accuracy\")\n```\n\n::: {.cell-output-display}\n![](2023-24-PSYC122-w16-workbook-answers_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n\n- Q.21. Can you find the ggplot reference page?\n\nDo a search with the keywords \"ggplot reference geom_point\"\n\n- A.21. -- It is here: \n\n<https://ggplot2.tidyverse.org/reference/geom_point.html>\n\n\n## Now you: experiment!\n\n\n## Step 7: Use correlation to to answer the research questions\n\n\n### Task 11 -- Examine the correlation between mean accuracy (mean.acc) and some numeric predictor variables\n\nWe use `cor.test()`\n\n- Q.22. What is r (given as `cor` in the output) for the correlation between `HLVA` and `mean.acc`?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(study.two.gen$HLVA, study.two.gen$mean.acc, method = \"pearson\",  alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  study.two.gen$HLVA and study.two.gen$mean.acc\nt = 7.5288, df = 170, p-value = 2.866e-12\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.3787626 0.6044611\nsample estimates:\n      cor \n0.5000559 \n```\n\n\n:::\n:::\n\n\n\n- A.22. r = 0.5000559 \n\n- Q.23. Is the correlation significant?\n\n- A.23. r is significant\n\n- Q.24. What are the values for t and p for the significance test for the correlation?\n\n- A.24. t = 7.5288, p = 2.866e-12\n\n- Q.25. What do you conclude, given the correlation results? (Maybe draw a scatterplot to examine the shape of the association.)\n\n- A.25. HLVA and mean.acc are positively correlated suggesting that as HLVA scores increase so also do\nmean.acc scores\n\n- Q.26. What is r (given as `cor` in the output) for the correlation between `mean.self` and `mean.acc`?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(study.two.gen$mean.self, study.two.gen$mean.acc, method = \"pearson\",  alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  study.two.gen$mean.self and study.two.gen$mean.acc\nt = 8.4991, df = 170, p-value = 9.356e-15\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.4317217 0.6431596\nsample estimates:\n      cor \n0.5460792 \n```\n\n\n:::\n:::\n\n\n\n- A.26. r = 0.5460792 \n\n- Q.27. Is the correlation between `AGE` and `mean.acc` significant?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(study.two.gen$AGE, study.two.gen$mean.acc, method = \"pearson\",  alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  study.two.gen$AGE and study.two.gen$mean.acc\nt = 0.30121, df = 170, p-value = 0.7636\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.1269774  0.1721354\nsample estimates:\n       cor \n0.02309589 \n```\n\n\n:::\n:::\n\n\n\n- A.27. r is not significant\n\n- Q.28. What are the values for t and p for the significance test for the correlation between `QRITOTAL`\nand `mean.acc`?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(study.two.gen$QRITOTAL, study.two.gen$mean.acc, method = \"pearson\",  alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  study.two.gen$QRITOTAL and study.two.gen$mean.acc\nt = 6.4711, df = 170, p-value = 9.993e-10\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.3159538 0.5571417\nsample estimates:\n    cor \n0.44457 \n```\n\n\n:::\n:::\n\n\n\n- A.28. t = 6.4711, p = 9.993e-10\n\n- Q.29. What do you conclude, given the correlation results, about the association between `SHIPLEY`\nand `mean.acc`?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(study.two.gen$SHIPLEY, study.two.gen$mean.acc, method = \"pearson\",  alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  study.two.gen$SHIPLEY and study.two.gen$mean.acc\nt = 6.8493, df = 170, p-value = 1.299e-10\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.3390103 0.5746961\nsample estimates:\n      cor \n0.4650537 \n```\n\n\n:::\n:::\n\n\n\n- A.29. `SHIPLEY` and `mean.acc` are positively correlated suggesting that as HLVA scores increase so also do\nmean.acc scores\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}