{
  "hash": "3f10a0c0fc8cb5ccbf34cfbe681d0edb",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"PSYC122-w17-workbook-answers\"\nauthor: Rob Davies\noutput: word_document\n---\n\n\n\n\n\n\n# Introduction\n\n\nIn Week 17, we aim to *further* develop skills in visualizing and testing the \nassociations between variables in psychological data.\n\nWe do this to learn how to answer research questions like:\n\n1. What person attributes predict success in understanding?\n2. Can people accurately evaluate whether they correctly understand written \nhealth information?\n\nThese kinds of research questions can be answered using methods like the **linear model**.\n\nWhen we do these analyses, we need to think about how we report the results:\n\n- we usually need to report information about the kind of model we specify;\n- and we will need to report the nature of the association estimated in our model;\n- we usually need to decide, is the association significant?\n- does the association reflect a positive or negative relationship between outcome \nand predictor?\n- and is the association we see in our sample data relatively strong or weak?\n\nWe will consolidate and extend learning on data visualization:\n\n- focusing on how we edit ggplot() code to produce professional looking plots.\n\n## Naming things\n\nI will format dataset names like this: \n\n- `study-two-general-participants.csv`\n\nI will also format variable (data column) names like this: `variable` \n\nI will also format value or other data object (e.g. cell value) names like this: `studyone`\n\nI will format functions and library names like this: e.g. function `ggplot()` or e.g. library `{tidyverse}`.\n\n## The data we will be using\n\nIn this activity, we use data from *a second* 2020 study of the response\nof adults from a UK national sample to written health information:\n\n- `study-two-general-participants.csv`\n\n\n# Answers\n\n\n## Step 1: Set-up\n\n\nTo begin, we set up our environment in R.\n\n\n### Task 1 -- Run code to empty the R environment\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list=ls())                            \n```\n:::\n\n\n\n\n### Task 2 -- Run code to load relevant libraries\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"tidyverse\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.0     ✔ readr     2.1.6\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.2     ✔ tibble    3.3.1\n✔ lubridate 1.9.4     ✔ tidyr     1.3.2\n✔ purrr     1.2.1     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n:::\n\n\n\n\n## Step 2: Load the data\n\n\n### Task 3 -- Read in the data file we will be using\n\nThe data file is called:\n\n- `study-two-general-participants.csv`\n\nUse the `read_csv()` function to read the data file into R:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudy.two.gen <- read_csv(\"study-two-general-participants.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 172 Columns: 12\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (5): participant_ID, study, GENDER, EDUCATION, ETHNICITY\ndbl (7): mean.acc, mean.self, AGE, SHIPLEY, HLVA, FACTOR3, QRITOTAL\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n\nWhen you read the data file in, give the data object you create a distinct name \ne.g. `study.two.gen`.\n\n\n### Task 4 -- Inspect the data file\n\nUse the `summary()` or `head()` functions to take a look.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(study.two.gen)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 12\n  participant_ID mean.acc mean.self study     AGE SHIPLEY  HLVA FACTOR3 QRITOTAL\n  <chr>             <dbl>     <dbl> <chr>   <dbl>   <dbl> <dbl>   <dbl>    <dbl>\n1 studytwo.1        0.411      6.07 studyt…    26      27     6      50        9\n2 studytwo.10       0.607      8.5  studyt…    38      24     9      58       15\n3 studytwo.100      0.875      8.93 studyt…    66      40    13      60       20\n4 studytwo.101      0.964      8.5  studyt…    21      31    11      59       14\n5 studytwo.102      0.714      7.07 studyt…    74      35     7      52       18\n6 studytwo.103      0.768      5.07 studyt…    18      40    11      54       15\n# ℹ 3 more variables: GENDER <chr>, EDUCATION <chr>, ETHNICITY <chr>\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(study.two.gen)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n participant_ID        mean.acc        mean.self        study          \n Length:172         Min.   :0.4107   Min.   :3.786   Length:172        \n Class :character   1st Qu.:0.6786   1st Qu.:6.411   Class :character  \n Mode  :character   Median :0.7679   Median :7.321   Mode  :character  \n                    Mean   :0.7596   Mean   :7.101                     \n                    3rd Qu.:0.8393   3rd Qu.:7.946                     \n                    Max.   :0.9821   Max.   :9.000                     \n      AGE           SHIPLEY           HLVA           FACTOR3     \n Min.   :18.00   Min.   :23.00   Min.   : 3.000   Min.   :29.00  \n 1st Qu.:25.00   1st Qu.:32.75   1st Qu.: 7.750   1st Qu.:47.00  \n Median :32.50   Median :36.00   Median : 9.000   Median :51.00  \n Mean   :35.37   Mean   :35.13   Mean   : 9.064   Mean   :51.24  \n 3rd Qu.:44.00   3rd Qu.:39.00   3rd Qu.:11.000   3rd Qu.:56.25  \n Max.   :76.00   Max.   :40.00   Max.   :14.000   Max.   :63.00  \n    QRITOTAL        GENDER           EDUCATION          ETHNICITY        \n Min.   : 6.00   Length:172         Length:172         Length:172        \n 1st Qu.:12.00   Class :character   Class :character   Class :character  \n Median :14.00   Mode  :character   Mode  :character   Mode  :character  \n Mean   :13.88                                                           \n 3rd Qu.:16.00                                                           \n Max.   :20.00                                                           \n```\n\n\n:::\n:::\n\n\n\nEven though you have done this before, you will want to do it \nagain, here, and pay particular attention to what you see, for the numeric variables, \nin the information about minimum (Min.) and maximum (Max.) values.\n\n\n## Step 3: Use histograms to examine the distributions of variables\n\n\n### Revise: practice to strengthen skills\n\n\n### Task 5 -- Draw histograms to examine the distributions of variables\n### hint: Task 5 \n\nUse `ggplot()` with `geom_histogram()`.\n\nWhen we create a plot, we take things step-by-step.\n\nHere's an example you have seen before: run the lines of code and see the result in the `Plots` window in `R-Studio`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = mean.acc)) + \n  geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](PSYC122-w17-workbook-answers_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\nThese are the steps, set out one at a time:\n\n1. `ggplot(...)` you tell R you want to make a plot using the `ggplot()` function\n2. `ggplot(data = study.two.gen ...)` you tell R you want to make a plot with the\n`study.two.gen` data\n3. `ggplot(..., aes(x = mean.acc))` you tell R that you want to make a plot with \nthe variable `mean.acc` -- here, you specify the aesthetic mapping, `x = mean.acc`\n4. `ggplot(...) + geom_histogram()` you tell R you want to plot values of `mean.acc` \nas a histogram\n\nNotice that the code works the same whether we have the different bits of code on the same\nline or in a series of lines.\n\n\n### Revise: make sure you are confident about doing these things\n\n\n### Task 6 -- Practice editing the appearance of a histogram plot step-by-step\n\nStart by constructing a basic histogram.\n\n#### hint: Task 6 -- Choose whichever numeric variable from the `study.two.gen` dataset you please\n\n#### hint: Task 6 -- Use the line-by-line format to break the plot code into steps\n\nIt will make it easier to read, and it will make it easier to add edits e.g.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = SHIPLEY)) + \n  geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](PSYC122-w17-workbook-answers_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\nWe are going to revise editing:\n\n1. The appearance of the bars using `binwidth`;\n2. The colour of the background using `theme_bw()`;\n3. The appearance of the labels using `labs().\n\nThen we are going to try some new moves:\n\n4. Setting the x-axis limits to reflect the full range of possible scores \non the x-axis variable;\n5. Adding annotation -- here, a vertical line -- indicating the sample average \nfor a variable.\n\n#### Questions: Task 6\n\n- Q.1. Edit the appearance of the bars by specifying a `binwidth` value.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = SHIPLEY)) + \n  geom_histogram(binwidth = 2)\n```\n\n::: {.cell-output-display}\n![](PSYC122-w17-workbook-answers_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n- Q.2. Then add an edit to the appearance of the background using `theme_bw()`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = SHIPLEY)) + \n  geom_histogram(binwidth = 2) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](PSYC122-w17-workbook-answers_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n- Q.3. Then add an edit to the appearance of the labels using `labs()`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = SHIPLEY)) + \n  geom_histogram(binwidth = 2) +\n  theme_bw() +\n  labs(x = \"SHIPLEY\", y = \"frequency count\")\n```\n\n::: {.cell-output-display}\n![](PSYC122-w17-workbook-answers_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n\n### Introduce: make some new moves\n\n\n- Q.4. Now add an edit by setting the x-axis limits using `x.lim()`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = SHIPLEY)) + \n  geom_histogram(binwidth = 2) +\n  theme_bw() +\n  labs(x = \"Vocabulary (SHIPLEY)\", y = \"frequency count\") +\n  xlim(0,40)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing missing values or values outside the scale range\n(`geom_bar()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](PSYC122-w17-workbook-answers_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n\n- Q.5. Then add an edit to draw a vertical line to show the mean value of \nthe variable you are plotting.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = SHIPLEY)) + \n  geom_histogram(binwidth = 2) +\n  theme_bw() +\n  labs(x = \"Vocabulary (SHIPLEY)\", y = \"frequency count\") +\n  xlim(0,40) +\n  geom_vline(xintercept = mean(study.two.gen$SHIPLEY), colour = \"red\", size = 1.5)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 2 rows containing missing values or values outside the scale range\n(`geom_bar()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](PSYC122-w17-workbook-answers_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\n- Q.6. Can you find information on how to define the limits on the x-axis \nand on the y-axis?\n- hint: Q.6. You can see the information in this week's how-to but try a \nsearch online for \"ggplot reference xlim\".\n\n- A.6. See ggplot reference information on setting limits here:\n\n<https://ggplot2.tidyverse.org/reference/lims.html>\n\n- Q.7. Can you find information on how to a reference line?\n- hint: Q.7. You can see the information in this week's how-to but try a \nsearch online for \"ggplot reference vline\".\n\n- A.7. See ggplot reference information on setting limits here:\n\n<https://ggplot2.tidyverse.org/reference/geom_abline.html>\n\n\n## Step 4: Now draw scatterplots to examine associations between variables \n\n\n### Consolidation: should be no surprises here\n\n\n### Task 7 -- Create a scatterplot to examine the association between some variables \n\nBetween the outcome `mean.acc` and each of three numeric potential predictor variables \n`SHIPLEY`, `HLVA` and `AGE`.\n\n#### hint: Task 7 -- We are working with `geom_point()` and you need x and y aesthetic mappings.\n#### hint: Task 7 -- The outcome variable `mean.acc` has to be mapped to the y-axis using `...y = ...`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = SHIPLEY, y = mean.acc)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](PSYC122-w17-workbook-answers_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = HLVA, y = mean.acc)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](PSYC122-w17-workbook-answers_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = AGE, y = mean.acc)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](PSYC122-w17-workbook-answers_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n\n### Revise: make sure you are confident about doing these things\n\n\n### Task 8 -- Edit the appearance of *each* plot step-by-step\n\n#### hint: Task 8 -- You may want to use the same plot appearance choices for all plots \n\nBecause a consistent appearance is generally neater and easier for \nyour audience to process.\n\n#### hint: Task 8 -- You can find links to reference information on options in the how-to guide\n\nUse the information to make the plots pleasing in appearance to you.\n\n#### hint: Task 8 -- Do not be afraid to copy then paste code you re-use.\n\nBut be careful that things like axis values are sensible for each variable.\n\n#### Questions: Task 8\n\n- Q.8. -- First, edit the appearance of the points using `alpha`, `size`, `shape`, and `colour`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = SHIPLEY, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')\n```\n\n::: {.cell-output-display}\n![](PSYC122-w17-workbook-answers_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = HLVA, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')\n```\n\n::: {.cell-output-display}\n![](PSYC122-w17-workbook-answers_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = AGE, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')\n```\n\n::: {.cell-output-display}\n![](PSYC122-w17-workbook-answers_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\n- Q.9. -- Then edit the colour of the background using `theme_bw()`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = SHIPLEY, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')   +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](PSYC122-w17-workbook-answers_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = HLVA, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')   +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](PSYC122-w17-workbook-answers_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = AGE, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')   +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](PSYC122-w17-workbook-answers_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n\n- Q.10. -- Then edit the appearance of the labels using `labs()`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = SHIPLEY, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')   +\n  theme_bw() +\n  labs(x = \"SHIPLEY\", y = \"mean accuracy\")\n```\n\n::: {.cell-output-display}\n![](PSYC122-w17-workbook-answers_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = HLVA, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')   +\n  theme_bw() +\n  labs(x = \"HLVA\", y = \"mean accuracy\")\n```\n\n::: {.cell-output-display}\n![](PSYC122-w17-workbook-answers_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = AGE, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')   +\n  theme_bw() +\n  labs(x = \"Age (Years)\", y = \"mean accuracy\")\n```\n\n::: {.cell-output-display}\n![](PSYC122-w17-workbook-answers_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n\n\n### Introduce: make some new moves\n\n\n- Q.11. -- Then set the x-axis and y-axis limits to the minimum-maximum ranges \nof the variables you are plotting\n- hint: Q.11. -- For these plots the y-axis limits will be the same because \nthe outcome stays the same\n- hint: Q.11. -- But the x-axis limits will be different for each different \npredictor variable\n- hint: Q.11. -- The minimum value will always be 0\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = SHIPLEY, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')   +\n  theme_bw() +\n  labs(x = \"SHIPLEY\", y = \"mean accuracy\") +\n  xlim(0, 40) + ylim(0, 1)\n```\n\n::: {.cell-output-display}\n![](PSYC122-w17-workbook-answers_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = HLVA, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')   +\n  theme_bw() +\n  labs(x = \"HLVA\", y = \"mean accuracy\") +\n  xlim(0, 16) + ylim(0, 1)\n```\n\n::: {.cell-output-display}\n![](PSYC122-w17-workbook-answers_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = AGE, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')   +\n  theme_bw() +\n  labs(x = \"Age (Years)\", y = \"mean accuracy\") +\n  xlim(0, 80) + ylim(0, 1)\n```\n\n::: {.cell-output-display}\n![](PSYC122-w17-workbook-answers_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n\n\n## Step 5: Use correlation to to answer the research questions \n\n\n### Revise: make sure you are confident about doing these things\n\n\nOne of our research questions is:\n\n1. What person attributes predict success in understanding?\n\n\n### Task 9 -- Examine the correlations between the outcome variable and predictor variables\n\n#### hint: Task 9 -- We use `cor.test()`\n#### hint: Task 9 -- You can look at the `how-to` guide for more advice\n\nYou need to run three separate correlations: \n\n1. between mean accuracy and SHIPLEY\n2. between mean accuracy and HLVA and \n3. between mean accuracy and AGE\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(study.two.gen$SHIPLEY, study.two.gen$mean.acc, method = \"pearson\",  alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  study.two.gen$SHIPLEY and study.two.gen$mean.acc\nt = 6.8493, df = 170, p-value = 1.299e-10\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.3390103 0.5746961\nsample estimates:\n      cor \n0.4650537 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(study.two.gen$HLVA, study.two.gen$mean.acc, method = \"pearson\",  alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  study.two.gen$HLVA and study.two.gen$mean.acc\nt = 7.5288, df = 170, p-value = 2.866e-12\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.3787626 0.6044611\nsample estimates:\n      cor \n0.5000559 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(study.two.gen$AGE, study.two.gen$mean.acc, method = \"pearson\",  alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  study.two.gen$AGE and study.two.gen$mean.acc\nt = 0.30121, df = 170, p-value = 0.7636\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.1269774  0.1721354\nsample estimates:\n       cor \n0.02309589 \n```\n\n\n:::\n:::\n\n\n\nNow use the results from the correlations to answer the following questions.\n\n- Q.12. -- What is `r`, the coefficient for the correlation between `mean.acc` and `SHIPLEY`?\n\n- A.12. -- r = 0.4650537\n\n- Q.13. -- Is the correlation between `mean.acc` and `HLVA`  significant?\n\n- A.13. -- r is significant, p < .05\n\n- Q.14. -- What are the values for t and p for the significance test for the correlation between \n`mean.acc` and `AGE`?\n\n- A.14. -- t = 0.30121, p = 0.7636\n\n- Q.15. -- For which pair of outcome-predictor variables is the correlation the largest?\n\n- A.15. -- The correlation is the largest between `mean.acc` and `HLVA`.\n\n- Q.16. -- What is the sign or direction of each of the correlations?\n\n- A.16. -- All the correlations are positive.\n\n\n## Step 6: Use a linear model to to answer the research questions \n\n\n### Introduce: Make some new moves\n\n\nOne of our research questions is:\n\n1. What person attributes predict success in understanding?\n\n### Task 10 -- Examine the relation between outcome mean accuracy (`mean.acc`) \n\nAnd each of the predictors: `SHIPLEY`, `HLVA` and `AGE`\n\n#### hint: Task 10 -- Use `lm()`\n#### hint: Task 10 -- Run three separate `lm()` analyses\n\nAll with `mean.acc` as the outcome but each with one predictor variable\n\n#### hint: Task 10 -- See the `how-to` guide for example code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.acc ~ SHIPLEY, data = study.two.gen)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ SHIPLEY, data = study.two.gen)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.285771 -0.076662  0.002099  0.079416  0.257793 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.308027   0.066426   4.637 7.01e-06 ***\nSHIPLEY     0.012854   0.001877   6.849 1.30e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.107 on 170 degrees of freedom\nMultiple R-squared:  0.2163,\tAdjusted R-squared:  0.2117 \nF-statistic: 46.91 on 1 and 170 DF,  p-value: 1.299e-10\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.acc ~ HLVA, data = study.two.gen)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ HLVA, data = study.two.gen)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.27457 -0.06777  0.01474  0.08025  0.23146 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.522016   0.032544  16.040  < 2e-16 ***\nHLVA        0.026207   0.003481   7.529 2.87e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1047 on 170 degrees of freedom\nMultiple R-squared:  0.2501,\tAdjusted R-squared:  0.2456 \nF-statistic: 56.68 on 1 and 170 DF,  p-value: 2.866e-12\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.acc ~ AGE, data = study.two.gen)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ AGE, data = study.two.gen)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.34684 -0.08464  0.01084  0.08323  0.21968 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.7519965  0.0267206  28.143   <2e-16 ***\nAGE         0.0002136  0.0007092   0.301    0.764    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1208 on 170 degrees of freedom\nMultiple R-squared:  0.0005334,\tAdjusted R-squared:  -0.005346 \nF-statistic: 0.09073 on 1 and 170 DF,  p-value: 0.7636\n```\n\n\n:::\n:::\n\n\n\nNotice that we do the linear model in the steps:\n\n1. `model <- lm(...)` fit the model using `lm(...)`, and give the model a name,\nhere, we call it `model`;\n2. `...lm(mean.acc ~ SHIPLEY...)` tell R you want a model of \nthe outcome `mean.acc` predicted `~` by the predictor `SHIPLEY`\n3. `...data = study.two)` tell R that the variables you name in the formula live in the \n`study.two` dataset.\n4. `summary(model)` ask R for a summary of the model you called `model`.\n\nNotice that R has a general formula syntax: \n\n`outcome ~ predictor *or* y ~ x`\n\n- and uses the same format across a number of different functions;\n- each time, the left of the tilde symbol `~` is some output or outcome;\n- and the right of the tilde `~` is some input or predictor or set of predictors.\n\n#### Questions: Task 10\n  \nIf you look at the model summary you can answer the following questions.\n\n- Q.17. What is the estimate for the coefficient of the effect of the predictor \n`HLVA` on `mean.acc`?\n\n- A.17. 0.026207 \n\n- Q.18. Is the effect significant?\n\n- A.18. It is significant, p < .05\n\n- Q.19. What are the values for t and p for the significance test for the coefficient?\n\n- A.19. t = 7.529, p = 2.87e-12\n\n- Q.20. How would you describe in words the shape or direction of the association \nbetween `HLVA` and `mean.acc`?\n\n- A.20. The slope coefficient -- and a scatterplot (draw it) -- suggest that \nas HLVA scores increase so also do mean accuracy scores.\n\n- Q.21. How how would you describe the relations apparent between the predictor and \noutcome in all three models?\n\n- A.21. It is possible to see, given coefficient estimates, that the association \nbetween predictor and outcome is positive for each model: mean accuracy appears to increase \nfor increasing values of SHIPLEY vocabulary, HLVA health literacy, and age.\n\n\n## Step 7: Use a linear model to generate predictions \n\n\n### Introduce: make some new moves\n\n\n### Task 11 -- We can use the model we have just fitted to plot the model predictions\n\n#### hint: Task 11 -- We are going to draw a scatterplot and add a line \n\nThe line will show the model predictions, given the model intercept and effect \ncoefficient estimates.\n\nFirst fit a model and get a summary: model the relationship between `mean.acc` and `HLVA`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(mean.acc ~ HLVA, data = study.two.gen)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean.acc ~ HLVA, data = study.two.gen)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.27457 -0.06777  0.01474  0.08025  0.23146 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.522016   0.032544  16.040  < 2e-16 ***\nHLVA        0.026207   0.003481   7.529 2.87e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1047 on 170 degrees of freedom\nMultiple R-squared:  0.2501,\tAdjusted R-squared:  0.2456 \nF-statistic: 56.68 on 1 and 170 DF,  p-value: 2.866e-12\n```\n\n\n:::\n:::\n\n\n\n- Q.22. What is the coefficient estimate for the intercept?\n\n- A.22. 0.522016\n\n- Q.23. What is the coefficient estimate for the slope of `HLVA` (see earlier)?\n\n- A.23. 0.026207\n\nSecond, use the `geom_point()` to draw a scatterplot and `geom_abline()` function \nto draw the prediction line representing the association between this outcome and predictor\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.two.gen, aes(x = HLVA, y = mean.acc)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"blue\", shape = 'square')   +\n  geom_abline(intercept = 0.522016, slope = 0.026207, colour = \"red\", size = 1.5) +\n  theme_bw() +\n  labs(x = \"HLVA\", y = \"mean accuracy\") +\n  xlim(0, 15) + ylim(0, 1)\n```\n\n::: {.cell-output-display}\n![](PSYC122-w17-workbook-answers_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\n\nYou can see reference information here:  \n\n<https://ggplot2.tidyverse.org/reference/geom_abline.html>\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}