{
  "hash": "44e2797a4a182e5606d01a5d2febe922",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"PSYC122-w16-how-to\"\nauthor: Rob Davies\noutput: word_document\n---\n\n\n\n\n\n\n# Introduction\n\n\nIn Week 16, we aim to develop skills in visualizing and testing the associations\nbetween variables in psychological data.\n\nWe do this to learn how to answer research questions like:\n\n1. What person attributes predict success in understanding?\n2. Can people accurately evaluate whether they correctly understand written\nhealth information?\n\nThese kinds of research questions can be answered using methods like **correlation**\nand **linear models**.\n\nWe will consolidate and extend learning on **data visualization**:\n\n- Use histograms to examine the distributions of variables;\n- Use scatterplots to examine the relationships we may observe or predict.\n\n## This how-to guide\n\nThis guide is designed to help you work out:\n\n- how to write or edit R code to do things like visualization or analysis;\n- how to identify key information for interpretation and reporting.\n\n## Naming things\n\nI will format dataset names like this: \n\n- `study-one-general-participants.csv`\n\nI will also format variable (data column) names like this: `variable` \n\nI will also format value or other data object (e.g. cell value) names like this: `studyone`\n\nI will format functions and library names like this: e.g. function `ggplot()` or e.g. library `{tidyverse}`.\n\n## We will take things step-by-step\n\nI will split .Rmd scripts by steps, tasks and questions:  \n\n- different steps for different phases of the analysis workflow;\n- different tasks for different things you need to do;\n- different questions to examine different ideas or coding challenges\n\n## The data we will be using\n\nIn this **how-to** guide, we use data from a 2020 study of the response\nof adults from a UK national sample to written health information:\n\n- `study-one-general-participants.csv`\n\nNotice that this dataset is **different** from the data you use to complete the Week 16 lab activity tasks or questions.\n\n\n## Step 1: Set-up\n\n\nTo begin, we set up our environment in R.\n\n\n### Task 1 -- Run code to empty the R environment\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list=ls())                            \n```\n:::\n\n\n\n\n### Task 2 -- Run code to load relevant libraries\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"tidyverse\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.0     ✔ readr     2.1.6\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.2     ✔ tibble    3.3.1\n✔ lubridate 1.9.4     ✔ tidyr     1.3.2\n✔ purrr     1.2.1     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n:::\n\n\n\n\n## Step 2: Load the data\n\n\n### Task Task 3 -- Read in the data file we will be using\n\nThe data file is called:\n\n- `study-one-general-participants.csv`\n\nUse the `read_csv()` function to read the data file into R:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudy.one <- read_csv(\"study-one-general-participants.csv\")  \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 169 Columns: 12\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (5): participant_ID, study, GENDER, EDUCATION, ETHNICITY\ndbl (7): mean.acc, mean.self, AGE, SHIPLEY, HLVA, FACTOR3, QRITOTAL\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n\nWhen you read the data file in, give the data object you create a distinct name \ne.g. `study.one`.\n\n\n### Task 4 -- Inspect the data file\n\nUse the `summary()` or `head()` functions to take a look\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(study.one)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 12\n  participant_ID mean.acc mean.self study     AGE SHIPLEY  HLVA FACTOR3 QRITOTAL\n  <chr>             <dbl>     <dbl> <chr>   <dbl>   <dbl> <dbl>   <dbl>    <dbl>\n1 studyone.1         0.49      7.96 studyo…    34      33     7      53       11\n2 studyone.10        0.85      7.28 studyo…    25      33     7      60       11\n3 studyone.100       0.82      7.36 studyo…    43      40     8      46       12\n4 studyone.101       0.94      7.88 studyo…    46      33    11      51       15\n5 studyone.102       0.58      6.96 studyo…    18      32     3      51       12\n6 studyone.103       0.84      7.88 studyo…    19      37    13      45       19\n# ℹ 3 more variables: GENDER <chr>, EDUCATION <chr>, ETHNICITY <chr>\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(study.one)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n participant_ID        mean.acc        mean.self        study          \n Length:169         Min.   :0.3600   Min.   :3.440   Length:169        \n Class :character   1st Qu.:0.7600   1st Qu.:6.080   Class :character  \n Mode  :character   Median :0.8400   Median :7.080   Mode  :character  \n                    Mean   :0.8163   Mean   :6.906                     \n                    3rd Qu.:0.9000   3rd Qu.:7.920                     \n                    Max.   :0.9900   Max.   :9.000                     \n      AGE           SHIPLEY           HLVA           FACTOR3     \n Min.   :18.00   Min.   :23.00   Min.   : 3.000   Min.   :34.00  \n 1st Qu.:24.00   1st Qu.:33.00   1st Qu.: 7.000   1st Qu.:46.00  \n Median :32.00   Median :35.00   Median : 9.000   Median :51.00  \n Mean   :34.87   Mean   :34.96   Mean   : 8.905   Mean   :50.33  \n 3rd Qu.:42.00   3rd Qu.:38.00   3rd Qu.:10.000   3rd Qu.:55.00  \n Max.   :76.00   Max.   :40.00   Max.   :14.000   Max.   :63.00  \n    QRITOTAL        GENDER           EDUCATION          ETHNICITY        \n Min.   : 6.00   Length:169         Length:169         Length:169        \n 1st Qu.:12.00   Class :character   Class :character   Class :character  \n Median :13.00   Mode  :character   Mode  :character   Mode  :character  \n Mean   :13.36                                                           \n 3rd Qu.:15.00                                                           \n Max.   :19.00                                                           \n```\n\n\n:::\n:::\n\n\n\nNote that `head()` will give you the top few rows of any dataset you have read into R.\n\n- `head(...)` is a function, and you put the name of the dataset inside the brackets to\nview it.\n- `summary()` will give you either descriptive statistics for variable columns classified as numeric or will tell you that columns in the dataset are not numeric\n- `summary()` is also a function and, again, you put the name of the dataset inside the brackets to view it\n\nUse the information in the summary view to answer the following questions.\n\n- Q.1. What is the mean of `mean.acc`?\n- A.1. 0.8163  \n\n- Q.2. What class is the variable `study`?\n- A.2. `character`  \n\n- Q.3. -- Does the summary indicate if any variable has missing values (`NA`)?\n- Q.3. -- No\n\n\n### Task 5 -- Change the class or type of the variable `study` to factor\n\n#### hint: Task 5 -- You can use the `as.factor()` function you have used before\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudy.one$study <- as.factor(study.one$study)\n```\n:::\n\n\n\n#### Question: Task 5\n\n- Q.4. After you have done this, what information does `summary()` give you about the variable `study`?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(study.one)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n participant_ID        mean.acc        mean.self          study    \n Length:169         Min.   :0.3600   Min.   :3.440   studyone:169  \n Class :character   1st Qu.:0.7600   1st Qu.:6.080                 \n Mode  :character   Median :0.8400   Median :7.080                 \n                    Mean   :0.8163   Mean   :6.906                 \n                    3rd Qu.:0.9000   3rd Qu.:7.920                 \n                    Max.   :0.9900   Max.   :9.000                 \n      AGE           SHIPLEY           HLVA           FACTOR3     \n Min.   :18.00   Min.   :23.00   Min.   : 3.000   Min.   :34.00  \n 1st Qu.:24.00   1st Qu.:33.00   1st Qu.: 7.000   1st Qu.:46.00  \n Median :32.00   Median :35.00   Median : 9.000   Median :51.00  \n Mean   :34.87   Mean   :34.96   Mean   : 8.905   Mean   :50.33  \n 3rd Qu.:42.00   3rd Qu.:38.00   3rd Qu.:10.000   3rd Qu.:55.00  \n Max.   :76.00   Max.   :40.00   Max.   :14.000   Max.   :63.00  \n    QRITOTAL        GENDER           EDUCATION          ETHNICITY        \n Min.   : 6.00   Length:169         Length:169         Length:169        \n 1st Qu.:12.00   Class :character   Class :character   Class :character  \n Median :13.00   Mode  :character   Mode  :character   Mode  :character  \n Mean   :13.36                                                           \n 3rd Qu.:15.00                                                           \n Max.   :19.00                                                           \n```\n\n\n:::\n:::\n\n\n\n- A.4. We can see the number 169 beside the word `studyone`: this tells us that there are 169 observations, in the column, each one is a value: the word or character string `studyone`.\n\n\n## Step 3: Use histograms to examine the distributions of variables\n\n\n## Revise: consolidate what you know\n\n\n### Task 6 -- Draw histograms to examine the distributions of variables\n\n#### Hint: Task 6\n\nUse `ggplot()` with `geom_histogram()`.\n\nThe first time we do this, we take things step-by-step.\n\nHere's an example: run the line of code and see the result in the `Plots` window \nin `R-Studio`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one, aes(x = mean.acc)) + geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](PSYC122-w16-how-to_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\nThese are the steps, set out one at a time:\n\n1. `ggplot(...)` you tell R you want to make a plot using the `ggplot()` function\n2. `ggplot(data = study.one ...)` you tell R you want to make a plot with the `study.one` data\n3. `ggplot(..., aes(x = mean.acc))` you tell R that you want to make a plot with the variable `mean.acc`\n3. here, you specify the aesthetic mapping, `x = mean.acc`\n4. `ggplot(...) + geom_histogram()` you tell R you want to plot values of `mean.acc` as a histogram\n\n#### Questions: Task 6\n\n- Q.5. Did you get a message in the `Console` window in `R-Studio`: \nwhat does it say?\n- A.5. The message says:\n\n```{}\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n- Q.6. What does `binwidth` refer to?\n\n- hint: Q.6. You need to do a search online (e.g., using Google) with the keywords:\n\"ggplot reference geom_histogram\"\n\n- A.6. If your search gets you to this page:\n\nhttps://ggplot2.tidyverse.org/reference/geom_histogram.html  \n\n- Then you will first see a technical definition \"The width of the bins. Can be specified as a numeric value ...\"\n- You will second see examples of the use of the term e.g.\n\n```{}\nggplot(diamonds, aes(carat)) + geom_histogram(binwidth = 0.01)\n```\n\n- If you run the example code, it will produce a plot. **Do it.**\n\nIt is a very good idea to get get some experience doing searches online for information about working with data analysis tasks.\n\n- You will find that there is a lot of useful information, written in different ways for people with different levels of expertise\n\nHere, we are interested in working with `binwidth` in `geom_histogram()`.\n\n- The example gives us a hint at what we can do: we can change the appearance of the bars in the histogram.\n- The bars in the histogram represent how often we observe, in a dataset, a grouping of similar values in a variable.\n- Larger (wider) bins count more different values as similar.\n- So increasing binwidth will give you fewer wider bars in a histogram. **Check it out.**\n\n### Task 7 -- Experiment with changing the binwidth\n\n#### hint: Task 7 -- Use `geom_histogram(binwidth = ...)` like you can see in the `ggplot()` reference example\n\nNote that binwidth needs to *take into account the scale* of the x variable:\n\n- It won't work for `mean.acc` if you make `binwidth = 100`.\n- The number will need to be something between 0 and 1 (the min and max for `mean.acc`).\n- **Try a few different numbers, like this:**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one, aes(x = mean.acc)) + geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](PSYC122-w16-how-to_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = study.one, aes(x = mean.acc)) + geom_histogram(binwidth = 0.1)\n```\n\n::: {.cell-output-display}\n![](PSYC122-w16-how-to_files/figure-html/unnamed-chunk-8-2.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = study.one, aes(x = mean.acc)) + geom_histogram(binwidth = 0.2)\n```\n\n::: {.cell-output-display}\n![](PSYC122-w16-how-to_files/figure-html/unnamed-chunk-8-3.png){width=672}\n:::\n:::\n\n\n\n\n## Step 4: Edit your plots to make them look good\n\n\n## Extend: make some new moves\n\n\n### Task 8 -- Edit the appearance of the plot step-by-step\n\n#### hint: Task 8 -- ggplot() code does not all have to be on the same line\n\nIf we break the plot code into steps, it will make it easier to read,\nand it will make it easier to add edits e.g.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one, aes(x = mean.acc)) + \n  geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](PSYC122-w16-how-to_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\nIf you run the selection of both lines, you get the code to work.\n\nHere, we are going to edit:\n\n1. The appearance of the bars using binwidth;\n2. The colour of the background using `theme_bw()`;\n3. The appearance of the labels using `labs()`.\n\nTake a look at how the code changes *and how the plot changes* with each edit to\nthe code.\n\n1. The appearance of the bars using binwidth\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one, aes(x = mean.acc)) + \n  geom_histogram(binwidth = 0.2)\n```\n\n::: {.cell-output-display}\n![](PSYC122-w16-how-to_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n\n2. The colour of the background using `theme_bw()`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one, aes(x = mean.acc)) + \n  geom_histogram(binwidth = 0.2) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](PSYC122-w16-how-to_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\n3. The appearance of the labels using `labs()`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one, aes(x = mean.acc)) + \n  geom_histogram(binwidth = 0.2) +\n  theme_bw() +\n  labs(x = \"mean accuracy\", y = \"frequency count\")\n```\n\n::: {.cell-output-display}\n![](PSYC122-w16-how-to_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n\nNotice how each line -- except the last one -- ends in a `+`\n\n- What we are doing is telling R we want this + this + this ...\n- Each line then adds an extra step.\n\n### Introduce: learn to handle errors and warnings\n\nYou can break this code by not adding a `+` at the end of each bit (except the last line)\n**Try it.**\n\n```{}\nggplot(data = study.one, aes(x = mean.acc))\n  geom_histogram(binwidth = 0.2) +\n  theme_bw() +\n  labs(x = \"mean accuracy\", y = \"frequency\")\n```\n\n- Q.7. You will get an error message in the console window, orange and grey, if you omit a `+` like in the example: what is the error message?\n- A.7. The message will read:\n\n```{}\nError: Cannot add ggproto objects together. Did you forget to add this object to a ggplot object?\n\nRun `rlang::last_error()` to see where the error occurred.  \n```\n\n- Q.8. Copy and then paste the error message into Google: click on one of the results: do you see any useful information?\n- A.8.  An explanation of the problem is shown e.g.    \n\n<https://community.rstudio.com/t/could-anybody-help-me-cannot-add-ggproto-objects-together/11271>  \n\nR will give you hints -- often in red -- in error messages if something has gone wrong.\nThis can be a bit frightening but usually you can fix a problem by:\n\n1. Using trial and error: try changing things to see what happens;\n2. Copying the error message into an online search: usually, that will \nget you to a blog or discussion that is helpful.\n\nThe R community has many millions of people in it.\nThe huge value of the community means that **for every problem you encounter, someone else has already met that problem, solved it, and posted a blog online about how to fix it**\n\n \n## Step 5: Now draw scatterplots to examine associations between variables\n\n\n## Revision: make sure you are confident about doing these things\n\n\nYou have seen these code moves before, in previous classes: we are \nstrengthening skills by practising coding in different contexts\n\n### Task 9 -- Create a scatterplot to examine the association between some variables\n\n#### hint: Task 9 -- We are working with `geom_point()` and you need x and y aesthetic mappings\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one, aes(x = mean.self, y = mean.acc)) + \n    geom_point()\n```\n\n::: {.cell-output-display}\n![](PSYC122-w16-how-to_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n- This plot shows the possible association between x-axis variable `mean.self` \nand y-axis variable `mean.acc`\n\nThe plot code moves through the following steps:  \n\n1. `ggplot(...)` make a plot\n2. `ggplot(data = study.one, ...)` with the `study.one` dataset\n3. `ggplot(...aes(x = mean.self, y = mean.acc))` using two aesthetic mappings\n\n- `x = mean.self` map `mean.self` values to x-axis (horizontal, left to right) positions\n- `y = mean.acc`- map `mean.acc` values to y-axis (vertical, bottom to top) positions\n\n4. `geom_point()` show the mappings as points.    \n  \n### Task 10 -- Now do scatterplots with any pair of numeric variables you like  \n#### hint: Task 10 -- Remember what we saw with `summary()`: not every variable consists of numbers  \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one, aes(y = mean.self, x = mean.acc)) +\n    geom_point()  \n```\n\n::: {.cell-output-display}\n![](PSYC122-w16-how-to_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = study.one, aes(x = AGE, y = mean.self)) +\n  geom_point()  \n```\n\n::: {.cell-output-display}\n![](PSYC122-w16-how-to_files/figure-html/unnamed-chunk-14-2.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = study.one, aes(x = SHIPLEY, y = mean.self)) +\n  geom_point()  \n```\n\n::: {.cell-output-display}\n![](PSYC122-w16-how-to_files/figure-html/unnamed-chunk-14-3.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data = study.one, aes(x = HLVA, y = mean.self)) +\n  geom_point()  \n```\n\n::: {.cell-output-display}\n![](PSYC122-w16-how-to_files/figure-html/unnamed-chunk-14-4.png){width=672}\n:::\n:::\n\n\n\n### Extend: make some new moves\n\n### Task 11 -- Edit the appearance of the plot step-by-step\n\n#### Hint: Task 11 -- We are going to edit:\n\n1. The appearance of the points using alpha and size;\n2. The colour of the background using `theme_bw()`;\n3. The appearance of the labels using `labs()`.\n\n1. The appearance of the points using alpha and size\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one, aes(x = HLVA, y = mean.self)) +\n  geom_point(alpha = 0.5, size = 2) \n```\n\n::: {.cell-output-display}\n![](PSYC122-w16-how-to_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n2. The colour of the background using `theme_bw()`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one, aes(x = HLVA, y = mean.self)) +\n  geom_point(alpha = 0.5, size = 2)  +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](PSYC122-w16-how-to_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n\n3. The appearance of the labels using `labs()`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one, aes(x = HLVA, y = mean.self)) +\n  geom_point(alpha = 0.5, size = 2)  +\n  theme_bw() +\n  labs(x = \"HLVA\", y = \"mean self rated accuracy\")\n```\n\n::: {.cell-output-display}\n![](PSYC122-w16-how-to_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\nThe arguments alpha and size can change the appearance of most geometric \nobjects (geoms) in ggplot:\n\n- In the code example, here, we vary the alpha number to change how opaque or\ntransparent the points are\n- And we vary the size number to vary the size of the points.\n\n### Task 12 -- Now you experiment: edit the appearance of the plot by changing alpha and size -- what about colour?\n\n#### hint: Task 12 -- Check out the ggplot reference for scatterplots\n\n- Q.9. -- Can you find the ggplot reference page?\n- hint: Q.9 -- Do a search with the keywords \"ggplot reference geom_point\"\n\n- A.9. -- It is here: \n\n<https://ggplot2.tidyverse.org/reference/geom_point.html>\n\n- Q.10. -- Can you change the colour of the points to a colour you like?\n- hint: Q.10. -- Useful information on colour can be found here:\n\n<https://r-graphics.org/recipe-colors-setting>\n\nSee also:\n\n<http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/>\n\n- A.10. -- Here is how you do it: \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = study.one, aes(x = HLVA, y = mean.self)) +\n  geom_point(alpha = 0.5, size = 2, colour = \"hotpink\")  +\n  theme_bw() +\n  labs(x = \"HLVA\", y = \"mean self rated accuracy\")\n```\n\n::: {.cell-output-display}\n![](PSYC122-w16-how-to_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n\n### Now you: experiment!\n\n\n## Step 6: Use correlation to to answer the research questions\n\n\n- **revision: make sure you are confident about doing these things**\n\nOne of our research questions is:\n\n2. Can people accurately evaluate whether they correctly understand written \nhealth information?\n\nWe can answer this question by examining whether mean self-rated accuracy \nof understanding correlates with mean accuracy of understanding.\nThe logic is that if we can accurately rate our own understanding (from bad \nto good) then that rating should be associated -- should be correlated with \nhow accurately we can actually respond to questions that test that \nunderstanding.\n\n### Task 13 -- Examine the correlation between mean self-rated accuracy (`mean.self`) and mean accuracy (`mean.acc`)\n\n#### hint: Task 13 -- We use `cor.test()`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(study.one$mean.acc, study.one$mean.self, method = \"pearson\",  alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  study.one$mean.acc and study.one$mean.self\nt = 7.1936, df = 167, p-value = 2.026e-11\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.3619961 0.5937425\nsample estimates:\n      cor \n0.4863771 \n```\n\n\n:::\n:::\n\n\n\n- Q.11. -- What is r, the correlation coefficient?\n- A.11. -- r = 0.4863771\n\n- Q.12. -- Is the correlation significant?\n- A.12. -- r is significant\n\n- Q.13. -- What are the values for t and p for the significance test for the correlation?\n- A.13. -- t = 7.1936, p = 2.026e-11\n\n- Q.14. -- What do you conclude, given the correlation results?\n- hint: Q.6 -- Review the scatterplot you drew earlier to examine the shape \nof the association between these variables\n- A.14. -- mean.acc and mean.self are positively correlated suggesting that as \nmean.acc scores increase so also do mean.self scores\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}