{
  "hash": "a03fd405acb8764c2962771fe096643a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"122_wk12_labActivity2\"\nauthor: \"Margriet Groen\"\ndate: \"2024-01-11\"\noutput: html_document\n---\n\n\n\n\n\n\n## Lab activity 2 - Vaping data\n\n# Step 1. Loading the relevant libraries\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(broom)\nlibrary(car)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: carData\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(lsr)\nlibrary(Hmisc)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'Hmisc'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    format.pval, units\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.0     ✔ readr     2.1.6\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.2     ✔ tibble    3.3.1\n✔ lubridate 1.9.4     ✔ tidyr     1.3.2\n✔ purrr     1.2.1     \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter()    masks stats::filter()\n✖ dplyr::lag()       masks stats::lag()\n✖ dplyr::recode()    masks car::recode()\n✖ purrr::some()      masks car::some()\n✖ dplyr::src()       masks Hmisc::src()\n✖ dplyr::summarize() masks Hmisc::summarize()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n:::\n\n\n\n# Step 2. Read in the data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- read_csv(\"VapingData.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 166 Columns: 8\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (1): Sex\ndbl (7): Participant, IAT_BLOCK3_RT, IAT_BLOCK3_Acc, IAT_BLOCK5_RT, IAT_BLOC...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n\n\n*Question 2a:* For how many participants do we have data?\n\nThere are 166 observations, so we have data for 166 participants. You can see this in the Environment window in the top right. This does not tell us whether any of these participants have any missing data.\n\n# Step 3. Data wrangling\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- dat %>% \n  filter(IAT_BLOCK3_Acc < 1) %>%                            # 1) only keep participants with accuracy scores equal to or smaller than 1 from block 3\n  filter(IAT_BLOCK5_Acc < 1) %>%                            # 1) only keep participants with accuracy scores equal to or smaller than 1 from block 5\n  mutate(IAT_ACC = (IAT_BLOCK3_Acc + IAT_BLOCK5_Acc)/2) %>% # 2) calculate an average IAT accuracy score across blocks 3 and 5\n  filter(IAT_ACC > .8) %>%                                  # 2) only keep participants with an average score greater than .8.\n  mutate(IAT_RT = IAT_BLOCK5_RT - IAT_BLOCK3_RT)            # 3) compute the IAT_RT score\n```\n:::\n\n\n\n\n*Question 3a:* For how many participants do we have data now that we have cleaned them up?\n\n104 participants.\n\n*Question 3b:* Use the information in the background description to understand how the scores relate to attitudes. What does a positive IAT_RT score reflect? What does a negative IAT_RT score reflect? What does a higher score on the 'VapingQuestionnaireScore' mean?\n\nPeople with a positive IAT_RT are considered to hold the implicit view that vaping is negative (i.e. congruent associations are quicker than incongruent associations).\n\nPeople with a negative IAT_RT are considered to hold the implicit view that vaping is positive (i.e. incongruent associations were quicker than congruent associations).\n\nHigher scores indicated a positive explicit attitude towards vaping.\n\n# Step 4: Calculating descriptive statistics\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndescriptives <- dat %>%\n  summarise(n = n(),\n            mean_IAT_ACC = mean(IAT_ACC),\n            mean_IAT_RT = mean(IAT_RT),\n            mean_VPQ = mean(VapingQuestionnaireScore, na.rm = TRUE))\ndescriptives\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n      n mean_IAT_ACC mean_IAT_RT mean_VPQ\n  <int>        <dbl>       <dbl>    <dbl>\n1   104        0.916        185.     62.7\n```\n\n\n:::\n:::\n\n\n\n\n*Question 4a:* Why might these averages be useful? Why are averages not always useful in correlations?\n\nIt is always worth thinking about which averages are informative and which are not. Knowing the average explicit attitude towards vaping could well be informative. In contrast, if you are using an ordinal scale and people use the whole of the scale then the average may just tell you the middle of the scale you are using - which you already know and really isn't that informative. So it is always worth thinking about what your descriptives are calculating.\n\n# Step 5: Check the assumptions\n\n## Variable types\n*Questions 5a:* What are the variable types for the implicit (IAT_RT) and the explicit (VapingQuestionnaireScore) attitude variables?\n\nBoth can be considered continuous variables and at least at interval level.\n\n## Missing data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- dat %>% \n  filter(!is.na(VapingQuestionnaireScore)) %>% \n  filter(!is.na(IAT_RT))\n```\n:::\n\n\n\n*Question 5b* How many people had missing data?\n\nBefore we removed participants with missing data, we had 104 observations, now we have 96. So there must have been 8 participants without a score on one or the other variable.\n\n## Normality\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dat, aes(x = VapingQuestionnaireScore)) + \n  geom_histogram(binwidth = 10) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](122_wk12_labAct2_files/figure-html/normality plots-1.png){width=672}\n:::\n\n```{.r .cell-code}\nqqPlot(x = dat$VapingQuestionnaireScore)\n```\n\n::: {.cell-output-display}\n![](122_wk12_labAct2_files/figure-html/normality plots-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 35 95\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(dat, aes(x = IAT_RT)) + \n  geom_histogram(binwidth = 10) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](122_wk12_labAct2_files/figure-html/normality plots-3.png){width=672}\n:::\n\n```{.r .cell-code}\nqqPlot(x = dat$IAT_RT)\n```\n\n::: {.cell-output-display}\n![](122_wk12_labAct2_files/figure-html/normality plots-4.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 25 54\n```\n\n\n:::\n:::\n\n\n\n\n*Question 5c* What do you conclude from the histograms and the qq-plots? Are the VapingQuestionnaireScore and the IAT_RT normally distributed?\n\nYes. Both histograms resemble a normal distribution (bell curve) and the open circles in the qq-plots fall within the blue stripy lines.\n\n## Linearity and homoscedasticity\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dat, aes(x = IAT_RT, y = VapingQuestionnaireScore)) + \n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE) +\n  theme_bw() +\n  labs(x = \"Implicit attitude\", y = \"Explicit attitude\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](122_wk12_labAct2_files/figure-html/linearity and homoscedasticity-1.png){width=672}\n:::\n:::\n\n\n\n\n*Question 5d* What do you conclude from the scatterplot in terms of the homoscedasticity of the data and the linearity, direction and strength of the relationship? What does the scatterplot tell you about possible issues (outliers, range restrictions)?\n\nThe data look like a cloud without a clear direction. This suggests the relationship might be weak. In terms of linearity, the scatterplot doesn't suggest any curvilinear relationships. Variance seems quite constant, but there do seem to be few people with negative IAT_RT (Implicit attitude) scores, suggesting few people held the view that vaping is positive.\n\n# Step 6: Conduct a correlation analysis ----------------------------------\n\n*Question 6a* Do you need to calculate Pearson's r or Spearman's rho? Why?\n\nPearson's *r* because the data do meet the assumptions.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresults <- cor.test(dat$VapingQuestionnaireScore, \n                    dat$IAT_RT, \n                    method = \"pearson\") %>% \n  tidy()\n\nresults\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 8\n  estimate statistic p.value parameter conf.low conf.high method     alternative\n     <dbl>     <dbl>   <dbl>     <int>    <dbl>     <dbl> <chr>      <chr>      \n1  -0.0232    -0.225   0.822        94   -0.223     0.178 Pearson's… two.sided  \n```\n\n\n:::\n\n```{.r .cell-code}\ncorrelation <- results %>% \n  pull(estimate) %>%\n  round(2)\n\ndf <- results %>% \n  pull(parameter) %>%\n  round(0)\n\npvalue <- results %>% \n  pull(p.value) %>%\n  round(3)\n```\n:::\n\n\n\n\n*Question 6b* Is the correlation significant?\n\nNo, *p* = .822, which is larger than .05.\n\n# Step 7: Write up\n\nTesting the hypothesis of a relationship between implicit and explicit attitudes towards vaping, a Pearson correlation found no significant relationship between IAT reaction times (implicit attitude) and answers on a Vaping Questionnaire (explicit attitude), *r*(94) = -.02, *p* = .822. Overall this suggests that there is no direct relationship between implicit and explicit attitudes with regard to vaping and as such our hypothesis was not supported; we cannot reject the null hypothesis.\n\n# Step 8: Intercorrelations\n\n## Create a new data frame that only includes the relevant variables\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_matrix <- dat %>%\n  select(Age, IAT_RT, VapingQuestionnaireScore) %>%\n  as.data.frame() # Make sure tell R that dat is a data frame\n```\n:::\n\n\n\n\n## Create a matrix of scatterplots\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairs(dat_matrix)\n```\n\n::: {.cell-output-display}\n![](122_wk12_labAct2_files/figure-html/matrix of scatterplots-1.png){width=672}\n:::\n:::\n\n\n\n\n*Question 8a* What do you conclude from the scatterplots?\n\nThe scatterplots with age suggest that age is highly skewed with only a few participants older than 25. For now, let's say we'll therefore calculate Spearman's rho, rather than Pearson's *r*. That is ok for now, but if you were analysing these data for a research project, you'd want to have a closer look at the age variable (think histogram, qq-plot, and think about either collecting more data from older participants or transforming the variable (more about that next year).\n\n## Conduct intercorrelation (multiple correlations)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nintercor_results <- correlate(x = dat_matrix, # our data\n                          test = TRUE, # compute p-values\n                          corr.method = \"spearman\", # run a spearman test \n                          p.adjust.method = \"bonferroni\") # use the bonferroni correction\nintercor_results\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCORRELATIONS\n============\n- correlation type:  spearman \n- correlations shown only when both variables are numeric\n\n                            Age    IAT_RT    VapingQuestionnaireScore   \nAge                           .     0.156                      -0.086   \nIAT_RT                    0.156         .                      -0.022   \nVapingQuestionnaireScore -0.086    -0.022                           .   \n\n---\nSignif. codes: . = p < .1, * = p<.05, ** = p<.01, *** = p<.001\n\n\np-VALUES\n========\n- total number of tests run:  3 \n- correction for multiple testing:  bonferroni \n- WARNING: cannot compute exact p-values with ties\n\n                           Age IAT_RT VapingQuestionnaireScore\nAge                          .  0.384                    1.000\nIAT_RT                   0.384      .                    1.000\nVapingQuestionnaireScore 1.000  1.000                        .\n\n\nSAMPLE SIZES\n============\n\n                         Age IAT_RT VapingQuestionnaireScore\nAge                       96     96                       96\nIAT_RT                    96     96                       96\nVapingQuestionnaireScore  96     96                       96\n```\n\n\n:::\n:::\n\n\n\n\n*Question 8b* What do you conclude from the results of the correlation analysis? \n\nNo significant correlation with age was found.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}