{
  "hash": "c814c2eca00dd55afe4039709df3da62",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Week 5. Testing differences between groups\nsubtitle: Written by Padraic Monaghan\norder: 6\n\n---\n\n\n\n\n## 5.1 Overview\n\nThis week, there are two mini lectures, and the practical workbook working with R-studio.\n\nBefore the practical on Tuesday, please try to work through the practical workbook in your group.\n\nBring your questions (and/or answers) to the practical.\n\n## 5.2 Learning Goals\n\n* Understand when t-tests are appropriately applied to data\n\n* Understand the distinction between paired and independent t-tests\n\n* Interpret p-values from t-tests\n\n* Determine how a paired t-test is calculated\n\n* Determine how an independent t-test is calculated\n\n* Understand effect sizes for t-tests\n\n* Be able to effectively interpret t-test results\n\n* Be able to accurately present t-test results in research reports\n\n\n## 5.3 Lectures and slides\n\n### 5.3.1 Lectures\n\nWatch Lecture week 5 part 1:\n\n\n\n```{=html}\n<iframe src=\"https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=98f7b065-26f1-42d9-9872-ac5900c7cda0&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=true&interactivity=all\" height=\"405\" width=\"720\" style=\"border: 1px solid #464646;\" allowfullscreen allow=\"autoplay\" aria-label=\"Panopto Embedded Video Player\" aria-description=\"psyc411_2025_w5_p1\" ></iframe>\n```\n\n\n\nWatch Lecture week 5 part 2:\n\n\n\n```{=html}\n<iframe src=\"https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=551cef0e-76e4-43b6-8895-ac5900cdf342&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=true&interactivity=all\" height=\"405\" width=\"720\" style=\"border: 1px solid #464646;\" allowfullscreen allow=\"autoplay\" aria-label=\"Panopto Embedded Video Player\" aria-description=\"psyc411_2025_w5_p2\" ></iframe>\n```\n\n\n\nTake [the quiz](https://modules.lancaster.ac.uk/mod/quiz/view.php?id=2680955){target=\"_blank\"} (not assessed) on the lecture materials.\n\n### 5.3.2 Slides\n\nDownload the lecture slides for:\n\n- [part 1](ppt/wk5/PSYC411 Lecture week5 part1 handout.pptx)\n\n- [part 2](ppt/wk5/PSYC411 Lecture week5 part2 handout.pptx)\n\n## 5.4 Practical Materials\n\n### 5.4.1 Workbook\n\n* Part 1 is some revision from the last 4 weeks.\n* Part 2 covers running an independent t-test.\n* Part 3 covers running a paired t-test.\n* Part 4 provides more practice running paired t-tests.\n* Part 5 presents some extras - exploring different datasets and running t-tests on those data.\n\n#### 5.4.1.1 Part 1: Revision\n\n##### Task 1: Checklist: What I can now do\n\nYou should be able to answer yes to all the following. If you can't yet, go back to the previous workbooks and repeat your working until you can answer yes, being able to type in and run the commands without referring to your notes. \n\n1. I can open R-studio\n\n2. I can open new libraries using `library()`\n\n3. I can make an R script file\n\n4. I can input a file into an object in R-studio using `read_csv()`\n\n5. I can join two files together using `inner_join()`\n\n6. I can select certain variables from an object using `select()`\n\n7. I can select subsets of data using `filter()` (e.g., I can select participants in two conditions from a data set containing participants in four conditions)  \n\n8. I can make new variables using `mutate()`\n\n9. I can arrange data according to subsets using `group_by()`\n\n10. I can change format of data from wide to long format using `pivot_longer`\n\n11. I can change format of data from long to wide format using `pivot_wider`\n\n12. I can produce summaries of means and standard deviations for subsets of data after applying `group_by()` using `summarise()` \n\n13. I can draw histograms of single variables, point plots of two ratio/interval/ordinal variables, bar plots of counts, and box plots of one categorical and one ratio/interval/ordinal variable using `ggplot()`\n\n14. I can run a Chi-squared test and Cramer's V test using `chisq.test()` and `cramersV()`\n\n15. I can interpret the results of a Chi-squared test and Cramer's V test and write up a simple report of the results. \n\n16. I can save an R script file.\n\n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## ANSWER\nHere are some examples of the commands/functions in use:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list=ls())\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.0     ✔ readr     2.1.6\n✔ forcats   1.0.1     ✔ stringr   1.6.0\n✔ ggplot2   4.0.2     ✔ tibble    3.3.1\n✔ lubridate 1.9.4     ✔ tidyr     1.3.2\n✔ purrr     1.2.1     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\n# from week4 practical\ndat <- read_csv(\"data/wk4/PSYC411-shipley-scores-anonymous-17_25_year_language.csv\") \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 293 Columns: 7\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (1): english_status\ndbl (6): subject_ID, Age, Shipley_Voc_Score, Gent_1_score, Gent_2_score, aca...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\ndat$academic_year <- as.factor(dat$academic_year)\n#View(dat)\n\n# from week2 practical\ndat2 <- read_csv(\"data/wk2/ahicesd.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 992 Columns: 50\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\ndbl (50): id, occasion, elapsed.days, intervention, ahi01, ahi02, ahi03, ahi...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\npinfo <- read_csv(\"data/wk2/participantinfo.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 295 Columns: 6\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\ndbl (6): id, intervention, sex, age, educ, income\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nall_dat <- inner_join(x = dat2, y = pinfo, by = c(\"id\", \"intervention\"))\nsummarydata <- select(all_dat, id, ahiTotal, cesdTotal, age, occasion)\ndat_17 <- filter(dat, academic_year == \"201718\")\nall_dat2 <- group_by(all_dat, intervention, occasion)\nsummarise(all_dat2, mean(ahiTotal), sd(ahiTotal), n())\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`summarise()` has regrouped the output.\nℹ Summaries were computed grouped by intervention and occasion.\nℹ Output is grouped by intervention.\nℹ Use `summarise(.groups = \"drop_last\")` to silence this message.\nℹ Use `summarise(.by = c(intervention, occasion))` for per-operation grouping\n  (`?dplyr::dplyr_by`) instead.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 24 × 5\n# Groups:   intervention [4]\n   intervention occasion `mean(ahiTotal)` `sd(ahiTotal)` `n()`\n          <dbl>    <dbl>            <dbl>          <dbl> <int>\n 1            1        0             68.4           14.0    72\n 2            1        1             69.5           13.4    30\n 3            1        2             70.3           15.7    38\n 4            1        3             75.0           12.8    29\n 5            1        4             76.5           16.2    36\n 6            1        5             75.5           14.5    27\n 7            2        0             68.8           13.0    76\n 8            2        1             71.6           12.5    48\n 9            2        2             73.0           14.0    48\n10            2        3             72.5           14.2    43\n# ℹ 14 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(dat, aes(x = Age)) + geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 216 rows containing non-finite outside the scale range\n(`stat_bin()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Week5_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(dat, aes(x = Shipley_Voc_Score, y = Gent_1_score)) + geom_point()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 11 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Week5_files/figure-html/unnamed-chunk-1-2.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(dat, aes(x = Shipley_Voc_Score, y = Gent_1_score)) + geom_point() + geom_smooth( method = lm)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 11 rows containing non-finite outside the scale range\n(`stat_smooth()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 11 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Week5_files/figure-html/unnamed-chunk-1-3.png){width=672}\n:::\n\n```{.r .cell-code}\nall_dat$occasion <- as.factor(all_dat$occasion)\nggplot(all_dat, aes(x = occasion, y = ahiTotal)) + geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](Week5_files/figure-html/unnamed-chunk-1-4.png){width=672}\n:::\n\n```{.r .cell-code}\ndat_long <- pivot_longer(dat, names_to = \"test\", values_to = \"score\", cols = c(\"Gent_1_score\", \"Gent_2_score\"))\n# or:\ndat_long <- pivot_longer(dat, names_to = \"test\", values_to = \"score\", cols = starts_with(\"Gent\"))\ndat_wide <- pivot_wider(dat_long, names_from = \"test\", values_from = \"score\")\n\nlibrary(lsr)\nchisq.test(x = all_dat$occasion, y = all_dat$intervention)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  all_dat$occasion and all_dat$intervention\nX-squared = 9.7806, df = 15, p-value = 0.8333\n```\n\n\n:::\n\n```{.r .cell-code}\ncramersV(x = all_dat$occasion, y = all_dat$intervention)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05732779\n```\n\n\n:::\n:::\n\n\n:::\n\n#### 5.4.1.2 Part 2: Running an independent t-test\n\n\n##### Task 2: Load, prepare, and explore the data\n\n17. Clear out R using `rm(list=ls())`\n\n18. Load again the data set on the Shipley and Gent vocabulary scores from week 4. \n\n19. Set the research question: do people who self-identify as male or female have different scores on the Gent vocabulary test? The research hypothesis is: \"People who identify as male or female have different vocabulary scores\". What is the null hypothesis?\n  \n  \n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## Answer\nThere is no difference between people who self-identify as male or female on vocabulary scores.\n:::\n\n20. To test the research hypothesis, we will filter people who self-identify as male or female from the data set. To be inclusive, additional research questions would be part of your research project to analyse also people who self-identify as other gender. Run this command to extract a  subset of the data (note that the `|` stands for \"or\", and means Gender matches male or gender matches female:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- read_csv(\"data/wk4/PSYC411-shipley-scores-anonymous-17_25_gender.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 293 Columns: 5\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (1): Gender\ndbl (4): subject_ID, Shipley_Voc_Score, Gent_1_score, Gent_2_score\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\ndat2 <- filter(dat, Gender == 'Male' | Gender == 'Female')\n```\n:::\n\n\n\n21. Draw a box plot of Gent vocabulary test 1 scores by gender. For a box plot, note that we need data in \"long format\", where each observation is on one line, and we have a column that indicates which condition (in this case Gender) the participant is in. Does it look like there might be a gender effect? What is the direction of the effect? \n\n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dat2, aes(x = Gender, y = Gent_1_score)) + geom_boxplot()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 4 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Week5_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nThe graph indicates that maybe males are slightly higher, but looks like a lot of overlap.\n:::\n\n\n22. Note that unless we had filtered the data, the box plot would contain 'NA' as well, which stands for missing data.  In a data set it's always a good idea to call missing data 'NA' rather than just leaving them blank because this could be interpreted as a zero or as an error of filling in data.  Missing values make things untidy, so it's good practice to focus only on the variables we need for the t-test and remove all other missing values. Use `select()` to get just the Gender and Gent_1_score variables, and put this in a new object called 'dat3'. \n\n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat3 <- select(dat2, Gender, Gent_1_score)\n```\n:::\n\n\n:::\n\n\n23. Next, in order to run a t-test we have to remove any rows of data which contain a 'NA' - either in the Gender or the Gent_1_score variables. We do this using `drop_na(dat3)`, put the result in a new object called 'dat4'. Run this command:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat4 <- drop_na(dat3)\n```\n:::\n\n\n\n\n24. Now, redraw the box plot from Step 21. Check there are just two groups still.\n\n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dat2, aes(x = Gender, y = Gent_1_score)) + geom_boxplot()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 4 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Week5_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nYes, two groups.\n:::\n\n25. Compute mean and SDs for people who self-identify as male or female on Gent vocabulary test 1 scores.\n\n::: {.callout-warning icon=\"false\" collapse=\"true\"}\n## Hint\n\nUse `group_by()` and `summarise()`.\n:::\n\n\n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat5 <- group_by(dat4, Gender)\nsummarise(dat5, mean(Gent_1_score), sd(Gent_1_score))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  Gender `mean(Gent_1_score)` `sd(Gent_1_score)`\n  <chr>                 <dbl>              <dbl>\n1 Female                 59.0               13.7\n2 Male                   62.3               13.7\n```\n\n\n:::\n\n```{.r .cell-code}\n# Or, if you know how to use the %>% (pipe) ...:\ndat4 %>% group_by(Gender) %>% summarise(mean(Gent_1_score), sd(Gent_1_score))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  Gender `mean(Gent_1_score)` `sd(Gent_1_score)`\n  <chr>                 <dbl>              <dbl>\n1 Female                 59.0               13.7\n2 Male                   62.3               13.7\n```\n\n\n:::\n:::\n\n\n:::\n\n##### Task 3: Run the independent t-test and measure effect size\n\n26. Conduct an independent t-test using this command:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(Gent_1_score ~ Gender, data = dat4 ) \n```\n:::\n\n\n\n<!--- ::: {.callout-caution icon=\"false\" collapse=\"true\"}\n## Bug warning!\nThis t-test command works on our https://psy-rstudio.lancaster.ac.uk/ system, but really annoyingly doesn't work in the very latest version of R. If you have downloaded R-studio onto your computer there is a chance this won't work! \n\nTo fix this on your own computer version, you need to download and install an older version of R from the [r server webpage](https://www.r-project.org){target=\"_blank\"}: version R4.2.3 *does* work ok, version 4.4 does not work, not sure about versions 4.3... \n::: --->\n\n\n- 'Gent_1_score ~ Gender' : the ~ can be interpreted as 'by', i.e., compute Gent_1_score by Gender \n\n27. The results should look like this, do yours?\n````\n\tWelch Two Sample t-test\n\ndata:  Gent_1_score by Gender\nt = -1.7019, df = 100.37, p-value = 0.09187\nalternative hypothesis: true difference in means between group Female and group Male is not equal to 0\n95 percent confidence interval:\n -7.2386790  0.5537475\nsample estimates:\nmean in group Female   mean in group Male \n            58.99087             62.33333 \n````\n\n28. The key part of the results to look at is the one that has t = -1.7019, df = 100.37, p-value = 0.09187. This is the result that you report: *t*(100.37) = -1.70, *p* = .092.\n\nThe value is negative because the function includes Female before Male - and Female score is lower than Male score. What matters is how far away from zero the t-test is (either positively or negatively).  The df value is slightly odd because the t.test() function figures out degrees of freedom in a technical way which takes into account differences in variance in the data between the two groups. We can just use the value that the `t.test()` function gives us. \n\n29. Is this a significant difference? \n\n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## Answer\nNo, it isn't. The p-value is greater than 0.05.\n:::\n\n30. Now we need to compute the effect size, using Cohen's d. You need to load the library lsr then use this command:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncohensD(Gent_1_score ~ Gender, method = \"unequal\", data = dat4)\n```\n:::\n\n\n\n\n- It's pretty much the same as the t-test() command except that we use 'method = 'unequal'. For a paired t-test you would use 'method = 'paired' \n\n\n31. What is the effect size? Make a brief report of the results - reporting means and SDs, the t-test, p-value, and Cohen's d. Discuss your brief report in your group.\n\n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## Answer\n d = 0.24\n\nAn ideal brief report of the results would state what the research question/hypothesis is, describe the means and SDs of the groups being compared, and then report the t-test statistic, with p-value and Cohen's d effect size, then provide a brief interpretation of what the results mean.\n\nBased on Hyde and Linn (1988), we hypothesised that people who self-identify as female may score slightly higher than males in\nterms of vocabulary scores. Males (mean = 62.33, SD = 13.74) scored higher than \nfemales (mean = 58.99, SD = 13.72) on the first time participants attempted the \nGent vocabulary test, however this difference was not significant,\n*t*(100.37) = -1.70, *p* = .092, Cohen's *d* = 0.24. We did not find evidence to support the hypothesis.\n\n*Reference*\n\nHyde, J. S., & Linn, M. C. (1988). Gender differences in verbal ability: A meta-analysis. *Psychological Bulletin, 104(1)*, 53–69. https://doi.org/10.1037/0033-2909.104.1.53\n:::\n\n\n32. Make sure all commands are in the source window, save them as a new R script file.\n\n##### Task 4: Practise running another independent t-test\n\n33. Next research question: do people who are native English speakers have different vocabulary scores than those who learned English as a second language? What is the research hypothesis and the null hypothesis?\n\n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## Answer\nResearch Hypothesis: People who speak English as a native language have higher vocabulary scores than those with English as a second language.\n\nNull Hypothesis: There is no difference in vocabulary scores between native English and second language English speakers.\n:::\n\n\n34. Repeat the Steps 22-30 in Tasks 2 and 3 except using english_status in place of Gender throughout.\n\n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- read_csv(\"data/wk4/PSYC411-shipley-scores-anonymous-17_25_year_language.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 293 Columns: 7\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (1): english_status\ndbl (6): subject_ID, Age, Shipley_Voc_Score, Gent_1_score, Gent_2_score, aca...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\ndat2 <- select(dat, english_status, Gent_1_score)\ndat3 <- drop_na(dat2)\nggplot(dat3, aes(x = english_status, y = Gent_1_score)) + geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](Week5_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n\n```{.r .cell-code}\ndat4 <- group_by(dat3, english_status)\nsummarise(dat4, mean(Gent_1_score), sd(Gent_1_score), n())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  english_status `mean(Gent_1_score)` `sd(Gent_1_score)` `n()`\n  <chr>                         <dbl>              <dbl> <int>\n1 ESL                            50.0              15.3    102\n2 native                         65.1               9.14   179\n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(Gent_1_score ~ english_status, data = dat3 )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  Gent_1_score by english_status\nt = -9.0756, df = 142.81, p-value = 8.239e-16\nalternative hypothesis: true difference in means between group ESL and group native is not equal to 0\n95 percent confidence interval:\n -18.37748 -11.80381\nsample estimates:\n   mean in group ESL mean in group native \n            50.04902             65.13966 \n```\n\n\n:::\n\n```{.r .cell-code}\ncohensD(Gent_1_score ~ english_status, method = \"unequal\", data = dat3 )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.19691\n```\n\n\n:::\n:::\n\n\n:::\n\n35. Write a brief report of the results, including means and SDs for native speakers and ESL speakers, t-test, p-value, and Cohen's d.  Discuss your report in your group.\n\n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## Answer\nWe hypothesised that English as an additional language would result in lower overall vocabulary scores than English as a first language, because of the relation between length of time learning a language and language skills (Davies et al., 2017). \nNative\nEnglish speakers (mean = 65.14, SD = 9.14) scored significantly higher\non the Gent vocabulary test than speakers of English as a second\nlanguage (mean = 50.05, SD = 15.31), *t*(142.81) = -9.08, *p* < .001,\nCohen's *d* = 1.20, a large effect size. Thus, the hypothesis was supported, with native English speakers scoring significantly higher on the Gent vocabulary test than those with English as an additional language.\n\n*Reference*\n\nDavies, R. A. I., Arnell, R., Birchenough, J., Grimmond, D., & Houlson, S. (2017). Reading Through the Life Span: Individual Differences in Psycholinguistic Effects. *Journal of Experimental Psychology: Learning, Memory, and Cognition, 43(8)*, 1298-1338. https://doi.org/10.1037/xlm0000366\n:::\n\n\n\n36. Save your R script file.\n\n\n#### 5.4.1.3 Part 3: Conducting a paired t-test\n\n\n##### Task 5: Conducting a paired t-test \n\n37. Clear out R-studio before we get started again using `rm(list=ls())`\n\n38. We are going to investigate again the data from this paper: Woodworth, R.J., O'Brien-Malone, A., Diamond, M.R. and Schuez, B., 2017. Data from, \"Web-based Positive Psychology Interventions: A Reexamination of Effectiveness\". Journal of Open Psychology Data, 6(1). \n\nOur research question is whether happiness scores are affected by the interventions. We will look at the pre-test (occasion 0)  and the first test after the intervention (occasion 1).\n\n39. What is the research hypothesis and what is the null hypothesis?\n\n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## Answer\nRH: happiness scores change (increase) from the first to the second\noccasion of testing. \n\nNH: happiness scores do not change across occasions.\n:::\n\n40. For a paired t-test we can only include data from people who have produced scores at both occasions of testing. So, we need a slightly different version of the data, which you can download [here for the ahicesd.csv file](data/wk5/ahicesd.csv) and [here for the participantinfo2.csv file](data/wk5/participantinfo2.csv). \n\nRemind yourself what these data mean.  \n      \n\n41. Once again, join the ahicesd.csv and participantinfo2.csv data in R-studio by aligning the names for the participant numbers in these two data sets (see week 2 workbook for reminders about this). \n\n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\ndat <- read_csv(\"data/wk5/ahicesd.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 992 Columns: 50\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\ndbl (50): id, occasion, elapsed.days, intervention, ahi01, ahi02, ahi03, ahi...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\npinfo <- read_csv(\"data/wk5/participantinfo2.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNew names:\nRows: 147 Columns: 7\n── Column specification\n──────────────────────────────────────────────────────── Delimiter: \",\" dbl\n(7): ...1, id, intervention, sex, age, educ, income\nℹ Use `spec()` to retrieve the full column specification for this data. ℹ\nSpecify the column types or set `show_col_types = FALSE` to quiet this message.\n• `` -> `...1`\n```\n\n\n:::\n\n```{.r .cell-code}\nall_dat <- inner_join(x = dat, y = pinfo, by = c(\"id\", \"intervention\"))\n```\n:::\n\n\n:::\n\n\n42. Let's select only the relevant variables. Use `select()` to select only id, ahiTotal, and occasion variables, and save this as a new object called 'summarydata' \n\n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummarydata <- select(all_dat, id, ahiTotal, occasion)\n```\n:::\n\n\n:::\n\n\n43. Use filter to pull out only occasion == 0 or occasion == 1 scores\n\n::: {.callout-warning icon=\"false\" collapse=\"true\"}\n## Hint\nuse `occasion == 0 | occasion == 1`, save this as a new object\ncalled `summarydata2`\n:::\n\n\n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummarydata2 <- filter(summarydata, occasion == 0 | occasion == 1)\n```\n:::\n\n\n:::\n\n\n44. Here is where we would usually remove all the NA values, but there aren't any in this file (so we don't need drop_na()). \n\n45. Now, we need to make sure occasion is treated as a categorical variable, rather than a continuous variable, so we need to convert it to a factor:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummarydata2$occasion <-as.factor(summarydata2$occasion)\n```\n:::\n\n\n\n46. Now, draw a box plot of ahiTotal scores by occasion (why do we use a box plot?)\n\n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(summarydata2, aes(x = occasion, y = ahiTotal)) + geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](Week5_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nWe use a boxplot because we have one nominal/categorical variable and one\ninterval/ratio/ordinal measure.\n:::\n\n47. Compute mean and SD for each occasion\n\n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummarydata3 <- group_by(summarydata2, occasion)\nsummarise(summarydata3, mean(ahiTotal), sd(ahiTotal), n())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  occasion `mean(ahiTotal)` `sd(ahiTotal)` `n()`\n  <fct>               <dbl>          <dbl> <int>\n1 0                    69.3           12.3   147\n2 1                    72.4           12.6   147\n```\n\n\n:::\n\n```{.r .cell-code}\n# or:\ngroup_by(summarydata2, occasion) %>% summarise(mean(ahiTotal), sd(ahiTotal), n())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  occasion `mean(ahiTotal)` `sd(ahiTotal)` `n()`\n  <fct>               <dbl>          <dbl> <int>\n1 0                    69.3           12.3   147\n2 1                    72.4           12.6   147\n```\n\n\n:::\n:::\n\n\n:::\n\n\n48. In order to run the paired t-test, we first need to make sure that the paired values (in this case the measures from the same person) are on the same row of the data. So, let's use pivot_wider to put the ahiTotal scores for occasion 0 in one column, and the ahiTotal scores for occasion 1 in another column:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummarydata2_wide <- pivot_wider(summarydata2, names_from = occasion, values_from = ahiTotal, names_prefix = \"occasion_\")\n```\n:::\n\n\n\n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## Note\nNote that we use the names_prefix = \"occasion_\" as an extra argument to make the column names \"occasion_0\" and \"occasion_1\". \n\nWhat would happen if we didn't use names_prefix? It would still work, but it's a bit more awkward to work with the output.\n:::\n\n49. Then, we can run the paired t-test in the following way:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(summarydata2_wide$occasion_0, summarydata2_wide$occasion_1, paired = TRUE)\n```\n:::\n\n\n\nIs the result significant? \n\n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## Answer\nyes, because *p* < .05.\n:::\n\n\n50. Now run Cohen's d: it's similar to the way we do the paired t-test:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncohensD( summarydata2_wide$occasion_0, summarydata2_wide$occasion_1, method =  \"paired\")\n```\n:::\n\n\n\nWhat is the value for Cohen's d?\n\n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## Answer\nd = 0.4059904\n:::\n\n51. Write up a brief report of the result and discuss in your group.\n\n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## Answer\nWe tested whether participants' happiness scores at first\ntesting after the interventions were different than their scores prior\nto the interventions. We found that, prior to the intervention, scores\nwere significantly lower (M = 69.3, SD = 12.3) than they were\nimmediately after the interventions (M = 72.4, SD = 12.6), *t*(146) =\n= 4.92, *p* < .001, Cohen's *d* = 0.41, a medium effect. The results indicate that \nthe intervention had a positive effect on happiness scores.\n:::\n\n\n52. Save your R script file.\n\n\n#### 5.4.1.4 Part 4: More practice running a paired t-test\n\nWe are going to figure out whether people have different scores the first and second time they take the Gent vocabulary test.\n\n53. Go back to the vocabulary scores data. Load the data into dat, and make another object dat2 that contains only the subject_ID, Gent_1_score and Gent_2_score.\n\n\n54. Some people did not do all the tests - look at participant 46 for instance. To do a t-test we need data where the person does both tests. We can filter out the scores where there are no NAs by repeating the drop_na we did at step 23, above. Call the new data object dat3.\n\n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- read_csv(\"data/wk4/PSYC411-shipley-scores-anonymous-17_25_year_language.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 293 Columns: 7\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (1): english_status\ndbl (6): subject_ID, Age, Shipley_Voc_Score, Gent_1_score, Gent_2_score, aca...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\ndat$academic_year <- as.factor(dat$academic_year)\ndat2 <- select(dat, subject_ID, Gent_1_score, Gent_2_score)\ndat3 <- drop_na(dat2)\n```\n:::\n\n\n:::\n\n55. Run the paired t-test. \n\nEach row contains a score for each person for each Gent test, and so we are ready to run the paired t-test:\n\n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(dat3$Gent_1_score, dat3$Gent_2_score, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  dat3$Gent_1_score and dat3$Gent_2_score\nt = -2.2279, df = 269, p-value = 0.02672\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n -2.2744165 -0.1403983\nsample estimates:\nmean difference \n      -1.207407 \n```\n\n\n:::\n\n```{.r .cell-code}\ncohensD( dat3$Gent_1_score, dat3$Gent_2_score, , method =  \"paired\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1355846\n```\n\n\n:::\n:::\n\n\n:::\n\n56. Get mean and SD of the scores for the tests.\n\n:::{.callout-note icon=\"false\" collapse=\"true\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummarise(dat3, mean(Gent_1_score), sd(Gent_1_score), mean(Gent_2_score), sd(Gent_2_score))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  `mean(Gent_1_score)` `sd(Gent_1_score)` `mean(Gent_2_score)`\n                 <dbl>              <dbl>                <dbl>\n1                 59.6               13.6                 60.8\n# ℹ 1 more variable: `sd(Gent_2_score)` <dbl>\n```\n\n\n:::\n:::\n\n\n:::\n\n\n57. In order to draw a box plot of the Gent vocabulary scores taken at the first and second occasion, we will need the data in \"long format\", so that there is a column saying which test it is and a column reporting the scores on the Gent tests.\nApply the `pivot_longer` command and then draw the box plot.\n\n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat4 <- pivot_longer(dat3, names_to = \"test\", values_to = \"score\", cols = c(\"Gent_1_score\", \"Gent_2_score\"))\nggplot(dat4, aes(x = test, y = score)) + geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](Week5_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n:::\n\n\n#### 5.4.1.5 Part 5: Extras\n\n58. In the Gent vocabulary scores data, is there a significant difference between native and ESL speakers for your academic year group? \n\n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- read_csv(\"data/wk4/PSYC411-shipley-scores-anonymous-17_25_year_language.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 293 Columns: 7\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (1): english_status\ndbl (6): subject_ID, Age, Shipley_Voc_Score, Gent_1_score, Gent_2_score, aca...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\ndat2 <- filter(dat, academic_year == \"202526\")\nggplot(dat2, aes(x = english_status, y = Gent_1_score)) + geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](Week5_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n\n```{.r .cell-code}\ndat3 <- group_by(dat2, english_status)\nsummarise(dat3, mean(Gent_1_score), sd(Gent_1_score), mean(Gent_2_score), sd(Gent_2_score), n())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 6\n  english_status `mean(Gent_1_score)` `sd(Gent_1_score)` `mean(Gent_2_score)`\n  <chr>                         <dbl>              <dbl>                <dbl>\n1 ESL                            63                 7.28                 63.1\n2 native                         64.2               6.57                 64.5\n# ℹ 2 more variables: `sd(Gent_2_score)` <dbl>, `n()` <int>\n```\n\n\n:::\n\n```{.r .cell-code}\n# or:\ndat2 %>% group_by(english_status) %>% summarise(mean(Gent_1_score), sd(Gent_1_score), mean(Gent_2_score), sd(Gent_2_score), n())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 6\n  english_status `mean(Gent_1_score)` `sd(Gent_1_score)` `mean(Gent_2_score)`\n  <chr>                         <dbl>              <dbl>                <dbl>\n1 ESL                            63                 7.28                 63.1\n2 native                         64.2               6.57                 64.5\n# ℹ 2 more variables: `sd(Gent_2_score)` <dbl>, `n()` <int>\n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(Gent_1_score ~ english_status, data = dat2 )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  Gent_1_score by english_status\nt = -0.37049, df = 10.511, p-value = 0.7184\nalternative hypothesis: true difference in means between group ESL and group native is not equal to 0\n95 percent confidence interval:\n -8.282346  5.907346\nsample estimates:\n   mean in group ESL mean in group native \n             63.0000              64.1875 \n```\n\n\n:::\n\n```{.r .cell-code}\ncohensD(Gent_1_score ~ english_status, method = \"unequal\", data = dat2 )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1711966\n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(Gent_2_score ~ english_status, data = dat2 )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  Gent_2_score by english_status\nt = -0.54825, df = 13.205, p-value = 0.5927\nalternative hypothesis: true difference in means between group ESL and group native is not equal to 0\n95 percent confidence interval:\n -6.696472  3.982186\nsample estimates:\n   mean in group ESL mean in group native \n            63.14286             64.50000 \n```\n\n\n:::\n\n```{.r .cell-code}\ncohensD(Gent_2_score ~ english_status, method = \"unequal\", data = dat2 )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2415341\n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(Gent_2_score ~ english_status, data = dat2 )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  Gent_2_score by english_status\nt = -0.54825, df = 13.205, p-value = 0.5927\nalternative hypothesis: true difference in means between group ESL and group native is not equal to 0\n95 percent confidence interval:\n -6.696472  3.982186\nsample estimates:\n   mean in group ESL mean in group native \n            63.14286             64.50000 \n```\n\n\n:::\n\n```{.r .cell-code}\ncohensD(Gent_2_score ~ english_status, method = \"unequal\", data = dat2 )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2415341\n```\n\n\n:::\n:::\n\n\nnothing significant...\n:::\n\n59. Are there significant differences for the Shipley vocabulary test measures between males and females, or between those with English as first or second language?\n\n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat3 <- group_by(dat2, english_status)\nsummarise(dat3, mean(Shipley_Voc_Score, na.rm=TRUE), sd(Shipley_Voc_Score, na.rm=TRUE), n())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  english_status mean(Shipley_Voc_Score, na.rm = …¹ sd(Shipley_Voc_Score…² `n()`\n  <chr>                                       <dbl>                  <dbl> <int>\n1 ESL                                          41.9                  17.6      7\n2 native                                       34.2                   3.38    16\n# ℹ abbreviated names: ¹​`mean(Shipley_Voc_Score, na.rm = TRUE)`,\n#   ²​`sd(Shipley_Voc_Score, na.rm = TRUE)`\n```\n\n\n:::\n\n```{.r .cell-code}\n# or:\ndat2 %>% group_by(english_status) %>% summarise(mean(Shipley_Voc_Score, na.rm=TRUE), sd(Shipley_Voc_Score, na.rm=TRUE), n())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  english_status mean(Shipley_Voc_Score, na.rm = …¹ sd(Shipley_Voc_Score…² `n()`\n  <chr>                                       <dbl>                  <dbl> <int>\n1 ESL                                          41.9                  17.6      7\n2 native                                       34.2                   3.38    16\n# ℹ abbreviated names: ¹​`mean(Shipley_Voc_Score, na.rm = TRUE)`,\n#   ²​`sd(Shipley_Voc_Score, na.rm = TRUE)`\n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(Shipley_Voc_Score ~ english_status, data = dat2 )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  Shipley_Voc_Score by english_status\nt = 1.1382, df = 6.207, p-value = 0.2971\nalternative hypothesis: true difference in means between group ESL and group native is not equal to 0\n95 percent confidence interval:\n -8.672518 23.986804\nsample estimates:\n   mean in group ESL mean in group native \n            41.85714             34.20000 \n```\n\n\n:::\n\n```{.r .cell-code}\ncohensD(Shipley_Voc_Score ~ english_status, method = \"unequal\", data = dat2 )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6025947\n```\n\n\n:::\n:::\n\n\nFor the eagle-eyed among you, you might notice that some of the scores are outside the possible range - these typos often occur in data, and should be filtered out. What is the result if you do the filtering?\n\n:::\n\n60. The data from this paper are called [ClassDraw.csv available here](data/wk5/ClassDraw.csv). The data are on osf as well, but they're not formatted in a very accessible way, so I adjusted them and put them here.\n\nJalava, S. T., Wammes, J. D., & Cheng, K. (2023). Drawing your way to an A: \nLong-lasting improvements in classroom quiz performance following drawing. \n*Psychonomic Bulletin & Review, 30*, 1939–1945. https://doi.org/10.3758/s13423-023-02294-2\n\nThere are some useful tips in the results of this study about the benefit of doodling...\n\nMy challenge to you:\n\n- Can you make a ggplot that looks a bit like Figure 2 from this study?\n\n\n::: {.callout-note icon=\"false\" collapse=\"true\"}\n## Answer\n\n\n::: {.cell}\n\n```{.r .cell-code}\njalava <- read_csv(\"data/wk5/ClassDraw.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 168 Columns: 9\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (1): Gender\ndbl (8): ID, Age, write_1, write_2, draw_1, draw_2, exam_draw, exam_write\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\njalava1 <- pivot_longer(jalava, names_to = c(\"test\",\".value\"), names_sep=\"_\" , values_to = \"score\", cols = c(\"write_1\",\"write_2\",\"draw_1\",\"draw_2\"))\njalava2 <- pivot_longer(jalava1, names_to = \"test_time\", values_to = \"score\", cols = c(`1`,`2`))\n\njalava2$test_time <- as.factor(jalava2$test_time)\nggplot(jalava2, aes(x = test_time, y = score, fill = test)) + geom_boxplot()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 48 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Week5_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# median looks very similar (boxplots very overlapping), but means are a bit different:\njalava2 %>% group_by(test, test_time) %>% summarise(mean(score, na.rm=TRUE), sd(score, na.rm=TRUE))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`summarise()` has regrouped the output.\nℹ Summaries were computed grouped by test and test_time.\nℹ Output is grouped by test.\nℹ Use `summarise(.groups = \"drop_last\")` to silence this message.\nℹ Use `summarise(.by = c(test, test_time))` for per-operation grouping\n  (`?dplyr::dplyr_by`) instead.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n# Groups:   test [2]\n  test  test_time `mean(score, na.rm = TRUE)` `sd(score, na.rm = TRUE)`\n  <chr> <fct>                           <dbl>                     <dbl>\n1 draw  1                               0.486                     0.215\n2 draw  2                               0.322                     0.216\n3 write 1                               0.467                     0.212\n4 write 2                               0.3                       0.212\n```\n\n\n:::\n:::\n\n\n:::\n\n\n\n61. If you've made some progress on the [de Zubicaray et al. (2024)](https://doi.org/10.1037/xhp0001209){target=\"_blank\"} data analysis, to the point where you have replicated (more or less) the multiple regression analysis from the first study in that paper, then here is the next step. \n\n*Note, this is a major challenge, but it will be a step into new research!*\n\nThe task is to take the de Zubicaray data, and add a new variable which determines whether the word is a palindrome or not. A palindrome is a word that is spelled the same backwards as forwards (e.g., abba, rotavator).\n\nI would like to know if being a palindrome or not affects processing of the words. My prediction is that being a palindrome helps access the word.\n\nWhat you will need to do is apply a function called \"palindrome\" to the words in the de Zubicaray dataset, to make a new variable, called \\pally or some other name then run a multiple regression with all the other variables plus this one.\n\n[Here is a script with the function called palindrome included](data/wk5/palindrome.r), with some comments to show how it is put into practice. You will need to add the function into the top of an analysis script (e.g., rmd or r script) file and make sure that is loaded along with the other commands you are using.\n\n\n## 5.4.2 Data\n\nData referred to in this workbook:\n\n- [PSYC411-shipley-scores-anonymous-17_25_gender.csv](data/wk4/PSYC411-shipley-scores-anonymous-17_25_gender.csv){target=\"_blank\"}\n- [PSYC411-shipley-scores-anonymous-17_25_year_language.csv](data/wk4/PSYC411-shipley-scores-anonymous-17_25_year_language.csv){target=\"_blank\"}\n- [ahicesd.csv adapted for t-test](data/wk5/ahicesd.csv) \n- [participantinfo2.csv adapted for t-test](data/wk5/participantinfo2.csv). \n- [ClassDraw.csv](data/wk5/ClassDraw.csv)\n\n## 5.4.3 Answers\n\nThe answers to the workbook appear below each question in the workbook, above, so you can check your work *after you've had a go at the exercises..!*.\n\n## 5.5 Extras\n\nOptionally, if you can give us your (anonymised) [feedback](https://modules.lancaster.ac.uk/mod/feedback/view.php?id=2680956){target=\"_blank\"} on how the course is going from your perspective, that would be very welcome.\n\nAlso optionally, read the articles on the importance of statistical understanding and insights from good data visualisation:\n\n  - [How scientists can be better at statistics](https://www.spectator.co.uk/article/vital-statistics/){target=\"_blank\"}. Note that this article is hosted on the Spectator website, and *(content warning)* refers to Harold Shipman, a serial killer.\n  \n  - [Florence Nightingale and data visualisation](https://www.scientificamerican.com/article/how-florence-nightingale-changed-data-visualization-forever/){target=\"_blank\"}. Note that this is hosted on Scientific American.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}