{
  "hash": "4c458e7ee1eef322da98723078a02b26",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Simple Regression Review\"\noutput: html_document\n---\n\n\n\n\n\nRegression models are wonderfully flexible.  There are several variants of the basic model which are also the beginning of many other types of models which you may learn about if you go beyond an undergraduate degree! While we cover the basics in the next ten weeks, this is only the beginning.\n\nRegression is an extension of a correlation analysis.  Instead of having two numerical variables for which we describe an association or a relationship, we denote one of the variables a predictor and the other variable the outcome. When both continuous variables are standardised (explained later), the regression coefficient for the slope ($b$) is equivalent to Pearson's *r*.\n\nAdditionally, the predictor variable need not be a continuous variable.  If your only predictor in a simple regression is a binary variable - one with two possible discrete responses - then a simple regression is equivalent to an independent t-test.  \n\nA regression analysis will find the best possible set of values that *predict* values of the outcome variable given the observed values.\n\n## Model for simple regression\n\nThere is an equation for regression: This is the one I use in the lecture\n\n$$\nY = b_0 + b_1*X_1+e\n$$\n\nThis second equation is equivalent, it just uses different letters.  This is the one that is used in WBA1\n$$\nY = a + b_1*X_1+e\n$$\nWhere:\n\n - $Y$ is the outcome variable - the values to be predicted.  Sometimes called the *criterion* variable.\n - $X$ is the predictor variable.  \n   - In ANOVA terms $Y$ is the dependent variable and $X$ is the independent variable.  \n - $b_0$ or $a$ is the intercept term;\n   - In ANOVA terms $a$ is the grand mean.\n - $b_1$ is the beta coefficient and represents the slope of change in $Y$ - how $Y$ changes with unit increases in $X$:\n   - when $b$ = 1, a 1 unit increase in $X$ predicts a 1 unit increase in $Y$\n   - when $b$ < 1, the rate of change between $Y$ and $X$ is slow and the slope is shallower\n   - when $b$ > 1, the rate of change between $Y$ and $X$ is faster and the slope is steeper\n   - the sign of $b$ tells the direction of the effect - positive or negative\n - $e$ is the error term,  the distance of each data point from the regression line\n \nUp until now, your statistics learning has been involved in null hypothesis significance testing.  The null hypothesis for a regression analysis is that the value of the slope is zero or in other words,  the regression coefficient for $b$ is 0, or in other words, there is no slope, only the intercept term.\n\n### Section 1: Longhand Calculations for Simple Regression - useful for WBA1 but not on the class test\n\nLonghand calculations can be useful to some people for understanding the underlying relationships of both the formula to the data but also the relationships between the different parts of the model.  There are three parts of a regression model: The intercept, the slope and the error term (or residual term)\n\nIn simple regression, where only one predictor is used,  we can estimate the slope ($\\hat{b}$) with a formula:\n\n#### Slope forumula\n\n$$\n\\hat{b} = \\frac{\\Sigma(X_i*Y_i)- (N*\\bar{X}*\\bar{Y})}{\\Sigma(X^2- (N*{X^2})}\n$$\n\nIn words, the top line of the equation may read like: in the first brackets, multiply the paired observations of X and Y and add these all together; in the second brackets multiply the number of observations with the mean of the X variable and the mean of the Y variable.  Take the result of the second term away from the results of the first term.\n\nThe bottom line may read as: in the brackets, multiply the squared observation of X by the number of observations. Second, square the observation in X. Thirdly, take away the result of the brackets from the squared observation of X and finally, add all those values together.\n\nThe slope is a result of dividing the top line by the bottom line.\n\n#### Intercept formula\n\nand we can estimate the value of the intercept ($\\hat{a}$):\n\n$$\n\\hat{a} = \\bar{Y} - \\hat{b}*\\bar{X}\n$$\n\nIn words this may read like: multiply the mean of X by the slope term and take it away from the mean of Y\n\n#### Predict values of Y for every observation of Y\n\nand we can estimate the predicted values of each observation of $Y_i$:\n\n$$\n\\hat{Y_i} = \\hat{a}+\\hat{b}*X_i\n$$\n\nIn words this may read like: multiply the X observation by the slope term and add it to the intercept term\n\n\n#### Estimate the error term\n\nand then we can estimate the error term ($\\hat{e_i}$):\n$$\n\\hat{e_i} = Y_i - \\hat{Y_i}\n$$\n\nIn words this may read like: From every observed value of Y, subtract the predicted value of Y.\n\n\n### Example of Calculating a Regression Line by Longhand\n\nWe need two variables to complete an example:\n\nIn the correlation review, we used Lets choose `IQ` and `Performance`.  Lets do the same here.  It is more intuitive to have `IQ` predict `Performance` so let `IQ` be $X$ and `Performance` be $Y$.\n\n#### Read in the data\n\nThis is a reduced set of values retrieved from PSYC122.  We used these to review correlation.  We will use them again to review simple regression\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd <- read_csv(\"Covariance_Data.csv\") # calling my dataframe d to save typing!\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 13 Columns: 5\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\ndbl (5): Participant_ID, Performance, IQ, Motivation, Social_Support\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n\n#### Slope term\n\nLets start with estimating the slope term ($\\hat{b}$):\n$$\n\\hat{b} = \\frac{\\Sigma(X_i*Y_i)- (N*\\bar{X}*\\bar{Y})}{\\Sigma{X^2}- (N*\\bar{X^2})}\n$$\n\nWe need several values: \n\n - observations on $X$ and $Y$ - already in our dataset\n - the number of paired observations ($N$), \n - the mean values of $X$ and $Y$ ($\\bar{X}$, $\\bar{Y}$) \n - squared values for each observation of $X$ ($X^2$) \n - squared value of mean of $X$ ($\\bar{X^2}$). \n \nWe can use commands in the base R package to generate the values we need to compute the slope term long hand:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# number of paired observations in the dataset\nN <- nrow(d)\n\n# mean values\nIQ_Av <- mean(d$IQ)\nPerf_Av <- mean(d$Performance)\n\n# squared values of X\n# create a new column for each observation\nd$IQ_sq <- d$IQ*d$IQ \n\n# squared value of mean of X\nIQ_Av_sq <- IQ_Av*IQ_Av\n```\n:::\n\n\n\n The steps to calculate the top line of the formula will then be:\n\n 1. multiply `IQ` and `Performance` values together\n 2. add all the values from step 1 together\n 3. multiply number of observations by the mean of `IQ` and the mean of `Performance`\n 4. subtract step 3 from step 2\n\n \nWe can perform each of those steps and add new columns where needed to our `d` dataset, so you can see what is happening along the way:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd$IQP <- d$IQ*d$Performance # multiply `IQ` and `Performance` values together\n\nIQP_sum <- sum(d$IQP) # add all the values from step 1 together\n\nAv_IQP_N <- N * IQ_Av * Perf_Av # multiply number of observations by the mean of `IQ` and the mean of `Performance`\n\n(Top <- IQP_sum - Av_IQP_N) # subtract step 3 from step 2 and print out result: this is the top line of the fraction\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -28.92308\n```\n\n\n:::\n:::\n\n\n\nSo the value for the top line of the fraction - the numerator is -28.92308\n\nRemember I am not rounding to 2 decimal places here because I am not at the end of the formula.\n \nNow for the bottom line of the fraction:\n\nThe steps to calculate the bottom line of the formula will then be:\n\n 1. square each `IQ` value (calculated earlier under `IQ_sq`)\n 2. sum the squared `IQ` values\n 3. multiply number of observations by the squared mean of `IQ`\n 4. subtract step 3 from step 2\n \n\n\n::: {.cell}\n\n```{.r .cell-code}\nIQ_sqsum <- sum(d$IQ_sq) # sum the squared `IQ` values\n\nIQ_Av_sqN <- IQ_Av_sq * N # multiply number of observations by the squared mean of `IQ`\n\nBottom <- IQ_sqsum - IQ_Av_sqN\n```\n:::\n\n\n\nNow we have all the values we need to be able to compute the slope term. Simply divide `Top` by `Bottom`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(slope <- Top/Bottom) # remember that wrapping a command in brackets is automatic print out of value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.01317634\n```\n\n\n:::\n:::\n\n\n\nOur slope term = -0.01 to 2.d.p.  This shows a negative direction of effect or relationship; as IQ values increase, job performance scores decrease.  However, the value is very small.\n\n#### Estimating the intercept\n\nestimate the value of the intercept ($\\hat{a}$):\n\n$$\n\\hat{a} = \\bar{Y} - \\hat{b}*\\bar{X}\n$$\n\nWe have the terms we need:  \n\n - mean of `Performance` $\\bar{Y}$, \n - the slope term $\\hat{b}$ \n - the mean of `IQ` $\\bar{X}$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(intercept <- Perf_Av - (slope * IQ_Av))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 79.03336\n```\n\n\n:::\n:::\n\n\n\nThe intercept term = 79.03 (2 d.p).\n\n#### Estimating predicted for Y (Job Performance) values\n\nestimate the predicted values of each observation of $Y_i$\n\n$$\n\\hat{Y_i} = \\hat{a}+\\hat{b}*X_i\n$$\n\nWe need to do this for every observation of $Y$. This is why the $\\hat{Y_i}$ term has that little _i subscript, this is notation that represents each value of Y. That is, every single row in the dataset's Y column. \n\nWe have the values we need - we have:\n\n - the intercept $\\hat{a}$, \n - the slope term $\\hat{b}$ \n - each observed value of `IQ` $X_i$. \n \nWe will create a new column in the dataset and call the variable $Y_pred$.\n \nBecause we are sending the result of this line of code to our dataset, it will\nnot print out below.  You have to click on the dataset and view it to inspect\nyour new column with its values.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd$Y_Pred <- intercept + (slope*d$IQ)\n```\n:::\n\n\n\n#### Estimating the error term ($\\hat{e_i}$)\n\n$$\n\\hat{e_i} = Y_i - \\hat{Y_i}\n$$\nAgain, we have the terms we need:  \n\n - the observed values of `Performance` $Y_i$\n - the predicted values of `Performance` $\\hat{Y_i}$ in the variable `Y_Pred`.  \n \nWe will create a new column in the dataset and call the variable for the error term `error`.\n\nBecause we are sending the result of this line of code to our dataset, it will\nnot print out below.  You have to click on the dataset and view it to inspect\nyour new column with its values.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd$error <- d$Performance - d$Y_Pred\n```\n:::\n\n\n\nWe have calculated each term of the regression equation by hand.\n\n$$\nY = a + b_1*X_1+e\n$$\n\n$$\nPerformance = 79.03 + -0.01*X_1 + e\n$$\n\n\n### Section 2:  Shorthand Using the (lm) function - useful for WBA1, and labs and could be in the Class Test\n\nThe `lm()` function does all of the above for us in one very simple formula.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(m1 <- lm(Performance ~ IQ, d))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Performance ~ IQ, data = d)\n\nCoefficients:\n(Intercept)           IQ  \n   79.03336     -0.01318  \n```\n\n\n:::\n:::\n\n\nThis model printout is fairly economical.  We get the model repeated, and the regression coefficients of the intercept and the `IQ` predictor.  Note that they are identical to the longhand calculations.\n\nCalling a summary for the saved model gives us more information:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Performance ~ IQ, data = d)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-12.281  -3.755  -1.439   6.363  12.363 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)   \n(Intercept) 79.03336   17.87633   4.421  0.00103 **\nIQ          -0.01318    0.16492  -0.080  0.93775   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.727 on 11 degrees of freedom\nMultiple R-squared:  0.00058,\tAdjusted R-squared:  -0.09028 \nF-statistic: 0.006384 on 1 and 11 DF,  p-value: 0.9378\n```\n\n\n:::\n:::\n\n\nYou should be familiar with this output after working with it in weeks 16 - 19 of PSYC 122 in your first year.  The four sections are also detailed in the text accompanying the first week of PSYC 234.\n\nHere is some sample text to report the model (but not the predictor variable):\n\nWe used a linear regression model to predict Job Performance Scores from IQ scores.  The model was non-significant (*F*(1, 11) = 0.006, *p* = 0.938) and explains 0% of the variance.\n\n\n#### Checking Whether the Linear Regression Model is Signficant By Hand - Fun to know but not on the class test!\n\nRegression models are tested for significance using the F distribution and the F-test, for which we need sums of squared values for Y and error observations and degrees of freedom.  You will be familiar with these from your ANOVA practice in PSYC 214 last term.\n\nThe sums of squares needed to calculate the F-test for simple regression are:\n\n$$\nSS_{total} = \\Sigma{Y_i^2}\n$$\n\nwhich is `d$Performance` values squared and summed: \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#`Performance` values squared\nd$P_sq <- d$Performance*d$Performance \n\n# sum of squared performance values\nSS_total <- sum(d$P_sq) \n```\n:::\n\n\n\nand\n$$\nSS_{error} = \\Sigma{e_i^2}\n$$\n\nwhich is `d$error` values squared and summed\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#`d$error` values squared\nd$error_sq <- d$error * d$error \n\n# sum of squared error values\nSS_error <- sum(d$error_sq) \n```\n:::\n\n\n\nand the number of paired observations multiplied by the squared mean value of Y\n$$\nSS_{a} = N * {\\bar{Y}}^2\n$$\n\nwhich is number of paired observations multiplied by squared mean value of `Performance`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSS_a <- N * (Perf_Av*Perf_Av)\n```\n:::\n\n\n\nand the sums of squares for the slope which you get by subtracting SS_intercept and SS_error from SS_total:\n$$\nSS_{b} = SS_{total} - SS_a - SS_{error}\n$$\n\nwhich is\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSS_b <- SS_total - SS_a - SS_error\n```\n:::\n\n\n\n\nTo calculate the degrees of freedom:\n\n  - one constant value of the intercept $a$ is calculated = $df_a$ = 1\n  - one value of $b$ is determined = $df_b$ = 1 (one predictor)\n  - $df_{error}$ is always N - (other dfs)\n\nlets hard code these now:\n  \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndfa <- 1\ndfb <- 1\ndferror <- N - (dfa +dfb)\n```\n:::\n\n\n\n  \nJust as in ANOVA we can use the sums of squares and corresponding degrees of freedom to calculate mean square terms, $MS_a$:\n\n$$\nMS_a = \\frac{SS_a}{df_a}\n$$\n\n$MS_b$:\n$$\nMS_b = \\frac{SS_b}{df_b}\n$$\n\nand $MS_{error}$ \n$$\nMS_{error} = \\frac{SS_{error}}{df_{error}}\n$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(MS_a <- SS_a/dfa)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 78313.92\n```\n\n\n:::\n\n```{.r .cell-code}\n(MS_b <- SS_b/dfb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3811003\n```\n\n\n:::\n\n```{.r .cell-code}\n(MS_e <- SS_error/dferror)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 59.69962\n```\n\n\n:::\n:::\n\n\nNow we have the mean-square terms we can calculate the Fa and Fb values.  We can calculate an *F* value for both the intercept and the slope.  \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(Fa <- MS_a/MS_e)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1311.799\n```\n\n\n:::\n\n```{.r .cell-code}\n(Fb <- MS_b/MS_e)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.006383629\n```\n\n\n:::\n:::\n\n\nWe are not generally interested in the significance of the *F* value for the intercept term (Fa), only the slope term (Fb).\n\nSo, remember the null hypothesis for the regression model is whether the slope term (*b*) is different from zero. We have calculated the observed *Fb* term and now we can compare this to a critical *F* with 1 degree of freedom in the numerator (dfb) and 11 degrees of freedom in the denominator (dferror).  And, just as in ANOVA, we reject the null hypothesis if $F_{observed}$ > $F_{critical}$.\n\nWe can find a critical value for *F* with the following line of code:\n\nqf(p, df1, df2. lower.tail=TRUE)\n\nwhere `qf()` is the function, `p` = is the significance level at which you are testing (here .05), `df1` is the numerator degrees of freedom (coded above as dfb), df2 is the error degrees of freedom (coded above as dferror).\n\nIf we put in the values we get:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqf(p = 0.05, df1 = 1, df2 = 11, lower.tail=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.844336\n```\n\n\n:::\n:::\n\n\n\n\n$F_{critical}$ for df = (1, 11) at the .05 level = 4.84. $F_{observed}$ = 0.006. It is not larger than $F_{critical}$ so we fail to reject the null hypothesis.  The slope term is not different from zero.\n\n\n#### Interpretation of the relationship - Could be on the class test\n\nWhen the $F_b$ is not significant then $b$ = 0 may be true.  The data do not demonstrate any tendency for larger values of $X$ to be associated with smaller or larger values of $Y$.  For this sample, IQ and job performance  appear to be unrelated.  This is a very small sample, however, maybe there is a small effect but this sample is too small to detect it.\n\n#### Plotting the effect (or lack of it) is very simple if we are not too worried about being pretty.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(predictorEffect(\"IQ\", m1))\n```\n\n::: {.cell-output-display}\n![](Simple_Regression_Review_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n\nPlotting it in this way also allows us, with a simple additional argument to the plot call, to see the partial residuals - thereby checking that we have residual values that are normally distributed (see below). I think the curved line probably tells us that we do not!  We should be looking for an alternative way to analyse these two variables....or some transformations!\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(predictorEffect(\"IQ\", m1, partial.residuals = TRUE))\n```\n\n::: {.cell-output-display}\n![](Simple_Regression_Review_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n#### Checking Linear Model Assumptions - Useful for WBA 1 and could be on the class test\n\nEvery regression model is built upon the following assumptions:\n\n  1. The relationship between $X$ and $Y$ is assumed to be linear (additive)\n  2. The residuals are not correlated (assumption of independence)\n  3. The residuals have constant variance (homoscedasticity)\n  2. The residual errors are normally distributed\n  \n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2)) # display plots in a 2 x 2 panel\nplot(m1) # plot diagnostic plots for m1\n```\n\n::: {.cell-output-display}\n![](Simple_Regression_Review_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n\n**Residuals vs Fitted**: \"fitted\" here means the predicted values. We want the pink line to align pretty closely with the horizontal dashed line.  The graph here shows that some of the datapoints are critically far from the dashed line - datapoints are labelled as rows from the dataset; Notice how the line echoes that of the partial residuals plot above. \n\nWe could try a log(x) transformation on the predictor coerce the residuals to show greater linearity\n\n**Normal Q-Q**: If the residual points (open circles) follow the dashed line, you can assume the residuals are normally distributed\n\n**Scale-Location**: This is checking for constant variance in the residuals - not much here.  A good indication would be a horizontal pink line with equally spread points.  Our graph is not good.\n\nWe could also use a log(y) transformation on the outcome variable to help here.\n\n**Residuals vs Leverage** - are there any points that are having a large influence on the regression results.  They will be numbered and you can then inspect them in your data file. Observations that show standardised residuals (see the .std.resid column in the table above) above 3 would be problematic. In this graph, observations on row 3, 4 and 13 look to have high influence. In the table they do not show values higher than three but relative to the other values, they may be having an undue influence.  \n\nAs would observations of a hat value above $2(p+1)/n$. Here, $p$ = is the number of predictors and $n$ = is the number of observations.  The hat value for this model therefore is:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- 1\n(m1_hat <- (2*(p+1))/N)  # model hat value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3076923\n```\n\n\n:::\n:::\n\n\nWe can collect some diagnostic measures to find hat values above 0.31, using the `augment()` function from the `broom` package:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(m1_metrics <- augment(m1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 13 × 8\n   Performance    IQ .fitted  .resid   .hat .sigma  .cooksd .std.resid\n         <dbl> <dbl>   <dbl>   <dbl>  <dbl>  <dbl>    <dbl>      <dbl>\n 1          85   109    77.6   7.40  0.0778   7.73 0.0420       0.998 \n 2          84   106    77.6   6.36  0.0781   7.83 0.0312       0.858 \n 3          87   125    77.4   9.61  0.215    7.34 0.269        1.40  \n 4          69    84    77.9  -8.93  0.331    7.33 0.494       -1.41  \n 5          81    89    77.9   3.14  0.235    8.02 0.0331       0.464 \n 6          71   109    77.6  -6.60  0.0778   7.81 0.0333      -0.889 \n 7          76   121    77.4  -1.44  0.159    8.09 0.00388     -0.203 \n 8          77   102    77.7  -0.689 0.0913   8.10 0.000440    -0.0936\n 9          76   111    77.6  -1.57  0.0821   8.09 0.00201     -0.212 \n10          90   106    77.6  12.4   0.0781   7.01 0.118        1.67  \n11          74   107    77.6  -3.62  0.0771   8.02 0.00995     -0.488 \n12          74    97    77.8  -3.76  0.128    8.00 0.0199      -0.521 \n13          65   133    77.3 -12.3   0.370    6.46 1.18        -2.00  \n```\n\n\n:::\n:::\n\n\nNote that this only shows 10 rows of the table at a time; you need to toggle the pages of the table by using the buttons in the bottom right hand corner: Previous, 1, 2 or Next, to see all the rows.\n\nColumns `Performance` and `IQ` and are our two observed variables - the beginning data. `fitted` and `residuals` are what R calls our `Y_pred` and the `error` values we calculated long hand above.  The final four columns we use below with some explanation.  \n\nBy this reckoning, observation number 4 and 13 are slightly above the hat value of 0.31 for the model.  These two values may have a high leverage on the regression results.\n\nChecking for observations that are influential follows a similar pattern:  observations that exceed the *Cook's distance* value = $4/(n-p-1)$ are likely to have high influence and the regression results may change if you exclude them.  In the presence of such observations that exceed Cook's distance, unless you know the observation are errors, you probably need to estimate the model without the observations and report both sets of results.\n\nThe Cook's Distance value for this model is:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(m1_Cooks <- 4/(N-p-1)) # model Cook's distance value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3636364\n```\n\n\n:::\n:::\n\n\nAgain, observations 4 and 13 are looking influential.  Time to inspect, possibly exclude and rerun!  The problem here however is that the sample is incredibly small to begin with.  The real solution is to collect more data.  Much more.\n",
    "supporting": [
      "Simple_Regression_Review_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}